### PR TITLE
Fix #6700/#6707: Revert Safari issue fix

### LINKED ISSUE #6700: Core: After updating a component using AJAX in Safari, the current scroll position changes
Test code;
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    	xmlns:p="http://primefaces.org/ui"
    xmlns:h="http://java.sun.com/jsf/html">
  
<h:head>
    <title>Test</title>
</h:head>
<h:body>
    <h:form>
	    <div style="height: 1000px">
	    	<div style="height:400px"></div>   
	    	<div style="height:1800px"> 
		        <h:inputText id="name" value="#{testBean.test}"></h:inputText>
		        <p:selectOneMenu>
		        	<f:selectItems value="#{testBean.values}" />
				<p:ajax listener="#{testBean.test()}" update="@form" />        
			</p:selectOneMenu>
		</div>
	    </div>
    </h:form>
</h:body>
</html>
```

### LINKED ISSUE #6707: SelectOneMenu: one of yesterdays (21.12.2020) commits broke integration-tests
Error:  Failures: 
Error:    SelectOneMenu001Test.testBasic:45 expected: `<Max>` but was: `<MaxMax>`
Error:    SelectOneMenu002Test.testSelectItemGroup:50 expected: `<Volkswagen>` but was: `<VolkswagenVolkswagen>`
Error:    SelectOneMenu005Test.testHideNoSelectionOption:54 expected: `<4>` but was: `<9>`
[INFO] 
Error:  Tests run: 142, Failures: 3, Errors: 0, Skipped: 2

https://github.com/primefaces-extensions/primefaces-integration-tests/actions/runs/436866298

### PR DESCRIPTION
**Pull request by melloware**
@mertsincan Can you please review your fix yesterday caused our Integration Test suite to fail in Linux.

### CODE REVIEW

**Comment by tandraschko** [comment]
whats broken in our tests?
it still replaces/removes it, so kinda weird

hmm, not sure in general about the original fix and the this PR

**Comment by melloware** [comment]
Well our integration tests were working fine without this fix and now with AJAX change we are seeing these errors:
```
Error: SelectOneMenu001Test.testBasic:45 expected: <Max> but was: <MaxMax>
Error: SelectOneMenu002Test.testSelectItemGroup:50 expected: <Volkswagen> but was: <VolkswagenVolkswagen>
Error: SelectOneMenu005Test.testHideNoSelectionOption:54 expected: <4> but was: <9>
```
We have verified its yesterday's fix that causes these errors. Our basic test that is failing is extremely basic.
```java
 @Test
    @DisplayName("SelectOneMenu: basic usecase")
    public void testBasic(Page page) {
        // Arrange
        SelectOneMenu selectOneMenu = page.selectOneMenu;
        Assertions.assertEquals("Lewis", selectOneMenu.getSelectedLabel());

        // Act
        selectOneMenu.select("Max");
        page.button.click();

        // Assert - part 1
        Assertions.assertEquals("Max", selectOneMenu.getSelectedLabel());
        assertConfiguration(selectOneMenu.getWidgetConfiguration());

        // Act
        selectOneMenu.select(3);
        page.button.click();

        // Assert - part 2
        Assertions.assertEquals("Charles", selectOneMenu.getSelectedLabel());
        assertConfiguration(selectOneMenu.getWidgetConfiguration());
    }
```

**Comment by tandraschko** [comment]
if such a basic case fails, im sure it fails for sure on safari, too
so the fix here isnt good

**Comment by tandraschko** [comment]
please just revert Merts change, i will ping him
seems like PrimeTek is in holiday

**Comment by melloware** [comment]
> if such a basic case fails, im sure it fails for sure on safari, too
> so the fix here isnt good

It's very possible but I don't have Safari to test with and I am assuming @mertsincan did when he made this fix for a PRO user?  I have no visibility into what PrimeTek is doing just assuming its been tested and verified.  Integration tests are failing and I was trying to keep the integrity of the original fix for PRO user while fixing the Integration tests...

if someone has Safari to test our Integration tests with that would be great.

**Comment by melloware** [comment]
OK Reverted his fix.

**Comment by tandraschko** [comment]
i pinged him, so he can check it when they are back

**Comment by christophs78** [comment]
The issue was not specific for Linux. I was able to reproduce it on my Windows-Dev-Machine too.

**Pull request merged**
