### PR TITLE
Fix #8773: Charts (jqPlot): Remove

### LINKED ISSUE #8773: Charts (jqPlot): Remove
The jqPlot charts are deprecated since 10. So they should be removed at some point. That will also take care of duplicate class names (making importing easier).

### PR DESCRIPTION
**Pull request by jepsar**
Fix #8773

### CODE REVIEW

**Comment by melloware** [comment]
I am just wondering if we should leave this in for 12.0 and remove it in 13.0.  One last version for people to migrate off of since 12.0 is out next month?

**Review by melloware — CHANGES_REQUESTED** [review]
Don't forget to remove `jqPlot` from `thirdpartylibs.md`

**Comment by jepsar** [comment]
I'm on vacation this week. Will take care of it next weekend.

**Comment by jepsar** [comment]
Reverted changes to the 12.0.0 docs. Will take care of the rest when 12 is released.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I am marking them deprecated in 12.0 to give users a heads up: https://github.com/primefaces/primefaces/pull/8904

**Comment by melloware** [comment]
Can you rebase this one and then we can merge it?

**Comment by jepsar** [comment]
@melloware I'll first add the PF 13 docs as we need changes there as well

**Comment by melloware** [comment]
Great work thanks!

**Pull request merged**
