### PR TITLE
Strengthen #3170 & #2907 - address the regression affects headline wr…

### PR DESCRIPTION
**Pull request by jxmai**
…appers

**Address the regression mentioned by**: https://github.com/primefaces/primefaces/commit/98a598f50bf3eca887960c6a8928c17b0608db94#commitcomment-27101765

**investigation**: https://github.com/primefaces/primefaces/commit/98a598f50bf3eca887960c6a8928c17b0608db94#commitcomment-27102378

**Solution** https://github.com/primefaces/primefaces/commit/98a598f50bf3eca887960c6a8928c17b0608db94#commitcomment-27105660

**test code**

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        
		 <h:form>
		 	<p:textEditor value="#{testView.text}"></p:textEditor>
		 	
		 	
		 	<p:commandButton value="Test" update="@form" actionListener="#{testView.printText()}"></p:commandButton>
		 </h:form>
    </h:body>
</html>
```

---

```java
package org.primefaces.test;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -450911487369298388L;

    private String testString;

    private String text;

    @PostConstruct
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public void printText() {
        System.out.println(text);
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }
}

```

### CODE REVIEW

**Comment by jxmai** [comment]
Quill's output is more complicated than I thought. There is another case if user mix p and h together. I will analyse it further and we might need to dump #2907 if necessary.

**Comment by jxmai** [comment]
Yep, the outer p tag is necessary in serveral cases:

quill generates a wrapper for every single line by design that is difficult for us to mess with it. 

1. multiple lines input

```xhtml
"<p>e</p><p><br></p><p><br></p>"
```

2. mix p and h which is pretty much the same as point 1

```xhtml
<p>e</p><p><br></p><h1>f</h1>
```

Basically, every single line has a wrapper in quill. `p` is just one of them

so either we need to remove outer p tag for every line, or dump #2907.

I would say #2907 is an annoying bug that does not appear on any other editors because of the quill's design...

Let's see if removing p tag on every line is doable or not.

**Comment by tandraschko** [comment]
I would actually dump 2907.

**Comment by jxmai** [comment]
No, there is a bigger problem which can determine  #2907 as not fixable.

image

```
this.editorContainer.get(0).children[0].innerHTML
"<p>1</p><p>5</p>"
```

1 and 5 will mix together.

**Comment by jxmai** [comment]
Yes, I will revert all the patches shortly. #2907  is not fixable by quill's design

**Pull request merged**
