### PR TITLE
Fix #4474: SelectManyCheckBox grid layout not rendering proper HTML.

### LINKED ISSUE #4474: SelectManyCheckBox grid layout - closing tr-tag not rendered
primefaces 7.0.RC1 - org.primefaces.component.selectmanycheckbox.SelectManyCheckboxRenderer

Obvious bug:  if the number of items in 'selectItem' is not a multiple of 'colums',  the closing 'tr'-tag  is not rendered. Result is an unbalanced DOM tree with ambiguous effects in the web browser. (parts of page not displayed, misalignments, ...)

``` 

protected void encodeGridLayout(FacesContext context, SelectManyCheckbox checkbox) throws IOException {
        ResponseWriter writer = context.getResponseWriter();
        List<SelectItem> selectItems = getSelectItems(context, checkbox);
        Converter converter = checkbox.getConverter();
        Object values = getValues(checkbox);
        Object submittedValues = getSubmittedValues(checkbox);
        int columns = checkbox.getColumns();

        if (columns != 0) {
            int idx = 0;
            int colMod;
            for (int i = 0; i < selectItems.size(); i++) {
                SelectItem selectItem = selectItems.get(i);
                colMod = idx % columns;
                if (colMod == 0) {
                    writer.startElement("tr", null);
                }

                writer.startElement("td", null);
                encodeOption(context, checkbox, values, submittedValues, converter, selectItem, idx);
                writer.endElement("td");

                idx++;
                colMod = idx % columns;

                if (colMod == 0) {
                    writer.endElement("tr");
                }
            }
        }
        else {
            throw new FacesException("The value of columns attribute must be greater than zero.");
        }
    }
```

### PR DESCRIPTION
**Pull request by melloware**
- Added TBODY tags
- Correctly check for closing TR tag and close out the final row i odd number of columns.

### CODE REVIEW

**Comment by tandraschko** [comment]
could add the tbody break something?
I would feel a bit safer to introduce it after 7.0, also if should not break something.

**Comment by melloware** [comment]
I can remove the TBODY lines if it will help it make it in 7.0.  I just hate having a component that is not rendering the proper HTML.   They are definitely not necessary.

**Comment by tandraschko** [comment]
yep, lets add the tbody after the release

**Comment by melloware** [comment]
Done!

**Pull request merged**
