### PR TITLE
Fix #3251 change imagecompare.js lib to a actively maintained one (juxtapose)

### LINKED ISSUE #3251: ImageCompare: migrate to newer JS plugin
I've found this one which seems to be nice:

https://github.com/NUKnightLab/juxtapose
https://juxtapose.knightlab.com/

A PR will follow, where i have tested this, and it seems to work fine with the current features

This will open the possibility to add new features such as:

- Date of the picture 
- Credit of the picture
- Responsive design
- Animation
- Does not rely on bitmap images

### PR DESCRIPTION
**Pull request by cnsgithub**
Solves issue: #3251

Tested properties:  leftImage, rightImage, width, height

### CODE REVIEW

**Comment by tandraschko** [comment]
@cnsgithub merged the PR but the showcase is broken now

**Comment by cnsgithub** [comment]
Has something else changed in the mean time? I'll check it

**Comment by tandraschko** [comment]
i just checked it and it seems that the old code used getResourceUrl to get the image path
currently checking if that fixes it

**Comment by tandraschko** [comment]
fixed it

**Comment by cnsgithub** [comment]
Thanks, some time saved :)

**Pull request merged**
