### PR TITLE
Added a sometimes failing integration test for #8857

### PR DESCRIPTION
**Pull request by nettozahler**
Added a sometimes failing integration test for #8857

### CODE REVIEW

**Comment by melloware** [comment]
Can you re-sync with master and run this again?  I just made some fixes that fixed InputText and InputTextArea but locally I can't get the Calendar issue to happen.

**Comment by nettozahler** [comment]
I hope I did the re-sync correctly since I am not yet familiar with the contribution workflow on GitHub.

**Comment by melloware** [comment]
I will take a look tomorrow. I think something is still wrong with Calendar component.

**Comment by melloware** [comment]
OK I got all your tests working locally I had to make some chnages to your test as some things were incorrect.  Can you re-sync with master again and we can watch it run?

**Comment by melloware** [comment]
ok this is definitely something timing related or something because if I run this same test locally it passes.  Here its getting an AJAX timeout on the Calrendar `setValue` call for some reason.

**Comment by stolp** [comment]
Welcome to hell. This matches my experiences with our integration tests.

Running tests locally has a much higher success rate as running them in a xvbf based test environment (both using Chrome). This may be related to the graphics performance of the local browser vs the slower performance of an emulated X-Framebuffer.

I spent some time trying to fix our tests today. Avoiding update="@form" helps getting fewer timeouts, but I cannot say that these are pinned to a certain component.

My gut feeling is, that the probability of hitting timeouts is more related to the amount of components being updated at one update action.

Currently, fixing tests is more like a game of Whack-a-mole. For every problem you solve a new one may evolve at a random other location at each new run.

We are on PrimeFaces/PrimeSelenium 11.

**Comment by nettozahler** [comment]
Was there really a TimeoutException during the last test run? What I see in the log is a failed assertion: **UpdateForm001Test.testUpdateForm:59 expected: not null** This could be another manifestation of the root problem which I have also seen before: you set a field's value via PrimeSelenium and a short time later (e. g. when pressing "Submit") the previously entered field's value is suddenly missing.

**Comment by melloware** [comment]
OK i have this test passing now except for 1 line `page.calendar.setValue(System.currentTimeMillis());`.

**Comment by melloware** [comment]
OK now its all passing. I am going to merge this and we can watch it on the nightly build and see if we get "flickering" results.

**Pull request merged**
