### PR TITLE
[JSDocs] Update dependencies, fix build errors, update docs and add missing docs

### PR DESCRIPTION
**Pull request by blutorange**
Finally had time for some needed updates and fixes for the JSDocs

* Update all `dependencies` and `devDependencies` and fix build 
* Fix dependencies for Yarn PNP, add peer dependendencies from vis-data and vis-timeline
* `PrimeFaces.ajax.ConfigurationExtender`: add key `partialSubmit`
* `PrimeFaces.ajax.Configuration.ext`: Make all keys optional.
* Add missing source attribute to `PrimeFaces.dialog.ExtendedConfirmDialogMessage`
* Add type declarations for `PrimeFaces.confirmPopupSource`
* Replace all `any` types and enable liniting rule that forbids `any`. Use `unknown`, `never` or a more specific type instead.
* Add `override` keyword to type declarations where appropriate
* Add new check that inspects the code for properties on the widget (e.g. `this.flag = false`) and emits an error when no doc comment exists for that property.
* Document about ~80 undocumented widget properties.
* Add new check that inspects the code for properties on the widget and emits an error when a doc comment exists, but that property is never used.
* Fix about ~20 non-existing props in doc comments
* Remove deprecated tslint in favor of @typescript/eslint.
* Add better lint checks for missing docs on interfaces and types and add some missing doc comments.
* Update links to JSDoc: TypeDoc now preserves capitalization for the generated HTML file names

### CODE REVIEW

**Comment by blutorange** [comment]
This is still a draft, I've got a project where I'm using the type declarations already, I'd like to check them against this PR tomorrow before it's ready to be merged.

**Comment by blutorange** [comment]
@melloware The links to the widgets have changed (since typedoc now respects upper / lowercase). Since we've only got one version of the JSDocs, the links in the showcase won't work anymore after this is merged.  If there's a branch for what's running on https://www.primefaces.org/showcase/index.xhtml,  you can cherry-pick this commit https://github.com/primefaces/primefaces/pull/7814/commits/13fd8780de6d565001d8648f4cb0b42ed2bcbf72 into the 10.0 showcase branch.

**Comment by melloware** [comment]
hmmm PrimeTek keeps a 10.0 branch of the framework in their private repo.

**Comment by melloware** [comment]
@blutorange @sqores just committed new component SpeedDial can you update your PR and verify its JSDOC is OK with your new changes?

**Comment by blutorange** [comment]
I took a quick look, the JSDocs look pretty well done. There are a few minor things I see, such as native DOM `Event` being used instead of `JQuery.TriggeredEvent`.   Let me make a few adjustments

**Comment by blutorange** [comment]
Ok I made some changes for speed dial.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Can you update this PR looks like you have a merge conflict

**Comment by blutorange** [comment]
Sure, I updated it. Luckily it was just a small conflict.

**Comment by melloware** [comment]
Sorry two more conflicts after I merged another PR.  Hopefully easy to fix as its just properties removed.

**Comment by melloware** [comment]
Actually I was able to resolve them in the editor.

**Comment by melloware** [comment]
Sorry one more merge i added `cfg.autoDetectDisplay` to DatePicker.

**Comment by blutorange** [comment]
No problem, I fixed it. The merge conflict was unrelated to `autoDetectDisplay` apparently, but I also added the docs for that configuration property

**Pull request merged**
