### PR TITLE
#1921 Integrationtest for DataTable: lazy loading pagination error

### PR DESCRIPTION
**Pull request by christophs78**
~~Look´s like this issue was already fixed during some other refactoring...
Please cross check whether i test the right things. :-)~~

### CODE REVIEW

**Comment by christophs78** [comment]
Figured out how to break it. Ready to get fixed. ;-)

**Comment by christophs78** [comment]
@tandraschko , @Rapster : Now we have two mutations of the test. One works´s and one is broken. Compare the tiny little details between `ProgrammingLanguageLazyDataModel `and `ProgrammingLanguageLazyDataModelRowCountOtherImpl`. It currently makes a difference how `getRowCount` / `setRowCount` is implemented.

**Comment by tandraschko** [comment]
yep, i see
i think ProgrammingLanguageLazyDataModel is correct
WDYT?

load should do 2 queries IMO:
- select count with all filters and apply it to setRowCount
- select entities with applied paging (first + pageSize) and filtering/sort

**Comment by christophs78** [comment]
Yep. `ProgrammingLanguageLazyDataModel` is correct and should work. That´s what is done in most real-world-usecases which
fetch data from a database.
Ideally we should not break `ProgrammingLanguageLazyDataModelRowCountOtherImpl` in our attempt to fix this issue.

Currently IMO it´s not clearly defined what we expect from developers implementing LazyDataModel. Maybe we should extend JavaDoc of `LazyDataModel#load`. And add some note to https://primefaces.github.io/primefaces/11_0_0/#/components/datatable?id=lazy-loading.

**Comment by tandraschko** [comment]
which one fails now?

**Comment by christophs78** [comment]
ProgrammingLanguageLazyDataModel fails

**Pull request merged**
