### PR TITLE
Fix #6355: DatePicker fixed missing formId in lazy metadata Ajax request

### LINKED ISSUE #6355: DatePicker: lazy load disabled dates
As explained in https://github.com/primefaces/primefaces/issues/6277 I would like to be able to lazy load disabled dates on `viewChange`. Also, I'm thinking of adding date CSS styles / colors / classes to dates later. This is also something which should be lazy loadable. So, I was thinking of adding a `DateMetaData` object which could contain stuff like `disabled` and `styleClass`.

@melloware can you assign this issue to me, please?

### PR DESCRIPTION
**Pull request by jepsar**
originally should have been part of this ticket: https://github.com/primefaces/primefaces/issues/6355

### CODE REVIEW

**Comment by tandraschko** [comment]
forms are mostly resolved on the server side and passed to the JS.
Can you check how other places did this?

**Comment by jepsar** [comment]
https://github.com/primefaces/primefaces/blob/47a1f00dc3f2be3a66e37e75330eba65a9e380d8/src/main/resources/META-INF/resources/primefaces/schedule/1-schedule.js#L44

**Comment by tandraschko** [comment]
What about DataTable e.g.?

**Comment by jepsar** [comment]
It is used halve a dozen times in the data table:

https://github.com/primefaces/primefaces/blob/47a1f00dc3f2be3a66e37e75330eba65a9e380d8/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L1760

But I cannot find where it is set. It's not in the script nor in the renderer. Also, based on this search:

https://github.com/primefaces/primefaces/search?l=JavaScript&q=formId

it seems to be "standard" to set the `formId` in the widget `init` function.

One use in Java:

https://github.com/primefaces/primefaces/search?l=Java&q=formId

**Comment by jepsar** [comment]
I should at least move it to the init method, so it does not have to be resolved every Ajax request...

**Comment by melloware** [comment]
@tandraschko I agree this is quite strange.  Should we just set formId in the BaseWidget `init` method so we don't have to repeat ourselves and the closest form will always be set in all widgets?

**Comment by tandraschko** [comment]
not every widget requires a form, so i would not change this.
I would just change this PR to make it like other widgets, to init form in init?

**Comment by jepsar** [comment]
I think we need the same fix on data table though. Will update this PR this evening (CET).

**Comment by tandraschko** [comment]
how does it work currently there?

**Review by melloware — APPROVED** [review]

**Comment by jepsar** [comment]
By the way.. I'm still not sure if not having a formId will cause issues. It will be a small performance boost to have it, so less form elements need to be handled and send. But it does seem to be missing in data table. See for example:

https://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml

and in the JS console:

PF('widget_form_customerTable').cfg.formId

**Comment by tandraschko** [comment]
would be great if you can create a issue and play a bit with it.
in general we should add it as the AJAX core will otherwise fallback to the first form found in the DOM normally, which isnt correct.

**Pull request merged**
