### PR TITLE
Fix #7986 - DataTable: Dynamic Columns with rendered attribute breaks…

### LINKED ISSUE #7986: DataTable: Dynamic Columns with rendered attribute breaks filter/sort functionality
**Describe the defect**

Trying to upgrade from PF8 to PF10, but I'm having issues with the rendered attribute in `p:columns`. It shows/hides columns properly, but it breaks the filter/sort functionality.

**Reproducer**

Reproducer attached.

**Environment:**

 - PF Version: _10.0_
 - JSF + version: _Mojarra 2.2.20 and MyFaces 2.3.9_
 - Affected browsers: _Chrome and Firefox_

**To Reproduce**

Navigate to `test.xhtml` and add/remove `rendered="#{column.rendered}"` to check the behaviour.

**Expected behavior**

Filter/Sort functionality should work with rendered attribute.

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7368200/primefaces-test-master.zip)

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by tandraschko** [comment]
i will have a look later

**Comment by Rapster** [comment]
IMO there is some clean up to do in ColumnAware:
- there are 5 methods foreachColumn!
- Function<UIColumn, Boolean> should be replaced with a Predicate<UIColumn>
- Javadoc on these methods (at least one) to explain at least what the predicate does
- Have a look again where applyStatelessModel is called, based on this PR, it's most probabaly useless to call it explicitely from now on

**Comment by tandraschko** [comment]
1-3 done ;)

**Comment by melloware** [comment]
I added Integration test PR for this.  It tests sorting and filtering and shows them currently broken. :0

**Comment by tandraschko** [comment]
applied your changes with small adjustments, thanks!

**Pull request closed without merging**
