### PR TITLE
Fix #11521: Datatable first value fix

### LINKED ISSUE #11521: DataTable: Paginator After upgrade to 13.0.6  always uses first=0 in .load() method
### Describe the bug

Upgraded PrimeFaces from 13.0.5 to 13.0.6 and noticed that DataTable with LazyDataModel stopped paginating properly. Investigation revealed that `.load()` method always called with `first=0` on pagination to other pages. Reverting back to 13.0.5 resolves the issue without any other code changes.

I am running Payara 6.2024.2 and PF with Jakarta classifier.

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

13.0.6

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

3.0.2

### Java version

17

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #11521: Datatable first value fix

### CODE REVIEW

**Comment by melloware** [comment]
@jungm i reverted your fix, added @tandraschko new test for #11521 and made sure your current DataTableTest044 still passes.  can you review the change please.

**Comment by jungm** [comment]
on first glance looks good to me, will test tomorrow in our real app but if my IT still passes this should be good IMHO

**Comment by jungm** [comment]
@melloware still works fine in our real app as well

**Comment by tandraschko** [comment]
+1 looks good to me

**Pull request merged**
