### PR TITLE
schedule and integration-test-profiles

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by tandraschko** [comment]
im not sure if this does correctly but i would like to have
1) run a single integration tests (firefox, myfaces) on each commit/PR
2) run all environments nightly (firefox/chrome, myfaces/mojara and so on)

**Comment by christophs78** [comment]
Seems like our integrations-test do not work with Java16 due to some OpenEJB issue.
```
java.lang.InternalError: 
LocalBeanProxyFactory.createProxy: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2a79781f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.apache.openejb.util.proxy.LocalBeanProxyFactory$Unsafe.getClassLoaderDefineClassMethod(LocalBeanProxyFactory.java:845)
	at org.apache.openejb.util.proxy.LocalBeanProxyFactory$Unsafe.defineClass(LocalBeanProxyFactory.java:828)
	at org.apache.openejb.util.proxy.LocalBeanProxyFactory.createProxy(LocalBeanProxyFactory.java:142)
	at org.apache.openejb.util.proxy.LocalBeanProxyFactory.createProxy(LocalBeanProxyFactory.java:152)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.eagerInitOfLocalBeanProxies(TomcatWebAppBuilder.java:1569)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1315)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1131)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:134)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5082)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.deployWar(TomcatWebAppBuilder.java:658)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.deployWebApps(TomcatWebAppBuilder.java:598)
	at org.apache.tomee.catalina.deployment.TomcatWebappDeployer.deploy(TomcatWebappDeployer.java:47)
	at org.apache.tomee.embedded.Container.deploy(Container.java:883)
	at org.primefaces.integrationtests.PrimeFacesSeleniumTomEEAdapter.startup(PrimeFacesSeleniumTomEEAdapter.java:70)
```

**Comment by melloware** [comment]
Looks like there is something off with the name see "Java ${matrix.java}".

image

**Comment by christophs78** [comment]
> Looks like there is something off with the name see "Java ${matrix.java}".
> 
> image

IMO this is expected, because we have some if´s within build.yml. One job for "normal" build and on nightly/scheduled. The disabled one generates the somewhat weird job-entry.

**Comment by christophs78** [comment]
Chrome 91 - issue persists also when running on macos. 
Some google-search shows there had been some under-the-hood-changes for Chrome 91: https://blog.chromium.org/2021/05/chrome-is-faster-in-m91.html
I´ll currently blame it on this. (And hope a fixed Chrome(Driver) is comming later).

**Comment by christophs78** [comment]
Hm. I´ll try two yml-files.

**Comment by melloware** [comment]
I like the idea of two files!

**Comment by melloware** [comment]
Going to merge this so we can watch it run tonight.

**Comment by christophs78** [comment]
Nightly / scheduled job runs as expected: https://github.com/primefaces/primefaces/actions/runs/924109680
We only have the Chrome-issue.

**Comment by tandraschko** [comment]
why dont we test CSP on firefox e.g.?

**Comment by christophs78** [comment]
> why dont we test CSP on firefox e.g.?

Good point. Feel free to add this. Up to this point our target was to limit test-mutations. But now after we have splitted build and nightly this should not be a issue anymore.

**Pull request merged**
