### PR TITLE
DataTable: Support for row-specific titles #9395

### PR DESCRIPTION
**Pull request by tuerker**

### CODE REVIEW

**Comment by jepsar** [comment]
Can you please update https://github.com/primefaces/primefaces/blob/master/docs/13_0_0/gettingstarted/whatsnew.md ?

**Comment by tuerker** [comment]
> Can you please update https://github.com/primefaces/primefaces/blob/master/docs/13_0_0/gettingstarted/whatsnew.md ?

done.

**Review by melloware — APPROVED** [review]

**Comment by tuerker** [comment]
could somebody please rerun the failed job. actually failure should have nothing todo with my commits.

**Comment by melloware** [comment]
> could somebody please rerun the failed job. actually failure should have nothing todo with my commits.

Don't worry about it I always check what fails and see its a flickering FileUpload test that only failed on one of the instance so I know your PR is ok.

**Pull request merged**
