### PR TITLE
isValueBlank: better implementation

### PR DESCRIPTION
**Pull request by Rapster**
Even better would to reuse the impl from StringUtils of Apache (but not sure if it is allowed due to license)
```java
    /**
     * <p>Checks if a CharSequence is whitespace, empty ("") or null.</p>
     *
     * <pre>
     * StringUtils.isBlank(null)      = true
     * StringUtils.isBlank("")        = true
     * StringUtils.isBlank(" ")       = true
     * StringUtils.isBlank("bob")     = false
     * StringUtils.isBlank("  bob  ") = false
     * </pre>
     *
     * @param cs  the CharSequence to check, may be null
     * @return {@code true} if the CharSequence is null, empty or whitespace
     * @since 2.0
     * @since 3.0 Changed signature from isBlank(String) to isBlank(CharSequence)
     */
    public static boolean isBlank(final CharSequence cs) {
        int strLen;
        if (cs == null || (strLen = cs.length()) == 0) {
            return true;
        }
        for (int i = 0; i < strLen; i++) {
            if (Character.isWhitespace(cs.charAt(i)) == false) {
                return false;
            }
        }
        return true;
    }
```

### CODE REVIEW

**Comment by melloware** [comment]
+1

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
I would actually just do the following:
replace
return value.trim().equals("");
with
return value.trim().isEmpty();

it should be available on java6

**Comment by jxmai** [comment]
The main benefit of `"".equal(str)` is that we don't need to do null check, but null check is necessary in this case as we need to call `trim`. 

`isEmpty()` introduced in Java 1.6 is faster and cleaner.

**Comment by Rapster** [comment]
Fair enough @tandraschko I'll change it

**Review by jxmai — APPROVED** [review]

**Pull request merged**
