### PR TITLE
Fix #11806: Fileupload ignore invalid content type

### LINKED ISSUE #11806: FileUpload: Decoding FileUpload requires contentType "multipart/form-data"
### Describe the bug

In FileUploadRenderer I see the following method:

 ```
   public void decode(FacesContext context, UIComponent component) {
        FileUpload fileUpload = (FileUpload) component;
        if (!fileUpload.isDisabled()) {
            if (!context.getExternalContext().getRequestContentType().toLowerCase().startsWith("multipart/")) {
                LOGGER.severe(() -> "Decoding FileUpload requires contentType \"multipart/form-data\"." +
                        " Skipping clientId: " + component.getClientId(context));
                return;
            }

            PrimeApplicationContext applicationContext = PrimeApplicationContext.getCurrentInstance(context);

            FileUploadDecoder decoder = applicationContext.getFileUploadDecoder();
            decoder.decode(context, fileUpload);
        }
    }

```

On one of my pages, I get the above severe error message. I did set a breakpoint there and find that the request in question is indeed `content-type = application/x-www-form-urlencoded;` but it also is `faces-request = partial/ajax`.

This is just during rendering of the p:fileUpload. The upload itself is working perfectly fine.

Is the logging condition correct as it is, or shouldn't it exclude partial ajax requests here?

### Reproducer

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>PrimeFaces Test</title>
        <h:outputScript name="test.js" />
        <h:outputStylesheet name="test.css" />
    </h:head>
    <h:body>

        <h:form id="frmTest">

          <p:fileUpload 
            auto="true" dragDropSupport="true" mode="advanced" skinSimple="false"
            update="@form" multiple="true" sequential="true" />

          <p:commandButton value="Refresh" partialSubmit="true" update="@form" />
        </h:form>

    </h:body>
</html>

### Expected behavior

The message should not be logged for partial updates.

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-RC3

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

21

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #11806: Fileupload ignore invalid content type

### CODE REVIEW

**Comment by Rapster** [comment]
Not a big fan of this method logDevelopementWarning, we lose the source class of where the issue actually comes from. I think we should add an additional parameter

**Comment by melloware** [comment]
That is true. I will update this PR for 15.0.0 but leave the simple change for 14.0.1

**Comment by tandraschko** [comment]
we should add comment here:
// skip further processing as servlet fileupload decoding would throw a exception because of wrong contentType

**Comment by melloware** [comment]
Updated for both your comments.  I removed a few of those log warnings as they are in deprecated methods being removed in another PR.

**Pull request merged**
