### PR TITLE
Fix #2650 - Datatable: duplicate cliend ids in custom facet paginator

### LINKED ISSUE #2650: DataTable: duplicate cliend ids in custom facet paginator
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
## 2) Expected behavior
As an example, menu button is used in facet, and as a result, menuButton should display menu items

## 3) Actual behavior
MenuButton is displayed, but does no show up menu items

## 4) Steps to reproduce

1. Using 5/ in showcase in http://localhost:8080/showcase/ui/data/datatable/paginator.xhtml
2. try to click on menu button
3. menu items does not show up

## 5) Sample XHTML
```xml
            <p:dataTable var="car" value="#{dtPaginatorView.cars}" rows="10" 
                         paginator="true"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} {Custom}"
                         rowsPerPageTemplate="5,10,15">

                 <f:facet name="{Custom}">
                    <p:menuButton value="Options">
                        <p:menuitem value="Save" actionListener="#{menuView.save}" icon="ui-icon-disk"/>
                        <p:menuitem value="Update" actionListener="#{menuView.update}" icon="ui-icon-arrowrefresh-1-w"/>
                        <p:menuitem value="Delete" actionListener="#{menuView.delete}" ajax="false" icon="ui-icon-close"/>
                        <p:separator />
                        <p:menuitem value="Homepage" url="http://www.primefaces.org" icon="ui-icon-extlink"/>
                    </p:menuButton>
                </f:facet>

                <p:column headerText="Id">
                    <h:outputText value="#{car.id}" />
                </p:column>

                <p:column headerText="Year">
                    <h:outputText value="#{car.year}" />
                </p:column>

                <p:column headerText="Brand">
                    <h:outputText value="#{car.brand}" />
                </p:column>

                <p:column headerText="Color">
                    <h:outputText value="#{car.color}" />
                </p:column>
            </p:dataTable>
```

## 6) Analysis
clientIds generated of both menubutton are the same... So I guess, the jQuery widget can't work properly...

### PR DESCRIPTION
**Pull request by Rapster**
I realized it is necessary to add the facet name in the id otherwise, it might still have id conlicts

### CODE REVIEW

**Comment by Rapster** [comment]
i'm wondering if I shouldn't use encodeFacet instead...

**Comment by tandraschko** [comment]
I really don't like the fix and i'm not sure if it would have side effects.
The problem probably is, that we should really avoid to render a facet multiple times.

**Comment by Rapster** [comment]
The only thing I don't like about this is that I'm using a regex, while there should probably be an util for that kind of thing... I guess then the support of facet should be done in header and not pagination. That would be a big breaking change...

But I think it still deserves some attention to make it work in the current state, I mean we're so close to get something working...

**Comment by Rapster** [comment]
As this PR does not cover composite components, I prefer to close it. As a workaround, we only use top paginator (instead of both)

**Pull request closed without merging**
