### PR TITLE
#7598: CLI-tool for PrimeFlex V2 --> V3 - migration

### PR DESCRIPTION
**Pull request by christophs78**
Very early days. :-)
Just to give you an idea of the direction i think.

### CODE REVIEW

**Comment by tandraschko** [comment]
i like the idea because we can really resolve many migration problems

also we should think about using something like: https://github.com/remkop/picocli

**Comment by christophs78** [comment]
Just converted my local PrimeFaces-showcase to PrimeFlex 3. Most things already look good. :-)
Someone who want´s to to have a look at this PR?

@mertsincan : This CLI-tool should propably work for PrimeNG, PrimeReact und PrimeVue too.

**Comment by christophs78** [comment]
Also added Grid CSS to PrimeFlex 2 migration. (We still have this in use.)
So you may first migrate vom Grid CSS to PrimeFlex 2. And then later from PrimeFlex 2 to PrimeFlex 3.

**Comment by melloware** [comment]
Nice!

**Comment by tandraschko** [comment]
i would rework the readme a bit:

1) Intro: global stuff like (It´s suggested to have no uncommited... and here always may be corner-cases which need some additional manual work...)

2) PrimeFlex 2 --> PrimeFlex 3 migration

3) Grid CSS --> PrimeFlex 2 migration

**Comment by tandraschko** [comment]
Otherwise great work!
we should probably add this to the docs and especially migration guide

**Comment by FlipWarthog** [comment]
This looks amazing! Great work, @christophs78!

**Comment by marcelocaser** [comment]
very nice ideia!! will be very util

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
Thanks @christophs78, thats a nice contribution!

**Pull request merged**
