### PR TITLE
Fix #5288: Dock reimplemented using CSS

### LINKED ISSUE #5288: Dock: Reimplement using CSS
Based on this original suggestion: https://github.com/primefaces/primefaces/issues/3153

Problems with current dock:
- Uses third party Fisheye JS which has not been updated since 2009
- Does not look quite like the modern Max OSX dock
- Uses Javascript for all the animation

The suggestion to use pure CSS with a little JS is a good one and I have settled on this really well done CSS that can be modified heavily to fit PF requirements.
http://www.alessioatzeni.com/mac-osx-lion-css3/

### PR DESCRIPTION
**Pull request by melloware**
- Adds RTL support
- Removes all old Fisheye JS library
- Add animation bounce to the icon click just like OSX
- Looks more like modern OSX
- Tested in IE11, Edge, Chrome and Firefox

### CODE REVIEW

**Comment by tandraschko** [comment]
PF7.1 RC1 is planned for mid november, i think it's better to postpone reimplementations for now to 7.2.

**Comment by melloware** [comment]
I agree we can just leave this PR.  Can you create a 7.2 milestone so I can mark the ticket for 7.2?

**Comment by melloware** [comment]
Nevermind I see you already created one!

**Comment by tandraschko** [comment]
feel free to fix conflicts and merge if well tested

**Pull request closed without merging**
