### PR TITLE
#9575, fix regression because of #8693,

### LINKED ISSUE #9575: Tree: Wrong node order because of #8693
### Describe the bug

The change in #8693 breaks the drag and drop of items in the same list. 

For a reproduces take the showcase:
In src/main/webapp/ui/data/tree/dragdrop.xhtml
change the update from ":form:msgs" to ":form".

Drag Node0 between Node1 and Node2. Node0 stays for a short while there. 
With the update coming back the Node0 is moved one Node up.

IMHO the changes done because of #8693 must be reverted. 

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

_No response_

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by OBreidenbach**
Fix #9575, fix regression because of #8693,
Changed Node numbers in test to 0-based as index is also 0 based. Hopefully less brain overload.

### CODE REVIEW

**Comment by OBreidenbach** [comment]
Is it 'normal' that some of the myfaces test runs always fail?

https://github.com/primefaces/primefaces/actions/runs/3821665317
https://github.com/primefaces/primefaces/actions/runs/3823695803
https://github.com/primefaces/primefaces/actions/runs/3824905507
https://github.com/primefaces/primefaces/actions/runs/3827698326

**Comment by tandraschko** [comment]
not really
started some days ago
i also switched back to selenium warning logging

**Comment by OBreidenbach** [comment]
So I guess that my change do not cause the test failures.

**Comment by tandraschko** [comment]
can you re-trigger? seems to work again since my last commit

**Review by melloware — APPROVED** [review]

**Pull request merged**
