### PR TITLE
Fix #6409 - Datatable: ColumnGroup refactoring

### LINKED ISSUE #3409: ComponentUtils.getHrefURL: lack of encoding
As already mentioned in [this](https://github.com/primefaces/primefaces/commit/41fd99e3375227ccda3c4559c64dda26fa02b82a) commit comment parameter keys are not encoded. This may lead to HTTP parameter pollution. 

~~Fragments are also not encoded.~~ See comment [below](https://github.com/primefaces/primefaces/issues/3409#issuecomment-370339135)

### LINKED ISSUE #6409: Datatable: ColumnGroup refactoring
**Description**
Columns grouping follows a very "unconventional" approach: 13 columns have to be defined when only 5 are displayed! My guess, is that no solution have been found at the time to render nested tr/th. Consequence of this, is the current implementation makes the code very hard to maintain at very low level for us as PF developers, but also for developers using column grouping. I can see that ColumnGroup has been giving a really hard time since it's been there 😅 

FYI: I believe other PrimeUI librairies should do the same (if possible)

**Describe the solution you would like**
Could be done 100 times simpler (colspan and rowspan automatically calculated):
```xml
                
<p:dataTable id="tblSales" var="sale" value="#{dtGroupView.sales}" columnGroupLegacyEnabled="false"
                             scrollable="#{dtGroupView.frozenColumns}" frozenColumns="#{dtGroupView.nbFrozenColumns}"
                             scrollWidth="500">

    <f:facet name="header">
        <h:outputText value="Product Sales"/>
    </f:facet>

    <p:column headerText="Product" field="manufacturer" footerText="Table footer (tfoot) using column footer facet"/>

    <p:columnGroup headerText="Sale Rate">
        <p:columnGroup headerText="Sales">
            <p:column headerText="Last Year" field="lastYearSale" footerText="A"/>
            <p:column headerText="This Year" field="thisYearSale" footerText="B"/>
        </p:columnGroup>
        <p:columnGroup headerText="Profit">
            <p:column headerText="Last Year" field="lastYearProfit" footerText="C"/>
            <p:column headerText="This Year" field="thisYearProfit" footerText="D"/>
        </p:columnGroup>
    </p:columnGroup>

    <f:facet name="tfooter">
        <p:row >
            <p:column>Table footer (tfoot) using table tfooter</p:column>
            <p:column colspan="2" style="text-align:right">Totals:</p:column>
            <p:column>
                <h:outputText value="#{dtGroupView.lastYearTotal}">
                    <f:convertNumber type="currency" currencySymbol="$"/>
                </h:outputText>
            </p:column>
            <p:column>
                <h:outputText value="#{dtGroupView.thisYearTotal}">
                    <f:convertNumber type="currency" currencySymbol="$"/>
                </h:outputText>
            </p:column>
        </p:row>
    </f:facet>

    <f:facet name="footer">
        <h:outputText value="Data between 2013-2014"/>
    </f:facet>
</p:dataTable>
```

**Additional context**
Besides it's easier to write and read _(less verbose)_, doing so, No trick is required to make a few features like filtering and sorting work. WDYT? 

**Done**
- Support of frozen columns
- Introducing new facet `tfooter` _(tfoot html tag)_ allowing to define your own tfoot instead of using `ColumnGroup#type`

**Todo**
- [x] Exporters (after #9969)
- [x] Support SubTable
- [x] Support TreeTable
- [ ] Support PanelGrid ?

**To check**
- I think there is a bit of code that will be either dead code, or no longer relevant like:
  -  1dcb97403bdfeaa10055aae7561951f033e56485 introduced getIterableChildren for "perf" reasons but introduced bugs like #2110 which introduced "not so good looking" fixes
  - #2672
  - _To complete if any_

### LINKED ISSUE #9854: DataTable: frozen columns + column groups not properly rendered
### Describe the bug

Having a table with frozen columns and columns groups doesn't render properly 

### Reproducer

Update `group.xhtml` from showcase with:

```xml
                <p:dataTable id="tblSales" var="sale" value="#{dtGroupView.sales}" frozenColumns="1" scrollable="true" scrollWidth="500">
                    <f:facet name="header">
                        <h:outputText value="Product Sales"/>
                    </f:facet>

                    <p:columnGroup type="frozenHeader">
                        <p:row>
                            <p:column rowspan="3" headerText="Product"/>
                            <p:column colspan="4" headerText="Sale Rate"/>
                        </p:row>
                        <p:row>
                            <p:column colspan="2" headerText="Sales"/>
                            <p:column colspan="2" headerText="Profit"/>
                        </p:row>
                        <p:row>
                            <p:column headerText="Last Year"/>
                            <p:column headerText="This Year"/>
                            <p:column headerText="Last Year"/>
                            <p:column headerText="This Year"/>
                        </p:row>
                    </p:columnGroup>

                    <p:column>
                        <h:outputText value="#{sale.manufacturer}"/>
                    </p:column>
                    <p:column>
                        <h:outputText value="#{sale.lastYearProfit}%"/>
                    </p:column>
                    <p:column>
                        <h:outputText value="#{sale.thisYearProfit}%"/>
                    </p:column>
                    <p:column>
                        <h:outputText value="#{sale.lastYearSale}">
                            <f:convertNumber type="currency" />
                        </h:outputText>
                    </p:column>
                    <p:column>
                        <h:outputText value="#{sale.thisYearSale}">
                            <f:convertNumber type="currency" />
                        </h:outputText>
                    </p:column>

                    <p:columnGroup type="frozenFooter">
                        <p:row>
                            <p:column colspan="3" style="text-align:right" footerText="Totals:"/>
                            <p:column>
                                <f:facet name="footer">
                                    <h:outputText value="#{dtGroupView.lastYearTotal}">
                                        <f:convertNumber type="currency" currencySymbol="$"/>
                                    </h:outputText>
                                </f:facet>
                            </p:column>
                            <p:column>
                                <f:facet name="footer">
                                    <h:outputText value="#{dtGroupView.thisYearTotal}">
                                        <f:convertNumber type="currency" currencySymbol="$"/>
                                    </h:outputText>
                                </f:facet>
                            </p:column>
                        </p:row>
                    </p:columnGroup>
                    <f:facet name="footer">
                        <h:outputText value="Data between 2013-2014"/>
                    </f:facet>
</p:dataTable>
```

You'll end up with this:

image

### Expected behavior

I honestly have no idea 😅  But not this for sure, at least I expect one column to be frozen and the rest in a scroll view. 

Note on the side: I have plan to do some "massive" refactoring regarding how ColumnGroup works (i'll try to keep some backward compatibility but no guarantee), see #6409, so if there is an easy fix let's welcome it otherwise maybe wait for the refacto

### PrimeFaces edition

Community

### PrimeFaces version

13.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

Chrome 110.0

### PR DESCRIPTION
**Pull request by Rapster**
Fix #6409 
Fix #9854

### CODE REVIEW

**Comment by tandraschko** [comment]
before you work on a PR which refactors such a important feature, we should discuss what you refactor and if we are all okay with it; especially PrimeTek and if we can also be backward compatible

**Comment by Rapster** [comment]
PrimeTek has already been pinged regarding this, and no answer. Community is aware of it, and also I'm trying to make it backward compatible as much as I can. If you have any feedbacks, please feel free to share in the original issue

**Comment by Rapster** [comment]
Don't wait for this PR to be merged, I don't think it's gonna happen anytime soon (few things must be done before having this merged)

**Comment by Rapster** [comment]
@primefaces/primefaces-committers I'm actually thinking of not keeping the backward compatibility here, it's a lot of hassle to make it so for a feature which is not so much used...

**Comment by melloware** [comment]
@Rapster i agree that to fix this correctly it needs to be refactored as you have mentioned we just have to make the migration guide extremely detailed.  I think more people use this feature than we think but who knows! 😄

**Comment by Rapster** [comment]
No you're right, I had look on issues, and col group are used more than I thought... But it doesn't change my previous statement on how tricky it is to make things backward compatible. Hopefully, migration should be easy for people using nested grid with flexgrid (just to name one example)

**Pull request closed without merging**
