### PR TITLE
Fix #10909 - Remove Code in 15.0.0 Reminder (DataExporter)

### LINKED ISSUE #10909: Remove Code in 15.0.0 Reminder
- [x] Remove Apache Commons FileUpload stuff (https://github.com/primefaces/primefaces/issues/10751)
- [x] Remove InputSwitch (https://github.com/primefaces/primefaces/issues/10874)
- [x] Remove legacy Chart.JS components and all PF models (https://github.com/primefaces/primefaces/issues/10870)
- [x] Remove `@Deprecated` legacy "table" layouts
- [x] Remove `@Deprecated` FileUpload properties
- [x] Remove `@Deprecated` DataExporter code

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by melloware** [comment]
It's weird why BlockUi ITs is failing and only on Mojarra

**Comment by melloware** [comment]
Oh it's all tests failing

**Comment by melloware** [comment]
I see

Caused by: java.lang.UnsupportedOperationException: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener

**Comment by Rapster** [comment]
ITSystemEventListener is actually called from ConfigureListener... Maybe an issue with Mojarra, anyway let's see if the fix works for both impl

**Review by melloware — APPROVED** [review]

**Pull request merged**
