### PR TITLE
Fix #3998: Checkstyle suppression location fixed to work in IDE and M…

### LINKED ISSUE #3998: CheckStyle: Fix suppression file location
I am using Eclipse so I can get in front of my checkStyle warnings because it can't find the suppression file:

```
!MESSAGE Checkstyle-Plugin: cannot initialize module SuppressionFilter - Unable to find: checkstyle-suppressions.xml
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressionFilter - Unable to find: checkstyle-suppressions.xml
```

Found this fix: https://sourceforge.net/p/eclipse-cs/discussion/274377/thread/3a790081/

Submitting a PR.

### PR DESCRIPTION
**Pull request by melloware**
Fix #3998: Checkstyle suppression location fixed to work in IDE and Maven.

### CODE REVIEW

**Comment by tandraschko** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project primefaces: Failed during checkstyle execution: Failed during checkstyle configuration: unable to parse configuration stream: Property ${samedir} has not been set -> [Help 1]

**Comment by melloware** [comment]
Fixed using this post: http://rolf-engelhard.de/2011/04/using-the-same-suppression-filter-for-checkstyle-in-eclipse-and-maven/

**Comment by tandraschko** [comment]
removed the supressions for now but thanks for the PR

**Comment by melloware** [comment]
Even better...

**Pull request closed without merging**
