### PR TITLE
#4560, change default labelSeparator from ',' to ', '

### PR DESCRIPTION
**Pull request by OBreidenbach**
#4560, include the space after the comma for the default labelSeparator.

### CODE REVIEW

**Comment by OBreidenbach** [comment]
@tandraschko, do I need to create a new issue? Or can you just merge the PR with the old closed issue?

**Comment by tandraschko** [comment]
new issue plz as we will start again to apply PRs after 7.0.

**Comment by OBreidenbach** [comment]
@tandraschko, by the way, what is the timetable for the 7.0 release?

**Comment by tandraschko** [comment]
probably this week

**Comment by OBreidenbach** [comment]
Thanks

**Pull request merged**
