### PR TITLE
Avoid "Uncaught TypeError" for autocomplete's blur event

### PR DESCRIPTION
**Pull request by PlassJ**
Fixed possible "Uncaught TypeError" for autocomplete's blur event.

### CODE REVIEW

**Comment by tandraschko** [comment]
Please create a issue with description before providing PRs.

**Comment by tandraschko** [comment]
Can't we use 
if (stripedItem)
instead
if (typeof(stripedItem) != "undefined")
?

**Comment by PlassJ** [comment]
Looks good to me.

**Comment by tandraschko** [comment]
Would you like to do this change in your PR?

**Comment by PlassJ** [comment]
Done (hopefully) :)

**Comment by tandraschko** [comment]
Thanks!

**Pull request merged**
