### PR TITLE
Fix #11980: Auto detect HTML5 compliance

### LINKED ISSUE #11980: Auto detect HTML5_COMPLIANCE
in Faces impls we detect if the current view uses HTML5 doctype

i think PF could do the same

### PR DESCRIPTION
**Pull request by melloware**
Fix #11980: Auto detect HTML5 compliance

### CODE REVIEW

**Comment by tandraschko** [comment]
It works like expected?

**Comment by melloware** [comment]
I am still testing but I am wondering instead of caching the Methods if we just cache the Boolean result?

**Comment by tandraschko** [comment]
Dont think its worth
We will just switch to normal method call when we remove javax support

**Comment by melloware** [comment]
Understood.

**Pull request merged**
