### PR TITLE
Upgrade to Font Awesome 5.0.1 #3056

### PR DESCRIPTION
**Pull request by ravihariharan**
Upgrade to Font Awesome 5.0.1 #3056

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by mertsincan** [comment]
Thanks a lot for the PR.

**Comment by jxmai** [comment]
@mertsincan  @melloware  Sorry for late to the party. Well, I don't quite agree upgrading font awesome 5 in this release since it could break the UI everywhere on existed applications last time I checked. Keeping in mind that Primefaces is a business oriented UI framework that stability could be the top priority at least from my point of view.

Please note that Font awesome  5 is a really different from font awesome 4. A lot of icons have been removed, some icon definition were changed. 

Even if you check this page: http://localhost:8080/showcase/ui/misc/fa.xhtml. **At least 10%** of the icons are broken or need to be migrated which is a real pain.

image

**Comment by tandraschko** [comment]
@jxmai Yep, thats not good BUT we would have the same problem for the next release. Sometimes users need to migrate something. 100% backward compatibility is just not possible.

**Comment by melloware** [comment]
I agree with @tandraschko with major release like 6.2 is the time to update FA since if users are updating to Jquery 3.X etc this is already a major release users will have to review their app for changes.  Plus the new FA icons are awesome and they have doubled the amount of icons available.

**Comment by melloware** [comment]
On that note I have to look at that showcase page i wonder if I can write something clever that parses the fa.css and generates that page dynamically so we don't have to update it everytime.

**Comment by jxmai** [comment]
Ok, I see. I just wanted to notify that the font awesome 5 migration effort could be a bit high and to make sure we are on the same pace. Please not to forget updating the migration guide.

**Comment by jxmai** [comment]
> if I can write something clever that parses the fa.css and generates that page dynamically so we don't have to update it everytime.

I like the idea

**Comment by melloware** [comment]
@jxmai Mission accomplished!  https://github.com/primefaces/showcase/pull/57   The page is completely dynamic now.

**Pull request merged**
