### PR TITLE
Fix #5901: Media for PDF remove ;filename from URL

### LINKED ISSUE #5901: Media: request for StreamedContent not captured by FacesServlet and hence 404 is returned
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? not tested
- Does it work on the newest sources in GitHub? not tested
- Application server + version: Tomcat 8.0.39, Tomcat 8.5.55
- Affected browsers: any

## 2) Expected behavior

I can display a pdf file named TEST.PDF supplied through a `StreamedContent` instance whose `getName()` returns `TEST.PDF`.

## 3) Actual behavior

The pdf file is not displayed by `p:media`, a 404 is returned for the generated URL.

## 4) Steps to reproduce

- in my web.xml I have the following mappings for FacesServlet:

```xml
<servlet>
  <servlet-name>Faces Servlet</servlet-name>
  <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
  <load-on-startup>1</load-on-startup>
</servlet>
<servlet-mapping>
  <servlet-name>Faces Servlet</servlet-name>
  <url-pattern>*.faces</url-pattern>
  <url-pattern>*.seam</url-pattern>
  <url-pattern>*.jspx</url-pattern>
  <url-pattern>*.xhtml</url-pattern>
  <url-pattern>/faces/*</url-pattern>
</servlet-mapping>
```

- I have a page with a simple:

```xml
<p:media value="#{myBean.myStreamedDocument}" player="pdf" />
```

- please note that in the above example `myBean.myStreamedDocument` returns a `StreamedContent` instance with `getName()` returning `TEST.pdf`
- `p:media` generates a `<object>` tag whose `data` attribute contains something like this:

    http://localhost:8080/shop-backend/javax.faces.resource/dynamiccontent.properties.jspx;/TEST.pdf?ln=primefaces&v=6.2&pfdrid=494db01692b3882917ffb08752dc12e8&pfdrt=sc&pfdrid_c=true

However, this URL resolves to a 404, because Tomcat (I tested with both 8.0.39 and 8.5.55, which is the latest 8.x one) is not mapping this URL to the `FacesServlet`, probably thinking that the file extension is `.pdf` rather than `.jspx`.

However,  if I change my `StreamedContent` instance to return `TEST.pdf.jspx` from its `getName()` method, all works fine and I can see my pdf. The URL in this case is something like this:

http://localhost:8080/shop-backend/javax.faces.resource/dynamiccontent.properties.jspx;/TEST.pdf.jspx?ln=primefaces&v=6.2&pfdrid=494db01692b3882917ffb08752dc12e8&pfdrt=sc&pfdrid_c=true

Please note that:
- no error log is produced either in the browser console, or in the server log
- I verified that in the first case the `FacesServlet` is not queried at all, because I put a breakpoint on `javax.faces.webapp.FacesServlet.service(ServletRequest, ServletResponse)` and it was not hit when the file name was set to `TEST.pdf`; instead it is when the file name is set to `TEST.pdf.jspx`

## 5) Sample XHTML

```xml
<p:media value="#{myBean.myStreamedDocument}" player="pdf" />
```

## 6) Sample bean

```
public class MyBean {
  public StreamedContent getMyStreamedDocument() {
    // let "is" be a FileInputStream built on a pdf file taken somewhere
    return new DefaultStreamedContent(new BufferedInputStream(is), "application/pdf", "TEST.pdf");
  }
}
```

### PR DESCRIPTION
**Pull request by melloware**
I have proved this definitely does not work with this reproducer. And by removing this filename it works.
[pf-5901.zip](https://github.com/primefaces/primefaces/files/5743493/pf-5901.zip)

### CODE REVIEW

**Comment by tandraschko** [comment]
+1

**Comment by aschneider12** [comment]
In my tests (PF v7.0) when create the StreamedContent  without the atribute "name" for the file, just the InputStream and ContentType the browser render the PDF correctly.

new DefaultStreamedContent(is, cnt); //this work

@jepsar My environment cannot run the OF 12 yet. thanks

**Comment by jepsar** [comment]
@aschneider12 please use English and test with PrimeFaces 12

**Comment by jepsar** [comment]
@aschneider12 please use https://github.com/primefaces/primefaces-test to test with 12

**Comment by aschneider12** [comment]
> @aschneider12 please use https://github.com/primefaces/primefaces-test to test with 12

@jepsar I checkout the primefaces-test and here is, in v7 and v8 the same problem occurs, in v11 not

stream = new DefaultStreamedContent(fis, "application/pdf", null); //v7.0 - ok
stream = new DefaultStreamedContent(fis, "application/pdf", "test.pdf"); //v7.0 - error 404
			
stream = DefaultStreamedContent.builder().contentType("application/pdf").name("test.pdf").stream(() -> fis).build(); //v8.0 - error 404
stream = DefaultStreamedContent.builder().contentType("application/pdf").stream(() -> fis).build(); //v8.0 - OK
			
stream = DefaultStreamedContent.builder().contentType("application/pdf").stream(() -> fis).build(); //v11.0 - OK
stream = DefaultStreamedContent.builder().contentType("application/pdf").name("test.pdf").stream(() -> fis).build(); //v11.0 - OK

**Comment by melloware** [comment]
@aschneider12 this issue was fixed in PF 10.0 see: https://github.com/primefaces/primefaces/issues/5901

so not sure what you need here?

**Comment by aschneider12** [comment]
@melloware sorry I was just looking for a solution in my version and I commented it. Thanks

**Comment by jepsar** [comment]
It's recommended to upgrade. You will enjoy many bug fixes and new features 😁

**Pull request merged**
