### PR TITLE
enh: added docs for FL JPALazyDataModel

### LINKED ISSUE #10691: Docs: add reference to FlowLogix JPA LazyDataModel
### Description

Hi,

I do believe that https://docs.flowlogix.com/#section-jpa-lazymodel is the best and simplest implementation of JPA LazyDataModel. I request it be added to the docs and showcase. Thank you

### Describe the solution you would like

Please add https://docs.flowlogix.com/#section-jpa-lazymodel to docs and showcase

### Additional context

Many ecosystem projects such as PrimeFaces support their community by listing projects that use and enhance the main product.
PrimeFaces can do the same.

### PR DESCRIPTION
**Pull request by lprimak**
fixes #10691

### CODE REVIEW

**Comment by tandraschko** [comment]
i think we should add a new menu entry like "community" and add other community projects
i dont like to have in our code docs

**Comment by tandraschko** [comment]
Please add a new menu "Community" as last item in "Getting started", add a headline "Community projects" and add some links like your and maybe?
https://github.com/omnifaces/arquillian-primefaces
https://github.com/omnifaces/optimusfaces

**Comment by FlipWarthog** [comment]
@melloware @tandraschko Is there already a link for PrimeFaces Extensions or should that be included too?

**Comment by tandraschko** [comment]
Include it pls as first link

**Comment by tandraschko** [comment]
will close this for now
feel free to create a new PR when you had time to work on it

**Comment by lprimak** [comment]
@tandraschko @melloware Please re-open this. It's ready to go.
Thank you

**Comment by melloware** [comment]
It looks like its deleted please submit a new PR.

**Comment by melloware** [comment]
OK

**Comment by melloware** [comment]
I still don't see your changes?

**Comment by lprimak** [comment]
or maybe b/c I force-pushed the chages... but they are there in the branch :)

**Comment by melloware** [comment]
It won't let me re-open

image

**Comment by lprimak** [comment]
ah, ok I'll create a new PR :)

**Comment by lprimak** [comment]
Thanks! Created #10919

**Pull request closed without merging**
