### PR TITLE
Fix #2720: Hidden elements should have the `hidden` HTML attribute

### LINKED ISSUE #2720: SelectBooleanCheckbox: Hidden elements should have the aria-hidden attribute
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: WebSphere 8.5.5.12
- Affected browsers: Internet Explorer/ Chrome/Firefox

## 2) Expected behavior

```
<p:selectBooleanCheckbox
  value="#{applicationBean.application.firstNation}"
  itemLabel="First Nation" />
```

Should render 

```
<div id="applicationForm:j_id1447386971_3_3b2db25b" class="ui-chkbox ui-widget"<div class="ui-helper-hidden-accessible">
  <input id="applicationForm:j_id1447386971_3_3b2db25b_input" name="applicationForm:j_id1447386971_3_3b2db25b_input" autocomplete="off" aria-checked="false" type="checkbox" hidden>
...
```

## 3) Actual behavior

```
<div id="applicationForm:j_id1447386971_3_3b2db25b" class="ui-chkbox ui-widget"<div class="ui-helper-hidden-accessible">
  <input id="applicationForm:j_id1447386971_3_3b2db25b_input" name="applicationForm:j_id1447386971_3_3b2db25b_input" autocomplete="off" aria-checked="false" type="checkbox" >
...
```

Missing `hidden` element causing accessibility tool to flag it.

## 4) Steps to reproduce

```
<p:selectBooleanCheckbox
  value="#{applicationBean.application.firstNation}"
  itemLabel="First Nation" />
```

## 5) Sample XHTML

```
<p:selectBooleanCheckbox
  value="#{applicationBean.application.firstNation}"
  itemLabel="First Nation" />
```

## 6) Sample bean

```
    Boolean firstNation;
    public Boolean getFirstNation() {
        return firstNation;
    }
    public void setFirstNation(final Boolean a) {
       firstNation = a;
    }
```

### PR DESCRIPTION
**Pull request by melloware**
Fix #2720: Hidden elements should have the `hidden` HTML attribute

I found everywhere "ui-helper-hidden-accessible" was hiding an input and added the hidden HTML attribute.

### CODE REVIEW

**Comment by tandraschko** [comment]
Is it correct to use a empty value? 

> In XHTML, attribute minimization is forbidden, and the hidden attribute must be defined as <element hidden="hidden">.

**Comment by tandraschko** [comment]
maybe also hidden=true is more correct as it's a boolean attribute. not sure here @melloware.

**Comment by melloware** [comment]
@tandraschko here is what I tried...

`writer.writeAttribute("hidden", null, null);` did not write anything out. It's like the response writer knew to ignore it.

`writer.writeAttribute("hidden", Constants.EMPTY_STRING, null);` writes out <input id="" hidden> just like the HTML5 docs had it.

`writer.writeAttribute("hidden", "true", null);` writes it out <input id="" hidden="true">

The HTML5 doc has it as a boolean so I suppose there is no harm in making it "true"?

https://www.w3schools.com/Tags/att_global_hidden.asp

**Comment by tandraschko** [comment]
Thats a good question. Not sure if "true" or "" is more vaild. Would be great if you could check the docus and examples on the web.

**Comment by melloware** [comment]
hidden="hidden" appears to be the most correct for XHTML.  So I have updated this PR.

**Differences Between HTML and XHTML**
In XHTML, attribute minimization is forbidden, and the hidden attribute must be defined as `<element hidden="hidden">`.

**Comment by tandraschko** [comment]
I didn't check each component for now but i hope you only applied it to the right elements :D

**Pull request merged**
