### PR TITLE
Fix incomplete PR #2898

### PR DESCRIPTION
**Pull request by fdellwing**
#2898 implemented the ability to click the label in a `selectManyMenu` to select an additional option, but missed the deselection part. This PR fixxes that.

### CODE REVIEW

**Comment by tandraschko** [comment]
@jxmai WDYT?

**Comment by jxmai** [comment]
Thanks. I will check :+1: . @fdellwing, ~~why build failure for this PR~~ ? (most likely upstream issue at that time. Please merge the current upstream codebase to remove the error )

**Comment by fdellwing** [comment]
Should be done, let's see if it fixes the travis build.

**Review by melloware — APPROVED** [review]

**Review by jxmai — APPROVED** [review]
I see. Good catch by the way.

**Pull request merged**
