### PR TITLE
#6296: DataTable: evaluate removal of SelectableDataModelWrapper

### LINKED ISSUE #6296: DataTable: evaluate removal of SelectableDataModelWrapper
follow-up to https://github.com/primefaces/primefaces/pull/6295

originally introduced with https://github.com/primefaces/primefaces/commit/a92e580ac1d4579661653f95001690d154e20851

### PR DESCRIPTION
**Pull request by christophs78**
@rapster: With our current integration-tests i can´t find a regression. But IMO we should add some more integration-tests before we merge this one.

### CODE REVIEW

**Comment by melloware** [comment]
So if I am reading this right the table has to be "selectable" and "filterable" at the same time?

**Comment by christophs78** [comment]
https://github.com/primefaces-extensions/primefaces-integration-tests/pull/34

**Comment by melloware** [comment]
Do you think this will fix this also: https://github.com/primefaces/primefaces/issues/1442

**Comment by christophs78** [comment]
> Do you think this will fix this also: #1442

Sound´s like i should add integration-tests for the combination of filter (and maybe sort) combined with rowedit. I am not sure without checking. 
We all know DataTable is quite complicated and it´s realy hard to tell sometimes why which code was introduced. Does some code still makes sense...

**Comment by tandraschko** [comment]
whats with this PR @Rapster @christophs78 ?

**Pull request closed without merging**
