### PR TITLE
Fix #6913 - DataTable: Sort on ListTableModel fails with NPE

### LINKED ISSUE #6913: DataTable: Sort on ListTableModel fails with NPE
DataTable Sort on ListDataModel fails with NPE - WrappedData List lost after sort order has been changed.
Using List instead of ListDataModel works.

**Environment:**
 - PF Version: _10.0.0-SNAPSHOT_
 - JSF + version: _Mojarra 2.3.14_
 - Java Runtime: 11.0.9.1

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {

    private DataService dataService;
    private DataModel dataModel;

    public DataModel getDataModel() {
         if ( dataModel == null ) {
              dataModel = new ListDataModel<>( dataService.getData() );
         }
         return dataModel;
    }
}
```

**Stacktrace**
```
10:06:24,955 INFO  [javax.enterprise.resource.webcontainer.jsf.context] (default task-7) java.lang.NullPointerException: java.lang.NullPointerException
	at deployment.test-SNAPSHOT.war//org.primefaces.component.datatable.feature.SortFeature.sort(SortFeature.java:154)
	at deployment.test-SNAPSHOT.war//org.primefaces.component.datatable.feature.SortFeature.decode(SortFeature.java:107)
	at deployment.test-SNAPSHOT.war//org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:72)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
	at deployment.test-SNAPSHOT.war//org.primefaces.component.api.UIData.processDecodes(UIData.java:117)
	at deployment.test-SNAPSHOT.war//com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
	at deployment.test-SNAPSHOT.war//com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at deployment.test-SNAPSHOT.war//org.primefaces.component.api.UIData.visitTree(UIData.java:683)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at deployment.test-SNAPSHOT.war//com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at deployment.test-SNAPSHOT.war//com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
	at deployment.test-SNAPSHOT.war//org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at deployment.test-SNAPSHOT.war//javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1008)
	at deployment.test-SNAPSHOT.war//com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:55)
	at deployment.test-SNAPSHOT.war//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at deployment.test-SNAPSHOT.war//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at deployment.test-SNAPSHOT.war//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at deployment.test-SNAPSHOT.war//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
```

```XHTML
<p:dataTable id="datatable" value="#{dataTable018.dataModel}" var="lang" paginator="true" rows="3"
                         filteredValue="#{dataTable018.filteredProgLanguages}" filterEvent="enter" rowKey="#{lang.id}" selectionMode="single"
                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="2,3,5,10">
    <p:column headerText="ID" sortBy="#{lang.id}">
        <h:outputText value="#{lang.id}"/>
    </p:column>
    <p:column headerText="Name" sortBy="#{lang.name}" filterBy="#{lang.name}" filterMatchMode="contains">
        <h:outputText value="#{lang.name}"/>
    </p:column>
    <p:column headerText="First appeared" sortBy="#{lang.firstAppeared}" filterBy="#{lang.firstAppeared}" filterMatchMode="gte">
        <h:outputText value="#{lang.firstAppeared}"/>
    </p:column>
    <p:column headerText="OS" field="mainOs.nameShort"/>
</p:dataTable>
```

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by Rapster** [comment]
@robtha Could you test this PR please? I couldn't reproduce the problem you mentionned regarding globalFilter though

**Comment by robtha** [comment]
I have tested my changes with Primefaces Showcase DataTable Filter example.
Because my method hasActiveFilter did not show the expected result I did some debugging
and discovered, that the globalFilter field contains an empty string (see attached screenshot)

Because `FilterMeta.isActive()` only checks for _null_ it returns true and indicates an active filter.

debug_screen

**Comment by Rapster** [comment]
Arf... Ok I see why... But for this ticket, is that a problem?

**Comment by Rapster** [comment]
@robtha can you confirm the empty globalFilter is a different problem, and does not trigger that problem?

**Comment by melloware** [comment]
@robtha any update on this issue?  We would like to get this resolved for RC2.

**Comment by melloware** [comment]
Wouldn't checking for `isNotEmpty` be a more accurate check?
```java
public boolean isActive() {
        return LangUtils.isNotEmpty(filterValue);
    }
```

**Comment by Rapster** [comment]
filterValue is not necessarily a String, but I'll fix this once I work again on filtering

**Comment by robtha** [comment]
Sorry had a very busy week before vacation. 
I also think that the best solution would be to modify FilterMeta.isActive() so it returns a correct result for global filter too.

Because filterValue might not necessarily contain String values I used `filterValue != null && !LangUtils.isValueEmpty( filterValue.toString() )` to check for active filter.

**Comment by Rapster** [comment]
I already answered to that but my question is, does empty global filter value triggers NPE based on this issue e.g value being a datamodel?

**Comment by Rapster** [comment]
I think I should merge this, besides the issue, it's a better check than simply checking filteredValue has a VE

**Comment by melloware** [comment]
Agreed.

**Comment by tandraschko** [comment]
i wonder if this could lead to a bug that when you filter and remove filter, that the filteredValue isnt "reset" to the whole list?

**Comment by Rapster** [comment]
I'll give it a try

**Comment by Rapster** [comment]
Seems working fine, when no filters set, filterValue is reset to the whole list which IMO is not right but that's another debate

**Comment by melloware** [comment]
When I run PF10 in Myfaces Development mode Myfaces spits out this.
```
13:29:48,337 WARNING [javax.faces.validator.BeanValidator] (default task-3) cannot validate component with empty value: form:dt-products:globalFilter
```

**Pull request merged**
