### PR TITLE
Fix #10046: InputNumber integration test

### LINKED ISSUE #10046: InputNumber: valueChange after updating without actually changing the value
### Describe the bug

InputNumber fires valueChange event even though the value was not changed at all. This happens when it gains focus during an update. (e.g. tab from other input that caused the InputNumber to be updated)

### Reproducer

see: https://github.com/jungm/primefaces/commit/52683d1d9b76d60938a528955d1efe512602cbc4

### Expected behavior

valueChange event is not fired as the user made absolutely no inputs at all in the InputNumber

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by melloware** [comment]
Oh I see caching the maven SNAPSHOT. That is weird though!  Unless its a timing issue and the build should happen first replacing the SNAPSHOT before the Selenium Tests run.

**Comment by christophs78** [comment]
Out of ideas for now.
Maybe we need to add some console.log and check them from our IT´s to see what´s going on...

**Comment by melloware** [comment]
Ok so we are not crazy!!

**Comment by christophs78** [comment]
Github Actions debug-output:
```
http://localhost:8960/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=C60969B1DB3D9C9F2A1D09FECCE45B45?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14378:16 "initialValue: "
http://localhost:8960/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=C60969B1DB3D9C9F2A1D09FECCE45B45?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14378:16 "initialValue: "
http://localhost:8960/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=C60969B1DB3D9C9F2A1D09FECCE45B45?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14487:20 "onchange - initialValue: , newValue: "
http://localhost:8960/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=C60969B1DB3D9C9F2A1D09FECCE45B45?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14488:20 "onchange - Number(initialValue): 0, Number(newValue): 0"
http://localhost:8960/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=C60969B1DB3D9C9F2A1D09FECCE45B45?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14492:24 "return false - A"
```

Local debug-output:
```
http://localhost:8652/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=925673B6293677FA8DDAAB336607530B?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14378:16 "initialValue: "
http://localhost:8652/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=925673B6293677FA8DDAAB336607530B?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14378:16 "initialValue: "
http://localhost:8652/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=925673B6293677FA8DDAAB336607530B?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14487:20 "onchange - initialValue: , newValue: "
http://localhost:8652/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=925673B6293677FA8DDAAB336607530B?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14488:20 "onchange - Number(initialValue): 0, Number(newValue): 0"
http://localhost:8652/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=925673B6293677FA8DDAAB336607530B?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 14492:24 "return false - A"
```

--> no difference ?!?

**Comment by christophs78** [comment]
Client-side stacktrace of the ajax-call on Github Actions:
`http://localhost:8993/javax.faces.resource/core.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT 1963:16 "Error\n    at PrimeFaces.ab (http://localhost:8993/javax.faces.resource/core.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:1963:19)\n    at HTMLInputElement.\u003Canonymous> (\u003Canonymous>:1:185)\n    at HTMLInputElement.jsWrapper (http://localhost:8993/javax.faces.resource/core.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:3484:37)\n    at HTMLInputElement.dispatch (http://localhost:8993/javax.faces.resource/jquery/jquery.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:2:43184)\n    at y.handle (http://localhost:8993/javax.faces.resource/jquery/jquery.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:2:41168)\n    at Function.triggerEvent (http://localhost:8993/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:11849:15)\n    at AutoNumeric._triggerEvent (http://localhost:8993/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:2373:66)\n    at AutoNumeric._onBlur (http://localhost:8993/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:5428:14)\n    at AutoNumeric._onFocusOutAndMouseLeave (http://localhost:8993/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:5011:16)\n    at HTMLInputElement._onFocusOutAndMouseLeaveFunc (http://localhost:8993/javax.faces.resource/inputnumber/inputnumber.js.xhtml;jsessionid=B3E915DD00D3E781C57E37778A89CF02?ln=primefaces&v=13.0.0-SNAPSHOT&v=13.0.0-SNAPSHOT:1063:16)"`

**Comment by christophs78** [comment]
Comparing this to my local output  of a valid change-event:

image

**Comment by melloware** [comment]
So it definitely looks like its firing the `onChange` event in the test when it should NOT be .  But it is so weird we can't make it happen locally.

**Pull request closed without merging**
