### PR TITLE
Fix #6169 - DataTable: Lazy getRowData Repeat the query twice

### LINKED ISSUE #6169: DataTable: Lazy getRowData Repeat the query twice
**1) Environment**

PrimeFaces version: 8.0

org.joinfaces.primefaces-spring-boot-starter  4.3.0

**2) Expected behavior**

I hope that when I select a piece of data in the datatable, getRowData is executed only once.

**3) Actual behavior**

When I select a piece of data in the datatable, getRowData is executed twice, which is very strange.

**AbstractLazyModel**

```
    public abstract class AbstractLazyModel<T> {

    private T[] selects;
    private T select;

    private LazyDataModel<T> lazyDataModel;

    protected abstract LambdaQueryWrapper<T> getQueryParam();

    protected abstract BasicService getBasicService();

    protected  abstract String getKey(T t);


    public LazyDataModel<T> getResultModel() {
        if (lazyDataModel == null) {
            lazyDataModel = new LazyDataModel<T>() {
                @Override
                public List<T> load(int first, int pageSize, Map<String, SortMeta> sortMeta, Map<String, FilterMeta> filterMeta) {
                    int currentPage = (first / pageSize) + 1;
                    Page<T> page =  new Page(currentPage,pageSize);
                    page.setOptimizeCountSql(false);
                    return getBasicService().getResultList(page,getQueryParam());
                }

                @Override
                public T getRowData(String rowKey) {
                    return   (T)getBasicService().findById(rowKey);
                }

                @Override
                public String getRowKey(T t) {
                    return getKey(t);
                }
            };
            lazyDataModel.setRowCount( getBasicService().getRowCount(getQueryParam()));
        }
        return lazyDataModel;
    }

    protected void refresh() {
        this.setSelect(null);
        search();
    }

    public void search() {
        lazyDataModel = null;
    }
```

**Example Bean**

```
@Slf4j
@Data
@Component
@ViewScoped
public class ErpSysCodeTypeView extends AbstractLazyModel<ErpSysCodeType> implements java.io.Serializable {

    @Autowired
    private ErpSysCodeTypeService erpSysCodeTypeService;


    @Autowired
    private PrimeFaces primeFaces;

    @Autowired
    private FacesContext facesContext;

    private SysCodeTypeRequest sysCodeTypeRequest;

    private String codeName;


    private List<ErpSysCodeType> sysCodeTypeList;

    private ErpSysCodeType oldErpSysCodeType;


    public void searchListener() {
        this.refresh();
    }

    public void onRowSelect(SelectEvent<ErpSysCodeType> event) {
      // this.setSelect( event.getObject());
    }




    @PreDestroy
    public void destroy() {
        log.info("ErpSysCodeTypeView destroy");
    }


    @Override
    protected LambdaQueryWrapper<ErpSysCodeType> getQueryParam() {
        return new LambdaQueryWrapper<ErpSysCodeType>().
                likeRight(!StringUtils.isEmpty(codeName),ErpSysCodeType::getName,codeName);
    }


    @Override
    protected BasicService getBasicService() {
        return erpSysCodeTypeService;
    }

    @Override
    protected String getKey(ErpSysCodeType erpSysCodeType) {
        return String.valueOf(erpSysCodeType.getId());
    }

}

```

**Example Xhtml**

```
  <p:dataTable id="dataTableId"
                                         widgetVar="sysCodeTypeTableVar"
                                         value="#{erpSysCodeTypeView.resultModel}"
                                         paginatorPosition="bottom"
                                         rowIndexVar="rowIdx"
                                         rows="10"
                                         lazy="true"
                                         selection="#{erpSysCodeTypeView.select}"
                                         selectionMode="single"
                                         rowKey="#{_sysCodeType.id}"
                                         var="_sysCodeType"
                                         emptyMessage="暂无数据."
                                         paginator="true"
                                         currentPageReportTemplate="查询到{totalRecords}条记录，本页显示{startRecord}～{endRecord}；第{currentPage}/{totalPages}页"
                                         paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                         rowsPerPageTemplate="5,10,15">

                                <p:ajax event="rowSelect"  listener="#{erpSysCodeTypeView.onRowSelect}" process="@this"/>

                                <p:column width="50">
                                    <f:facet name="header">序号</f:facet>
                                    <h:outputText value="#{rowIdx + 1}"/>
                                </p:column>

                                <p:column headerText="字典代码">
                                    <h:outputText value="#{_sysCodeType.code}"/>
                                </p:column>

                                <p:column headerText="字典名称">
                                    <h:outputText value="#{_sysCodeType.name}"/>
                                </p:column>

                                <p:column headerText="启用">
                                    <h:outputText value="#{_sysCodeType.status == 1 ? '启用':'关闭'}"/>
                                </p:column>

                                <p:column headerText="创建时间">
                                    <h:outputText value="#{_sysCodeType.createDate}">
                                        <f:convertDateTime pattern="yyyy-MM-dd HH::mm:ss"/>
                                    </h:outputText>
                                </p:column>

                            </p:dataTable>

```

### PR DESCRIPTION
**Pull request by Rapster**
This PR should fix the corresponding issue, and bring few enhancements also:
- `DataTable#rowKey` should be the single source of truth, today either you use `DataTable#rowKey` or `LazyDataModel#getRowKey` depending your use case, which is a bit confusing.
- in terms of perf:
  - Selection of one element: today it's O(n) which is okay (not great but okay...)
  - Select All: today it would be O(N²) which is pretty bad.
  - Encoding one page: O(N²), `DataTable#getRowData` is called for every row

The solution is pretty simple to make it O(1): using a cache. `DefaultSelectableDataModel` wraps any data model, and build a cache every time `DefaultSelectableDataModel#setWrappedData` is called.

Also, `DataTable#rowKey` becomes optional, by default `System#identityHashCode` is used to create a rowKey of an item.

Let me know what you think, there is only one breaking change: LazyDataModel no longer implements SelectableDataModel, but as I said, since there is a default value for rowKey, the migration should be pretty quick

N.B: this PR is a draft, due to JSF impl few things are not as good as I hoped...

### CODE REVIEW

**Review by melloware — APPROVED** [review]
i actually like this change a lot and it solves the problem of multiple get RowData calls

**Comment by tandraschko** [comment]
puh, thats not a easy PR which we can just merge

we need at least tests
when i see code like "row key cache", i fear that we can break a lot of stuff

also i would like to see another PR with just the isValueLazyDataModel change, sp we can easier look at the other changes
in the PR i would to see something like:
getLazyDataModel()
which returns null if it's not a lazyDataModel, so we reduce the calls to getDataModel, which likely calls a EL each time

**Comment by Rapster** [comment]
I'm not worried about that internal cache since datamodel is constantly reseted (set to null)... I'm trying to figure out a way to improve the `DefaultSelectableModel#isDirty` method. If I can't, I guess we'll have to live with that, although I think few modifications of this PR should go into PF core (like getting rid of LazyDataModel implementing SelectableModel)

**Comment by Rapster** [comment]
I'm gonna close this PR as I don't see a nice and simple way to avoid building cache every time datamodel is reseted.

**Pull request closed without merging**
