### PR TITLE
Fix #6802: Core: Remove redundant initializer

### LINKED ISSUE #6802: Core: Remove redundant initializer
Java will initialize fields with known default values so any explicit initialization of those same defaults is redundant and results in a larger class file (approximately three additional bytecode instructions per field).

### PR DESCRIPTION
**Pull request by arturobernalg**
* Remove redundant initializer

### CODE REVIEW

**Comment by Rapster** [comment]
First create an issue, follow template, explain what's on your mind

**Comment by tandraschko** [comment]
I dont think this brings more performance, i hope the compiler is smart enough to create the same code in both ways ;)

but i think the PR is ok for codestyle / more consistent.

**Comment by Rapster** [comment]
I was planning to change the title, as I don't think it's about performance here but more about code consistency. Issue still need to be created to fully understand what's on your mind (so far we're guessing)

**Comment by arturobernalg** [comment]
Hi @Rapster  @tandraschko 

Agree with change the title. Is basically minor improvement.  The  idea it's avoid explicit initialization

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I am OK with this too.

**Comment by stolp** [comment]
Am I mistaken, or does this patch introduce additional whitespace before the semicolons?

    private boolean zoom = false; 
    private boolean zoom  ;
                        ^^

**Comment by Rapster** [comment]
Well spotted, only in md files though. I quite don't mind boolean initiliazed with false, as it shows explicitely the intention, but that's my personal taste , also IntelliJ doesn't seem to complain about it (there is probably a reason to it)

**Comment by arturobernalg** [comment]
> Am I mistaken, or does this patch introduce additional whitespace before the semicolons?
> 
> ```
> private boolean zoom = false; 
> private boolean zoom  ;
>                     ^^
> ```

Mi mistake. fixed

**Pull request merged**
