### PR TITLE
Fix #7419 Part 1 - use org.json instead of shaded

### LINKED ISSUE #7419: Development: multi-module + shade + IDE - issues
Not a issue for PrimeFaces-users, but a issue for people working on this OpenSource-project.

IntelliJ does not understand shaded classes in multi-module-projects: https://stackoverflow.com/questions/30407065/getting-intellij-to-import-shaded-dependencies-in-a-multi-module-maven-project/30898810

Causes e.g. issues for showcase-module:
image

And i can´t start showcase on Tomcat via IntelliJ-run-configuration any more. (so i´m able do debug showcase/PrimeFaces) I have to fallback to the jetty-plugin.

I don´t expect a short-term-solution for this. Just want to create some awareness of this issue.

### PR DESCRIPTION
**Pull request by christophs78**
... to avoid IDE-issues. (please keep #7419 opened; there seems to be more work to be done)

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
This is a good change.

**Comment by tandraschko** [comment]
Tbh i dont like that 😂

**Comment by melloware** [comment]
Its just for the Showcase so it untangles them.

**Comment by melloware** [comment]
org.shaded classes should be considered almost private to PF and not be used by an external webapp.

**Pull request merged**
