### PR TITLE
Fix #1297

### LINKED ISSUE #1297: Avoid label "Choose" when we don't define the attribute for p:fileUpload
Don't put default label "Choose" when we don't define the attribute for p:fileUpload

If i put the attribute without value, the draw button doesn't have height

image

In the imagen there are a button (left) with a fileUpload (right)

### PR DESCRIPTION
**Pull request by Rapster**
Fix #1297 and better format, plus add some conventionnal brackets. Add **?w=1** to see real changes

### CODE REVIEW

**Comment by tandraschko** [comment]
Please fix your PR to not change our formattings (new line / { })

**Comment by Rapster** [comment]
Done

**Comment by Rapster** [comment]
I think this one can be easily merged

**Comment by tandraschko** [comment]
Will check it before 6.1 release ;)

**Comment by tandraschko** [comment]
Seems to be fixed by mert. Will close it.

**Pull request closed without merging**
