### PR TITLE
Possible solution to fix #4656

### LINKED ISSUE #4656: Slider: validate not working with converter
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: tomcat 9.0
- Affected browsers: all

## 2) Expected behavior
When having a slider **non range** with `<f:converter converterId="converterId" />` at the input field slider should validate values same as with a range slider.

## 3) Actual behavior
For a **non range** slider you get:
java.lang.NumberFormatException: For input string at org.primefaces.component.slider.Slider.validate(Slider.java:146)
A range slider works as expected

## 4) Steps to reproduce

see example below

## 5) Sample XHTML

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Slider</title>
</h:head>
<h:body>
  <h:form>
    <p:growl id="growl" showDetail="true" />
    <h3>Basic</h3>
    <h:panelGrid columns="1" style="margin-bottom: 10px">
        <h:inputHidden id="txt1" value="#{sliderView.hex1}">
          <f:converter converterId="HexDecConverter" />
        </h:inputHidden>
        <h:outputText id="display" value="" />
        <p:slider
          for="txt1"
          display="display"
          style="width: 400px"
          displayTemplate="{value}"
          minValue="0"
          maxValue="255">
        </p:slider>
    </h:panelGrid>
    
    <h3>Range Slider</h3>
    <h:panelGrid columns="1" style="margin-bottom: 10px">
        <h:outputText id="displayRange" value="" />
        <p:slider for="txt6,txt7"
          display="displayRange"
          style="width: 400px"
          range="true"
          displayTemplate="Between {min} and {max}"
          minValue="0"
          maxValue="255">
        </p:slider>
    </h:panelGrid>
    <h:inputHidden id="txt6" value="#{sliderView.hex2}">
      <f:converter converterId="HexDecConverter" />
    </h:inputHidden>
    <h:inputHidden id="txt7" value="#{sliderView.hex3}">
      <f:converter converterId="HexDecConverter" />
    </h:inputHidden>
  
    <p:separator />
  
    <p:commandButton value="Submit" update="values growl" oncomplete="PF('dlg').show();" />
  
    <p:dialog header="Slider Values" showEffect="fade" hideEffect="fade" widgetVar="dlg">
      <h:panelGrid id="values" columns="1" cellpadding="5">
        <h:outputText value="hex 1: #{sliderView.hex1}" />
        <h:outputText value="Range: [#{sliderView.hex2},#{sliderView.hex3}]" />
      </h:panelGrid>
    </p:dialog>
  </h:form>
</h:body>
</html>
```

## 6) Sample bean
```java
public class SliderView implements Serializable {

    private static final long serialVersionUID = -1682856792995977368L;

    private String hex1 = "#26";
    private String hex2 = "#26";
    private String hex3 = "#64";

    public String getHex1() {
        return hex1;
    }

    public void setHex1(final String hex1) {
        this.hex1 = hex1;
    }

    public String getHex2() {
        return hex2;
    }

    public void setHex2(final String hex2) {
        this.hex2 = hex2;
    }

    public String getHex3() {
        return hex3;
    }

    public void setHex3(final String hex3) {
        this.hex3 = hex3;
    }

}
```
```java
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.util.Locale;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.ConverterException;
import javax.faces.convert.NumberConverter;
import javax.inject.Named;

import org.apache.commons.lang3.StringUtils;
import org.primefaces.util.MessageFactory;

import de.gid.ws.webapp.basis.jsf.FaceletsFunktionen;

public class HexDecConverter implements Converter {

    private static final int HEX_RADIX = 16;

    /**
     * Default-Konstruktor.
     */
    public HexDecConverter() {
    }

    @Override
    public Object getAsObject(final FacesContext context, final UIComponent component,
            final String value) {

        BigDecimal alpha;
        if (StringUtils.isBlank(value)) {
            return null;
        } else {
            try {
                Locale locale = FaceletsFunktionen.getLocale();
                DecimalFormatSymbols symbols = new DecimalFormatSymbols(locale);
                DecimalFormat df = new DecimalFormat();
                df.setDecimalFormatSymbols(symbols);
                df.setParseBigDecimal(true);
                alpha = (BigDecimal) df.parse(value);
            } catch (ParseException e) {
                FacesMessage facesMessage = MessageFactory.getMessage(NumberConverter.NUMBER_ID,
                        FacesMessage.SEVERITY_ERROR, new Object[]{
                                value
                        });
                throw new ConverterException(facesMessage, e);
            }
        }
        return "#" + alpha.toBigInteger().toString(HEX_RADIX);
    }

    @Override
    public String getAsString(final FacesContext context, final UIComponent component,
            final Object value) {
        if (value == null) {
            return "";
        }
        if (value instanceof String) {
            String hexstring = StringUtils.remove((String) value, "#");
            BigDecimal alpha255 = BigDecimal.valueOf(Long.parseLong(hexstring, HEX_RADIX));
            Locale locale = FaceletsFunktionen.getLocale();
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(locale);
            DecimalFormat format = new DecimalFormat("0", symbols);
            format.setRoundingMode(RoundingMode.HALF_UP);
            return format.format(alpha255);
        }
        return "";
    }

}
```

### PR DESCRIPTION
**Pull request by patzi**
Maybe there is a more direct approach to fix #4656. because the range slider is already getting the correct values, but i couldn't find it for now.

### CODE REVIEW

**Comment by melloware** [comment]
This looks reasonable to me.

**Comment by tandraschko** [comment]
Thanks!

**Comment by AndrewG10i** [comment]
Guys, not sure how to reach to PF team but is there any chance to have this included in the next fix release (v7.0.11 let say), as this has already affected our app. Thank you!

**Comment by melloware** [comment]
That's up to @mertsincan

**Comment by mertsincan** [comment]
I'll add it to next release.

**Comment by AndrewG10i** [comment]
> I'll add it to next release.

Thank you so much, already got it with 7.0.11! Issue is resolved now properly! )

**Pull request merged**
