### PR TITLE
Fix NotSerializableException 

### PR DESCRIPTION
**Pull request by redrede**
Fix Exception when context parameter (javax.faces.SERIALIZE SERVER STATE=true) of web.xml is used.
The parameter javax.faces.SERIALIZE SERVER STATE=true was used to resolve a memory leak in com.sun.faces.util.LRUMap.

### CODE REVIEW

**Comment by redrede** [comment]
By using the parameter below in web.xml
    
     <context-param>
         <param-name>javax.faces.SERIALIZE_SERVER_STATE</param-name>
         <param-value>true</param-value>
     </context-param>

The following error was generated when using the DataTable component:

09:05:53,593 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-2) Error Rendering View[/restricted/commons/flexregistration/maintainFlexRegistration.xhtml]: javax.faces.FacesException: java.io.NotSerializableException: org.primefaces.component.datatable.DataTable
        at com.sun.faces.renderkit.ServerSideStateHelper.handleSaveState(ServerSideStateHelper.java:420)
        at com.sun.faces.renderkit.ServerSideStateHelper.writeState(ServerSideStateHelper.java:207)
        at com.sun.faces.renderkit.ResponseStateManagerImpl.getViewState(ResponseStateManagerImpl.java:139)
        at javax.faces.application.StateManager.getViewState(StateManager.java:594)
        at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:483)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:325)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:432)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
        at org.apache.deltaspike.jsf.impl.listener.request.DeltaSpikeLifecycleWrapper.render(DeltaSpikeLifecycleWrapper.java:111)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:111)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at br.com.cpqd.saf.commons.commonsweb.filter.SetParamsHeaderFilter.doFilter(SetParamsHeaderFilter.java:58)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at br.com.cpqd.saf.commons.commonsweb.filter.SetParamsHeaderFilter.doFilter(SetParamsHeaderFilter.java:58)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at br.com.cpqd.saf.commons.commonsweb.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:46)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.NotSerializableException: org.primefaces.component.datatable.DataTable
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at java.util.HashMap.internalWriteEntries(HashMap.java:1793)
        at java.util.HashMap.writeObject(HashMap.java:1363)
        at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at com.sun.faces.renderkit.ServerSideStateHelper.handleSaveState(ServerSideStateHelper.java:417)
        ... 77 more

**Comment by Rapster** [comment]
Again, create an issue first following the template...

**Comment by redrede** [comment]
In the migration from Primefaces version 6.2.0 to 10.0.0 the following o
  memory leak problem was observed in my application.

```
3.078.383Kb (85,5%) Object tree for GC root(s) Java Static io.undertow.websockets.jsr.UndertowContainerProvider.webSocketContainers

Root object j.u.concurrent.ConcurrentHashMap@67b430110
	j.u.concurrent.ConcurrentHashMap ↘3.078.383Kb (85,5%), self 208b (< 0.1%), 1 object(s)
		{values} ↘ 3.078.382Kb (85,5%), 2 reference(s)

			io.undertow.websockets.jsr.ServerWebSocketContainer ↘3.078.382Kb (85,5%), self 208b (< 0.1%), 2 object(s)

				.contextToAddFilter ↘ 3.078.362Kb (85,5%), 2 reference(s)

					io.undertow.servlet.spec.ServletContextImpl ↘3.078.362Kb (85,5%), self 176b (< 0.1%), 2 object(s)

						.deployment ↘ 3.063.402Kb (85,0%), 2 reference(s)

							io.undertow.servlet.core.DeploymentImpl ↘3.063.402Kb (85,0%), self 176b (< 0.1%), 2 object(s)

								.sessionManager ↘ 3.061.297Kb (85,0%), 2 reference(s)

									io.undertow.server.session.InMemorySessionManager ↘3.061.297Kb (85,0%), self 176b (< 0.1%), 2 object(s)

										.sessions ↘ 3.061.296Kb (85,0%), 2 reference(s)

											j.u.concurrent.ConcurrentHashMap ↘3.061.296Kb (85,0%), self 1Kb (< 0.1%), 2 object(s)

												{values} ↘ 3.061.289Kb (85,0%), 42 reference(s)

													io.undertow.server.session.InMemorySessionManager$SessionImpl ↘3.061.289Kb (85,0%), self 3Kb (< 0.1%), 42 object(s)

														.attributes ↘ 3.061.285Kb (85,0%), 42 reference(s)

															j.u.concurrent.ConcurrentHashMap ↘3.061.285Kb (85,0%), self 48Kb (< 0.1%), 42 object(s)

																{values} ↘ 3.061.218Kb (85,0%), 863 reference(s)

																	j.u.Collections$SynchronizedMap ↘2.974.930Kb (82,6%), self 3Kb (< 0.1%), 126 object(s)

																		.m ↘ 2.974.925Kb (82,6%), 126 reference(s)

																			com.sun.faces.util.LRUMap ↘2.974.922Kb (82,6%), self 5Kb (< 0.1%), 84 object(s)

																				.table ↘ 1.992.596Kb (55,3%), 84 reference(s)

																					j.u.HashMap$Node[] ↘1.992.596Kb (55,3%), self 9Kb (< 0.1%), 84 object(s)

																						{array elements} ↘ 1.992.587Kb (55,3%), 367 reference(s)

																							j.u.LinkedHashMap$Entry ↘1.992.587Kb (55,3%), self 14Kb (< 0.1%), 367 object(s)

																								.value ↘ 1.493.586Kb (41,5%), 367 reference(s)

																									com.sun.faces.util.LRUMap ↘1.493.488Kb (41,5%), self 9Kb (< 0.1%), 145 object(s)

																										.head ↘ 820.791Kb (22,8%), 145 reference(s)

																											j.u.LinkedHashMap$Entry ↘820.791Kb (22,8%), self 5Kb (< 0.1%), 145 object(s)

																												.value ↘ 781.056Kb (21,7%), 145 reference(s)

																													Object[] ↘781.056Kb (21,7%), self 3Kb (< 0.1%), 145 object(s)

																														{array elements} ↘ 781.052Kb (21,7%), 145 reference(s)

																															j.u.HashMap ↘781.052Kb (21,7%), self 2.597Kb (< 0.1%), 145 object(s)

																																{values} ↘ 766.533Kb (21,3%), 66.933 reference(s)

																																	Object[] ↘766.530Kb (21,3%), self 1.970Kb (< 0.1%), 66.788 object(s)

																																		{array elements} ↘ 764.560Kb (21,2%), 66.480 reference(s)

																																			Object[] ↘762.939Kb (21,2%), self 1.880Kb (< 0.1%), 66.084 object(s)

																																				{array elements} ↘ 761.058Kb (21,1%), 69.193 reference(s)

																																					Object[] ↘609.922Kb (16,9%), self 1.602Kb (< 0.1%), 46.216 object(s)

																																						{array elements} ↘ 608.320Kb (16,9%), 43.297 reference(s)

																																							Object[] ↘606.654Kb (16,8%), self 1.553Kb (< 0.1%), 32.019 object(s)

																																								{array elements} ↘ 605.101Kb (16,8%), 4.085 reference(s)

																																									j.u.ArrayList ↘605.023Kb (16,8%), self 484Kb (< 0.1%), 3.246 object(s)

																																										{list elements} ↘ 604.539Kb (16,8%), 88.929 reference(s)

																																											javax.faces.component.StateHolderSaver ↘604.539Kb (16,8%), self 2.084Kb (< 0.1%), 88.929 object(s)

																																												.savedState ↘ 602.455Kb (16,7%), 36.937 reference(s)

																																													org.primefaces.model.SortMeta ↘592.686Kb (16,5%), self 65Kb (< 0.1%), 1.404 object(s)

																																														.component ↘ 592.354Kb (16,4%), 1.404 reference(s)

																																															org.primefaces.component.column.Column ↘592.354Kb (16,4%), self 131Kb (< 0.1%), 1.404 object(s)

																																																.children ↘ 301.364Kb (8,4%), 1.404 reference(s)
	
																																																.parent ↘ 289.395Kb (8,0%), 270 reference(s)
		
																																																... 4320 more referenced objects retaining 1.463Kb (< 0.1%)
```

  
 To solve this problem, we changed the javax.faces.SERIALIZE_SERVER_STATE from false to true.

What causes the java.io.NotSerializableException in org.primefaces.component.datatable.DataTable.

**Comment by redrede** [comment]
I'm sorry, I didn't see the messages from the first Pull Request when I sent the second Pull Request. As an alert message occurred, I thought it hadn't been sent.
I've never done that, I didn't know the right way to help.
Next time I will try to follow the process correctly.

**Comment by Rapster** [comment]
Use primefaces from jitpack to try with the latest source. Looks like your problem is from SortMeta not DataTable (believe me you don't want to serialize that...) Create an issue from now on

**Pull request closed without merging**
