### PR TITLE
Fix #5497: Expose "data" in exporters

### LINKED ISSUE #5497: DataTablePDFExporter: Accessing Document Object
## 1) Environment
- PrimeFaces version: 8.0RC2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Irrelevant
- Affected browsers: Irrelevant

## 2) Expected behavior

I like to extend the `DataTablePDFExporter` class to export a PDF document with landscape orientation.
For this, I must overload the `preExport` method as I need to call a different constructor for document.

I expected to see a protected `setDocument` method to set the document in `DataTablePDFExporter` from my overloaded method. Would this be possible to add this to the `DataTablePDFExporter` class?

## 3) Actual behavior

I need to overload all methods which are using the document field in DataTablePDFExporter. This is not the best solution here, since a lot of code has to be needlessly duplicated.
..

## 4) Steps to reproduce

Does not apply here.

## 5) Sample XHTML

Does not apply here.

## 6) Sample bean

Does not apply here.

### PR DESCRIPTION
**Pull request by melloware**
@Rapster @stolp please review this refactor makes the exporters more consistent by exposing their "data" as a getter and all have or already had a createXXX method for creating a new instance.

### CODE REVIEW

**Comment by stolp** [comment]
I am fine with this. Thank you!

**Comment by tandraschko** [comment]
me too
@rapster ?

**Comment by Rapster** [comment]
At a glance, okay but I'll have a closer look later (in 9.0)

**Comment by melloware** [comment]
I am going to merge this now as it makes the API more extensible for 8.0. Rapster you can refactor in 9.0 as well but I would like to get this improvement in for 8.0.

**Comment by stolp** [comment]
Thank you for including this in 8.0. If there is an RC3 I am going to test this before the 8.0 release.

**Comment by melloware** [comment]
I am pretty sure there will be an 8.0RC3 usually PrimeTek does 3 RC's before a final release.

**Pull request merged**
