### PR TITLE
Fix #7889: OutputPanel: change loaded attribute to Boolean object

### LINKED ISSUE #7867: OutputPanel: Deferred mode ignored when component is rendered after AJAX interaction
**Describe the defect**

The defect occurs in a page with 2 sections. The first one, which can be viewed as a menubar or a sidebar, is responsible to trigger the load of the second section using AJAX. The second section contains a listing component (e.g., a `p:dataTable`), and for each element in the list, a `p:outputPanel` is rendered, with deferred loading enabled and deferred mode set to "visible".

In this scenario, when the user triggers the load of the second section by clicking in the button of the first section, all of the content in the list is loaded, ignoring the deferred mode configuration (visible).

If the code is changed to load the listing without the need to click in the button of the first section, the configuration works as expected.

**Reproducer**

1. Clone repository https://github.com/rvieira5/primefaces-test
2. Checkout branch **deferred-loading-bug**

**Environment:**
 - PF Version: _10.0_
 - JSF versions: _Mojarra 2.2.20_, _Mojarra 2.3.16_, _MyFaces 2.2.12_, _MyFaces 2.3.9_
 - Affected browsers: _Firefox_, _Opera_, possibly _ALL_

**To Reproduce**
1. Clone repository https://github.com/rvieira5/primefaces-test
2. Checkout branch **deferred-loading-bug**
3. Run the command `mvn jetty:run` in the root directory of the project
4. Open the URL http://localhost:8080/primefaces-test in the browser
5. Choose one of the 6 scenarios
6. Click on the "Load content" button
7. At this point, it is possible to see that all the items were loaded in the page, both by checking visually and by checking the HTTP request in the browser developer tools.

**Expected behavior**
Only the content of the visible items should be loaded in the page.

**Example XHTML**
```html
<div id="loader-container">
    <h:form>
        <p:commandButton update="loaded-container"
                       action="#{testView.setFlag(true)}"
                       value="Load content" />
    </h:form>
</div>

<h:panelGroup id="loaded-container">
    <ui:fragment rendered="#{testView.flag}">
        <p:dataTable value="#{testView.list}" var="obj">
            <p:column>
                <p:outputPanel deferred="true" deferredMode="visible">
                    <div class="loaded-content">
                        Loaded
                    </div>
                </p:outputPanel>
            </p:column>
        </p:dataTable>
    </ui:fragment>
</h:panelGroup>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private List<Object> list;
    private boolean flag;

    @PostConstruct
    public void init() {
        list = new ArrayList<>();

        for (int i = 0; i < 15; i++) {
            list.add(new Object());
        }

        // To load the page correctly, change the following value to true
        flag = false;
    }

    public boolean isFlag() {
        return flag;
    }

    public void setFlag(boolean flag) {
        this.flag = flag;
    }

    public List<Object> getList() {
        return list;
    }

    public void setList(List<Object> list) {
        this.list = list;
    }

}
```

### LINKED ISSUE #7889: OutputPanel: loaded attribute should not require an EL expression
See https://github.com/primefaces/primefaces/issues/7867#issuecomment-927317625

### PR DESCRIPTION
**Pull request by jepsar**
See https://github.com/primefaces/primefaces/issues/7867#issuecomment-927317625

Should I create an issue for this PR?

Fix #7889

### CODE REVIEW

**Comment by tandraschko** [comment]
Yes, please make a new issue

**Comment by tandraschko** [comment]
Or does it fix the linked issue?

**Comment by jepsar** [comment]
> Or does it fix the linked issue?

I don't fully understand the comment(s) by @melloware. It might. It's an improvement at least. Just in case I added an issue.

**Comment by melloware** [comment]
@jepsar i just retested my reproducer with your latest fix and it seems to work fine with his original use case.

**Pull request merged**
