### PR TITLE
Fix #6215: RadioSelection only allow single selection

### LINKED ISSUE #6215: DataTable: Selection; Radio-Buttons; multiple rows can be selected
**Describe the defect**
Regression in 9.0-SNAPSHOT. Multiple rows can be selected by clicking onto the row instead of direct to the radio-button.

**Reproducer**
http://localhost:8080/showcase_war_exploded/ui/data/datatable/selection.xhtml
Example "RadioButton"
image

**Environment:**
 - PF Version: 8.0 works
 - PF Version: 9.0 broken
 - Browser: Chrome, FF, (new) Edge

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by christophs78** [comment]
Looks good. At least in theory. :-) I´ll recheck after it is merged.

**Comment by melloware** [comment]
ok merged give it a try

**Comment by christophs78** [comment]
also good in real world

**Comment by melloware** [comment]
thanks for testing!

**Pull request merged**
