### PR TITLE
Fix #5345: SplitButton support of p:confirm

### LINKED ISSUE #5345: SplitButton: Support for p:confirm
Issue #507 introduced support for `p:confirm` in the menu items of the split button. This issue is about to support the split button itself.

PR is on the way.

### PR DESCRIPTION
**Pull request by fanste**
Add support for p:confirm on the default button of p:splitButton

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by Rapster** [comment]
Safe to merge this one no? WDYT?

**Comment by melloware** [comment]
Looks good to me

**Comment by tandraschko** [comment]
I think we have to use the statehelper instead a var, to be compatible for MyFaces View pooling

**Comment by tandraschko** [comment]
ok, we have a general problem here. we sometimes have normal variables, especially in DataTable.

For now it would be good to change all confirmationScripts to the stateHelper. Can you do it @fanste ?

**Comment by tandraschko** [comment]
will do it

**Pull request merged**
