### PR TITLE
Greedy

### PR DESCRIPTION
**Pull request by wattsec**
Adds greedy attribute to droppable component.

Default value is false, keeping backward compatibility with current implementation.

### CODE REVIEW

**Comment by Rapster** [comment]
Please attach ticket number in your title (e.g `Fix #<ticket_number> - <ticket_title>`) that's how I use to submit PR

**Comment by jxmai** [comment]
found the attached ticket: https://github.com/primefaces/primefaces/issues/3111. And yes I agree with @Rapster 's suggestion since there seems no link between this ticket and the pull based on the first impression.

**Comment by Rapster** [comment]
The description should be clearer. From jQuery website (at least pick few words)

> By default, when an element is dropped on nested droppables, each droppable will receive the element. However, by setting this option to true, any parent droppables will not receive the element. The drop event will still bubble normally, but the event.target can be checked to see which droppable received the draggable element.

**Comment by tandraschko** [comment]
Yep, @julioa please update the attribute description like rapster mentioned.

**Comment by wattsec** [comment]
Hi, I've updated the attribute description. I hope is clear and short enough. J.

**Comment by caiomerino92** [comment]
I need attribute greedy implementation, but I couldn't find it in gitHub.
I'm using primefaces 6.2, but there isn't greedy implementation yet.
How can I get access to the latest code which added greedy attribute to droppable component. Can anyone help me please?

**Comment by Rapster** [comment]
Greedy will be available in 6.3, see #3111 

To get the lastest code, simply clone the repository and `mvn clean install`

**Comment by caiomerino92** [comment]
Thanks a lot

**Pull request merged**
