### PR TITLE
Fix #4513 DataTable add globalFilterFunction (no conflicts)

### LINKED ISSUE #4513: DataTable: custom global filter function
.. allowing to create your own, custom global filter function.

See also: https://stackoverflow.com/questions/54543368/primefaces-datatable-multiple-keyword-search-using-global-filter

### PR DESCRIPTION
**Pull request by jepsar**
Fix #4513 DataTable add globalFilterFunction (no conflicts)

### CODE REVIEW

**Review by melloware — CHANGES_REQUESTED** [review]
Does this also need to be added to to the doc .md file?

**Comment by jepsar** [comment]
@melloware Yes, when #4673 is taken care of. I'll do a PR for the showcase when this PR is merged.

**Comment by jepsar** [comment]
@tandraschko @melloware Okay, #4673 has been taken care of. I'll push changes to the documentation into this PR.

**Comment by jepsar** [comment]
@tandraschko @melloware Documentation has been taken care of.

**Comment by tandraschko** [comment]
Thanks for the PR!

**Pull request merged**
