### PR TITLE
Fix #7020: TriStateCheckbox add 'escape' attribute

### LINKED ISSUE #7020: TriStateCheckbox: Escape Attribute is missing
**Description**
To allow html in the tristatecheckbox's label the escape attribute would be needed similiar to SelectCheckboxButton

**Describe the solution you would like**
Added attribute and 'escape' and handling in renderer

See Pull Request #7019

### PR DESCRIPTION
**Pull request by gako**
Add escape attribute similiar to SelectBooleanCheckbox

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
You need to update `src\main\resources\META-INF\primefaces-p.taglib.xml` and `\docs\10_0_0\components\tristatecheckbox.md`

**Review by melloware — CHANGES_REQUESTED** [review]
See comments

**Comment by melloware** [comment]
@gako any update on this PR?

**Comment by gako** [comment]
ah missed that one, updated the docu now.

**Review by melloware — APPROVED** [review]

**Pull request merged**
