### PR TITLE
Fix #2153 - showAllOption in paginator

### LINKED ISSUE #2153: Re-Add "*" and "All Rows" paginator options
#1072 from sudheerj/ShowAllOption … was overriden by changes from #191 

Please bring back the option to show all rows from the table

### PR DESCRIPTION
**Pull request by lagar84**
Any non-number input, like 'All rows', '*', etc. will render Integer.MAX_VALUE - In practice, is equivalent to all rows.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
Not sure - can't we just skip the current option if it isn't a number?

**Comment by lagar84** [comment]
If we skip the option, it will be not possible to show an "All rows" option to the user. Given the context of this selectOneMenu, sounds reasonable to render all rows if it is not a number. 
This is almost the same as https://github.com/primefaces/primefaces/pull/1072

**Comment by tandraschko** [comment]
I see
woudln't it better to use "uidata.getRowCount()" then?

**Comment by lagar84** [comment]
I thought of using uidata.getRowCount() like #1072, but Integer.MAX_VALUE sounded like a magic number for all rows - it could be useful to test for this particular number in LazyDataModel to retrieve all rows.
I really dont have a preference for Integer.MAX_VALUE or getRowCount, any of it will be good.

Edit: If a row is added to the table, using getRowCount could miss one row? I am not sure, but I was thinking..)

**Comment by tandraschko** [comment]
Thanks for the PR - did it with a IF instead Try/Catch

**Pull request closed without merging**
