### PR TITLE
Fix #12731: Export columns in correct order after reorder

### LINKED ISSUE #12731: Dynamic draggable columns with data exporter question
### Describe the bug

hello, I cloned the repository and checked out version 14.0.5 of primefaces, built it as well as primefaces-showcase.
I subsequently edited the src/main/webapp/ui/data/datatable/columns.xhtml file under the primefaces-showcase, and added p:command button for doing CSV export pointing to the table, and also added draggableColumns="true" to the p:table definition.

After running recompiled showcase, I dragged some columns around to change the column ordering from default, then pressed my exporter button and downloaded a file that had columns in their original order, not in updated one.

Can you please advise as to what is the recommended course of action if i want the column order to be preserved as it is on the screen for this scenario? thank you kindly. Attaching modified file for reference.

### Reproducer

[columns.xhtml.zip](https://github.com/user-attachments/files/17405975/columns.xhtml.zip)

### Expected behavior

_No response_

### PrimeFaces edition

Community

### PrimeFaces version

14.0.5

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #12731: Export columns in correct order after reorder

cc @newk5

I tested this against:

- [x] #12731 
- [x] #7200 
- [x] #9197

### CODE REVIEW

**Comment by tandraschko** [comment]
i general it looks good, however we could adjust the naming a bit in master at least, it quite hard to read:

exportableColumns -> exportableColumnsCache
exportcolumns -> exportableColumns
visibleColumnMetadata -> exportableColumnsMetadata

i feel it makes a difference, maybe there are some other adjustments possible to make it more readable

**Comment by melloware** [comment]
I agree the names are a mess let me adjust them.

**Comment by melloware** [comment]
Renamed looks much better now!

**Comment by tandraschko** [comment]
+1

**Pull request merged**
