### PR TITLE
Fix #5009 - Refactor AbstractMenu/Splitbutton common methods

### LINKED ISSUE #5009: Refactor AbstractMenu/Splitbutton common methods
First, since I introduced  `OutcomeTargetRenderer#encodeOnClick()` (see 9521ca5c539dfa382ca9b151ae5130418a0a513c), `OutcomeTargetRenderer` is awkwardly bound to Menu API. IMO, it's a bad design I introduced 😅 _(Doesn't mean the commit is bad :wink:)_ Why? `OutcomeTargetRenderer` is for `UIOutcomeTarget` components. `AbstractMenu` and `SplitButton` are not.

Second, `AbstractMenu` and `SplitButton` are sharing some common methods (e.g `AbstractMenu#findMenuItem()`, `SplitButton#broadcast()` and `BaseMenuRenderer#decode()`

PR in his way to refacor all of that. Again, feedbacks are welcome

### PR DESCRIPTION
**Pull request by Rapster**
First draft

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Again this is a really nice refactoring.

**Comment by Rapster** [comment]
Can this be reviewed please I'd like this to get this merged into master

**Comment by tandraschko** [comment]
will check it in 1-2 weeks

**Comment by tandraschko** [comment]
I like your changes, thanks!
I will just do a small refactor to match DialogReturnAware

**Pull request merged**
