### PR TITLE
Fix #10909: Remove deprecated InputSwitch

### LINKED ISSUE #10909: Remove Code in 15.0.0 Reminder
- [x] Remove Apache Commons FileUpload stuff (https://github.com/primefaces/primefaces/issues/10751)
- [x] Remove InputSwitch (https://github.com/primefaces/primefaces/issues/10874)
- [x] Remove legacy Chart.JS components and all PF models (https://github.com/primefaces/primefaces/issues/10870)
- [x] Remove `@Deprecated` legacy "table" layouts
- [x] Remove `@Deprecated` FileUpload properties
- [x] Remove `@Deprecated` DataExporter code

### PR DESCRIPTION
**Pull request by melloware**
Fix #10909: Remove deprecated InputSwitch

### CODE REVIEW

**Review by Rapster — APPROVED** [review]

**Comment by Rapster** [comment]
The fact that it's failing is odd..

**Comment by Rapster** [comment]
Might be failing because of #11516 ?

**Comment by melloware** [comment]
That is weird. The tests were passing before. Let's see how it goes!

**Comment by Rapster** [comment]
Maybe the PR has not been updated with recent changes, and we probably have made changes that makes this PR fail?

**Pull request merged**
