### PR TITLE
#8355 Split DataTable026Test

### PR DESCRIPTION
**Pull request by jepsar**
Firefox IT of #8355

### CODE REVIEW

**Comment by jepsar** [comment]
@melloware the first part does not work for me locally, but I guess it's due to my screen width.

**Comment by melloware** [comment]
yep firefox fails for me locally too but as long as we get it working on the server i will be happy for now.

**Comment by jepsar** [comment]
Cool, it's passing again! @melloware @christophs78

**Comment by melloware** [comment]
woo hoo!   Safari failed last night but I didn't look at it yet

**Comment by christophs78** [comment]
Safari fails since we upgraded to Selenium 4.
IMO because it´s enormous slow. (was already slow before on Safari; got even worse with Selenium 4 because of whatever)

**Pull request merged**
