### PR TITLE
Fix #4036: Documentation Picklist escape default true, rearranged props.

### LINKED ISSUE #4036: PickList: String values are encoded on submit
1) Environment
- PrimeFaces version: 6.2.8
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**
- Application server + version: JBoss EAP 7.0.8.GA
- Affected browsers: Not depends on the browser

## 2) Expected behavior
`DualModel<String>` containing strings with `&` is supposed to contain same string after submit

## 3) Actual behavior
`DualModel<String>` contains encoded strings with `&amp;` instead of `&` after submit

## 4) Steps to reproduce
Create picklist with `DualModel<String>` filled with strings with `&`

## 5) Sample XHTML
```xml
      <h:form>
        <p:pickList value="#{pickListModel.model}"
                    var="value"
                    itemLabel="#{value}"
                    itemValue="#{value}">
        </p:pickList>

        <p:commandButton value="Submit" action="#{pickListModel.post}" />
      </h:form>
```
## 6) Sample bean
```java
package org.example;

import java.util.ArrayList;
import java.util.Collections;
import javax.el.MethodExpression;
import javax.faces.view.ViewScoped;
import org.primefaces.model.DualListModel;
import org.springframework.stereotype.Component;

@Component
@ViewScoped
public class PickListModel {

    private DualListModel<String> model;

    public PickListModel() {
        model = new DualListModel<>();
        model.setSource(new ArrayList<>(Collections.singletonList("&source&")));
        model.setTarget(new ArrayList<>(Collections.singletonList("&target&")));
    }

    public DualListModel<String> getModel() {
        return model;
    }

    public void setModel(DualListModel<String> model) {
        this.model = model;
    }

    public void post() {
        System.out.println(model.getTarget());
    }
}
```

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
please don't refactor the docu, only do this in 7.1 directory
mert and i agreed on to freeze the 7.0 docu for refactoring

**Comment by melloware** [comment]
Ahh sorry about that. I didn't know.  I just fixed it to make the minor change.

**Comment by tandraschko** [comment]
could you please also change this in 7.1?

**Comment by melloware** [comment]
Yep didn't realize you made a new folder let me fix.

**Pull request closed without merging**
