### PR TITLE
Fix #9485: ContentLength to long from int

### LINKED ISSUE #9485: DefaultStreamedContent.contentLength is Integer
I think Long would be better for bigger files.

### PR DESCRIPTION
**Pull request by melloware**
Fix #9485: ContentLength to long from int

### CODE REVIEW

**Comment by tandraschko** [comment]
Can you uncomment all old externalContext calls and add a comment?

**Comment by melloware** [comment]
I will update and add comments

**Comment by melloware** [comment]
Old code commented out with comment above explaining why in both places.

**Comment by tandraschko** [comment]
+1

**Pull request merged**
