### PR TITLE
Fix #10762 - Chronoline: generate unique client ids per iteration

### LINKED ISSUE #10762: Chronoline: Inherit UIData
### Describe the bug

In the following example:
```xhtml
<p:chronoline value="#{searchChatBean.conversations}" var="conv">
    <p:commandLink action="#{searchChatBean.switchConversation(conv)}" update=":chat" process="@this">
          <h6 class="mb-0">#{conv.title}</h6>
    </p:commandLink>
</p:chronoline>
```

When `searchChatBean.switchConversation(conv)`  called `conv` is always `null`. However, replacing `p:chronoline` with `ui:repeat` fixes the issue.

### Reproducer

_No response_

### Expected behavior

Item iteration works in the same way as in `ui:repeat`.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

4.0.1

### Java version

17

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by Rapster**
Fix #10762

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Nice!  I would like to put this in 14.0.0

**Comment by Rapster** [comment]
inheriting from UIData is overkill (UIData is simply a custom UIRepeat which supports row/column and has special options) which is not needed here.

**Comment by tandraschko** [comment]
are you sure about that?
AFAIR MyFaces UIRepeat is just a copy of UIData and vice-versa
both have almost the same LOC (2100 vs 2200)

**Comment by Rapster** [comment]
It would make sense at least UIData inherits UIRepeat... Anyway, I switch to PF UIData (the idea would be to get rid of UITabPanel)

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
looks good to me
@melloware if you can test the showcase, +1 to put it into 14.0.0-RC2

i will work on #11569 today, i'm fine if you could release a RC2 on weekend and do the final in ~2 weeks
did we forget to rename milestones after releasing RC1?

**Comment by melloware** [comment]
Great plan @tandraschko i will do an RC2 this weekend after your PR for the Locale change.

**Pull request merged**
