### PR TITLE
fix: schedule: URL events enable phishing attacks (#4154)

### PR DESCRIPTION
**Pull request by cnsgithub**
After applying this PR you can perform the reproduction steps from the issue once again. Then you'll notice the redirect on the opener is gone and the target site is showing 
image

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by cnsgithub** [comment]
Successfully tested with latest Firefox, Chrome and IE 11.

**Comment by tandraschko** [comment]
Why not doing it like in the owasp cheatsheet?
https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Tabnabbing

**Comment by cnsgithub** [comment]
@tandraschko Thanks for pointing out this `windowFeatures ` parameter of `window.open`. However, I just tested with this piece of code and it doesn't seem to work correctly:
```javascript
                var targetWindow = window.open(calEvent.url, $this.cfg.urlTarget, 'noopener,noreferrer');
                targetWindow.opener = null;
```
Both windows are getting redirected to https://cnsgithub.github.io/foo/ then in latest Firefox and Chrome. It just seems to be working in Internet Explorer.

**Comment by tandraschko** [comment]
I wonder if we should make it configurable in general (but enabled per default) as some portals may depend on it (same for the link rel="noopener noreferrer" later)

**Comment by cnsgithub** [comment]
Hi @tandraschko, what do you want to enable per default - security or phishing? :jack_o_lantern: 

Do you have any preferences for attribute names we could introduce for `p:schedule`, e.g. `noopener="true|false"` or `opener="false|true"`? Or do you prefer it even more fine-grained, having it attached to the `ScheduleEvents`?

Or were you thinking of having it globally configured just once in `web.xml`? I think that might be too coarse-grained.

**Comment by tandraschko** [comment]
pishing per default ofc :D

I would call it "noopener" with "true" per default

Hmm, i don't know. I would do it on component level for now, not for each event.

**Comment by cnsgithub** [comment]
@tandraschko Added attribute `p:schedule noOpener="true"`. This needs to be documented in the user guide.

**Pull request merged**
