### PR TITLE
Fix #7733: DataScroller: add loading facet

### LINKED ISSUE #7733: DataScroller: add loading facet
Which should be shown when data is being loaded, similar to #7712

### PR DESCRIPTION
**Pull request by jepsar**
Fix #7733

Screenshot 2021-09-04 at 10 57 41

You can enable the `loading` facet while developing like:
```js
PF('ds').loadStatus.appendTo(PF('ds').loaderContainer);
```

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
Cant we render the HTML?
Passing it as widget param might destroy escaping
Also not sure about Scripts

**Comment by jepsar** [comment]
Sure thing. I'll try to fix it asap. I'll be on vacation for one week from Wednesday through.

**Comment by jepsar** [comment]
Done

**Comment by tandraschko** [comment]
Whats the old loader facet?

**Comment by jepsar** [comment]
That to show a load button to load data on click instead of scroll

**Comment by tandraschko** [comment]
All right
Looks good for me
I just wonder about the loadStatus.remove call

**Comment by tandraschko** [comment]
can you fix conflicts please? then we can merge, i did a bit more review

**Comment by jepsar** [comment]
@tandraschko done

**Pull request merged**
