### PR TITLE
Fix #11398: jQuery 4.0.0

### LINKED ISSUE #11398: jQuery 4.0.0
See: https://blog.jquery.com/2024/02/06/jquery-4-0-0-beta/

Should be done in 15.0.0 so it can be heavily tested.  I want to try and add Trusted Types support as well.

### PR DESCRIPTION
**Pull request by melloware**
Fix #11398: jQuery 4.0.0

### CODE REVIEW

**Comment by melloware** [comment]
OK good Integration Tests caught errors!

**Comment by melloware** [comment]
@Rapster I fixed it. FileUpload was using `$.type` which was removed in Jquery 4 and has been deprecated since 3.3 I searched the rest of the code base and no one else is using `$.type`

**Comment by Rapster** [comment]
mmh, that's our first patch of blueimp fileupload...

**Comment by melloware** [comment]
well i think i had fixed other Jquery deprecations in the past I think I just missed this one.

**Pull request merged**
