### PR TITLE
#5483: DataView: add multiViewState

### PR DESCRIPTION
**Pull request by christophs78**
Showcase-PR: https://github.com/primefaces/showcase-facelift/pull/110

### CODE REVIEW

**Comment by Rapster** [comment]
I would go differently about it. Have an interface `MultiViewStateAware<T>` with methods:
- isMultiViewState
- restoreState: void
- getState(boolean create): T (I think you should be able to have a default impl here)
- reset: void (will be called by PrimeFaces#multiViewState facade)

On top of my head, that should be enough

**Comment by Rapster** [comment]
Don't bother, i'll do the interface thingy as I need it for #5482

**Comment by tandraschko** [comment]
@christophs78 can you adjust your PR? as we had many changes now regarding multiViewState, i think we can apply it

**Comment by christophs78** [comment]
Yes, i´ll update this PR.

**Comment by christophs78** [comment]
Updated this PR and showcase-PR.

**Comment by tandraschko** [comment]
Can you call it #saveMultiViewState? Otherwise it's to much relation with the JSF viewstate

**Comment by tandraschko** [comment]
and #isMultiViewState probably misses a @Override

**Comment by christophs78** [comment]
Good points. Done.

**Comment by tandraschko** [comment]
Thanks, perfect!

**Pull request merged**
