### PR TITLE
Fix #8470: ARIA readonly and disabled attribute removal

### LINKED ISSUE #8470: ARIA: Hidden and ReadOnly Inputs
**Describe the defect**
ARIA should not repeat hidden or readonly if the type is already hidden or readonly.

image

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
Can you Check other screenreaders? Just wonder why we introduced it

**Comment by melloware** [comment]
@tandraschko I can only image it was in there defensively or at the time we thought it was the safe and right thing to do but its definitely wrong.  The screenreaders do not need it.

**Comment by melloware** [comment]
@miedrl do you want to confirm this issue?

**Comment by miedrl** [comment]
> @miedrl do you want to confirm this issue?

@melloware What exactly do you mean by "confirm this issue"?

**Comment by jepsar** [comment]
I can review this tonight, because I'd need to dive into the specs.

**Comment by melloware** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden

image

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-readonly

image

**Comment by melloware** [comment]
> > @miedrl do you want to confirm this issue?
> 
> @melloware What exactly do you mean by "confirm this issue"?

@miedrl  I assumed you were using screenreaders since you have been reporting accessibility issues. The spec seems pretty clear we do not need `aria-hidden` and `aria-readonly` when the `input` is already `readonly or hidden`

**Comment by melloware** [comment]
@jepsar any chance you had to review this? It removes a ton of noise from W3C Validator checking.

**Comment by jepsar** [comment]
Based what I'm reading on MDN it looks ok!

**Review by jepsar — APPROVED** [review]

**Pull request merged**
