### PR TITLE
Fix #10549 - UITable: cache columns when possible

### LINKED ISSUE #10334: DataTable: dynamic columns have wrong order after sorting
### Describe the bug

When you use a p:dataTable with dynamic, sortable, draggable columns (p:columns) the ordering gets lost:
- change order of columns by dragging
- click on a column header to sort
Result: the headers are still in the manually changed order, but the data is in the original order

This occurs (at least) since PF 10.0.

### Reproducer

This can be reproduced with the showcase project:
- edit src/main/webapp/ui/data/datatable/columns.xhtml: add draggableColumns="true"
- execute the steps described above

### Expected behavior

Expected result: column data should be in the manually changed order (aligned with the column headers)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

17

### Browser(s)

_No response_

### LINKED ISSUE #10549: UITable: rework caching columns
### Description

After #10334 I recently realized that the cached columns was useless when used with dynamic columns, as it is invalidated all over the place whenever we iterate over rows. This is due to #6659, as there is no details in there, I tried to simplify few things based on this sample #2154

### Describe the solution you would like

simplification

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rapster**
Fix #10549 - UITable: Rework caching columns

### CODE REVIEW

**Comment by tandraschko** [comment]
it seems we have some tests using p:columns
could you please check if we should add some more? i dont know TBH why we cached it anyway, maybe a performance thing

Otherwise the change looks good

**Comment by Rapster** [comment]
Is draggable columns supported by PF selenium?

**Comment by melloware** [comment]
I don't think we ever figured that out because moving the mouse and dragging is a PITA with Selenium if I remember.

**Review by melloware — APPROVED** [review]

**Comment by Rapster** [comment]
Still wanna try one thing

**Comment by Rapster** [comment]
Ok I gave up trying to reproduce the scenario... Like you said it's a PITA...

**Comment by Rapster** [comment]
I finally came up with an IT where I test hybrid columns (mulitple p:columns + p:column)

**Comment by melloware** [comment]
Fantastic!

**Pull request merged**
