### PR TITLE
fixed multiple autoComplete with dropdown

### PR DESCRIPTION
**Pull request by Karolis92**
This fixes problem mentioned on #1478

### CODE REVIEW

**Comment by anishakamble** [comment]
I'm currently using PF 6.0 How do I get this fix?

**Comment by anishakamble** [comment]
I'm currently using PF 6.0 via a pom dependency. How do I get this fix?

**Comment by Karolis92** [comment]
Primefaces team haven't accepted it yet...

**Comment by anishakamble** [comment]
Hmm okay. Any idea how long they take?

**Comment by Karolis92** [comment]
No idea... You can add css to your project manually. Just don't forget to match the selector

**Comment by anishakamble** [comment]
Hmm yes. Thanks.

**Pull request merged**
