### PR TITLE
Fix #4123 DataTable: Fix keyboard checkbox selection and styles.

### LINKED ISSUE #4123: DataTable: With selectionMode=multiple it's not possible to select a row using the keyboard
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Yes Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
We should be able to select a row using the keyboard.

## 3) Actual behavior
When we use the keyboard to select a row using the checkbox, the row is not selected.

## 4) Steps to reproduce
1. Open https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml
2. Go to the datatable example with checkbox.
3. Use the keyboard to focus the checkbox of a row and press the key space.
4. The row is selected and unselected.

### PR DESCRIPTION
**Pull request by wsaca**
This PR fix the issue #4123 and improve the checkbox styles to align them with the ones applied to the selectBooleanCheckbox component.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by wsaca** [comment]
I would like this error is fixed in PF 6.3, if this PR has something wrong I could change it.

**Comment by tandraschko** [comment]
mert will probably review it until RC1

**Comment by wsaca** [comment]
I hope the datatable keyboard selection issue could be resolved before the release of PF 7.0

**Comment by melloware** [comment]
@mertsincan Can you review this one?  Looks good to me but you are the datatable master!

**Comment by mertsincan** [comment]
Hi @wsaca,

Does the fix work for you? When I focus on a row using Tab and press Space key, I can't select it. 

Test code with your fixes;

[test.txt](https://github.com/primefaces/primefaces/files/2863682/test.txt)

**Comment by mertsincan** [comment]
Thanks a lot for the PR! I made some changes using your PR on datatable.js. Also, after 7.0.Final, I think of removing the conditions like;
```
if(!box.hasClass('ui-state-active')) {
   box.addClass('ui-state-hover');
}

or 

if(input.prop('checked')) {
   box.removeClass('ui-state-active');
}

etc.
```
I need to make changes in themes to remove them.

Best Regards,

**Pull request closed without merging**
