### PR TITLE
Fix #8416 - DataTable: clarify / rename selection attributes

### LINKED ISSUE #8416: DataTable: clarify / rename selection attributes
Currently we have following attributes to define selection and modes:

**p:dataTable**
`selectionMode=single | multiple` - defines the selection mode, without rendering checkbox/radiobuttons
`rowSelectMode=new | add | checkbox` - defines how selection should work when clicking on the row itself; new = unselect all rows before; add = just add the new to the selection; checkbox = disables selection on the row itself
`disabledSelection=EL` - disables the current row for selection

**p:column**
`selectionMode=single | multiple` - defines the selection mode, with rendering a checkbox or radiobuttion; rows are still selectable
`selectRow=true | false` - disables the selection in content of the current column

### PR DESCRIPTION
**Pull request by Rapster**
fix #8416

### CODE REVIEW

**Review by melloware — APPROVED** [review]
I like this change

**Comment by tandraschko** [comment]
will review end of the week

**Comment by tandraschko** [comment]
its on my list for this week

**Comment by tandraschko** [comment]
+1 looks good for me

**Pull request merged**
