### PR TITLE
#1834 fix blockui render position

### LINKED ISSUE #1834: p:dialog bad renderer combined with p:blockUI
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version?
- Application server + version: All
- Affected browsers: All
## 2) Expected behavior

The p:dialog render normally combined with p:blockUI
...
## 3) Actual behavior

I want to block the p:dialog when a event of p:commandButton is present, but when i put a p:blockUI to block the p:dialog the dialog render bad.

**p:diaglog without p:blockUI**
image

**p:diaglog with p:blockUI**
image

..
## 4) Steps to reproduce

.. 
## 5) Sample XHTML

`<p:commandButton value="Open Dialog without p:blockUI" type="button" onclick="PF('dlgNoBlock').show()" />
  <p:dialog id="dlgNoBlock" widgetVar="dlgNoBlock" dynamic="true" header="Title" modal="true" showEffect="fade" hideEffect="fade" resizable="false"
    closeOnEscape="true">
    <p:commandButton id="btnNoBlock" value="Do Something and Not Block Dialog" />
  </p:dialog>
  <p:commandButton value="Open Dialog with p:blockUI" type="button" onclick="PF('dlgBlock').show()" />
  <p:dialog id="dlgBlock" widgetVar="dlgBlock" dynamic="true" header="Title" modal="true" showEffect="fade" hideEffect="fade" resizable="false"
    closeOnEscape="true">
    <p:commandButton id="btnBlock" value="Do Something and Block Dialog" />
    <p:blockUI block="dlgBlock" trigger="btnBlock" />
  </p:dialog>`
..
## 6) Sample bean

Not necessary
..

### PR DESCRIPTION
**Pull request by vonnai**

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Thanks for the PR. I will wait until others weigh in.

**Comment by tandraschko** [comment]
basically +1 as the code looks good

however, please test some cases if everything still works 
like blocking the whole body, relative elements, the dialog as in the example...

**Comment by melloware** [comment]
@tandraschko I have poked around a few scenarios with this fix and it looks good to me.

**Comment by tandraschko** [comment]
@vonnai could you please provide a simple test.xhtml without beans to replicate your issue?

**Comment by melloware** [comment]
@tandraschko I attached a reproducer to the ticket and testing so far looks good with this fix.

**Pull request merged**
