### PR TITLE
Fix #12104: TabMenu make using activeIndex optional

### LINKED ISSUE #12104: TabMenu: Generalize such that no explicit index setting is required
### Description

Currently, the tab index must be set explicitly, as in the show demo:

```
<p:tabMenu activeIndex="#{param.i}">
        <p:menuitem value="Home" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-home">
            <f:param name="i" value="0"/>
        </p:menuitem>
        <p:menuitem value="Calendar" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-calendar"
                    badge="#{menuBadgeView.badgeModel}">
            <f:param name="i" value="1"/>
        </p:menuitem>
        <p:menuitem value="Edit" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-pencil"
                    disabled="true">
            <f:param name="i" value="2"/>
        </p:menuitem>
        <p:menuitem value="Documentation" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-file">
            <f:param name="i" value="3"/>
        </p:menuitem>
        <p:menuitem value="Settings" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-cog">
            <f:param name="i" value="4"/>
        </p:menuitem>
    </p:tabMenu>
```

To use the tabMenu in a more dynamic setting where the menu items are created dynamically, it would be good not to be forced to set the tab index explicitly. Rather, the tab index could be derived from the position of the menuitem while the activeIndex is handled by the tabMenu component.

### Describe the solution you would like

I would like to be able to use the tabMenu as follows:

```
<p:tabMenu>
        <p:menuitem value="Home" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-home" />
        <p:menuitem value="Calendar" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-calendar" badge="#{menuBadgeView.badgeModel}"/>
        <p:menuitem value="Edit" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-pencil" disabled="true"/>
        <p:menuitem value="Documentation" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-file"/>
        <p:menuitem value="Settings" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-cog"/>
    </p:tabMenu>
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #12104: TabMenu make using activeIndex optional

- [x] If you use `activeIndex` like today it all works just like it does now
- [x] If you choose not to use `activeIndex` it uses browser SessionStorage to remember tabs between navigations

cc @tuerker

### CODE REVIEW

**Comment by tandraschko** [comment]
I feel we need some discussion first here

**Comment by melloware** [comment]
marked as draft

**Comment by tandraschko** [comment]
im a bit unsure about this in general. IMO if you reload a page or hit the page some views later again, why should the tab still be selected, even the content now might be completely different?
should it somehow only be remembered during postbacks?

second, its actually a alternative implementation of multiViewState
this is a general problem with multiViewState; when should it be stored on server side, when should it be stored on sessionStorage on the client?
you know; if you store on client side, there will be flickering; not on server side.

**Comment by melloware** [comment]
Got it let me investigate MVS for this component.

**Comment by tandraschko** [comment]
i think this is more a general discusssion, we would need to change other menus, too.

**Comment by tandraschko** [comment]
Closing in favor of: https://github.com/primefaces/primefaces/issues/12926

**Comment by tandraschko** [comment]
i really appreciate your work here @melloware, i just care about consistency here

**Comment by melloware** [comment]
No problem!

**Pull request closed without merging**
