### PR TITLE
Fix #59: DataExporter for ColumnGroup

### LINKED ISSUE #59: DataExporter with p:columnGroup
Add columnGroup support to DataExporter, probably only to pdf, maybe excel as well.

### PR DESCRIPTION
**Pull request by melloware**
Ported code from PF Extensions and cleaned it up greatly.

**Before:**
image

**After:**
image

**PDF:**
image

### CODE REVIEW

**Comment by tandraschko** [comment]
Please dont use final everywhere

**Comment by melloware** [comment]
Sorry a I copied from PFE. I will fix them all

**Comment by tandraschko** [comment]
all right, feel free to merge the PR when you removed it

**Comment by melloware** [comment]
Removed all finals so merging

**Pull request merged**
