### PR TITLE
Update Rome and Commons-io

### LINKED ISSUE #5991: General: Update rome and commons-io
Please update a few dependencies to their latest versions for multiple reasons including security updates, sniffed issues, and others

### PR DESCRIPTION
**Pull request by GedMarc**
Updates the two libraries rome and commons io to their latest counterparts

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
@melloware can you please give it a good test?
AFAIR we downgraded a commons dependency in the past because of shading

**Comment by melloware** [comment]
Yep I will do thorough testing. File upload and download especially.

**Comment by tandraschko** [comment]
yep, please.
See issues like https://github.com/primefaces/primefaces/issues/4111

**Comment by melloware** [comment]
so far I have been testing ImageCropper, FileUpload, and FileDownload which all use Commons-IO with no issues.

I also tested FeedReader with the new Rome and also no issues.

**Comment by tandraschko** [comment]
did you also try commons fileupload? see https://github.com/primefaces/primefaces/issues/4236

AFAIR BoundedInputStream was the problem as it has other class dependencies in newer versions

**Comment by melloware** [comment]
I will try that it looks like ImageCropper also uses BoundedInputStream and was OK but I will try Commons FileUpload as well.

**Comment by GedMarc** [comment]
With the introduction of the native file upload decoder I found that most of these were resolved?

If you are using the commons file upload (remove native from the service provider list), i think that may be a valid test scenario - otherwise we are using this in production, cropper upload and download :)

**Comment by tandraschko** [comment]
nope, commons fileuplod is still there
native still makes problem sometimes

if commons fileupload works -> we can leave it as it is now

**Comment by melloware** [comment]
Tested Commons FileUpload and its working perfectly so I think we are good.

**Comment by GedMarc** [comment]
whoop whoop onto the next!

For interests sake though - I run through the native uploader on JDK 14, in a JImage / docker kuber setup
@tandraschko i don't wanna run into anything nasty, could you lead me to the right place to find the sometimes issue so i can just knock that one out in a separate pr

**Comment by Rapster** [comment]
I think upgrading commons-io has a few side effects. I just tried with `FileUpload#validateContentType` and I'm having this exception:

```
GRAVE: org/apache/commons/io/output/AppendableWriter
java.lang.NoClassDefFoundError: org/apache/commons/io/output/AppendableWriter
	at org.primefaces.util.FileUploadUtils.isValidFileContent(FileUploadUtils.java:224)
	at org.primefaces.util.FileUploadUtils.isValidType(FileUploadUtils.java:149)
	at org.primefaces.util.FileUploadUtils.tryValidateFile(FileUploadUtils.java:308)
	at org.primefaces.component.fileupload.FileUpload.validateValue(FileUpload.java:84)
	at javax.faces.component.UIInput.validate(UIInput.java:1016)
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1317)
	at javax.faces.component.UIInput.processValidators(UIInput.java:733)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:608)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIForm.visitTree(UIForm.java:355)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1308)
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:73)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1411)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.AppendableWriter
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:543)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 64 more

```

I tried so hard to figure out how this could happen but I don't see when the class loader try to load `AppendableWriter`

**Comment by melloware** [comment]
That is really strange I tried commons fileupload before I merged this and wasn't having any issues.    Let me investigate.

**Comment by Rapster** [comment]
To correctly test that scenario, you need to set `validateContentType` and `accept` attributes.

**Comment by melloware** [comment]
OK so i believe its used in `IOUtils.copyLarge(in, out);` in FileUploadUtils.

I fixed it by adding the AppendableWriter to our Shaded list of classes and I added a showcase example using `validateContentType` for Single example so we have this example in the future.

**Comment by Rapster** [comment]
Yeah but I wish I could understand where this class is loaded from `IOUtils#copyLarge`. BTW why commons-io has been upgraded? So far we're only using four methods of it so I wonder what this upgrade fixes. There was a reason to stick to 2.4 so we don't have to shade more than necessary

**Comment by melloware** [comment]
I think its 2 things. 
1) not using older libraries 2.4 was released Jun 12, 2012 which is 8 years ago. 
2) we were stuck using IO 2.4 because it still supported Java 7.  Now that we support Java 8 we can move to their latest version which is 2.7 released May 4, 2020.

**Comment by melloware** [comment]
And its used in IOUtils because copyLarge wraps the writer which is this method here:
https://github.com/apache/commons-io/blob/bf3108c1fa0831cb86dc263f5391c3708475c714/src/main/java/org/apache/commons/io/IOUtils.java#L3320-L3338

**Comment by melloware** [comment]
Actually looking at it I am not sure why its being class loaded.

**Comment by Rapster** [comment]
Mmmh using the latest version is always relevant argument, but I don't think java version is an issue here. As stated in pom.xml

```xml
        <!-- will be shaded; use 2.4 as later versions would require multiple files to shade -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.7</version>
            <optional>true</optional>
        </dependency>
```

For more details, see https://github.com/primefaces/primefaces/issues/4019

My personal thought is that, sure that's one way to fix it but at this rate we'll have to shade more and more classes which are not usefull to PF. Since we're using very few things from commons-io right now, I would keep 2.4.

> And its used in IOUtils because copyLarge wraps the writer which is this method here:
https://github.com/apache/commons-io/blob/bf3108c1fa0831cb86dc263f5391c3708475c714/src/main/java/org/apache/commons/io/IOUtils.java#L3320-L3338

We're not using methods with Writer parameters

**Comment by melloware** [comment]
So my fear is staying on a library from 2012 seems like a bad idea in today's world.  If that were the argument the reason we are shading is so we can upgrade future versions and grab all the changes in an open Source library.  If that is not the concern here and we are going to stay on 2.4 from 2012 why not just copy the 3 classes into PF and NOT shade IO?

**Comment by GedMarc** [comment]
and here i was gonna suggest a bump to .15 xD

**Comment by GedMarc** [comment]
Vulnarability wise there's nothing between the versions  
https://snyk.io/vuln/maven:commons-io:commons-io 

As the base is changing to JDK 8 though, maybe possible to leave it as an external reference? it is a very commonly used library everwhere

**Comment by tandraschko** [comment]
-1 as external dependency

we should shade or copy it; if it works fine now, its ok for me

**Comment by melloware** [comment]
-1 as external dependnecy as it violates PF goal of a standalone JAR with optional third party deps.

Unless we find anymore missing shaded classes i say we leave it shaded at 2.7. @Rapster in your testing let us know if you find any more missing shaded classes and then maybe we can decide to "unshade" at that point.  OK?

**Comment by GedMarc** [comment]
Cool :)

**Comment by Rapster** [comment]
For users using servlet containers not embedding `commons-io` (jetty does embed commons-io 2.5), they'll certainly have the same problem with `StringBuilderWriter` due to the static initialization in `IOUtils`. Just for info, I tried to remove that static initialization and I no longer have any class loading issues, so my thought was `StringBuilderWriter` in commons-io 2.5 tried to load `AppendableWriter` but does not, so I remain clueless)

**Comment by tandraschko** [comment]
so the bug is still not fixed on e.g. tomcat?

**Comment by melloware** [comment]
I think to prevent this problem in the future we should copy the 3 classes from Commons IO 2.4 and remove the dependency in the pom.xml.   There is no point in shading them if we are NEVER going to upgrade commons IO.  I can submit a PR if you want?

**Comment by Rapster** [comment]
Or, we create our own IOUtils. Copying all these classes while we just use a very few methods is probably not the best way to go. 

FYI, `FastStringWriter` is the same as `StringBuilderWriter` from `commons-io`

**Comment by tandraschko** [comment]
yep
-1 for just copy
we use some IOUtils methods which are basic read/write utils, which can be inside LangUtils.

The BoundedInputStream needs to be copied, we also only use 1 method of the FilenameUtils AFAICS

**Comment by Rapster** [comment]
3 methods from FileNameUtils, but after having a look at `FileNameUtils#getPrefixLength`, there is lot of use of constants so it might be simpler to just get the whole file... Shading that file is okay then

**Comment by melloware** [comment]
OK so do we have a suggested plan of attack?

**Comment by tandraschko** [comment]
i would revert the upgrade for now and only extract the code if we need some security update or similar in the future

**Comment by melloware** [comment]
Reverted: https://github.com/primefaces/primefaces/pull/6166

**Pull request merged**
