### PR TITLE
#5363 DatePicker: inline="true" broken; refactor

### PR DESCRIPTION
**Pull request by christophs78**
@Rapster : this way better?

### CODE REVIEW

**Comment by tandraschko** [comment]
IMO it was better before :D

maybe its better to move those checks to the renderer and leave @(body) the default in the datepickerbase

**Comment by Rapster** [comment]
Yes +1 to move that new method in the renderer

**Comment by christophs78** [comment]
satisfied?

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for the PR, @christophs78 ;) But, I think we can add if-check to datepicker core widget to control appendTo and inline. If the calendar has inline mode, the appendTo is unnecessary. 

Thanks a lot again ;)

**Pull request closed without merging**
