### PR TITLE
Fixes #11043 - Advanced FileUpload: migrate client side validation to CSV

### LINKED ISSUE #11043: Advanced FileUpload: migrate client side validation to CSV
see #11001

### PR DESCRIPTION
**Pull request by tandraschko**
Fixes #11043, #11212

### CODE REVIEW

**Comment by melloware** [comment]
I marked this breaking change so it gets picked up in our 14.0.0 release notes that way

**Comment by tandraschko** [comment]
its ready now

**Comment by tandraschko** [comment]
seems even that allowTypes was not validated in `mode=simple skinSimple=false` before, not its working
i stripped this tests a bit

**Comment by tandraschko** [comment]
should be fixed now

**Pull request merged**
