### PR TITLE
Fix #6917: Add StyleBuilder

### LINKED ISSUE #6917: StyleBuilder: create style attribute easily
**Description**
Similar to #6610 for created style classes we need one similar for creating style attribute.

### PR DESCRIPTION
**Pull request by melloware**
Added Builder and I picked SkeletonRenderer to show its capabilities and how much it cleans up IF ELSE's!

### CODE REVIEW

**Comment by tandraschko** [comment]
please add some unittests

**Comment by melloware** [comment]
Added unit tests to test all cases

**Comment by tandraschko** [comment]
another test with multiple calls to builder.add would be nice, so we catch all cases

**Comment by melloware** [comment]
Added "complex" use case with multiple different `adds`

**Pull request merged**
