### PR TITLE
Fix time handling for mindate and maxdate, Fix #5186

### LINKED ISSUE #5186: DatePicker: pattern messed with LocalDateTime and showTime="true"
## 1) Environment
- PrimeFaces version: trunk
- Application server + version: jetty 9.20
- Affected browsers: all

## 2) Expected behavior
The user-provided pattern is not modified.

## 3) Actual behavior
HH:mm is added to the pattern, causing conversion errors.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
```xhtml
<h:form>
	<div>
		<p:outputLabel for="date1" value="Date1" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date1" value="#{testViewCdi.date1}" showTime="true"/>
		<p:message for="date1"/>
	</div>
	<div>
		<p:outputLabel for="date2" value="Date2" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date2" value="#{testViewCdi.date2}" showTime="true" pattern="dd/MM/yy HH:mm"/>
		<p:message for="date2"/>
	</div>
	<div>
		<p:outputLabel for="date3" value="Date3" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date3" value="#{testViewCdi.date3}"/>
		<p:message for="date3"/>
	</div>
	<div>
		<p:outputLabel for="date4" value="Date4" style="display: inline-block; width: 120px;"/>
		<p:datePicker id="date4" value="#{testViewCdi.date4}" pattern="dd/MM/yy"/>
		<p:message for="date4"/>
	</div>
	<p:commandButton id="sub" value="submit" update="@form"/>
</h:form>
```

## 6) Sample bean
```java
@Named
@ViewScoped
public class TestViewCdi implements java.io.Serializable {

	private java.time.LocalDateTime date1 = java.time.LocalDateTime.now();

	private java.time.LocalDateTime date2 = java.time.LocalDateTime.now();

	private java.time.LocalDateTime date3 = java.time.LocalDateTime.now();

	private java.time.LocalDateTime date4 = java.time.LocalDateTime.now();

	// getters and setters
}
```

### PR DESCRIPTION
**Pull request by NicolaIsotta**

### CODE REVIEW

**Comment by tandraschko** [comment]
@christophs78 @mertsincan can you review?

**Comment by mertsincan** [comment]
Hi @NicolaIsotta,

Firstly, thanks a lot for the PR ;) Could you please change parseOptionValue method for this issue?
- remove parseMinMaxValue method
- change parseDate with parseDateTime method in parseOptionValue method.

I'll check your PR asap.

**Comment by NicolaIsotta** [comment]
@mertsincan 
I've added a new method because parseOptionValue is used for parsing disabledDates.

**Comment by christophs78** [comment]
@NicolaIsotta , @mertsincan : https://github.com/primefaces/showcase-facelift/pull/85 adds examples for this to the Showcase

I´m sorry, but i think we have to do some more work....
- DatePicker on the client-side IMO does not limit time (timeOnly="true" and showTime="true"); 0-datepicker.js; renderDateCellContent checks for date.selectable; renderHourPicker and renderMinutePicker does not check minDate / maxDate; this may be relative easy to implement for timeOnly="true" but much harder for showTime=true
- DatePicker on the server-side does not validate time (timeOnly="true" and showTime="true"); we need to add some checks to DatePicker#validateValueInternal (we need to look for LocalTime; and check for java.util.Date and timeOnly="true"; we need to look for LocalDateTime and for java.util.Date and showTime="true")

IMO this is not a new issue for PrimeFaces 8.0; i think this limitations already came with PrimeFaces 7.0

**Comment by christophs78** [comment]
We also should look into https://github.com/primefaces/primefaces/issues/4627. (https://github.com/primefaces/showcase-facelift/pull/86; adds examples for this to the Showcase)

**Comment by christophs78** [comment]
We have similar issues with showTime=true and timeOnly=true.

**Comment by NicolaIsotta** [comment]
I can take a look at the server-side part; the client side is a bit beyond my skills.
Should we create new issues?

**Comment by christophs78** [comment]
Same for me. It would be really great to get some help from @mertsincan who is the author of 0-datepicker.js.

**Comment by christophs78** [comment]
@NicolaIsotta : Thanks for your work! 
I´ll look into the client-side JS later this day. I won´t add client-side-time-restricitions for now. But i hope to figure out, why the hour-selector is disabled in some usecases. And I´ll try to fix this. (It´s not ideal, but in this way we make sure a) the user is able to select time-values b) there´s server-side validation thanks to your work.)

**Comment by christophs78** [comment]
Some analytics of the client-side part....
- 0-datepicker.js already has functions validateHour and validateMinute. Both function seem to be ok.
- part of the issue seems to be we send for mindate and maxdate only the date-part to the client
`pf.cw("DatePicker","widget_form_time3",{id:"form:time3",inline:false,userLocale:"en",dateFormat:"m\/d\/y",minDate:"11\/6\/19",maxDate:"11\/20\/19",selectionMode:"single",showOnFocus:true,rangeSeparator:"\-",showTime:true});`

Think we need to send minDate and maxDate always with the date- and time-part to the client. (and ignore the date-only-pattern for this.)

**Comment by christophs78** [comment]
Uuups... your PR still compiles 7.1-SNAPSHOT. My local ShowCase uses 8.0-SNAPSHOT. Fixed this and have to recheck.

**Comment by NicolaIsotta** [comment]
Yep, just noticed my fork is 34 commits behind. I'll try to update/rebase without making a mess.

**Comment by christophs78** [comment]
Looks way better now. You did initialy the right things. :-)
Some minor issues are left:
- showTime=true, maxDate 11/20/19 15:00, currentDate 11/13/19 18:20; user switches within DatePicker from 11/13 to 11/20, time is still 18:20; 11/20/10 18:20 is past maxDate; for this usecase we should change time after switching date to maxDate; same for minDate
- timeOnly=true, maxDate 15:00, currentDate 18:20; we should not default to currentDate (now) if this is before minDate or past maxdate

**Comment by christophs78** [comment]
@NicolaIsotta , @melloware : IMO this PR is ready to be merged. We may work on the minor client-side issues noted in my comment yesterday in a separat PR.

**Pull request merged**
