### PR TITLE
Fix #5579: Spinner do not allow non numeric characters

### LINKED ISSUE #5579: Spinner: should not allow to enter non-numeric values
The p:spinner component should not allow to enter non-numeric values. 

## 1) Environment
- PrimeFaces version: 8.0 RC3

## 2) Expected behavior

The spinner component allows only numeric values and does not let the user enter any symbols that would lead to non-numeric values.

Above that the spinner should only allow only values that are instances of the underlying number class. For instance, if the spinner is invoked with Long/Integer/Short values it should automatically apply decimalPlaces="0". 

Ideally, all bean validation constraints should be also fully respected to.

## 3) Actual behavior

Current you can enter any string. In some cases, the spinner will crop them to numeric values, in some not. See Below:

* you can enter -1-222 and will produce -1.

* when you enter .022.222 it will even be accepted as it is.

## 4) Steps to reproduce

Just use the basic spinner demo https://www.primefaces.org/showcase/ui/input/spinner.xhtml
and enter the above values.

## 5) Sample XHTML

..

## 6) Sample bean

..

### PR DESCRIPTION
**Pull request by melloware**
Failing Integration Tests proving the bugs.
https://github.com/primefaces-extensions/primefaces-integration-tests/commit/2028db3f4cf8670825892ce6eb0698ca72885860

```
Error:  Failures: 
Error:    Spinner001Test.testDecimalSeparator:97 expected: <34> but was: <3>
Error:    Spinner001Test.testInvalidCharacter:80 expected: <0> but was: <abc0>
Error:    Spinner001Test.testThousandSeparator:114 expected: <1,456> but was: <14,560>
Error:    Spinner002Test.testInvalidCharacter:83 expected: <> but was: <abc>
[INFO] 
Error:  Tests run: 114, Failures: 4, Errors: 0, Skipped: 1
```

### CODE REVIEW

**Comment by melloware** [comment]
Passing Integration Tests after merging this fix.

https://github.com/primefaces-extensions/primefaces-integration-tests/actions/runs/368763582

**Comment by tuerker** [comment]
is this fix already merged into the master? i used the latest PF snapshot. there it was still not working. you can still enter non-numeric characters for spinner on a numeric field. 

Screenshot from 2020-11-19 12-11-31

or is there still something to be fixed?

**Comment by melloware** [comment]
Yep its merged in and you can see I have a Integration Test proving the fix works.
```java
 @Test
    @Order(3)
    @DisplayName("Spinner: GitHub #5579 Test integer invalid characters should be ignored")
    public void testInvalidCharacter(Page page) {
        // Arrange
        Spinner spinner = page.spinner;
        Assertions.assertEquals("0", spinner.getValue());

        // Act
        ComponentUtils.sendKeys(spinner.getInput(), "abc");
        page.button.click();

        // Assert
        Assertions.assertEquals("0", spinner.getValue());
        assertConfiguration(spinner.getWidgetConfiguration());
    }
```

**Comment by tuerker** [comment]
thanks. good to know. then, there must be another bug (as you can see from screenshot above) which appears under certain conditions. hope to find that and provide you a reproducer.

**Comment by tuerker** [comment]
could be good if the delete, backspace, left and right-arrow buttons would still work. useful in case of longer numbers. i know than one could discuss whether the spinner is the right widget in such a case.

**Comment by tandraschko** [comment]
why isnt spinner type=number?

**Comment by melloware** [comment]
> why isnt spinner type=number?

Good question it looks like it has always been this way.   Want me to submit another ticket changing it to `type=number`???

**Comment by tandraschko** [comment]
you have to check all features if thats possible
some ppl would like to see it for AutoNumeric buts thats not possible because of prefix/suffix strings

**Comment by melloware** [comment]
I can try it. I have quite a few Integration tests testing the Spinner now so we would see if any fail.  That is the nice thing of adding these Integration Tests!

**Comment by melloware** [comment]
confirmed its type=text because of `prefix` and `suffix`.  The `type=number` breaks that feature.

**Pull request merged**
