### PR TITLE
Fix #5523: RowsPerPage always set data values

### LINKED ISSUE #5523: DataTable: rowsPerPage from paginator broken after using a filter
## 1) Environment
- PrimeFaces version: 8.0-SNAPSHOT (commit 6b6c2be from 2020-01-15)
- Does it work on the newest released PrimeFaces version? Version? It works on 7.0, can't test 7.0.x.
- Does it work on the newest sources in GitHub? No, it's broken.
- Application server + version: Jetty 9.4.15 from primefaces-test
- Affected browsers: Tested with Firefox 67 and 71 but probably independent from browser

## 2) Expected behavior
DataTable has a paginator which supports a _{RowsPerPageDropdown}_ to select number of rows displayed per page. This dropdown should work even after filtering for a column was used.

## 3) Actual behavior
Once filtering was used, the rowsPerPage-dropdown stops working. The user has to change filter again, so apply to changes in the drowdown.

## 4) Steps to reproduce

* clone https://github.com/matinh/primefaces-test.git using the branch _dataTable-rowsPerPage_ with `git clone 'https://github.com/matinh/primefaces-test.git' -b dataTable-rowsPerPage`
* change directory `cd primefaces-test`
* run `mvn jetty:run-exploded`
* goto http://localhost:8080/primefaces-test/
* try changing the number of rows per page, which works
* now apply a filter (for example "o" in the second column) which triggers an AJAX request and reduces displayed rows correctly
* remove the filter and try again to change the number of rows per page, which now has no effect.
 
## Further comments
* This issue is a regression bug. It used to work with 7.0 but no longer works with recent 8.0-SNAPSHOT versions.
* This issues is probably related to issue #4931 respectively to the changes from PR #4956.

### PR DESCRIPTION
**Pull request by melloware**
I think we need to always set the "data" values and not optionally set them. @matinh please test

### CODE REVIEW

**Comment by matinh** [comment]
@melloware thanks for the quick response and the fix. Your suggested fix solves my concrete problem. And I was already thinking about the same fix. However, two issues come to my mind:
1. A potential NPE when the argument to `Integer.valueOf()` is `null`. Not sure if this could ever happen.
2. The semantic changes again, compared to the original fix, based on https://github.com/primefaces/primefaces/issues/4931#issuecomment-505080207. And I'm afraid this could re-introduce the issue #4931.

**Comment by melloware** [comment]
yes can you try my fix and see if it regresses #4391 ? I didn't test that.

**Comment by matinh** [comment]
Yes, your fix breaks #4391 again, so we need to find some other solution.

**Comment by melloware** [comment]
Actually even with my fix this scenario is still broken.

1. Set RowsPerPage to 1.
2. Filter String field by character "o".
3. use the Pagintor to go to Page 2.
4. Now set RowsPerPage back to 5...nothing happens. That should cause the table to repaint with 5 rows.

**Comment by matinh** [comment]
I just double-checked: your fix works for me (but re-introduces #4391). Maybe you mixed something up with used primefaces version?
However, as the fix introduces another problem, it won't be usable anyway.

**Pull request closed without merging**
