### PR TITLE
solve ajax update not work for selectonemenu if inside <ui:component> and rendered via facet 

### PR DESCRIPTION
**Pull request by markusg80**
Solve issue #1790. Please review if this generate side effects

### CODE REVIEW

**Comment by tandraschko** [comment]
We do it the same as myfaces (the jsf impl) does.
Does it work with h:selectOneMenu correctly for you?

**Comment by tandraschko** [comment]
Same for Mojarra. Will close the PR as we are aligned with the JSF specs.

**Comment by markusg80** [comment]
With h:selectonemenu it works!

**Comment by markusg80** [comment]
Please reopen

**Comment by tandraschko** [comment]
If it works with h:selectOneMenu, than the fix in this PR is not correct. The empty value handling, which is changed by your PR, is the same as in the JSF impl.

**Pull request closed without merging**
