### PR TITLE
Fix #6359: Dynamic downloads should not be cached

### LINKED ISSUE #6359: FileDownload: configure Cache-Control
**Description**
Currently the fileDownload component uses Cache-Control: public and Pragma: public as the default response header.  Sometimes users have the possibility to download sensitive data. These files should not be cached anywhere. (especially considering the GDPR)

**Describe the solution you would like**
Adding a new attribute "cache-handling" or possibly a generic "response-headers", where the cache-control level can be configured.

### PR DESCRIPTION
**Pull request by melloware**
Consolidated cache control into ResourceUtils.

3 spots are caching and were all doing it slightly differently.

### CODE REVIEW

**Comment by tandraschko** [comment]
1) if (PrimeRequestContext.getCurrentInstance(context).isSecure()) { - can you check why we only add it on https? doesnt make sense for me
2) addCacheControl is to common, maybe addNoneCacheControl

**Comment by melloware** [comment]
OK I called it "addNoCacheControl" as that is a better name thanks!  

I thought that secure only was strange too let me look when that was added.

**Comment by melloware** [comment]
OK the `isSecure` check  was from Cagatay in 2013 with the commit message "SSL fix for IE8". So I think it is safe to remove.

**Comment by tandraschko** [comment]
+1, sounds good

**Pull request merged**
