### PR TITLE
 Fix #5060: DatePicker: No timeInput attribute like Calendar 

### LINKED ISSUE #5060: DatePicker: No timeInput attribute like Calendar
## 1) Environment
- PrimeFaces version: 6.2.21
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Payara 5.192
- Affected browsers: All

## 2) Expected behavior

Datepicker should have timeInput attribute to enter time/date manually like with calendar.

## 3) Actual behavior

There is no obvios way in actual API to get this 

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

..

## 6) Sample bean

..

### PR DESCRIPTION
**Pull request by christophs78**
Showcase-PR: https://github.com/primefaces/showcase-facelift/pull/102

- [x] We should first care about: https://github.com/primefaces/primefaces/pull/5390, https://github.com/primefaces/primefaces/pull/5384, https://github.com/primefaces/primefaces/pull/5377.
- [x] After they are done i have to add timeValidation to this PR. 

@markusg80: Can you check this PR and provide feedback?
@mertsincan: Can you have a look at his PR? It´s "your" component and it would be great to get some valuable feedback.

### CODE REVIEW

**Comment by melloware** [comment]
@christophs78 This is a really impressive and I think its a huge feature win for DatePicker.

**Comment by markusg80** [comment]
It looks good to me! I think this feature is a huge benefit for the Datepicker Component. Because changing time values with mouse only can be annoying and time intensive. Thx

**Comment by melloware** [comment]
@christophs78 do you think this PR also covers this one: https://github.com/primefaces/primefaces/issues/4685

**Comment by christophs78** [comment]
> @christophs78 do you think this PR also covers this one: #4685

No. When we look at https://material.angular.io/components/datepicker/overview#keyboard-interaction this would require much more. And that´s only for the date-component. (I have a blind colleague at work. From my experience making a complex component compliant to https://www.w3.org/WAI/standards-guidelines/aria/ and similar rules is a work of days not of hours.)

One other thing we may think about is defaulting timeInput to true. And maybe apply some css-styles to the time-component-input's to make them look nicer.

**Comment by melloware** [comment]
I agree keyboard accessibility and ARIA support is not an insignificant effort.  And plus all the different ScreenReaders seem to treat things differently similar to browsers so you have to find someone to test them all.

**Comment by markusg80** [comment]
you will merge this pull request into 7.x branch or master sometimes?

**Comment by christophs78** [comment]
> you will merge this pull request into 7.x branch or master sometimes?

That´s up to PrimeTek / @mertsincan. (Because DatePicker is - to some degree - a shared component between PrimeFaces, PrimeNG, PrimeReact and PrimeVue.)

**Comment by mertsincan** [comment]
Thanks a lot @christophs78, I'll check it after RC2 ;)

**Comment by tandraschko** [comment]
@christophs78 can you solve the conflicts?

**Comment by christophs78** [comment]
@tandraschko: Conflicts resolved.

**Comment by christophs78** [comment]
@tandraschko , @mertsincan: Some chance to get this into 8.0? This PR is now open for 2 months...
I know it´s not ideal to add features after the last (planed) RC. But i´m pretty confident this PR does not change the DatePicker-Default-behaviour. Everything i added only applies for `timeInput="true"`.

**Comment by tandraschko** [comment]
thats up to mert

**Comment by melloware** [comment]
@mertsincan this is the last PR not merged for the 8.0 release on Monday.  we would really like to get this important DatePicker feature in for 8.0.  Is there any chance you could review today?

**Comment by christophs78** [comment]
Some chance to get this in for 9.0?  Or is this a unwanted feature due to some reasons i do not know yet.

**Comment by tandraschko** [comment]
here we go ;) also moved the docu to 9.0

**Comment by markusg80** [comment]
@mertsincan: can you please add this to 8.0.1? Its really important feature for my project! I do the effort to migrate my project to pf8 now only for this. So i dont like to use 9.0 Snapshot for production. I have elite subscription so i can get elite version. Or should i do a special build of the 8.0 tag? And when yes how? Im not so expierenced with git i use Subversion in my project.

**Pull request merged**
