### PR TITLE
Fix #4224 When a submenu is clicked the entire panel shouldn't be hidden

### LINKED ISSUE #4224: SlideMenu/TieredMenu: When a submenu is clicked the entire panel is hidden
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Yes Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
When we click the submenu this action shouldn't hide the entire panel.

## 3) Actual behavior
When we click the submenu this action hide the entire panel.

## 4) Steps to reproduce
1. Run the showcase and go to: /showcase/ui/menu/slideMenu.xhtml or /showcase/ui/menu/tieredMenu.xhtml
2. Click the button "Show"
3. Click the first submenu, the entire panel is hidden. That behavior is not the right one.

### PR DESCRIPTION
**Pull request by wsaca**
To resolve the issue #4224.

### CODE REVIEW

**Comment by melloware** [comment]
@mertsincan please review

**Review by melloware — APPROVED** [review]

**Comment by wsaca** [comment]
Hello, is there something wrong with this PR?

**Comment by tandraschko** [comment]
don't think so, just nobody reviewed till now.

**Comment by mertsincan** [comment]
Thanks a lot for the Good PR ;)

**Pull request merged**
