### PR TITLE
donate ajax session timeout listener

### PR DESCRIPTION
**Pull request by eduarddrenth**

### CODE REVIEW

**Comment by Rapster** [comment]
Please create an issue first, so you can explain what this is about

**Comment by eduarddrenth** [comment]
fixes #4109

**Comment by tandraschko** [comment]
Will close the PR for now. You first need to check the root problem.
And a -1 for me to include such a solution to PF - a ViewExpired thought be thrown.

**Comment by eduarddrenth** [comment]
This: https://myfaces.apache.org/wiki/core/user-guide/jsf-and-myfaces-howtos/managing-errors---infos---warnings/viewexpiredexception-and-session-expiry.html is interesting. I'll see how payara does this and what config options I have there and how that cooperates with PF exception handling.

**Pull request closed without merging**
