### PR TITLE
Fix #5817: Dialog CSS issues with height width

### LINKED ISSUE #5817: JS: Remediate all JQMIGRATE deprecations
I think the JQMigrate plugin needs to be run against the showcase and all deprecation warnings should be addressed.

https://github.com/jquery/jquery-migrate

A lot of these deprecation are being removed in Jquery 4.0 so fixing them now will alleviate pain later.

- [x] jQuery.fn.bind()/unbind() are deprecated
- [x] jQuery.isArray is deprecated
- [x] jQuery.isFunction is deprecated
- [x] jQuery.trim is deprecated; use String.prototype.trim 
- [x] Use of number-typed values is deprecated in CSS
- [x] jQuery.fn.click() event shorthand is deprecated, use `on` and `trigger` instead.  Also includes blur, focus, focusin, focusout, resize, scroll, dblclick, mousedown, mouseup, mousemove, mouseover, mouseout, mouseenter, mouseleave, change, select, submit, keydown, keypress, keyup, and contextmenu

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
can you explain it? Must we also fix other places again?

**Comment by melloware** [comment]
Dialog has Height and Width as Java String instead of Integer.

So you can do "100" or "100px" or "100vh" or "100%".  I was adding 'px' on the end of `this.cfg.height` and width when it simply just needs to ensure its a string with `String(this.cfg.height)`

**Comment by melloware** [comment]
I am going to do more testing today with dialogs of various flavors.

**Comment by erickdeoliveiraleal** [comment]
yes it fixed the original issue I was having, but now my dialog which was in center is in left top position.

**Comment by melloware** [comment]
Yep just fixed that please pull and try again.  I "over" fixed it.

**Pull request merged**
