### PR TITLE
fixes #3828 - XSS in PrimeFaces.showMessageInDialog

### LINKED ISSUE #3828: XSS in PrimeFaces.showMessageInDialog
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
Proper escaping

## 3) Actual behavior
Improper escaping

## 4) Steps to reproduce
Go to the showcase, open the console and enter `PrimeFaces.showMessageInDialog({severity:"ERROR", summary:"summary", detail:"<script>alert('xss');</script>"});` This will bring up an alert box.

The aforementioned JS function is also called by method `PrimeFaces.showMessageDynamic `in Java.

### PR DESCRIPTION
**Pull request by cnsgithub**
- supports newlines in unix, windows and apple style
- mitigates XSS
- newlines in summary now working as expected

**Test it:**
`PrimeFaces.showMessageInDialog({severity:"ERROR", summary:"summary\nunix newline\r\nwindows newline\rapple newline", detail:"<script>alert('xss');</script>\nunix newline\r\nwindows newline\rapple newline"});
`

**Result:**
image

### CODE REVIEW

**Comment by cnsgithub** [comment]
Oops, I just realized that IE11 does not support arrow functions: https://caniuse.com/#search=arrow%20functions :disappointed:

**Comment by cnsgithub** [comment]
Now IE11 is supported.

Before:
`var summaryHtml = msg.summary ? msg.summary.split(/\r\n|\n|\r/g).map(line => PrimeFaces.escapeHTML(line)).join("<br>") : "";
`

After:
`var summaryHtml = msg.summary ? msg.summary.split(/\r\n|\n|\r/g).map(function(line) { return PrimeFaces.escapeHTML(line); }).join("<br>") : "";`

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
Ahh, it conflicts now, sry :/

**Comment by cnsgithub** [comment]
Conflict resolved.

**Pull request merged**
