### PR TITLE
Fix for #4931: DataGrid and DataTable: rows- and first-attributes ignored after use of paginator

### LINKED ISSUE #4931: DataGrid and DataTable: rows- and first-attributes ignored after use of paginator
## 1) Environment
- PrimeFaces version: 7.0/7.1-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No, neither with 7.0, nor with 7.1-SNAPSHOT.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source). No.
- Application server + version: Tested with Wildfly 11 and Jetty 9.4.15 from the primefaces-test project.
- Affected browsers: probably all (tested with Firefox 60.7.0esr, Opera 58 and Chromium 75). Note: Opera and Chromium seem to have other problems with 7.1-SNAPSHOT, which is probably unrelated)

## 2) Expected behavior

The `rows`-attribute from the `<p:dataGrid>` component should always use the actual value.

## 3) Actual behavior

After the use of the pager, the `rows`-attribute seems to be ignored and the last value before the pager was used is always used, no matter what the actual value of the rows EL is.

## 4) Steps to reproduce

* clone https://github.com/matinh/primefaces-test.git using the branch _dataGrid_ with `git clone 'https://github.com/matinh/primefaces-test.git' -b dataGrid`
* change directory `cd primefaces-test`
* run `mvn jetty:run-exploded`
* goto http://localhost:8080/primefaces-test/
* use the spinner to change number of rows in the dataGrid
* use pager to switch to another page
* try to use spinner again to change number of rows, which is no longer working.

## Further comments

* There are no JavaScript Errors in the browsers console.
* The setter of the columns-attribute is called with the correct value.

### PR DESCRIPTION
**Pull request by matinh**
Based on @Rawi01's https://github.com/primefaces/primefaces/issues/4931#issuecomment-505080207 I created a PR that fixes https://github.com/primefaces/primefaces/issues/4931.

### CODE REVIEW

**Comment by matinh** [comment]
Sorry guys, I really messed my branch/pull-request up a bit with accidental commits (I'm relatively new to git).
However the final diff should be ok. If you have problems with this PR, let me know.

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
is it really correct to do the assignement (data.setRows, data.setFirst) in the else block?

**Comment by matinh** [comment]
Hmm... that's what @Rawi01 suggested and @melloware gave a thumb up. I know this is not what the original code did, but I thought that was exactly the problem.
The PR definitely fixes the issue and I didn't find any other problems so far.

**Comment by tandraschko** [comment]
sorry but "i tried something and it works" is not enough for me to apply such a PR :/
i would like to have a description in the issue from @Rawi01, why it fixes that issue and what exactly happens before and after the fix.
i just dont have time to retest all changes.

**Comment by melloware** [comment]
Looks like there is a conflict now.

**Comment by matinh** [comment]
@tandraschko: See comments from @Rawi01 and @matinh in the corresponding issue (#4931) and let me know what you think.
@melloware : conflict already resolved.

**Comment by melloware** [comment]
@matinh Looks like there is a new conflict with UIData.  @tandraschko made some fixes yesterday fix the paginator = "All" issue.  Can you merge and retest your changes?

**Comment by matinh** [comment]
Sorry guys. I totally screwed up my fork/branch when merging changes from primefaces into my fork and thus close this PR. I'll try to create a clean new branch and create a new PR for the problem.

**Comment by matinh** [comment]
I created a new PR now, with a clean history and no messed up merges: PR #4956 .

**Pull request closed without merging**
