### PR TITLE
Refactor more FacetUtils

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
Its actually both "component" and "facet"
So not sure where to place it

**Comment by melloware** [comment]
Yeah I saw that too but since it was facet related it felt like we could declutter the Component Utils some more?

**Comment by tandraschko** [comment]
Not sure
It feels more related to common components
Not just exclusive to facets

**Comment by melloware** [comment]
No problem I will close thanks for checking!

**Pull request closed without merging**
