### PR TITLE
Fixed #4808

### LINKED ISSUE #4808: Tree: dropRestrict="sibling" does not work as expected.
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No. Same issue in 7.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Jetty
- Affected browsers: All

## 2) Expected behavior
Node 0
Node 1

Dragging Node 1 over Node 0 should not make node 1 the child of Node 0 (as dropRestrict="sibling")

## 3) Actual behavior

Dragging Node 1 over Node 0 makes Node 1 child of Node 0

Before dragging

Node 0
Node 1

After dragging

Node 0
\> Node 1

## 4) Steps to reproduce
To reproduce use this test (dropRestrict branch) repo - https://github.com/amathew121/primefaces-test/tree/dropRestrict

Go to http://localhost:8080/primefaces-test/

Drag Node 1 on to Node 0. 
Expected nothing to happen. Instead, Node 1 is made the child of Node 0
 

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="form">
            <p:growl id="msgs" showDetail="true" />

            <p:tree id="tree1" value="#{treeDNDView.root1}" var="node"
                    draggable="true" droppable="true" dragdropScope="demo" dropRestrict="sibling">
                <p:ajax event="dragdrop" listener="#{treeDNDView.onDragDrop}" update=":form, :form:msgs" />
                <p:treeNode>
                    <h:outputText value="#{node}" />
                </p:treeNode>
            </p:tree>
        </h:form>
    </h:body>
</html>
```

## 6) Sample bean

```
@Named("treeDNDView")
@ViewScoped
public class DragDropView implements Serializable {
     
    private TreeNode root1;

    @PostConstruct
    public void init() {
        root1 = new DefaultTreeNode("Root", null);
        TreeNode node0 = new DefaultTreeNode("Node 0", root1);
        TreeNode node1 = new DefaultTreeNode("Node 1", root1);
    }
 
    public TreeNode getRoot1() {
        return root1;
    }

    public void onDragDrop(TreeDragDropEvent event) {
        TreeNode dragNode = event.getDragNode();
        TreeNode dropNode = event.getDropNode();
        int dropIndex = event.getDropIndex();
         
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Dragged " + dragNode.getData(), "Dropped on " + dropNode.getData() + " at " + dropIndex);
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
}
```

### PR DESCRIPTION
**Pull request by ghost**
#4808

### CODE REVIEW

**Comment by melloware** [comment]
This PR looks good to me. Although I haven't use this component yet it sounds like you were motivated to fix it.

**Comment by melloware** [comment]
Also fixes: https://github.com/primefaces/primefaces/issues/3543

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
I think we still support ie11, so please dont use Lambda in js

**Comment by tandraschko** [comment]
array.includes is not supported in IE. Can you use the jquery alternative?
Also please just test ie11.

**Comment by melloware** [comment]
@tandraschko I am going to fix the array.includes and test in IE11 and merge this PR.  I need this functionality.

**Pull request merged**
