### PR TITLE
PhotoCam fix WebcamJS 1.0.19 + iOS support

### PR DESCRIPTION
**Pull request by zsalab**
The PhotoCam component in the master not works, the JS upgraded to WebcamJS 1.0.12 but the swf file is not.
The WebcamJS project also added some fixes the current and stable version is 1.0.19, this pull requests fix the swf and js incompatibility and add iOS failback support too. The iOS failback support currently not part of the WebcamJS project, I will create a pull request there soon for add this functionality to the main codebase. The iOS failback support is created by me and it coded as keep the furthermore updates simple as possible (no basic code structure changed is WebcamJS).

This pull request is also extend the PhotoCam whit the functionality to improve the usage in dialog boxes
- autoStart property - by default true to keep the compatibility but now is possible to do not start the camera by default
- attach and detach methods in PF to be able to disable and reenable the camera on the component 

The functionality tested in
- Safari on Mac OS X (latest) -  Adobe flash (latest)
- Google Chrome (latest) on Mac OS X - HTML5
- Firefox (latest) on Mac OS X - HTML5
- Edge (latest) on Windows 10 - HTML5
- Safari on iOS (latest) - iOS failback

Please review and merge this pull request.

Best regards, Zsalab

### CODE REVIEW

**Comment by tandraschko** [comment]
Did you applied the ios sutff on the WebcamJS or is it from a update?
If you applied it on WebcamJS, it would be better to provide a PR in WebcamJS first. Otherwise your changes would be lost if we upgrade the WebcamJS.

**Comment by zsalab** [comment]
I've sent the pull request to webcamjs too, hopefully they will merge

https://github.com/jhuckaby/webcamjs/pull/209

I know it can be little bit difficult to maintain until they merge, but think about the feature what you get for the Primefaces component. I wrote the WebcamJS modification as easy to merge because I have to maintain until you merged (and looks until WebcamJS merged), so hopefully it not a big deal. I do not expect to take this plus job to merge future versions, but maybe you or other Primefaces users can speed up the WebcamJS merge.

**Comment by sunnykgupta** [comment]
I'm trying this out this week. Will update with any modifications if needed.

**Comment by erickdeoliveiraleal** [comment]
fixes #2050

**Comment by tandraschko** [comment]
Please use PrimeFaces.error instead console.error
Also it would be great if you could seperate your PR and issues.
1) for upgrade the version
2) for the new features you added

**Comment by zsalab** [comment]
I'm not expert on github PR-s, can you suggest something how should I separate?

**Comment by tandraschko** [comment]
Next time please seperate PRs and create a issue before raising PRs.

**Comment by tandraschko** [comment]
But thanks ofc! ;)

**Comment by zsalab** [comment]
I'm really sorry about my mistake with this PR (mix the fix and the iOS support), I had a hope to get merged this code to WebcamJS and I had a hope the original developer willing to develop further the iOS support. Unfortunately he never gonna merge this code even if I fix and improve anything what he ask. I don't know his reason but of course you can remove my modifications easily.
I'm still going further with the iOS support development, I more then happy if you can accept more fixes and improvements there but of course I can understand if you don't want to take the risk to use a non official WebcamJS fork. I can use my custom component in this case.

**Pull request merged**
