### PR TITLE
#10605: Colorpicker switch to enums

### PR DESCRIPTION
**Pull request by melloware**
@jepsar et all I decided to use ColorPicker as the demo for what this might look like.  What is nice is EL already coerces to ENUM's so this will make the code way more robust in the future.

When you put an invalid value on the XHTML like `theme="xxx"` and that is not in the enum you get this error.

```
javax.el.ELException: Cannot convert [xxx] of type [class java.lang.String] to [class org.primefaces.component.colorpicker.ColorPickerTheme]
        at org.apache.el.lang.ELSupport.coerceToEnum(ELSupport.java:224)
        at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:536)
```

### CODE REVIEW

**Comment by tandraschko** [comment]
i general i like it but not sure if its worth TBH

also e.g. "hex" actually needs by HEX by naming conventions and you have to introduce HEX("hex") for each enum
really not sure

**Comment by melloware** [comment]
Yeah I know java conventions are `HEX("hex")` but man that would be a lot of work.  So maybe we should scrap this?

**Comment by tandraschko** [comment]
doers the EL coerce work correctly for ColorPickerTheme#default?

**Comment by melloware** [comment]
Crap I don't think it does. I didn't even realize that.

**Comment by tandraschko** [comment]
Then we can just close it?

We can just validate enum like properties in the renderer then, in development stage

**Pull request closed without merging**
