### PR TITLE
ShowAll records option in RowsPerPageTemplate

### PR DESCRIPTION
**Pull request by sudheerj**

### CODE REVIEW

**Comment by tandraschko** [comment]
Would be great if you could fix the PR - you also update the terminal.js.

**Comment by sudheerj** [comment]
Thomas,Do you want me to do PR on latest branch?

**Comment by tandraschko** [comment]
I just want that the PR doesn't modify the terminal.js which should be completely unlreated to the described changes.

**Comment by sudheerj** [comment]
Due to somehow other PR commit also added here.I will create a new PR for this issue.Thanks.

**Comment by sudheerj** [comment]
Created a new PR #1072 for this issue.So closing this PR.

**Pull request closed without merging**
