### PR TITLE
Fix #6083: Add version to theme.css URL

### LINKED ISSUE #6083: Theme: CSS is loaded without version
**Description**
PrimeFaces theme.css is loaded in `HeadRenderer` but does not append the version so its causing the browser to not refresh the cache on PF updates.

```xml
<link type="text/css" rel="stylesheet" 
         href="/primefaces-test/javax.faces.resource/theme.css.xhtml?ln=primefaces-omega" />
```

**Describe the solution you would like**
The version to be appended to the theme.css resource.

```xml
<link type="text/css" rel="stylesheet" 
         href="/primefaces-test/javax.faces.resource/theme.css.xhtml?ln=primefaces-omega&amp;v=8.0"" />
```

**Additional context**
The bug is in `PrimeResource` only looking for ln=primefaces exactly and not "startsWith" primefaces because the themes are `ln=primefaces-omega` etc.

### PR DESCRIPTION
**Pull request by melloware**
Resubmitting this PR

### CODE REVIEW

**Comment by tandraschko** [comment]
i think this is not correct if you use a premium theme, right?
Themes in core.jar can append the PF version but not external ones as the release lifecycle is different

**Comment by melloware** [comment]
Correct this would only apply to a theme library that starts with "primefaces". So all of the themes included with PF like "primefaces-nova-light" and "primfaces-omega" etc.

At our production client we have two themes and we kept that pattern of "primefaces-client-dark" and "primefaces-client-light". 

However for some premium themes like Babylon the library name is "babylon-layout" so this would not pick it up.  I wasn't trying to solve the premium theme issue i was trying to solve the themes included with PF problem.

**Comment by tandraschko** [comment]
what about pfe?

**Comment by melloware** [comment]
You mean would this interfere with PFE?  I have tested and it does not interfere at all.

**Comment by tandraschko** [comment]
i think would append the PF version to PFE?

**Comment by melloware** [comment]
It does so now in PFE 9.0 I also changed it version from `v=` to `e=`.

So for PF/PFE 9.0 URL's look like this...for example if PF was 9.0 community and PFE was 9.0.1 release the URL would look like this

`/primeext-showcase/javax.faces.resource/fa/font-awesome.css.jsf?ln=primefaces&v=9.0&e=9.0.1`

So now we get cache busting whenever you update your PF or PFE version which to me is ideal.

**Comment by tandraschko** [comment]
I would not pass the locale, it's the default behavior of "toLowerCase" without params anyway

**Comment by melloware** [comment]
Removed `Locale` from toLowercase.

**Pull request merged**
