### PR TITLE
Fix #7772: FileUpload: Explain show and user activation

### LINKED ISSUE #7772: FileUpload: Explain client side API show() and user activation
https://www.primefaces.org/showcase/ui/file/upload/basic.xhtml (so PrimeFaces 10.0.0, but I don't think that matters) 

```js
PF('widget_j_idt302_j_idt303').show()
```

Logs this error in the JS console:

```
<input> picker was blocked due to lack of user activation.
```

Firefox version: 91.0.2

No longer works with Chrome (it used to). Chrome reports:

```
File chooser dialog can only be shown with a user activation.
```

### PR DESCRIPTION
**Pull request by jepsar**
Fix #7772

Ended up in a documentation note

### CODE REVIEW

**Comment by Rapster** [comment]
` onclick="PF('upload')` _(without return false)_ works fine with firefox 92, it seems it was a bug in chromium that has been fixed 10 months ago

**Comment by jepsar** [comment]
I was following https://github.com/primefaces/primefaces/issues/7729

I can take out `;return false` though, no problem

**Comment by Rapster** [comment]
I think the only thing that has to be said is the version of chromium in which the issue has been raised and fixed: two things I can't find :( 

I might have misread something, not due to chromium but the browser itself and problem has been seen and fixed in 85

**Comment by jepsar** [comment]
We can avoid using a `p:button` in the documentation and replace it with

```xhtml
<a href="javascript:PF('upload').show()">Choose</a>
```

**Review by melloware — APPROVED** [review]

**Comment by Rapster** [comment]
I don't know... I don't feel there is not much to say in the doc... IMO, I wouldn't write anything since the problem is for a very specific version of Firefox. If user have this issue, they will google it, end up on that issue and get the answer, which is to update their web browser

**Comment by jepsar** [comment]
Fine with me. @melloware shall I close it and can you remove the milestone and mark as won't fix?

**Comment by melloware** [comment]
Yep close this and I will close the ticket as WontFix.

**Pull request closed without merging**
