### PR TITLE
Fix #5614: Datatable sorting taglib and docs

### LINKED ISSUE #5438: DataTable: cleanup sorting
Filters previous had 3 similar attributes:
Filters
FilterBy
FilterMeta

we should check the same for sorting.

All properties related to sort:
* sortMeta
* sortField
* sortBy
* sortOrder
* sortFunction
* sortMode (single | multiple)
* allowUnsorting

Some facts:
1) it seems like sortBy and sortField is similar. One points to a fieldname of the entity, one is a VE? @Rapster Maybe you have a better overview here?
2) if sortMode = multi, sortMeta is the source of all sort informations
3) if sortMode = single, sortBy+sortOrder+sortFunction is used
4) in general, sortMeta is just a collection of (sortBy+sortOrder+sortFunction) for mulitple columns. So multiSort is actually the same thing as singleSort, just that sortMeta could only contain 1 value instead of multiple.

Goals (Reduce attributes to):
* sortBy (a map of SortMeta, multisort will contain mulitple values, singlesort only 1 value)
* initial sorting can by defined by sortOrder and sortPriority on p:column
* allowMultiSort (sortMode before, default = true?)
* allowUnsorting
* remove old attributes from PropertyKeys+taglib and throw a exception in getter/setter

### LINKED ISSUE #5614: DataTable: Initial multi-column sorting using SortMeta doesn't highlight column headers
There's a forum conversation for this issue: https://forum.primefaces.org/viewtopic.php?f=3&t=61170

There's also a fork to a PF test case detailing the problem at https://github.com/kawoolutions/primefaces-test

Note the `multisort` dirs under Java and webapp dirs, for beans + XHTML respectively.

## 1) Environment
- PrimeFaces version: 8.0.RC3
- Does it work on the newest released PrimeFaces version? Version? No. 8.0.RC3
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No.
- Application server + version: Any
- Affected browsers: Firefox (others untested)

## 2) Expected behavior

Usually the given SortMeta columns for a 

```
<p:dataTable ...
                     sortBy="#{multiSortView.getInitialSortMetas()}"
                     sortMode="multiple">
```
shall be highlighted with `ui-state-active`, which doesn't seem to happen.

## 3) Actual behavior

No highlighting is present.

## 4) Steps to reproduce

Just call the page multisort.xhtml as in the test case, the initial table view suffices to see the effects.

## 5) Sample XHTML

https://github.com/kawoolutions/primefaces-test/tree/master/src/main/webapp/multisort

## 6) Sample bean

See 3 files here: https://github.com/kawoolutions/primefaces-test/tree/master/src/main/java/org/primefaces/test/multisort

### PR DESCRIPTION
**Pull request by melloware**
- add `sortMeta` to taglib
- updated all sort fields docs

### CODE REVIEW

**Comment by melloware** [comment]
@tandraschko do you mind reviewing this one its just taglib and docs changes.  I don't think we needed to do anything else?

**Comment by tandraschko** [comment]
thats ok for me currently
we need to refactor the datatable to remove sortMeta in the future and resuse sortBy for both cases

**Comment by melloware** [comment]
ahh OK let me leave this open then. I wasn't clear what the goal was but reusing SortBy does seem like a good idea.

**Comment by melloware** [comment]
OK for now this clears up the confusion on #5614 so merging and closing that ticket.

**Pull request merged**
