### PR TITLE
Add real file upload cancellation and oncancel callback

### PR DESCRIPTION
**Pull request by danielthegray**
- Fixes the upload that continues in the background (issues #1529, #844)
- Adds an oncancel callback function (#845)

### CODE REVIEW

**Comment by tandraschko** [comment]
Did you test it in all the common browsers?
Otherwise, the changes are looking good +1

**Comment by Rapster** [comment]
Sounds awesome! Thanks a lot @thedanielgray

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
This looks good to me too!

**Comment by danielthegray** [comment]
I've tested it on IE11, Chrome (I'm on 67), Firefox (I tried it with the most recent Firefox Developer Edition as well), and Opera.

The main function call added is the `abort()` method of the `XMLHttpRequest`, which is supported widely across browsers (even since IE7: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort#Browser_compatibility) so I think it should behave stably across all browsers.

The `onCancel` callback I implemented here also works on all the mentioned browsers. (IE11, Chrome, Firefox and Opera)
**If it doesn't work on your browser, let me know and I will look into it!**

**Comment by tandraschko** [comment]
Thanks!

**Pull request merged**
