### PR TITLE
Fix #11409: OverlayPanel add `destroyWithTarget` prop

### LINKED ISSUE #11409: OverlayPanel won't show when attached to a CommandButton
### Describe the bug

The fix in #11244 causes problems with an OverlayPanel attached to a CommandButton. The panel will be destroyed and isn't rendered any more, resulting in a JS error like: `Widget for 'xxxx' not available!`

The fix in #11387 does not fix this behavior.

### Reproducer

Not working examples:
```xml
<p:commandButton id="btn" value="Open" />
<p:overlayPanel for="btn" dynamic="true">
  <i>Hint</i>
</p:overlayPanel>
```
```xml
<h:panelGroup id="grp">
  <p:commandButton id="btn" value="Open" />
  <p:overlayPanel for="grp" dynamic="true">
    <i>Hint</i>
  </p:overlayPanel>
</h:panelGroup>
```
Partially working example:
```xml
<h:panelGroup id="grp">
  Working on Text
  <p:commandButton id="btn" value="Not working on button" />
  <p:overlayPanel for="grp" dynamic="true">
    <i>Hint</i>
  </p:overlayPanel>
</h:panelGroup>
```

Workaround, updating the wrapper:
```xml
<h:panelGroup id="wrp">
  <p:commandButton id="btn" value="Open" update="wrp"/>
  <p:overlayPanel for="btn" dynamic="true">
    <i>Hint</i>
  </p:overlayPanel>
</h:panelGroup>
```

### Expected behavior

The minimal example was working in 13.0.4 and should work again.
```xml
<p:commandButton id="btn" value="Open" />
<p:overlayPanel for="btn" dynamic="true">
  <i>Hint</i>
</p:overlayPanel>
```

### PrimeFaces edition

Community

### PrimeFaces version

13.0.5

### Theme

_No response_

### JSF implementation

All

### JSF version

2.3.21

### Java version

17.0.10

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #11409: OverlayPanel add `destroyWithTarget` prop

@tandraschko @jepsar @Rapster this was the best name I could come up with but I am open to suggestions...

### CODE REVIEW

**Comment by melloware** [comment]
Sure.  So the original bug: https://github.com/primefaces/primefaces/issues/5710

Basically if the OverlayPanel was in the `body` and it is updated in an `update` statement it creates two overlay panels because the old one is still in the DOM and never gets removed.  I had added `remove` subscription on the `for` element so then the `for` element is removed from the DOM it will also remove the `OverlayPanel` as well.  This works great and fixes #5710 however in this new ticket there are scenario's where that doesn't work so I made it an option.

Although now it has me wondering if I can check if the `appendTo` is `body` automatically apply this?

**Comment by tandraschko** [comment]
> Basically if the OverlayPanel was in the body and it is updated in an update statement it creates two overlay panels because the old one is still in the DOM and never gets removed.

really? shouldnt the AJAX core just replace by ID?

**Comment by melloware** [comment]
Maybe but when we do `appendTo="@body"` is it really replacing the old one by ID or just appending this new element into the DOM in the body?

**Comment by tandraschko** [comment]
the appendTo logic should remove the old one actually

**Comment by melloware** [comment]
here is a great reproducer showing the issue: 
[pf-5710.zip](https://github.com/primefaces/primefaces/files/14229338/pf-5710.zip)

Click "Alert State" and it will show 1 in the DOM.  Then click "Update OP" and then click "Alert State" it shows now 2 instance in the DOM.

**Comment by tandraschko** [comment]
where are the 2 instances? can't see it in firefox

**Comment by melloware** [comment]
I will double check but his jquery code reports 2 instances right?

**Comment by tandraschko** [comment]
yeah but it checks for selectOneMenu, not overlay panel instances?

maybe its a selectOneMenu problem because it has appendTo and is placed inside the overlayPanel, which also has appendTo logic?

**Comment by tandraschko** [comment]
yeah
1 overlayPanel DOM
2 selectOneMenu DOM

**Comment by melloware** [comment]
Sorry it's not the Dom it's the overlay widget is left hanging around

**Comment by tandraschko** [comment]
what do you mean exactly?

**Comment by melloware** [comment]
Yeah it's definitely that the overlay panel is not registered to "destroy" itself.

**Comment by tandraschko** [comment]
i cant follow
there is 1 overlayPanel DOM and 1 overlayPanel widget instance?

**Comment by melloware** [comment]
Sorry no it looks like 1 OverlayPanel and a 2nd SelectOneMenu.

image

**Comment by tandraschko** [comment]
yeah, thats what i said

we need to really dig deep here and analyze #5710 before
everything else is hacking around a workaround propably

i removed your commit [from ](https://github.com/primefaces/primefaces/pull/11244) in my local code and i still have no idea

if you press update+alert, it says that there are 2 "frm:som" but its not really there in the HTML

might be a timing problem

**Comment by melloware** [comment]
OK I have reverted #5710 in main and re-opened the ticket.

**Comment by tandraschko** [comment]
i think its a general problem with nested appendTo components
not sure if i have enough time to check it

would be great if someone could dig deeper (debug both OP and SOM init,refresh,destroy methods and appendToLogic)

**Comment by melloware** [comment]
i will close this for now as its not solving the underlying problem

**Comment by fanste** [comment]
I just stumpled on this issue on my list. Let me explain, why it has two SelectOneMenu (SOM) but only single OverlayPanel (OP).

The page is opend the first time. You get a fresh DOM where appendTo of the OP will transfer the DOM of the OP(containing the SOM) to the correct position. This is triggert by the JS code of the widget, that is always contained in a script tag below the component DOM.

In short, this looks like this:
```
<div id="OP">
    <div id="SOM"></div>
    <script id="SOM_s">...</script>
</div>
<script id="OP_s">...</script>
```

The AJAX triggers a re-render of the OP (and therefore also SOM, as it is contained in OP). But not directly the OP (then is should be no problem) but by updating the parent of OP.

Now you have two times the upper shown DOM. At the original/updated position of the parent of OP and at the appendTo-moved position. As the DOM is processed top-down, it will first run the script of SOM, which will then find the DOM of SOM at two positions (same ID) and so SOM#jq contains two instances. Next it will run the script of OP. The logic of OP is smart enough  to detect the old DOM and removes it first.

But the SOM is already miss-initialized.

**Comment by melloware** [comment]
@fanste yep we removed this PR from 14.0.0 as it did not fix the actual issue.   We are open to suggestions.

**Pull request closed without merging**
