### PR TITLE
Fix #11857: Remove BoundedInputStream shading

### LINKED ISSUE #11857: Core: Do not shade BoundedInputStream
See conversation: https://github.com/primefaces/primefaces/pull/11707

### PR DESCRIPTION
**Pull request by melloware**
Fix #11857: Remove BoundedInputStream shading

### CODE REVIEW

**Comment by tandraschko** [comment]
Looks much better IMO
Wdyt @Rapster?

**Comment by Rapster** [comment]
The whole idea of no longer shading, is with recent upgrades it causes too many issues? That's why we stop shading IOUtils for example, right ?

I personnally prefer shading than copy/pasting even if it means to stick to one specific version of commons-io, now if the upgrade is really necessary and stop us to do some stuff, i'm cool with that

**Comment by melloware** [comment]
That is a good point we could simply lock on 2.15.1 and have dependabot never notify us about commons IO.

I am ok with that if you guys are?

**Comment by tandraschko** [comment]
also ok for now

**Pull request closed without merging**
