### PR TITLE
Fix #2099

### LINKED ISSUE #2099: outputLabel support for p:chips.
## 1) Environment
PrimeFaces version 6.0.15. Tomcat EE 8.5.6

## 2) Expected behavior
When I click on the corresponding chips label, the system should move to the chips component so that I can start typing.

## 3) Actual behavior
When I click on the corresponding chips label, the system doesn't put focus on the chips component.

## 4) Steps to reproduce
(See sample XHTML as reference)
1. Click on the label "CHIPS LABEL"
2. System should put focus on the chips component but it doesn't

## 5) Sample XHTML
<p:outputLabel for="chips" value="CHIPS LABEL:" />
<p:chips id="chips" value="#{testController.test}" />

### PR DESCRIPTION
**Pull request by Rapster**
clicking p:outputLabel doesn't focus with p:chips.

### CODE REVIEW

**Comment by Rapster** [comment]
@tandraschko it would be nice to update the showcase by adding a label to chips. I think it's quicker that you do it than me doing a PR :)

**Comment by tandraschko** [comment]
Don't have time today, so if you don't provide a PR, i will likely forget it :P

**Comment by Rapster** [comment]
No problem, I'll do it ;)

**Comment by Rapster** [comment]
It's done

**Pull request merged**
