### PR TITLE
Document JavaScript, create type declarations file, generate Java Script Api Docs

### PR DESCRIPTION
**Pull request by blutorange**
Hope everybody's doing well.

This is the PR for issue #5027 - it adds doc comments to all JavaScript files. Doc comments include type annotations (JSDoc style). Based on that, the client side JavaScript Api Docs are generated via [typedoc](https://typedoc.org/), in combination with the [maven-frontend-plugin](https://github.com/eirslett/frontend-maven-plugin).

Please [see the README in the type declarations directory](https://github.com/blutorange/primefaces/blob/merge/src/main/type-definitions/README.md), it contains information on how to generate the type declarations file and the documentation. It also explains how it works and includes a short tutorial on how to document a widget.

TODOs / open questions (in approximate order of importance)

- [x] Build process. Is the workflow / build process OK with you or should it be changed ? The Api Docs are currently generated to `docs/<version>/jsdocs` when running `mvn install -P fc-delivery`. When running `mvn install`, no docs are created, but the type declaration files is created in a temp dir and linted for errors.
- [x] Windows build. Can anybody try if this PR builds on Windows? ([instruction](https://github.com/blutorange/primefaces/blob/merge/src/main/type-definitions/README.md#build)). If not, I'll see if I can find a Windows installation somewhere. 
    * ~~There seem's to be an issue with line breaks, I'm taking a look at it now...~~ fixed
    * ~~Unrelated to the commits of this PR, but a recent commit added one non-breaking space character to a JS file, which causes the build to fail in Windows. I'll just correct that as well.~~ fixed
- [x] Smoke test. Done* ~~A quick test with the showcase to check that all widgets are still working. I made sure to only change doc comment and no actual code, but better safe than sorry. I'll do that while you are reviewing this PR.~~
- [x] Travis CI. Add the `jsdoc` profile to the Travis CI build so that it checks commits for errors in the doc comments and types.
- [x] Git wiki. Once this is merged. ~~Update the [contribution guide](https://github.com/primefaces/primefaces/wiki/Contributing-to-PrimeFaces) and the  [build guide](https://github.com/primefaces/primefaces/wiki/Building-From-Source). Mention the new profile `jsdoc` profile and add a link to the README.md in `src/main/type-definitions/README.md`~~
- [x] User guide. We should probably update the user guide `*.md` files. Any preferences on that? I'd add add a link to the JS Api Docs to the start page, and possibly a link to each widget.
- [x] NPM package. Any opinions on publishing the type declarations file to NPM? Might make it easier for people to get / use it.
- [x] ~~Maven plugin. Right now, the JavaScript for generating the documentation is located in `src/main/type-definitions`. We could extract that into a separate maven plugin and then just use that in the `pom.xml`. I already did something like that for a different project and it's not much work - but I'd say we can do that later when it becomes necessary (such as when / if we want to use the same process for primefaces-extensions).~~ Perhaps later.

---

Phew, took more time than I had anticipated, but it's finally done. There's still lots of room for improvement, but I trust the community to improve things gradually :+1: 

---

(*) Smoke test: I started the showcase locally with this PR applied and went through every showcase. All widgets were working, I did not find any obvious bugs and saw no JavaScript errors in the console - at least none that were caused by this PR. I found a few issues that are present in the official showcase or current master branch, see below. When I've got some time I might create an issue for these, or if somebody wants to investigate, go ahead.

<details>
<summary>Click to expand</summary>

```
http://localhost:8080/showcase/ui/data/tree/dragdrop.xhtml (happens on current master branch)
  Drag Item 1 to Node 1 -> Error
    Apr 05, 2020 2:14:35 PM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
    SEVERE: null
    java.lang.StackOverflowError
	    at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:835)
	    at java.base/java.lang.StringBuilder.append(StringBuilder.java:247)
	    at org.primefaces.model.TreeNodeChildren.updateRowKeys(TreeNodeChildren.java:229)
	    at org.primefaces.model.TreeNodeChildren.updateRowKeys(TreeNodeChildren.java:213)
	    at org.primefaces.model.TreeNodeChildren.updateRowKeys(TreeNodeChildren.java:231)
	    at org.primefaces.model.TreeNodeChildren.updateRowKeys(TreeNodeChildren.java:213)
	    at org.primefaces.model.TreeNodeChildren.updateRowKeys(TreeNodeChildren.java:231)


http://localhost:8080/showcase/ui/dnd/dataTable.xhtml (happens on current master branch)
  -> Drag any car to the panel below -> JS error

    Uncaught TypeError: Cannot read property 'is' of null
        at $.<computed>.<computed>.cancel (jquery-plugins.js.xhtml?ln=primefaces&v=9.0-SNAPSHOT:2255)
        at $.<computed>.<computed>.cancel (jquery-plugins.js.xhtml?ln=primefaces&v=9.0-SNAPSHOT:144)


https://www.primefaces.org/showcase/ui/data/timeline/linked.xhtml
  -> Clicking on an event in timeline 1 does not select an event in timeline 2


https://www.primefaces.org/showcase/ui/data/diagram/basic.xhtml
  -> Drag a node -> Error

    Apr 05, 2020 2:16:23 PM com.sun.faces.context.PartialViewContextImpl processPartial
    INFO: java.lang.NullPointerException
    java.lang.NullPointerException
	    at org.primefaces.component.diagram.DiagramRenderer.decodePositionChange(DiagramRenderer.java:123)
	    at org.primefaces.component.diagram.DiagramRenderer.decode(DiagramRenderer.java:63)
	    at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
	    at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
	    at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
	    at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)


https://www.primefaces.org/showcase/ui/multimedia/cropper.xhtml
  -> Click on "crop" -> error

    Apr 05, 2020 1:28:16 PM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
    SEVERE: Path traversal attempt - absolute path not allowed.
    javax.faces.FacesException: Path traversal attempt - absolute path not allowed.
	    at org.primefaces.util.FileUploadUtils.checkPathTraversal(FileUploadUtils.java:333)
	    at org.primefaces.component.imagecropper.ImageCropperRenderer.getConvertedValue(ImageCropperRenderer.java:206)


https://www.primefaces.org/showcase/ui/misc/watermark.xhtml
  -> Click on "AJAX" -> JS error

    watermark.xhtml:1146 Uncaught TypeError: PrimeFaces.cleanWatermarks is not a function
        at HTMLButtonElement.<anonymous> (watermark.xhtml:1146)
        at Object.bcn (VM38 core.js.xhtml:727)
        at HTMLButtonElement.onclick (watermark.xhtml:1146)
    (anonymous) @ watermark.xhtml:1146
    bcn @ VM38 core.js.xhtml:727
    onclick @ watermark.xhtml:1146


https://www.primefaces.org/showcase/ui/data/mindmap.xhtml
  -> Drag node "Malware" with the mouse -> JS error
  -> RaphaelPaper#safari seems to have been removed in 2.2.0

    VM20 mindmap.js.xhtml:387 Uncaught TypeError: this.raphael.safari 
      is not a function
        at Class.updateConnections (VM20 mindmap.js.xhtml:387)
        at S.textDrag (VM20 mindmap.js.xhtml:371)
        at x (VM19 raphael.js.xhtml:10)
        at Function.Ot (VM19 raphael.js.xhtml:10)
        at HTMLDocument.n (VM19 raphael.js.xhtml:10)


https://www.primefaces.org/showcase/ui/panel/layout/events.xhtml
  -> Resize event does not seem to be triggered when resizing the width of a panel via dragging (?)
```

</details>

### CODE REVIEW

**Comment by melloware** [comment]
This is an impressive and incredible amount of work.  Kudos to you @blutorange !!

I volunteer to test on Windows since I develop on Windows 10 mostly.  I will let you know the results.

**Comment by blutorange** [comment]
@melloware I'm glad you like it. Can you please wait an hour before you test on Windows, there's an issue I already found, will add a commit in a few minutes.

**Comment by blutorange** [comment]
Alright, it should build on Windows now, so if anybody want to try, go ahead.

**Comment by melloware** [comment]
Tested on windows an works great!   My only comment is this really slows down the build greatly.

I wonder if we should use `<pluginManagement>` to have the plugin configured once.  And then create a new `<profile>` called `typedoc` so anyone can run it at will.

Then also add this snippet in the `release` profile to activate it when releases are cut.

```xml
<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
</plugin>
```

**Comment by tandraschko** [comment]
+1 for a profile if it slows down the normal build

**Comment by blutorange** [comment]
Hmm, how long is it taking for you? For me it takes: 

* `mvn install (without docs)`: 50s
* `mvn install -DskipTests`: 65s
* `mvn install`: 90s

Some notes:

1. The frontend maven plugin downloads a temporary copy of node into the target dir - if you run install again without a clean it should be significantly faster. Also, the actual documentation is generated only when you add `-P release`. Without that profile it should also be significantly faster.
1. Generating the docs takes 40s for me (see above). Of that, 15s are for self tests of the doc generation code. These self tests can be skipped via `-DskipTests`, or could be skipped if we extract it into a separate maven plugin (see checklist in first post).
1. For me that leaves 25s seconds extra build time when I run a local `install` - I didn't consider it that much so I left it as it is now.

If it takes really long for you then I guess a profile is the way to go. Actually, there's already the `release` profile, and the documentation pages are generated only when that profile is activated. What happens when doing a normal build without a profile is:
* It parses the JavaScript doc comments and checks for missing comments and errors (wrong types etc.). I wanted to do that check on a normal `install` to catch possible errors early, when a contributor makes a commit (so we would not have to fix all error at once when it's release time)
* Although we could activate a separate profile for the travis CI build

**Comment by melloware** [comment]
First time yeah it downloaded NPM etc I am ok with that.  But my typically daily process becuase I switch between branches constantly I do `mvn clean install` to make sure the clean deletes old classes etc that may be in one branch and not another.  Here are my timings.

- `mvn clean install` current 32s
- `mvn clean install -Dmaven.test.skip` current 22s
- `mvn clean install` with your new frontend plugin 95s

**Comment by blutorange** [comment]
That's a bit long, yeah. My only concern with an additional profile is that when a contributor runs a local install and they forget about the profile, they would not be notified about errors in the docs.

But alright, here's my idea:

* I'll take a look at whether it's possible to check whether any of the JavaScript files have changed in the git index, and only run the frontend maven plugin if they did. @melloware Would that work for you - there shouldn't be any unstaged files after a clean?
* If that's not possible, I'll just add an additional profile

**Comment by melloware** [comment]
Sure I think the goal is we want local builds as fast as possible and the builds done on TravisCI can do the full thing and let people know their docs have failed.  Every PR gets checked by Travis CI so they would be notified if their doc is messed up.

**Comment by blutorange** [comment]
Alright, so

* Profile `jsdoc` runs all the checks and creates the docs in the target directory. This profile can be added to Travis CI.
* Profile `release` runs all checks and creates the docs in the `docs/<version>/jsdocs` directory. These are uploaded to github together with the normal user guide when the release is committed.

Is that alright?

**Comment by melloware** [comment]
That sounds good to me!

**Comment by blutorange** [comment]
Most of the checklist is done, I'll just need to update the user guide with a link to the documentation.

There's one other issue I noticed though: the size of the documentation:

* The JavaScript API docs are about as large as the generated JavaDocs (~40 MB)
* Pushing that to github to be able to use github pages seems like a bad idea, the current repo is only ~25MB. And it gets worse when the docs for multiple versions are uploaded.
* Anywhere where we could host the documentation? JavaDocs seem to be hosted at https://www.primefaces.org/docs/api/7.0/ - can we use that?

**Comment by melloware** [comment]
You are right 40MB is a lot for GitHub.  This is a question for @mertsincan and PrimeTek.

**Comment by christophs78** [comment]
Wow! What a big effort!

**Comment by tandraschko** [comment]
hmmm, really big
for me it would be ok if we only have 1 version in each branch, not multiple like the normal documenation
so we have full control instead of hosting it on primetek

**Comment by christophs78** [comment]
@blutorange: Some maybe stupid questions about how you use TypeDeclaration and TypeDoc within your development-process.
- Which IDE do you use?
- Do you use one single IDE or do you use one IDE for all server-side things and another one for the client-side things?
- Do TypeDeclaration and TypeDoc help (for eg code-completion) when you write JavaScript-code within your XHTML?
- How do you integration TypeScript with JSF? Do you write JS-"components" which extend PrimeFaces-components with TypeScript and compile this into JS? Add the compiled JS to your JSF-project? Or do you have some tighter integration?

Sounds like we may learn a few new "tricks" from you.

(Personally i have some (limited) background with Angular, TypeScript and Visual Studio Code.)

**Comment by blutorange** [comment]
@christophs78 

I'm glad you ask (hope this isn't too wall-of-texish)

> Which IDE do you use?
> Do you use one single IDE or do you use one IDE for all server-side things and another one for the client-side things?

Depends on the project and the language, mainly VisualStudioCode (JavaScript/TypeScript/SCSS/LESS), Eclipse (Java), IntelliJ (when I have a license). For small Java project I use VisualStudioCode because it's faster and doesn't hang as much as Eclipse does.

> Do TypeDeclaration and TypeDoc help (for eg code-completion) when you write JavaScript-code within your XHTML?
> How do you integration TypeScript with JSF? Do you write JS-"components" which extend PrimeFaces-components with TypeScript and compile this into JS? Add the compiled JS to your JSF-project? Or do you have some tighter integration?

Unless it's just a single line of code, I don't write JavaScript in XHTML files. Scripting is logic, and XHTML is the view, and I try to keep that separate. On top of that, I also don't like it because

* it makes the XHTML larger and harder to read
* there's pretty much no good auto completion and checking
* you have to escape XML special characters such as `&&`

__One note:__ JavaScript and TypeScript aren't really that different. For some smaller projects, I just write normal JavaScript, but add the `// @ts-check` comment at the top of each file. Types can then be added as doc comments, and can be checked by running the TypeScript compiler on the JavaScript files. I then add an appropriate `tsconfig/jsconfig.json` file with all strict options enabled, which enforces type annotations. In fact, that's what I did in this PR for [the JavaScript code that creates the documentation](https://github.com/blutorange/primefaces/tree/merge/src/main/type-definitions), for example [lang.js](https://github.com/blutorange/primefaces/blob/merge/src/main/type-definitions/src/lang.js). It's JavaScript, but fully type- and null-checked. And the tooling is as good as with TypeScript : )

What's makes a bigger difference to me, instead of JavaScript VS TypeScript, is legacy JavaScript VS modern JavaScript. It's much easier to code and read.

For example, I created a PrimeFaces component wrapper for the monaco-editor (which is essentially what powers VSCode), and for that, I used an ES6 class:

```javascript
export class ExtMonacoEditorBase extends PrimeFaces.widget.DeferredWidget { ... }
```

For another project we didn't have to write custom components, but interact with existing components via JavaScript for some customization. There I created a separate folder with many ES6 module (import / export) JavaScript files. These are then transpiled via the `closure-compiler-maven-plugin` into a single JavaScript file. It exports some functions that can be used within XHTML pages, like `p:ajaxStatus onstart="CustomLibrary.OnLoadStart"`. This keeps the JavaScript code in XHTML files to a minimum, lets us use modern JavaScript, and still allows for the entire JavaScript to be type checked -- assuming there's a declarations file for PrimeFaces -- which this PR adds.

**Comment by blutorange** [comment]
So I did some tests regarding the file size and git:

* The jsdocs directory compresses to ~1.6MB with 7zip
* I pushed the jsdocs to a new branch on my forked repo - which resulted in `Writing objects: 100% (1444/1444), 3.22 MiB`
* Making some changes to a component, regenerating the docs and pushing results in `Writing objects: 100% (23/23), 202.91 KiB`
*  Cloning the repo *before* I uploaded the docs: `Receiving objects: 100% (168093/168093), 61.85 MiB`
*  Cloning the repo *after* I uploaded the docs: `Receiving objects: 100% (169532/169532), 64.98 MiB`
* [git-sizer](https://github.com/github/git-sizer) reports pretty much the same statistics before and after I pushed the jsdocs.

<details>
<summary>git-sizer output before the push</summary>

```
xxx@yyy:/tmp/pf-before$ git sizer --verbose
Processing blobs: 46067                        
Processing trees: 110730                        
Processing commits: 11295                        
Matching commits to trees: 11295                        
Processing annotated tags: 1                        
Processing references: 81                        
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Commits                    |           |                                |
|   * Count                    |  11.3 k   |                                |
|   * Total size               |  3.49 MiB |                                |
| * Trees                      |           |                                |
|   * Count                    |   111 k   |                                |
|   * Total size               |  63.5 MiB |                                |
|   * Total tree entries       |  1.79 M   |                                |
| * Blobs                      |           |                                |
|   * Count                    |  46.1 k   |                                |
|   * Total size               |  1.12 GiB |                                |
| * Annotated tags             |           |                                |
|   * Count                    |     1     |                                |
| * References                 |           |                                |
|   * Count                    |    81     |                                |
|                              |           |                                |
| Biggest objects              |           |                                |
| * Commits                    |           |                                |
|   * Maximum size         [1] |  3.77 KiB |                                |
|   * Maximum parents      [2] |     2     |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [3] |   212     |                                |
| * Blobs                      |           |                                |
|   * Maximum size         [4] |  42.5 MiB | ****                           |
|                              |           |                                |
| History structure            |           |                                |
| * Maximum history depth      |  9.23 k   |                                |
| * Maximum tag depth      [5] |     1     |                                |
|                              |           |                                |
| Biggest checkouts            |           |                                |
| * Number of directories  [6] |   594     |                                |
| * Maximum path depth     [7] |    17     | *                              |
| * Maximum path length    [7] |   192 B   | *                              |
| * Number of files        [8] |  3.14 k   |                                |
| * Total size of files    [9] |  87.4 MiB |                                |
| * Number of symlinks    [10] |     2     |                                |
| * Number of submodules       |     0     |                                |
```

</details>

<details>
<summary>git-sizer output after the push</summary>

```
xxx@yyy:/tmp/pf-before$ git sizer --verbose
Processing blobs: 47501                        
Processing trees: 110756                        
Processing commits: 11297                        
Matching commits to trees: 11297                        
Processing annotated tags: 1                        
Processing references: 82                        
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Commits                    |           |                                |
|   * Count                    |  11.3 k   |                                |
|   * Total size               |  3.49 MiB |                                |
| * Trees                      |           |                                |
|   * Count                    |   111 k   |                                |
|   * Total size               |  63.7 MiB |                                |
|   * Total tree entries       |  1.80 M   |                                |
| * Blobs                      |           |                                |
|   * Count                    |  47.5 k   |                                |
|   * Total size               |  1.19 GiB |                                |
| * Annotated tags             |           |                                |
|   * Count                    |     1     |                                |
| * References                 |           |                                |
|   * Count                    |    82     |                                |
|                              |           |                                |
| Biggest objects              |           |                                |
| * Commits                    |           |                                |
|   * Maximum size         [1] |  3.77 KiB |                                |
|   * Maximum parents      [2] |     2     |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [3] |  1.00 k   | *                              |
| * Blobs                      |           |                                |
|   * Maximum size         [4] |  42.5 MiB | ****                           |
|                              |           |                                |
| History structure            |           |                                |
| * Maximum history depth      |  9.23 k   |                                |
| * Maximum tag depth      [5] |     1     |                                |
|                              |           |                                |
| Biggest checkouts            |           |                                |
| * Number of directories  [6] |   603     |                                |
| * Maximum path depth     [7] |    17     | *                              |
| * Maximum path length    [7] |   192 B   | *                              |
| * Number of files        [6] |  3.97 k   |                                |
| * Total size of files    [8] |  87.4 MiB |                                |
| * Number of symlinks     [9] |     2     |                                |
| * Number of submodules       |     0     |                                |
```

</details>

Now I'm not an expert on git, but that seems to indicate it might be fine even if we kept several version at once. Though for starters I'd say we do as @tandraschko suggested and keep only the latest version around. One could still get the docs for a different version by checking out a certain tag.

Any opinions?

**Comment by melloware** [comment]
I say we go with @tandraschko suggestion for now... and we can always decide in the future to change if we need mutli-versions.

**Comment by blutorange** [comment]
That leaves one final point on my checklist I'd like to hear your opinion on:

> NPM package. Might make it easier for people to get / use it. Especially when creating an NPM project for a JavaScript bundle that is then included in the JSF / PrimeFaces web app

If we want to publish to NPM, I could probably integrate it in the maven build so that it publishes on `-P deploy` when a password / token is entered.

**Comment by blutorange** [comment]
Alright, happy easter everybody.

So I went ahead and added the script for publishing to npm. Requires the credentials to be entered, if none are provided, nothing is published.

Basically, you can now publish on deploy:

```sh
mvn deploy -P release \
  -Dnpm.username=username \
  -Dnpm.password=password \
  -Dnpm.email=email@example.com
```

Or manually later:

```sh
mvn org.codehaus.mojo:build-helper-maven-plugin:parse-version \
  com.github.eirslett:frontend-maven-plugin:npm@publish-to-npm \
  -Dnpm.token=token
```

You can edit the `src/main/type-definitions/package.json` as necessary. The package name now is `primefaces`, and the version is taken from the `pom.xml`. See [the README for more info](https://github.com/blutorange/primefaces/tree/merge/src/main/type-definitions#publish-to-npm).

**Comment by melloware** [comment]
That is very cool and I am sure PrimeTek already has NPM access since they release PrimeNG etc there.

**Comment by blutorange** [comment]
Hope everybody had a nice Easter.

Well, as far as I'm concerned, everything's done now, so I'll be waiting for everyone involved to review this. If you want, I can then also make a final merge and generate the initial version of the docs for the 9.0-SNAPSHOT.

Regarding the git wiki, either somebody updates it and mentions the new profiles or I'll see if I can suggest an edit once this is merged.

**Comment by tandraschko** [comment]
So i can just merge it, use the jsdoc profile and commit?

Not sure about PrimeTek will handle the NPM automatically, we need to talk with them

**Comment by blutorange** [comment]
Regarding NPM, publishing there is easy. In principle we could just create an account and use that. Would have the advantage that we can quickly update the package if there is a bug or mistake.

NPM also doesn't really show who uploaded a package - it just [shows the collaborators](https://docs.npmjs.com/cli/owner), i.e. the people who can publish the package. [primeng](https://www.npmjs.com/package/primeng/v/9.0.5) is a public package, with the collaborators set to `cagatay.civici` and `yigitfindikli`.

I guess it's a good idea to ask PrimeTek (who can do it?) though.

**Comment by tandraschko** [comment]
what about my first question? :D

as you said, mvn deploy now also publish to NPM?
Could we only push to npm with active jsdoc profile?

**Comment by blutorange** [comment]
@tandraschko The second question I'm thinking about right now : )

`npm publish` is completely optional for now. Unless you activate the profile or specify the credentials via `-D` cli parameters, it won't do any publishing.

**Comment by blutorange** [comment]
@tandraschko Regarding the merge, I'll generate and upload the first version of the JavaScript docs, then you can merge as far as I'm concerned.

**Comment by tandraschko** [comment]
So it doesn't break the normal "mvn deploy" when not adding the npm user/pw params?

**Comment by blutorange** [comment]
@tandraschko  Yes, exactly. It just skips it in that case. (It can be published later via `-P jsdoc-publish`) See here for details: https://github.com/blutorange/primefaces/tree/merge/src/main/type-definitions#publish-to-npm

I'm testing the github pages on my branch now

**Comment by blutorange** [comment]
Alright, I generated the initial version of the docs for the 9.0-SNAPSHOT version.

You can see it on my fork before merging if you want: https://blutorange.github.io/primefaces/9_0/#/components/accordionpanel (widgets link to the JavaScript docs)

@tandraschko  Unless anybody else has got any objections, you can merge if you want.

**Comment by blutorange** [comment]
I edited the wiki page and mentioned the `jsdoc` goal: https://github.com/primefaces/primefaces/wiki/Building-From-Source

(On a side note - interesting that anybody can just edit the wiki...)

**Pull request merged**
