### PR TITLE
jquery plugins better description

### PR DESCRIPTION
**Pull request by erickdeoliveiraleal**
jquery plugins better description

### CODE REVIEW

**Comment by tandraschko** [comment]
Thanks! Applied some changes but no all.

**Comment by erickdeoliveiraleal** [comment]
I stil think that the description is wrong.  jQueryUI position is not present, and Draggable etc, is in umbrella of UI Interactions.

**Comment by tandraschko** [comment]
better? ;)

**Comment by erickdeoliveiraleal** [comment]
👍

**Pull request closed without merging**
