### PR TITLE
#7419 make multimoduled showcase get up-and running and debug-able on IntelliJ + Tomcat again

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
and same for integration-tests

**Comment by tandraschko** [comment]
That doesnt really make sense
Isnt there a IDE config for something Like this?

**Comment by christophs78** [comment]
See https://stackoverflow.com/questions/30407065/getting-intellij-to-import-shaded-dependencies-in-a-multi-module-maven-project/30898810

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@christophs78 merge conflicts.

**Review by melloware — APPROVED** [review]

**Pull request merged**
