### PR TITLE
Fix #5579: Spinner allow navigation keys

### LINKED ISSUE #5579: Spinner: should not allow to enter non-numeric values
The p:spinner component should not allow to enter non-numeric values. 

## 1) Environment
- PrimeFaces version: 8.0 RC3

## 2) Expected behavior

The spinner component allows only numeric values and does not let the user enter any symbols that would lead to non-numeric values.

Above that the spinner should only allow only values that are instances of the underlying number class. For instance, if the spinner is invoked with Long/Integer/Short values it should automatically apply decimalPlaces="0". 

Ideally, all bean validation constraints should be also fully respected to.

## 3) Actual behavior

Current you can enter any string. In some cases, the spinner will crop them to numeric values, in some not. See Below:

* you can enter -1-222 and will produce -1.

* when you enter .022.222 it will even be accepted as it is.

## 4) Steps to reproduce

Just use the basic spinner demo https://www.primefaces.org/showcase/ui/input/spinner.xhtml
and enter the above values.

## 5) Sample XHTML

..

## 6) Sample bean

..

### PR DESCRIPTION
**Pull request by melloware**
@tuerker added navigation keys

### CODE REVIEW

**Comment by tuerker** [comment]
strange. although i have the latest PF snapshot (see your changes in the screenshot), the four buttons do not work. attached is my reproducer.

Screenshot from 2020-11-19 17-42-27

[p-spinner.zip](https://github.com/primefaces/primefaces/files/5568346/p-spinner.zip)

**Comment by melloware** [comment]
Let me try it

**Comment by melloware** [comment]
Works fine for me in latest Firefox and Chrome.  All 4 keys work fine arrows and backspace and delete

**Comment by melloware** [comment]
I even put a breakpoint in the JS and I can see it hitting the `return` statement when I press one of those 4 keys.

**Comment by tuerker** [comment]
I tried it on my machine at home. There, the same reproducer is working. Sorry, for the false alarm.

And as usual, many thanks for your great job.

**Comment by melloware** [comment]
No problem thanks for reporting back!

**Pull request merged**
