### PR TITLE
Fix #4647: UIData "All" pagesPerRow validation.

### LINKED ISSUE #4647: DataTable: fix "All" pagesPerRow validation
See: https://github.com/primefaces/primefaces/issues/4636

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
Didn't we added the validation already?

**Comment by tandraschko** [comment]
Please also See: https://github.com/primefaces/primefaces/issues/4647

**Comment by melloware** [comment]
I think this fix addresses "fabermundi's" comment on https://github.com/primefaces/primefaces/issues/4636 that its not quite fixed all the way if filtering is enabled.

**Comment by tomlux** [comment]
yes, this is solving "fabermundi's" bug, we are working together

**Comment by tandraschko** [comment]
Also what happens when "value" is a Datamodel?

**Comment by tomlux** [comment]
Should be like this, but didn't tested it:
```Java
            int totalRowCount = 0;
            Object valueObj = getValueExpression("value").getValue(getFacesContext().getELContext());
            if (valueObj instanceof Collection) {
                totalRowCount = ((Collection) valueObj).size();
            } else if (valueObj instanceof DataModel) {
                totalRowCount = ((DataModel) valueObj).getRowCount();
            }
```

**Comment by melloware** [comment]
Pushed a fix.

**Comment by tandraschko** [comment]
IMO the client should send "all" instead a Count as it might Chance during requests Like mentioned in my linked ticket

**Comment by tandraschko** [comment]
@melloware would you like to rework it?

**Comment by melloware** [comment]
Let me look at this one and see if I can rework it.

**Comment by tandraschko** [comment]
@melloware 
here is a prototype patch: https://gist.github.com/tandraschko/14f411b503d415ec50ffab53ba78534f

**Comment by tandraschko** [comment]
also see #4944

**Comment by melloware** [comment]
@tandraschko I am out today but will test your patch tomorrow morning (US Eastern Time) and let you know how it goes!

**Comment by melloware** [comment]
@tandraschko so far this seems to be working well for me. I think its safe for you to merge and I will kill this PR. and we can see anyone using 7.1-SNAPSHOT reporting any issues.

**Pull request closed without merging**
