### PR TITLE
fix for issue #5523

### PR DESCRIPTION
**Pull request by matinh**
Ok, here is a PR that tries to fix issue #5523. It does not re-introduce issue #4931!

### CODE REVIEW

**Comment by melloware** [comment]
Unfortunately still doesn't fix all scenarios.  Just run the showcase locally and go to this example: http://localhost:8080/showcase/ui/data/datatable/paginator.xhtml

The paginator is not working at all.

**Comment by melloware** [comment]
Or just switch your use case from `rows="#{testViewCdi.rowsPerPage}"` to `rows="2"` to see the broken default use case

**Comment by matinh** [comment]
Ok, I fixed this issue. Now the mentioned show-case and the two mentioned issues work.
Anyway, I can't say I'm confident that everything is working now. I just don't know PrimeFaces components to little.

**Comment by melloware** [comment]
You are going great.  let me test out your latest changes

**Comment by melloware** [comment]
OK you definitely fixed the main use case without using an EL expression using the hard coded "2".

However try this...

1. Set rowsperPage to 1
2. Filter by String "o" which will produce 3 records and now you have 3 pages and the row being displayed is "One".
3. Page to page 2 and you will see the row being displayed is still "One" and it should be "Two".  Same for Page 3.

**Comment by matinh** [comment]
You are just too fast ;-)

I was just reviewing my changes when noticing, that using stateHelper for `first` as well was just too much. I committed some more changes. Could you please try once more.

**Comment by melloware** [comment]
OK that looks good.  Now I am just down to 1 scenario not working.

1. Set rowsPerPage to 1.
2. Filter by "o" should produce 3 pages.
3. click on Page 3 you properly see item "Four".
4. Now change rowsPerPage to "3" so you can see all 3 items.  Nothing happens.

**Comment by matinh** [comment]
You are right, I can reproduce this. However, I've absolutely no idea why this happens. I noticed, that the last click on "rowsPerPage" doesn't even create an AJAX request in the browser. Very strange! Maybe this is some other, unrelated bug?

**Comment by melloware** [comment]
Yeah it might be a problem in the paginator.js not sending the Ajax request if it thinks someting hasn't changed.   Might want to set a browser breakpoint there.

**Comment by matinh** [comment]
It seems this only happens, when you increase rows in a ways the currently active page would no longer exist and should thus be reset/decremented.

**Comment by melloware** [comment]
You are right this feels like a JS fix needs to be done.

**Comment by melloware** [comment]
OK the regression was caused by #5493.  You can close this PR i am submitting one that fixes all issues for #5523,  #4931 and for  #5493

**Comment by matinh** [comment]
Closing this PR, as PR #5527 includes this fix.

**Pull request closed without merging**
