### PR TITLE
Fix #232: Schedule localization of 'weekNumberTitle'.

### LINKED ISSUE #232: Schedule component Internationalization support for 'weekNumberTitle' property
Currently Schedule component always displays the default value of 'weekNumberTitle' property.It should support internationalization through locale configuration.

### PR DESCRIPTION
**Pull request by melloware**
Fix #232: Schedule localization of 'weekNumberTitle'.

### CODE REVIEW

**Comment by jxmai** [comment]
build failure ? Is it something wrong in trunk ?

**Comment by melloware** [comment]
yep @mertsincan broke it this morning with his check in.

**Comment by jxmai** [comment]
Not checkstyle this time, so not that we can help

https://travis-ci.org/primefaces/primefaces/jobs/308315495

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project primefaces: Compilation failure
[ERROR] /home/travis/build/primefaces/primefaces/src/main/java/org/primefaces/component/tree/TreeRenderer.java:[287,43] cannot find symbol
[ERROR]   symbol:   method getDropMode()
[ERROR]   location: variable tree of type org.primefaces.component.tree.Tree
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
```

**Comment by jxmai** [comment]
@melloware The trunk is working now, but this pull won't be able to re-run travis unless we trigger it again.

so you can 1. fetch upstream. 2. git rebase upstream/master 3. git push --force to this branch again.

**Comment by melloware** [comment]
Let me do that now to both these branches

**Pull request merged**
