### PR TITLE
Update the terminal component to fix scrolling, sanitize input and allow async push

### PR DESCRIPTION
**Pull request by jcetkov**

### CODE REVIEW

**Comment by srbala** [comment]
Pull request missing the link to [Primefaces forum](http://forum.primefaces.org/viewforum.php?f=3) discussion. Discuss the issue in the forum before post pull request.

Also review the [contributing rules](https://github.com/primefaces/primefaces/wiki/Contributing-to-Primefaces).

**Comment by tandraschko** [comment]
Also you use an static id which will not work correctly if you have multiple terminals on the same view.

**Comment by jcetkov** [comment]
I'll create a forum discussion, sorry for that, I went from a bit different direction - I did the modifications so the component worked for what I needed, and thought I might as well contribute it back.
tandraschko, yes I was thinking of that, is there a way to read a java constant from js? - or what would be the least dirty trick to achieve that?

**Comment by jcetkov** [comment]
I submitted a forum post, waiting for approval. I'll also change obtaining of the prompt container from the fixed id to something similar to obtaining other pieces in the terminal.js, for the multiple terminals issue

**Comment by tandraschko** [comment]
As you render it inside a div with the componentClientId, you can just give it a own css class and get it in js via: this.jq.find('.myPromtCss');
or e.g. clientId + "_promt" or something.

Thats the problem with pull requests. We need to do a detailed review and test it. It's very time consuming...
In many cases it will be much better that the PF team implements the changes.

**Comment by kryckann** [comment]
Remove me from your thread. I have nothing to do with this. Someone has
signed up my email address.

Thank you!
Jonas

fredag 17 april 2015 skrev Thomas Andraschko notifications@github.com:

**Comment by jcetkov** [comment]
Well, thats the downside of OSS (I try to make it as clean as possible and comment to make it easier for you). I changed the id to a class and lookup, similar to what is already there for the content.

the forum post is http://forum.primefaces.org/viewtopic.php?f=3&t=41857&e=0

**Comment by tandraschko** [comment]
@kryckann than stop watching the project etc, WE can't remove you.

**Comment by kryckann** [comment]
Jonas (kryckann), remove me please. I don't want these emails as I You have registered the wrong email address. Thanks

Jonas

**Comment by srbala** [comment]
@kryckann: Since you have commented on this issue, you many want to use right hand side menu "Notifications" and choose "Unsubscribe". Project members have no control over notifications sent out to participants. 

Another location you may want to review is your [account settings](https://github.com/settings/notifications). You can pick and choose web/email notifications and alternative email address in case of change is required. After that check your [watch list](https://github.com/watching) then pick and choose necessary action as required.

Other link could be useful are 

https://github.com/notifications?all=1
https://github.com/notifications/participating

**Comment by tandraschko** [comment]
your PR looks better now! I will give a detailed review and a small test the next days.

**Comment by shikida** [comment]
I need it to scroll too

**Comment by jcetkov** [comment]
@shikida before it's merged in the master, you can just have my changes as a custom component in your own source base (that's what I am doing now)

**Comment by cagataycivici** [comment]
Please create an issue ticket with details on what the PR does. I couldn't understand the changes yet.

**Comment by jcetkov** [comment]
I updated the forum post with breakdown of the changes (http://forum.primefaces.org/viewtopic.php?f=3&t=41857&p=137629#p137629). Please let me know if you need more clarification. Or do you mean to create separate git issue? In the time of submission of this ticket, forum was the proffered way (but it was just after the migration to github)

**Comment by tandraschko** [comment]
I implemented your changes on based on your PR.
See: https://github.com/primefaces/primefaces/commit/390d3c7bfd3708d0a1b063e7f1e40808f23c2df4

Thanks for your effort.

**Pull request closed without merging**
