### PR TITLE
Fix #3416 - Panel: do not encode footer if child not rendered

### LINKED ISSUE #316: Allow EventBus injection
Currently there is no easy way to inject the `EventBus` into a class. With Atmosphere 2.3.2 it would be quite simple, as explained [here](https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere's-Classes-Creation-and-Injection)

### LINKED ISSUE #3416: Panel: do not encode footer if child not rendered
## 1) Environment
- PrimeFaces version: 6.2

## 2) Expected behavior

Footer should not be displayed if child not rendered

## 3) Actual behavior

Footer is displayed

## 4) Steps to reproduce
```xml
            <p:panel id="basic" header="Basic" style="margin-bottom:20px">
                <h:panelGrid columns="2" cellpadding="10">
                    <p:graphicImage name="demo/images/godfather/godfather1.jpg" />
                    <h:outputText
                        value="The story begins as Don Vito Corleone, the head of a New York Mafia family, oversees his daughter's wedding.
                        His beloved son Michael has just come home from the war, but does not intend to become part of his father's business.
                        Through Michael's life the nature of the family business becomes clear. The business of the family is just like the head of the family, kind and benevolent to those who give respect,
                        but given to ruthless violence whenever anything stands against the good of the family." />
                </h:panelGrid>
                
                <f:facet name="footer">
                    <p:commandButton value="Test" rendered="false"/>
                </f:facet>
            </p:panel>
```

image

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by tandraschko** [comment]
What about using ComponentUtils#shouldRenderFacet?

**Comment by Rapster** [comment]
Yes indeed, do you think this method could also test nullity of the component? To avoid cumbersome testing while using a utility method

**Comment by tandraschko** [comment]
yup

**Comment by Rapster** [comment]
Okay, I'll do the change in the PR itself then

**Pull request merged**
