### PR TITLE
Fix #6506: Calendar/DatePicker allow java.sql.Date

### LINKED ISSUE #6506: Calendar: Using min-/maxdate throws an error
**Describe the defect**
When using mindate or maxdate as java.sql.Date the calendar component throws an exception.
See
`class java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException
	at java.sql.Date.toInstant(Date.java:315)
	at org.primefaces.util.CalendarUtils.convertDate2ZonedDateTime(CalendarUtils.java:439)
	at org.primefaces.util.CalendarUtils.convertDate2LocalDate(CalendarUtils.java:452)
	at org.primefaces.util.CalendarUtils.convertDate2LocalDate(CalendarUtils.java:444)
	at org.primefaces.util.CalendarUtils.getObjectAsLocalDate(CalendarUtils.java:80)
	at org.primefaces.component.calendar.Calendar.validateValue(Calendar.java:139)
	at javax.faces.component.UIInput.validate(UIInput.java:670)`

**Environment:**
 - PF Version: 8.0.3
 - JSF version: MyFaces 2.3
 - Affected browsers: ALL

**Example XHTML**
```<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui">
	
	<h:form>
		<p:messages />
		<p:calendar mindate="#{testHandler.minDate}" maxdate="#{testHandler.maxDate}" value="#{testHandler.date}" />
		<p:commandButton value="Save" actionListener="#{testHandler.save}" update="@form" />
	</h:form>

</ui:composition>
```

**Example Bean**
```java
package test;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Date;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestHandler implements Serializable {

	private static final long serialVersionUID = 1L;

	private Date date;

	public Date getMinDate() {
		return java.sql.Date.valueOf(LocalDate.now().minusDays(10));
	}

	public Date getMaxDate() {
		return java.sql.Date.valueOf(LocalDate.now());
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public void save() {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "saved", null));
	}

}
```

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
@christophs78 can you review?

+1 from my side

**Comment by christophs78** [comment]
@melloware : You tested this PR and it works?
I would have expect we need to take java.sql.Date also into account at `org.primefaces.component.calendar.BaseCalendarRenderer#getConvertedValue`. 

Ah. Maybe you "only" fixed 6506 and added support for java.sqlDate as mindate/maxdate. I think we should also allow to value-bind  Calendar/DatePicker to java.sql.Date. For this i would expect we need to touch `org.primefaces.component.calendar.BaseCalendarRenderer#getConvertedValue` and/or `org.primefaces.component.calendar.BaseCalendarRenderer#convertToLegacyDateAPI`.

**Comment by melloware** [comment]
Correct this fixes the issue with min/max date.  Yep let me update my Integration test not to use `LocalDate` i will use `java.sql.Date`.

**Comment by melloware** [comment]
Ahh according to BalusC this is not supported:
https://stackoverflow.com/questions/10286724/cannot-convert-4-23-12-1200-am-of-type-class-java-util-date-to-class-java-sql-d

You should never use `java.sql` as your binding value. And I can confirm this never even gets into PF code.

```
Caused by: javax.el.ELException: /test.xhtml @17,134 value="#{testView.date}": Cannot convert [11/12/20, 12:00 AM] of type [class java.util.Date] to [class java.sql.Date]
        at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:139)
        at javax.faces.component.UIInput.updateModel(UIInput.java:834)
        ... 48 more
Caused by: javax.el.ELException: Cannot convert [11/12/20, 12:00 AM] of type [class java.util.Date] to [class java.sql.Date]
        at org.apache.el.lang.ELSupport.coerceToType(ELSupport.java:576)
        at org.apache.el.parser.AstValue.setValue(AstValue.java:202)
        at org.apache.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:263)
        at org.apache.webbeans.el22.WrappedValueExpression.setValue(WrappedValueExpression.java:93)
        at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:131)
```

**Pull request merged**
