### PR TITLE
SelectManyMenu: selectAll/unselectAll throws an exception when showCheckbox is true 

### PR DESCRIPTION
**Pull request by andrewtobilko**
`children('td')` or `children('td').first()` fixes the issue I described here
https://github.com/primefaces/primefaces/issues/5600

### CODE REVIEW

**Comment by christophs78** [comment]
@andrewtobilko: Please look at my comment on the issue. We are not allowed to always do children('td').
There´s different HTML-structure between basic and advanced sample.

**Comment by andrewtobilko** [comment]
@christophs78 We are inside the `if(this.cfg.showCheckbox)`, which means a `td` for the checkbox has been rendered and at least one `td` is present in DOM. Please, correct me if I am wrong.

**Comment by christophs78** [comment]
```
<p:selectManyMenu id="basic" widgetVar="basic" value="#{selectManyView.selectedOptions}" showCheckbox="true">
	<f:selectItem itemLabel="Option 1" itemValue="1" />
	<f:selectItem itemLabel="Option 2" itemValue="2" />
	<f:selectItem itemLabel="Option 3" itemValue="3" />
</p:selectManyMenu>
```
generates
grafik
--> no table, no tr, no td, ....

```
<p:selectManyMenu id="advanced" value="#{selectManyView.selectedThemes}" converter="#{themeConverter}"
				  var="t" filter="true" filterMatchMode="contains" showCheckbox="true" widgetVar="advanced">
	<f:selectItems value="#{selectManyView.themes}" var="theme" itemLabel="#{theme.displayName}" itemValue="#{theme}" />

	<p:column>
		<h:graphicImage name="showcase/images/themeswitcher/themeswitcher-#{t.name}.png" alt="#{t.name}" styleClass="ui-theme" />
	</p:column>

	<p:column>
		<h:outputText value="#{t.displayName}" />
	</p:column>
</p:selectManyMenu>
```
generates
grafik
--> this one has a table

So we need to check which variant we have.

**Comment by andrewtobilko** [comment]
@christophs78 makes sense, thanks. I am closing this PR.

**Pull request closed without merging**
