### PR TITLE
Adding CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by hatemalimam**
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

I think the part of creating pull requests and the proper branch is
missing ?

### CODE REVIEW

**Comment by cagataycivici** [comment]
There is a wiki;

https://github.com/primefaces/primefaces/wiki/Contributing-to-Primefaces

**Comment by hatemalimam** [comment]
I understand that there's a wiki, as I have requested a pull request earlier today and you have pointed me out that I should pull a tag reagarding jsf-maven-plugin I didn't get an automatic notice from github that there are a contributing terms to follow, which might have prevented me from submiting that request, as a result I figured out that a contributing.md is handy to alert the users before submitting any pull-request which is done by github :)

**Comment by srbala** [comment]
He has used the same of PrimeFaces wiki Contributing page, his suggesting is to make use of github features to show the link to new issue creator.

Example: If you try to create a issue with thymeleaf project, you could see their contributing link.

Try the two links below (may be ctrl+click to see it on two pages side by side) , you could see the difference, you don't really have to create a issue.

https://github.com/thymeleaf/thymeleaf/issues/new
https://github.com/primefaces/primefaces/issues/new

My recommendation is to accept the patch, when PrimeFaces users create a issue, contribution link will show up after that.

**Comment by cagataycivici** [comment]
Does contributing.md show up when you create an issue as well in addition to when creating pull requests?

**Comment by ubala** [comment]
Yes it does.

I did a test on one of my repository. I have attached screen capture
jsftools-pull

**Comment by cagataycivici** [comment]
Thanks, I'll commit soon.

**Comment by cagataycivici** [comment]
Merged, thank you.

**Pull request merged**
