### PR TITLE
fix #4385 - calendar: potential XSS when using user-supplied timeOnlyTitle translation

### LINKED ISSUE #4385: calendar: potential XSS when using user-supplied timeOnlyTitle translation
## 1) Environment
- PrimeFaces version: 6.3-snapshot

## 2) Expected behavior
`timeOnlyTitle `is contained in `PrimeFaces.locales` (https://github.com/primefaces/primefaces/wiki/Locales) and therefore must be considered as user-supplied input.

## 3) Actual behavior
The value is passed through to `jquery.ui.timepicker.js` without being escaped there: 					https://github.com/primefaces/primefaces/blob/f6f316d851da276824fdf70495c160b071386d37/src/main/resources/META-INF/resources/primefaces/jquery/jquery.ui.timepicker.js#L440

This is actually a bug in `jquery.ui.timepicker.js`. However, since PrimeFaces bundles it, it should be fixed here as well.

Basically all strings contained in `PrimeFaces.locales` should be paid extra attention.

### PR DESCRIPTION
**Pull request by cnsgithub**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@cnsgithub Just add a comment to \jquery\extensions.txt and add TimePicker and mention this ticket as to what has been updated like...

> jquery.ui.timepicker.js:
> - Added fix to timepicker from https://github.com/trentrichardson/jQuery-Timepicker-Addon/issues/848
> - Fixed XSS in timepicker from https://github.com/primefaces/primefaces/issues/4385

**Comment by cnsgithub** [comment]
@melloware Done. Thx.

**Comment by melloware** [comment]
Thanks and nice work!

**Comment by mertsincan** [comment]
Thanks a lot, @cnsgithub ;) 

https://www.primefaces.org/primefaces-7-0-rc1-released/
> Special Thanks
>
> ... we’d like to thank PrimeFaces committers Rapster, Melloware and security contributor Cnsgithub along with all the members of PrimeFaces who bring in constant feedback to help us out.

**Pull request merged**
