### PR TITLE
fix #899: enhance dialog fitViewport funcionality

### LINKED ISSUE #899: fitViewport in dialog does consider header/footer height
The facelets page below should show a dialog with a content, that is to large to fit on the window. It is expected, that the dialog content is sized, so that header an footer fit the window.

Currently after clicking on "Show Dialog" the dialog is correctly opened, but the footer is invisible (outside the window to the south). When the dialog is resized, the dialog snaps to the right size.

The test was done with:

primefaces 5.3
payara 4.1.153

Client browsers Firefox 42, Chromium 45 and IE 11

``` xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Demo fitViewport</title>
    </h:head>
    <h:body>
        <h:form>
            <p:commandButton  type="button" onclick="PF( 'Test' ).show()" value="Show Dialog"/>

            <p:dialog id="Test" widgetVar="Test" header="Test" fitViewport="true" modal="true">
                <div style="height: 2000px">
                    Demo content
                </div>
                <f:facet name="footer">
                    <p:commandButton type="button" onclick="PF( 'Test' ).hide()" value="Hide Dialog"/>
                </f:facet>
            </p:dialog>
        </h:form>
    </h:body>
</html>
```

### PR DESCRIPTION
**Pull request by vonnai**
Hi I fixed issue #899. If fitViewPort is true, dialog computes height by dialog margin, titlebar, content and footer (if exists). For correct compute dialog height I had to create his clone with different css styles. I added support for responsivity. If window resize is fired, fitVieport function is called.

### CODE REVIEW

**Comment by melloware** [comment]
I think this is also related to #1862 can you verify?

**Comment by vonnai** [comment]
You are right

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
Whats wrong with the current calculation of the size?

**Comment by melloware** [comment]
@vonnai please feel free to correct me if I am wrong but I think the biggest things this PR does is..

1) For lazy loaded dialogs it correctly computes the height.
2) Its responsive, If content is bigger than viewport, height is correctly computed and there is scrollbar on the right side of dialog. 
3) Entire dialog is always visible and for example buttons in footer part will be always visible too.
4) If the window size changes this is responsive so it will re-calculate the dialog.

**Comment by ghost** [comment]
Could also fix https://github.com/primefaces/primefaces/issues/2062 but not sure.

In which new PF version will this be included?

**Comment by tandraschko** [comment]
Probably in 6.2

**Comment by brunoaandrade** [comment]
@tandraschko, in version 6.2 i still have the same problem.

**Pull request merged**
