### PR TITLE
Fix #11685 - Datatable: action not called if columns is rendered conditionnally

### LINKED ISSUE #11685: Datatable: action not called if columns is rendered conditionnally
### Describe the bug

From @BryanV91

> Im facing an issue with dataTable, dynamic columns and rendered attribute
trying to download a file, but method is never invoked
when I set rendered to a custom value, it doesnt work
however, if I manually set rendered to true, it works

### Reproducer

```xml
<h:form id="frmTest">
<p:dataTable id="tbl" var="record" value="#{testView.list}">
  <p:columns id="column" value="#{testView.cols}" var="col" columnIndexVar="index" rendered="#{col.rendered}">
      <p:commandButton value="Download" ajax="false" icon="pi pi-arrow-down" styleClass="mr-2">
        <p:fileDownload value="#{testView.file}" /> File #{column}
      </p:commandButton>
  </p:columns>
</p:dataTable>
</h:form>
```

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/14782284/primefaces-test-master.zip)

### Expected behavior

file should be downloaded

### PrimeFaces edition

Community

### PrimeFaces version

13.0.7

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by Rapster**
Fix #11685

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by Rapster** [comment]
@melloware let me try https://github.com/primefaces/primefaces/issues/7986 first before merging (i'll let you know by this evening)

**Comment by melloware** [comment]
@Rapster got it just let me know when you want me to merge and backport.

**Comment by Rapster** [comment]
https://github.com/primefaces/primefaces/issues/7986 still working 😉

**Comment by Rapster** [comment]
Pinging @tandraschko to chime in

**Comment by tandraschko** [comment]
looks good
i think we should just add a test here

**Comment by melloware** [comment]
I wrote a failing integration test: https://github.com/primefaces/primefaces/pull/11721

Will merge this and then see if it passes

**Pull request merged**
