### PR TITLE
Docu: Prime Client Window

### PR DESCRIPTION
**Pull request by christophs78**
It´s very basic at this point in time. We may add more over time.

### CODE REVIEW

**Comment by tandraschko** [comment]
i would change the docu in multiviewstate.md a bit.
Currently it reads like its only compatible with PF ClientWindow
but its also compatible with the default JSF one or DeltaSpike.

**Comment by christophs78** [comment]
> 
> 
> i would change the docu in multiviewstate.md a bit.
> Currently it reads like its only compatible with PF ClientWindow
> but its also compatible with the default JSF one or DeltaSpike.

Good point!

**Comment by tandraschko** [comment]
I think we should also point out (at least a bit) whats the difference compared to the plain JSF one
- JSF doesnt append the url param on initial redirect, so f5 creates a new windowId
- JSF doesnt validate if the tab was initialy openend with another windowId
- it uses sessionStorage for save and validate the windowId
- the worklfow is the same as deltaspike lazy mode

**Comment by tandraschko** [comment]
Thanks :)

**Pull request merged**
