### PR TITLE
PF-2407: remove autocomplete attribute from hidden inputs because of …

### PR DESCRIPTION
**Pull request by OBreidenbach**
…w3c validator

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Changes look good to me as long as their was no PF reason for having these autocomplete attributes on there in the first place.

**Comment by tandraschko** [comment]
@mertsincan @cagataycivici do you remember why we added this? AFAIK there was a reason but can't remember.

**Comment by mertsincan** [comment]
Hi @tandraschko,

We need to keep autocomplete on hidden elements as it causes issues on firefox. Exp;
on Basic AccordionPanel demo;
- select the second header(Godfather Part II)
- refresh page
- please see the value of hidden input on DOM;

Screenshot without autocomplete="off";
without autocomplete_off

You can see the same behavior in other components(without autocomplete="off")

**Comment by tandraschko** [comment]
Yep, ok. See we should just close it as won't fix?

**Pull request closed without merging**
