### PR TITLE
Fix #5097 - Timeline: move event between groups change its type

### LINKED ISSUE #5097: Timeline: move event between groups change its type
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: WildFly 10.1
- Affected browsers: all

## 2) Expected behavior
When user moves a timeline event between groups, the event should maintain its type ('range', 'box', etc). 

## 3) Actual behavior
When user moves a timeline event between groups, the event change its type to 'box' always.

## 4) Steps to reproduce

1. Go to timeline/custom showcase: https://www.primefaces.org/showcase/ui/data/timeline/custom.xhtml
2. Move an event to another group

     image

3. The event change its type from 'range' to 'box'.

     image

### PR DESCRIPTION
**Pull request by jasonex7**

### CODE REVIEW

**Review by melloware — APPROVED** [review]
@tandraschko Since this library is the last version and we already have a backlog ticket to move to the new vis.js library I am OK with making this change directly in the timeline.js code.  Thoughts?

https://github.com/primefaces/primefaces/issues/3245

**Comment by jasonex7** [comment]
@melloware I've downloaded timeline.js version [2.9.1](http://almende.github.io/chap-links-library/js/files/timeline-2.9.1.zip) from the site http://almende.github.io/chap-links-library/timeline.html and that file already had the fix. I don't know why primefaces timeline.js differs from the original on that line.

**Comment by melloware** [comment]
Oh wow did you do a diff to see if there any other differences?  I thought we were using 2.9.1?

**Comment by jasonex7** [comment]
Yes, I did a diff. There are only 2 more differences:

#### Diff 1 
##### PF timeline.js starting from line 774
````javascript
links.Timeline.prototype.setVisibleChartRangeAuto = function() {
    if (this.options && (this.options.start || this.options.end)) {
        this.setVisibleChartRange(this.options.start, this.options.end);
    } else {
        var range = this.getDataRange(true);
        this.setVisibleChartRange(range.min, range.max);
    }
};
````
##### Original timeline.js starting from line 774
````javascript
links.Timeline.prototype.setVisibleChartRangeAuto = function() {
    var range = this.getDataRange(true);
    this.setVisibleChartRange(range.min, range.max);
};
````

#### Diff 2 
##### PF timeline.js starting from line 5336
````javascript
if (axisOnTop) {
      groupBase += Math.max(options.groupMinHeight, group.labelHeight) + eventMargin;
} else {
       groupBase -= (Math.max(options.groupMinHeight, group.labelHeight) + eventMargin);
}
````
##### Original timeline.js starting from line 5332
````javascript
if (axisOnTop) {
       groupBase += options.groupMinHeight + eventMargin;
} else {
       groupBase -= (options.groupMinHeight + eventMargin);
}
````

**Comment by melloware** [comment]
OK so Diff#2 the "groupbase" fix was done on purpose: https://github.com/primefaces/primefaces/issues/1995

Diff#1 I can't explain.

**Comment by jasonex7** [comment]
I've investigated about my commit proposed on this PR and I found that this was the original behavior until change was introduced in primefaces-extensions on this commit: https://github.com/primefaces-extensions/core/commit/60e9188b2182e15492ebda6bfd1599044643d61a on [line 4931](https://github.com/primefaces-extensions/core/blob/04311a7197309c3dab9ce9cac3f32aa18768497b/src/main/resources/META-INF/resources/primefaces-extensions/timeline/0-timeline.js#L4931) related to [issue 298](https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/298). I think that change was mistakenly introduced.

**Comment by jasonex7** [comment]
> Diff#1 I can't explain.

I've investigated that Diff#1 comes from this commit on primefaces-extensions https://github.com/primefaces-extensions/core/commit/0d9d7fe395f2dc8578181b8e3d63cf6860b92daa to resolve [issue 323](https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/323)

**Comment by melloware** [comment]
OK cool. great detective work.

**Comment by jasonex7** [comment]
> OK cool. great detective work.

Thank you.

> I think I will do this for PF 7.1  My client started using this component and it would be good to update but its too close to 7.0 release.
> _Originally posted by @melloware in https://github.com/primefaces/primefaces/issues/3245#issuecomment-463615310_


By the way @melloware how does issue #3245 is going? :smile: :+1:

**Comment by melloware** [comment]
HA I think it was bigger than i thought so I put it to the side.  As a note we are successfully using Timeline in production and its quite solid!

**Comment by jasonex7** [comment]
Thanks for that comment, I hope some day that issue was closed. By now I only miss from vis.js the capability of hide some ranges of time (perhaps non labor hours/days) using `hiddenDates` [configuration option](https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options).

**Comment by melloware** [comment]
Have you looked into it at all on how difficult it would be to migrate to vis.js. I didn’t know how drastically rewritten it was?

**Comment by jasonex7** [comment]
I've only compared javascript sources (timeline.js vs vis-timeline-graph2d.esm.js version 5.1.0 and also timeline.js vs vis.js version 4.21) superficially and saw that there are plenty of differences.

**Pull request merged**
