### PR TITLE
quill editor

### PR DESCRIPTION
**Pull request by husnutapan**

### CODE REVIEW

**Comment by tandraschko** [comment]
Sorry but we already have 2 editors in the primefaces universe
1) cleditor in PF
2) ckeditor in PFE
i think we will add another but this probably needs discussions
@cagataycivici  WDYT?

**Comment by cagataycivici** [comment]
Our current editor is old and we need something modern, I guess we can just replace cleditor instead?

**Comment by tandraschko** [comment]
we should yes, but i don't think that ckeditor or quill will suite or license terms
ckeditor would be the better choice

**Comment by tandraschko** [comment]
quill is also only compatible with IE11+
i think the best choice is really CKEditor but we can't include it directly in PF as it's GPL/MPL/LPGL which is not compatible with apache2.
Our resources jar for ckeditor is currently also not released under apache2.

**Comment by tandraschko** [comment]
Will close it for now, we will discuss it internally as quill can't be used (license doesn't match and we have customers with < IE11)

**Pull request closed without merging**
