### PR TITLE
Fix #4727: Dialog only use aria-labelledby is showHeader=true.

### LINKED ISSUE #4727: Dialog: improve accessibility when showHeader=false
## 1) Environment
- PrimeFaces version: 7.0
- Affected browsers: all

## 2) Expected behavior

The attribute `aria-labelledby` of p:dialog is hidden when there is no header. (`showHeader="false"`)

## 3) Actual behavior

An `aria-labelledby` is present and it references a not existing ID, which is forbidden. It should be generated only when showHeader is true.

## 4) Steps to reproduce

Add a p:dialog with `showHeader="false"` into a page.

## 5) Sample XHTML

```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">
    <h:head />
    <h:body>
        <h:form>
        	<p:dialog widgetVar="dia" showHeader="false">Hello World !</p:dialog>
        	<p:commandButton onclick="PF('dia').show()" />
        </h:form>
    </h:body>
</html>
```

## 6) Sample bean

None is necessary.

### PR DESCRIPTION
**Pull request by melloware**
I simply check for the existence of the title element and only set aria-labelledBy if the title is found.

### CODE REVIEW

**Comment by tandraschko** [comment]
Don't you miss a "#" in the selector?

**Comment by melloware** [comment]
I sure did. Committed.

**Comment by tandraschko** [comment]
Still not sure if this works as this.id can contain ":", which must be escaped.
We use PrimeFaces.escapeCLientID for this

**Comment by melloware** [comment]
You are right updated to PrimeFaces.escapeClientId.

**Pull request merged**
