### PR TITLE
Fix #7364: enhanced FileUpload documentation

### LINKED ISSUE #7364: FileUpload: Multiple with auto="true" only works first time
**Describe the defect**
Getting irregular and unreliable results when performing an auto, advanced, multiple file upload.  
On startup you simply get a file upload instance to select csv files from. I'm assuming you have, or can get a set of csv files (~4) to be able to use for this. On first selection it appears to work correctly, i.e., select 4 files and upon submit, the table showing files selected will list all four.  
The `Clear List` button does just that... it removes the file selected list and refreshes the section and should see no files selected.  
Now do this again... select the same four files. I'm seeing that subsequent file selections are being missed... in fact, most of the time.

**Reproducer**
I have a fork of the primefaces-test repo [here.](https://github.com/karlkras/primefaces-test)

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _e.g. Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. Have 4 csv files available in a test directory.
2. Click on the `Choose` button (FileUpload control)
3. Navigate to directory with test csv files, select all.
4. When updated, you will see list of files selected in a table below the control.
5. (First time in, it appear to show all files correctly.)
6. Click on `Clear List`
7. File resources will be deleted from backing bean, form updated, and fileupload will be available again.
8. Repeat #s 2-4 
9. Subsequent selections will show irregular results in the files that were selected. Mostly incorrectly.

**Expected behavior**
I would expect to see the resulting file list represent exactly what I had selected.

```

### PR DESCRIPTION
**Pull request by wal-jan**
Just a proposal for version 11. (Maybe it can be copied to version 10 docs.)

### CODE REVIEW

**Comment by melloware** [comment]
This looks good!

**Comment by melloware** [comment]
Feel free to copy it to the 10.0.0 version of the doc too.

**Comment by wal-jan** [comment]
IMO we can close #7364 now.

**Comment by melloware** [comment]
Done!

**Pull request merged**
