### PR TITLE
Fix #9780 - MatchMode: returns STARTS_WITH by default if blank

### LINKED ISSUE #9780: MatchMode: should returns STARTS_WITH by default if blank
### Describe the bug

Following up discussion in #9767 

`MatchMode` should returns `STARTS_WITH` if blank, and throw exception if unkown value

### Reproducer

_No response_

### Expected behavior

Be lenient with blank value, and prevent further error

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

All

### JSF version

2.3

### Java version

8

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I like this a lot.  @newk5 ??

**Comment by Rapster** [comment]
Maybe in `Column#getFilterMatchMode` instead of a raw string, make a reference to something like `UIColumn#DEFAULT_FILTER_MATCH_MODE`. WDYT?

**Comment by melloware** [comment]
Yep I always like a constant better.

**Comment by newk5** [comment]
Yea I prefer constant aswell

**Review by melloware — APPROVED** [review]

**Pull request merged**
