### PR TITLE
Fixed #1818

### LINKED ISSUE #1818: calling ClearFilters on DataTable without filter - No error was thrown but something failed internally
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version: Primefaces v5.3
- Does it work on the newest PrimeFaces version? No, it failed on v6.0.x
- Application server + version: Tomcat v8.0
- Affected browsers: Firefox v49.0 (Browser version is irrelevant for this issue actually)
## 2) Expected behavior

Calling clearFilters on DataTable without filter **should do nothing as if nothing happened**. 
## 3) Actual behavior

No error was thrown, but the table was frozen. It will give developers a hard time to trace the bug ...
## 4) Steps to reproduce

Step 1: Click **Add a new row** footer button on the table, and a new record will be added

capture

Step 2: Click **Clear Filter** footer button on the table

Step 3: Repeat Step 1, and **add button stops working from UI perspective**. No error was thrown

**_on Browser Side (No error):**_

capture

**_on Server Side (No error)**_:

capture
## 5) Sample XHTML

**table.xhtml**

``` html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<h:head>

</h:head>

<h:body>
    <h:form id="form">
        <p:growl id="msgs" showDetail="true" />

        <p:dataTable value="#{editableTableBean.persons}" 
                    var="person"
                    widgetVar="editableTableWidget"
                    editable="true"
                    editMode="cell">
            <f:facet name="header">
                A DataTable without filter
            </f:facet>

            <p:column headerText="Name">

                <p:cellEditor>
                    <f:facet name="output">
                        <p:outputLabel value="#{person.name}"></p:outputLabel>
                    </f:facet>

                    <f:facet name="input">
                        <p:inputText value="#{person.name}"></p:inputText>
                    </f:facet>
                </p:cellEditor>
            </p:column>

            <p:column headerText="Date of Birth">
                <p:cellEditor>
                    <f:facet name="output">
                        <p:outputLabel value="#{person.dateOfBirth}"></p:outputLabel>
                    </f:facet>
                    <f:facet name="input">
                        <p:calendar value="#{person.dateOfBirth}" navigator="true">
                        </p:calendar>
                    </f:facet>
                </p:cellEditor>
            </p:column>

            <f:facet name="footer">
                <p:commandButton value="Add a new row"
                    actionListener="#{editableTableBean.addRow()}" update="@form" />
                <p:commandButton value="Clear Filter"
                                oncomplete="PF('editableTableWidget').clearFilters()"
                />
            </f:facet>
        </p:dataTable>
    </h:form>
</h:body>
</html>
```
## 6) Sample bean

**EditableTableBean.java**

``` java
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "editableTableBean")
@ViewScoped
public class EditableTableBean implements Serializable {

    private static final long serialVersionUID = -4217194079931366514L;
    private List<Person> persons = new ArrayList<Person>();


    public void addRow() {
    this.persons.add(new Person("new record", new Date()));
    }

    public List<Person> getPersons() {
    return persons;
    }

    public void setPersons(List<Person> persons) {
    this.persons = persons;
    }

}
```

**Person.java**

``` java
import java.io.Serializable;
import java.util.Date;

public class Person implements Serializable {

    private static final long serialVersionUID = 7247747818315769598L;
    private String name;
    private Date dateOfBirth;

    public Person() {
    super();
    }

    public Person(String name, Date dateOfBirth) {
    super();
    this.name = name;
    this.dateOfBirth = dateOfBirth;
    }

    public String getName() {
    return name;
    }

    public void setName(String name) {
    this.name = name;
    }

    public Date getDateOfBirth() {
    return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    }

}

```

### PR DESCRIPTION
**Pull request by jxmai**

### CODE REVIEW

**Comment by jxmai** [comment]
capture

**Comment by tandraschko** [comment]
don't like the "throw" actually. It should just do nothing if there are no filters currently.

**Comment by jxmai** [comment]
@tandraschko Calling clear filters without filters has severe side effect for **a table with some records at the moment**: In issue #1818 for example, the table cannot be able to add any new record

During my debugging, I noticed the `this.filter()` always got call even we can detect no filters at all at the beginning of the clearFilters function.

I will update the commit using early return instead of throw.

**Comment by jxmai** [comment]
I tested. It works. Please review. 

The issue's expected behavior has been updated as well :)

**Pull request merged**
