### PR TITLE
 Fixes #12966  - Advanced FileUpload: add empty facet 

### LINKED ISSUE #12966: Advanced FileUpload: add empty facet

### PR DESCRIPTION
**Pull request by tandraschko**
Fixes #12966  - Advanced FileUpload: add empty facet

### CODE REVIEW

**Comment by tandraschko** [comment]
i also restructered the whole upload showcase into simple & advanced

**Review by melloware — APPROVED** [review]
This is way better.  i was always confused that there we too many example links!

**Comment by jepsar** [comment]
Maybe also add this to the documentation and what's new?

**Comment by tandraschko** [comment]
+1
Would you Like to add a PR? Im out today

**Comment by jepsar** [comment]
I can have a look tomorrow

**Pull request merged**
