### PR TITLE
Fix #8595: Swap YUICompressor for Extensions Resource Optimizer

### LINKED ISSUE #8595: Tech Debt: YUI Compressor to Resource Optimizer plugin
**Description**
YUI Compressor is dead and its not coming back from the dead.  Last commit on Github 3 years ago: https://github.com/yui/yuicompressor

Maven Plugin also not released in 3 years Archived/ReadOnly: https://github.com/davidB/yuicompressor-maven-plugin/issues/99

Resource Optimizer; https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Maven-plugin-for-web-resource-optimization

- [x] Shrinks the JAR by about 80K
- [x] Allow for transpiling so we can ensure all code is ECMASCRIPT5 and works on IE11
- [x] Simplifies the pom.xml configuration

### PR DESCRIPTION
**Pull request by melloware**
- [x] Shrinks the JAR by about 80K
- [x] Allow for transpiling so we can ensure all code is ECMASCRIPT5 and works on IE11
- [x] Simplifies the pom.xml configuration

image

### CODE REVIEW

**Comment by melloware** [comment]
I need to check a couple more things...

**Comment by melloware** [comment]
OK latest changes this is ready.  Have compared old JAR to new JAR and everything is being compressed the same way.

**Comment by tandraschko** [comment]
great!

**Comment by tandraschko** [comment]
did a small optimization: https://github.com/primefaces/primefaces/commit/4e7662b2796eb16d35dcfcb92f674a198b21b465

**Comment by melloware** [comment]
Oh I love that change so they don't forget.

**Pull request merged**
