### PR TITLE
Fix #11401: calculate first row even if rowCount=0

### LINKED ISSUE #11401: DataTable: DefaultLazyDataModel throws IllegalArgumentException with external filter
### Describe the bug

`DefaultLazyDataModel#load()` can cause an IllegalArgumentException when the user is on a page > 1 and `DefaultLazyDataModel#filter` filters out _all_ elements

### Reproducer

Bean:
```java
@Named
@ViewScoped
public class DataTable044 implements Serializable {
    @Getter @Setter private String programmingLanguageFilter;
    @Getter private LazyDataModel<ProgrammingLanguage> lazyDataModel;

    @Inject private ProgrammingLanguageService service;

    @PostConstruct
    public void init() {
        lazyDataModel = DefaultLazyDataModel.<ProgrammingLanguage>builder()
                .valueSupplier(service::getLangs)
                .filter((ctx, value, filter, locale) -> {
                    if (programmingLanguageFilter == null) {
                        return true;
                    }

                    return ((ProgrammingLanguage) value).getName().contains(programmingLanguageFilter);
                }).build();
    }
}
```

XHTML:
```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html;charset=UTF-8" encoding="UTF-8">
    <h:head>

    </h:head>

    <h:body>

        <h:form id="form">
            <p:messages id="msgs" showDetail="true">
                <p:autoUpdate/>
            </p:messages>

            <p:inputText id="filterInput" value="#{dataTable044.programmingLanguageFilter}">
                <p:ajax process="@this" update="datatable"/>
            </p:inputText>

            <p:dataTable id="datatable" value="#{dataTable044.lazyDataModel}" paginator="true" rows="3" var="lang" >
                <p:column field="id"/>
                <p:column field="name"/>
                <p:column field="firstAppeared"/>
                <p:column field="type"/>
            </p:dataTable>
        </h:form>

    </h:body>
</f:view>

</html>
```

Test:
```java
public class DataTable044Test extends AbstractDataTableTest {
    @Test
    @DisplayName("first index is properly reset when table is filtered externally")
    public void test(Page page) throws InterruptedException {
        // Arrange
        page.dataTable.selectPage(2);

        // Act
        page.filterInput.setValue("asdf");

        // Assert
        assertTrue(page.isAt());
    }

    public static class Page extends AbstractPrimePage {
        @FindBy(id = "form:filterInput")
        InputText filterInput;
        @FindBy(id = "form:datatable")
        DataTable dataTable;

        @Override
        public String getLocation() {
            return "datatable/dataTable044.xhtml";
        }
    }
}
```

### Expected behavior

Works, table is empty

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-RC1

### Theme

_No response_

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by jungm**
Fixes #11401

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Excellent PR and Integration Test!

**Comment by melloware** [comment]
@Rapster care you review this before I merge?

**Comment by tandraschko** [comment]
+1

**Comment by Rapster** [comment]
Yup I think it makes sense

**Review by Rapster — APPROVED** [review]

**Pull request merged**
