### PR TITLE
Label attribute should not be required for the selectCheckboxMenu

### LINKED ISSUE #2996: Label attribute should not be required for the selectCheckboxMenu
Currently `selectCheckboxMenu` has `label` attribute marked as `required=true`. The component is working perfectly fine when this attribute is not set, but IDEs complain about missing required attribute:

image

I believe this attribute should not be required because:
* other components have `label` as `required=false`
* there are [possibilities to set component's label](http://showcase.omnifaces.org/components/outputLabel) via `outputLabel` and thus avoid duplication in code.  

PR #2995 applies suggested change and sets `label`'s `required` to `false` for the `selectCheckboxMenu`.

### PR DESCRIPTION
**Pull request by orange-buffalo**
Fixes #2996.

### CODE REVIEW

**Comment by Rapster** [comment]
Looks fine, but next time create an issue first :wink:

**Comment by orange-buffalo** [comment]
@rapster ok, will keep this in mind for future :)

**Comment by melloware** [comment]
@orange-buffalo do you mind creating and issue and putting all these details in there?  The PF team will want it for tracking and release notes and it will help your PR get merged.

**Comment by orange-buffalo** [comment]
@melloware, sure, I have created issue #2996 and linked it with this PR.

**Comment by melloware** [comment]
Thanks a lot!

**Comment by tandraschko** [comment]
THanks!

**Pull request merged**
