### PR TITLE
Fix #13013: FilterMeta add value to equals()/hashcode()

### LINKED ISSUE #13013: FilterMeta: filterValue is ignored in equals/hashcode
### Describe the bug

Code change for issue #6219 [excluded](https://github.com/primefaces/primefaces/pull/6223/files#diff-23729d17e405f6d0d1b1474e76789f78f44ea7fd0a7fea532d97a900adee5881) filterValue from FilterMeta.equals and FilterMeta.hashcode. filterValue is an important part of FilterMeta object state and FilterMeta class is a part of API and can be used externally. Client code will be unpleasantly surprised to find, that FilterMeta with different filterValue are equals and have the same hashcode.

Example of such surprise is this [demo project](https://github.com/bvfalcon/PrimeFaces-FilterMeta-test). 

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

8.0.4 and later

### Theme

_No response_

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #13013: FilterMeta add value to equals()/hashcode()

### CODE REVIEW

**Comment by tandraschko** [comment]
rapster can decide, i'm -0.5 here 
for me its the same case like entities

**Comment by melloware** [comment]
yep @Rapster thoughts please

**Comment by melloware** [comment]
pin @Rapster

**Comment by Rapster** [comment]
> rapster can decide, i'm -0.5 here for me its the same case like entities, where want to identify the filterMeta by its "keys/ids/metadata", not its mutual state

+1

It's fine as it is, no need to change

**Pull request closed without merging**
