### PR TITLE
Fix #5817: JQMIGRATE: jQuery.trim is deprecated; use String.prototype.trim

### LINKED ISSUE #5817: JS: Remediate all JQMIGRATE deprecations
I think the JQMigrate plugin needs to be run against the showcase and all deprecation warnings should be addressed.

https://github.com/jquery/jquery-migrate

A lot of these deprecation are being removed in Jquery 4.0 so fixing them now will alleviate pain later.

- [x] jQuery.fn.bind()/unbind() are deprecated
- [x] jQuery.isArray is deprecated
- [x] jQuery.isFunction is deprecated
- [x] jQuery.trim is deprecated; use String.prototype.trim 
- [x] Use of number-typed values is deprecated in CSS
- [x] jQuery.fn.click() event shorthand is deprecated, use `on` and `trigger` instead.  Also includes blur, focus, focusin, focusout, resize, scroll, dblclick, mousedown, mouseup, mousemove, mouseover, mouseout, mouseenter, mouseleave, change, select, submit, keydown, keypress, keyup, and contextmenu

### PR DESCRIPTION
**Pull request by melloware**
Too much to fix in 1 PR so will be creating separate PR's for each thing fixed.

### CODE REVIEW

**Comment by tandraschko** [comment]
only difference could be that $.trim also worked for null values`?

**Comment by melloware** [comment]
Yep I was afraid of that.  What do you think we should do?  Create a core.utils `trim`???

**Comment by tandraschko** [comment]
yep, probably

**Comment by melloware** [comment]
I looked at what jQuery trim was doing and make a `PrimeFaces.trim` to match it.

**Pull request merged**
