### PR TITLE
Added attribute "showWeekNumbers" to schedule.

### PR DESCRIPTION
**Pull request by tryptichon**
Activate the attribute weekNumbers in fullCalendar.io to display the current week of the year in the schedule.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Why do we also need timeFormat here?

**Comment by tryptichon** [comment]
We don't. The patch removes the line with timeFormat and adds the same line again without the ';' at the end because the attr() for "weekNumbers" follows.

**Comment by cagataycivici** [comment]
Missed that sorry, I'll review, thank you.

**Comment by cagataycivici** [comment]
Could you please create an issue for this as well?

**Pull request merged**
