### PR TITLE
Fix #3146: Remove unused param from ComponentUtils.getUnwrappedRenderer

### LINKED ISSUE #3146: Remove unused method parameter "rendererClass" in ComponentUtils.getUnwrappedRenderer
Hint SONAR lint

2 possible fixes:
- Either remove this parameter
- Or use `rendererClass` to cast the renderer which has been found

Whatever the solution choosed, the result will be the same in case rendererClass does not match the renderer found: a ClassCastException

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by melloware** [comment]
I have no idea why the ValueExpressionAnalyzerTest tests are failing they are passing locally for me.

**Comment by tandraschko** [comment]
my bad :O

does this still work on java7?

**Comment by melloware** [comment]
I build using JDK8 with the Maven Compiler set to 7.  So it definitely builds like that :)

**Comment by melloware** [comment]
I don't even have a true 7 to build with. :)

**Comment by tandraschko** [comment]
Hmm, maybe lets apply it after the release :D

**Comment by melloware** [comment]
Good call!

**Comment by melloware** [comment]
@tandraschko I have realized the failing ValueExpressionAnalyzerTest unit tests started with your check in yesterday of your ClassLoader refactoring.   So far I have fixed one NullPointerException by returning a mock object in ExternalContextMock..

```java
    @Override
    public Object getContext() {
        return Mockito.mock(ServletContext.class);
    }
```

but now 3 tests are still failing because it can't class load caused by

> Caused by: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
> 	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:101)
> 	at javax.el.FactoryFinder.find(FactoryFinder.java:197)
> 	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:197)
> 	at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:168)
> 	at javax.el.ELUtil.<clinit>(ELUtil.java:93)
> 	... 37 more
> Caused by: java.lang.ClassNotFoundException: com.sun.el.ExpressionFactoryImpl
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at javax.el.FactoryFinder.newInstance(FactoryFinder.java:87)
> 	... 41 more
> 
>

**Comment by tandraschko** [comment]
Can you update? It could be causes by the portet dependency, i removed this yesterday again.

**Comment by melloware** [comment]
Confirmed its fixed!

**Comment by melloware** [comment]
And the build is now passing. Thanks!

**Comment by Rapster** [comment]
Since this parameter was never used anyway, I'm okay to merge that PR for 6.3

**Comment by tandraschko** [comment]
I can't remember why i introduced the parameter. I normally don't introduce unused parameters.
Could it be that Java1.6 or 1.7 couldn't resolve \<T\> otherwise?
Therefore, if noone tests it on a JDK1.7, i would like to apply it after the release.

**Pull request merged**
