### PR TITLE
Fix #10588: Hindi translation

### LINKED ISSUE #10588: Locale: Hindi Translation
See title

### PR DESCRIPTION
**Pull request by melloware**
Fix #10588: Hindi translation

### CODE REVIEW

**Comment by tusharsrivastava** [comment]
Hi @melloware let me have a look. I will translate them as well. Thanks

**Comment by melloware** [comment]
@tusharsrivastava reminder....

**Comment by shivam-sharma7** [comment]
@melloware 
It should be fine.

"accept": "हाँ", -> "accept": "स्वीकार करें",
"reject": "नहीं", -> "reject": "अस्वीकार करें",

**Comment by melloware** [comment]
@shivam-sharma7 any chance you want to help translate the bottom part of this file?

```js
 PrimeFaces.locales['hi'] = $.extend(true, {}, PrimeFaces.locales['hi'], {
     weekNumberTitle: 'W',
     isRTL: false,
     yearSuffix: '',
     timeOnlyTitle: 'Only Time',
     timeText: 'Time',
     hourText: 'Hour',
     minuteText: 'Minute',
     secondText: 'Second',
     millisecondText: 'Millisecond',
     year: 'Year',
     month: 'Month',
     week: 'Week',
     day: 'Day',
     list: 'Agenda',
     allDayText: 'All Day',
     moreLinkText: 'More...',
     noEventsText: 'No Events',
     aria: {
         'datatable.sort.ASC': 'activate to sort column ascending',
         'datatable.sort.DESC': 'activate to sort column descending',
         'datatable.sort.NONE': 'activate to remove sorting on column',
         'colorpicker.OPEN': 'Open color picker',
         'colorpicker.CLOSE': 'Close color picker',
         'colorpicker.CLEAR': 'Clear the selected color',
         'colorpicker.MARKER': 'Saturation: {s}. Brightness: {v}.',
         'colorpicker.HUESLIDER': 'Hue slider',
         'colorpicker.ALPHASLIDER': 'Opacity slider',
         'colorpicker.INPUT': 'Color value field',
         'colorpicker.FORMAT': 'Color format',
         'colorpicker.SWATCH': 'Color swatch',
         'colorpicker.INSTRUCTION': 'Saturation and brightness selector. Use up, down, left and right arrow keys to select.',
         'spinner.INCREASE': 'Increase Value',
         'spinner.DECREASE': 'Decrease Value',
         'switch.ON': 'On',
         'switch.OFF': 'Off',
         'messages.ERROR': 'Error',
         'messages.FATAL': 'Fatal',
         'messages.INFO': 'Information',
         'messages.WARN': 'Warning'
     }
 });
```

**Comment by shivam-sharma7** [comment]
@melloware anything else for me!

```
 PrimeFaces.locales['hi'] = $.extend(true, {}, PrimeFaces.locales['hi'], {
     weekNumberTitle: 'सप्ताह संख्या शीर्षक',
     isRTL: गलत,
     yearSuffix: 'वर्षप्रत्यय',
     timeOnlyTitle: 'केवल समयशीर्षक',
     timeText: 'समयपाठ',
     hourText: 'घंटापाठ',
     minuteText: 'मिनटपाठ',
     secondText: 'सेकंड पाठ',
     millisecondText: 'मिलीसेकंड',
     year: 'वर्ष',
     month: 'महीना',
     week: 'सप्ताह',
     day: 'दिन',
     list: 'सूची',
     allDayText: 'पूरे दिन का पाठ',
     moreLinkText: 'अधिक लिंक पाठ',
     noEventsText: 'कोई घटना पाठ नहीं',
     aria: {
         'datatable.sort.ASC': 'activate to sort column ascending',
         'datatable.sort.DESC': 'activate to sort column descending',
         'datatable.sort.NONE': 'activate to remove sorting on column',
         'colorpicker.OPEN': 'Open color picker',
         'colorpicker.CLOSE': 'Close color picker',
         'colorpicker.CLEAR': 'Clear the selected color',
         'colorpicker.MARKER': 'Saturation: {s}. Brightness: {v}.',
         'colorpicker.HUESLIDER': 'Hue slider',
         'colorpicker.ALPHASLIDER': 'Opacity slider',
         'colorpicker.INPUT': 'Color value field',
         'colorpicker.FORMAT': 'Color format',
         'colorpicker.SWATCH': 'Color swatch',
         'colorpicker.INSTRUCTION': 'Saturation and brightness selector. Use up, down, left and right arrow keys to select.',
         'spinner.INCREASE': 'Increase Value',
         'spinner.DECREASE': 'Decrease Value',
         'switch.ON': 'On',
         'switch.OFF': 'Off',
         'messages.ERROR': 'Error',
         'messages.FATAL': 'Fatal',
         'messages.INFO': 'Information',
         'messages.WARN': 'Warning'
     }
 });

**Comment by melloware** [comment]
@shivam-sharma7 thanks! but what about these...

```js
 aria: {
         'datatable.sort.ASC': 'activate to sort column ascending',
         'datatable.sort.DESC': 'activate to sort column descending',
         'datatable.sort.NONE': 'activate to remove sorting on column',
         'colorpicker.OPEN': 'Open color picker',
         'colorpicker.CLOSE': 'Close color picker',
         'colorpicker.CLEAR': 'Clear the selected color',
         'colorpicker.MARKER': 'Saturation: {s}. Brightness: {v}.',
         'colorpicker.HUESLIDER': 'Hue slider',
         'colorpicker.ALPHASLIDER': 'Opacity slider',
         'colorpicker.INPUT': 'Color value field',
         'colorpicker.FORMAT': 'Color format',
         'colorpicker.SWATCH': 'Color swatch',
         'colorpicker.INSTRUCTION': 'Saturation and brightness selector. Use up, down, left and right arrow keys to select.',
         'spinner.INCREASE': 'Increase Value',
         'spinner.DECREASE': 'Decrease Value',
         'switch.ON': 'On',
         'switch.OFF': 'Off',
         'messages.ERROR': 'Error',
         'messages.FATAL': 'Fatal',
         'messages.INFO': 'Information',
         'messages.WARN': 'Warning'
     }
```

**Comment by shivam-sharma7** [comment]
@melloware updated, see https://github.com/primefaces/primefaces/pull/10589#issuecomment-1717608813

**Comment by tusharsrivastava** [comment]
Hi @melloware apologies, I was away for personal vacation. Thanks @shivam-sharma7 for taking care of this. I am adding the following as well. See if it helps as well. Although most of the translation seems pretty accurate to me
```js
PrimeFaces.locales['hi'] = $.extend(true, {}, PrimeFaces.locales['hi'], {
     weekNumberTitle: 'स',
     isRTL: false,
     yearSuffix: '',
     timeOnlyTitle: 'केवल समय',
     timeText: 'समय',
     hourText: 'घंटा',
     minuteText: 'मिनट',
     secondText: 'सेकंड',
     millisecondText: 'मिलीसेकंड',
     year: 'वर्ष',
     month: 'महीना',
     week: 'सप्ताह',
     day: 'दिन',
     list: 'सूची',
     allDayText: 'पूरा दिन',
     moreLinkText: 'अधिक...',
     noEventsText: 'कोई घटनाएं नहीं',
     aria: {
         'datatable.sort.ASC': 'कॉलम को आरोही क्रम में करने के लिए सक्रिय करें',
         'datatable.sort.DESC': 'कॉलम को अवरोही क्रम में करने के लिए सक्रिय करें',
         'datatable.sort.NONE': 'कॉलम पर क्रमबद्धता हटाने के लिए सक्रिय करें',
         'colorpicker.OPEN': 'रंग चयनकर्ता खोलें',
         'colorpicker.CLOSE': 'रंग चयनकर्ता बंद करें',
         'colorpicker.CLEAR': 'चयनित रंग को हटाएं',
         'colorpicker.MARKER': 'संतृप्ति: {s}. चमक: {v}.',
         'colorpicker.HUESLIDER': 'रंग स्लाइडर',
         'colorpicker.ALPHASLIDER': 'अपारदर्शिता स्लाइडर',
         'colorpicker.INPUT': 'रंग मान क्षेत्र',
         'colorpicker.FORMAT': 'रंग प्रारूप',
         'colorpicker.SWATCH': 'रंग स्वैच',
         'colorpicker.INSTRUCTION': 'संतृप्ति और चमक चयनकर्ता। चयन करने के लिए ऊपर, नीचे, बाएं और दाएं तीर कुंजी का उपयोग करें।',
         'spinner.INCREASE': 'मान बढ़ाएं',
         'spinner.DECREASE': 'मान घटाएं',
         'switch.ON': 'चालू',
         'switch.OFF': 'बंद',
         'messages.ERROR': 'त्रुटि',
         'messages.FATAL': 'घातक',
         'messages.INFO': 'सूचना',
         'messages.WARN': 'चेतावनी'
     }
```

**Comment by melloware** [comment]
Thank you!

**Pull request merged**
