### PR TITLE
#7999 integrationtest

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by melloware** [comment]
Nice to see these results prove Mojarra fails and MyFaces works!

**Comment by tandraschko** [comment]
I dont think we should merge this yet as it just contains a workaround?

**Comment by melloware** [comment]
Oh I didn't consider `filtervalues` a workaround I have been using Mojarra for years and we ALWAYS have put `filterValues` on our datatables I thought it was required.  So this test is how all of my production code already is.

**Comment by christophs78** [comment]
Can we log an error and/or add for jsf-dev-stage a faces-message when filter is used without defining filterValues?

**Comment by melloware** [comment]
I personally like that idea.  @tandraschko Thoughts?

**Comment by tandraschko** [comment]
I dont think that its an mandatory attr, so -1

**Pull request merged**
