### PR TITLE
Fix #1745 tab navigation between editable cells in dataTable with non editable columns

### LINKED ISSUE #1745: Tab navigation between editable cells in dataTable issue
## 1) Environment
- PrimeFaces version: 5.3.16 (elite)
- Does it work on the newest PrimeFaces version? No
- Application server + version: Tomcat 8.0.23
- Affected browsers: All
## 2) Expected behavior

Tab navigation skips non editable cells and jump to next editable cell
## 3) Actual behavior

In an editable dataTable, if some columns, last or middle are NOT editable, tab navigation stops working
## 4) Steps to reproduce

In showcase ( http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml ), last table (Cell Editing with Click and RightClick), all cells are editable. Click on first cell and press 'Tab' (on keyboard) to jump to next cell. Everything works good.

Now, make last column non editable (read only). Instead of jumping to next editable cell, tab go to read only cell and breaks tab switching.
## 5) Sample XHTML

Just make last column non editable
## 6) Sample bean

Not needed

### PR DESCRIPTION
**Pull request by wal-jan**
Just a little JS tweak to skip non editable columns

### CODE REVIEW

**Comment by jxmai** [comment]
Conventionally PF requires an issue as an attachment of a pull request for documentation purposes (Labels, milestone etc although the same documentation can be done on a pull request ), so please create one if you don't have.

Otherwise, you will likely to receive a response as 

> please create an issue first...

---

From my point of view, the purpose of this pull request is valid since we cannot tab across non-editable cell in the same row currently. Usually user might need checkbox element in between that does not need cell-editor to modify the content.

**Comment by wal-jan** [comment]
Sorry if I did not comply with the PF conventions.
The Issue is [https://github.com/primefaces/primefaces/issues/1745](#1745).
Hopefully this comment is sufficient for the documentation.

**Comment by tandraschko** [comment]
Could someone test it? Also please check if tabCell() is only called when the DOM tree really contains "ui-editable-column"s

**Comment by jxmai** [comment]
Test code:

```java
package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 4124891683211838799L;

    private String testString;

    private List<Person> people;

    @PostConstruct
    public void init() {
	testString = "Welcome to PrimeFaces!!!";
	this.people = new ArrayList<Person>();
	Person person1 = new Person(1, "Alice", true, "This is Alice ...");
	Person person2 = new Person(2, "Bob", true, "This is Bob  ...");
	people.add(person1);
	people.add(person2);
    }

    public String getTestString() {
	return testString;
    }

    public void setTestString(String testString) {
	this.testString = testString;
    }

    public List<Person> getPeople() {
	return people;
    }

    public void setPeople(List<Person> people) {
	this.people = people;
    }
}

```

---

```java
package org.primefaces.test;

import java.io.Serializable;

public class Person implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 9204747603994128392L;

    private Integer id;

    private String name;

    private Boolean isActive;

    private String description;

    public Person(Integer id, String name, Boolean isActive, String description) {
	super();
	this.id = id;
	this.name = name;
	this.isActive = isActive;
	this.description = description;
    }

    public Integer getId() {
	return id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    public String getName() {
	return name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public Boolean getIsActive() {
	return isActive;
    }

    public void setIsActive(Boolean isActive) {
	this.isActive = isActive;
    }

    public String getDescription() {
	return description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

}

```

---

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        
        <h1>#{testView.testString}</h1>
        
        <h:form>
	        <p:dataTable value="#{testView.people}" 
	        			var="person"
	        			editable="true"
	        			editMode="cell"
	        			>
	        	<p:column headerText="Id">
	        		<p:cellEditor>
	        			<f:facet name="input">
		        			<p:inputText value="#{person.id}"></p:inputText>
	        			</f:facet>
	        			<f:facet name="output">
		        			<h:outputText value="#{person.id}" />
	        			</f:facet>
	        		</p:cellEditor>
	        	</p:column>
	        	
	        	<p:column headerText="Active">
	        		<p:selectBooleanCheckbox value="#{person.isActive}">
	        		
	        		</p:selectBooleanCheckbox>
	        	</p:column>
	        	
	        	<p:column headerText="Name">
	        		<p:cellEditor>
	        			<f:facet name="input">
		        			<p:inputText value="#{person.name}"></p:inputText>
	        			</f:facet>
	        			<f:facet name="output">
		        			<h:outputText value="#{person.name}" />
	        			</f:facet>
	        		</p:cellEditor>
	        	</p:column>
	        	
	        	<p:column headerText="Description">
	        		<p:cellEditor>
	        			<f:facet name="input">
		        			<p:inputText value="#{person.description}"></p:inputText>
	        			</f:facet>
	        			<f:facet name="output">
		        			<h:outputText value="#{person.description}" />
	        			</f:facet>
	        		</p:cellEditor>
	        	</p:column>
	        	
	        	<!-- <p:column headerText="Id">
			        <h:outputText value="#{person.id}" />
			    </p:column> -->
	        </p:dataTable>
        </h:form>
       
    </h:body>
</html>
```

image


Originally the tab will stuck at the checkbox and cannot get pass to the end, but with the patch we can get to the end of the editable cell. 👍 

> Also please check if tabCell() is only called when the DOM tree really contains "ui-editable-column"s

Yes, as you can see the debugger breakpoint does not trigger when I tab

image

**Review by jxmai — APPROVED** [review]
👍

**Comment by jxmai** [comment]
Treetable should work the same as datatable, so I assume it should also work OK.

**Pull request merged**
