### PR TITLE
Fix #7615: DatePicker NPE for getType

### LINKED ISSUE #7615: DatePicker: crashes with NPE when converting from p:calendar
**Describe the defect**
When migrating from PF8.0 to PF10.0.4 changing p:calendar to p:datePicker causes Null Pointer Exceptions if the referenced object is null. (which is not terribly surprising, but this code works on p:calendar, and I cannot see an easy way around this.)

**Environment:**
 - PF Version: 10.0.4
 - JSF + version: JSF 2.3, WildFly 24.0.0_Final
 - Affected browsers: ALL

**To Reproduce**
1. Create a Controller with an object (such as a User object that is NULL initially, as would be the case when editing a user from a table at the point at which the table is rendered, the user object will be null as no user is selected)
2. Create a form with the user details, such as userId, email address, date of birth in a dialog that will be opened on selecting the user
3. Change p:calendar to p:datePicker
4. NPE

**Expected behavior**
No NPE

**Example XHTML**
```html
<h:form id="frmTest">
  <p:calendar id="dateOfBirth" value="#{userController.selectedUser.dateOfBirth}"/> 
</h:form>
```
vs
```html
<h:form id="frmTest">
  <p:datePicker id="dateOfBirth" value="#{userController.selectedUser.dateOfBirth}"/> 
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class UserController implements Serializable {
    private Users selectedUser;

   //at this point selectedUser is null (as would be the case with a table where nothing is selected)
    public Users getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(Users selectedUser) {
        this.selectedUser = selectedUser;
    }
}
```
The above code works PERFECTLY with p:calendar, but p:datePicker crashes:

SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-65) Error Rendering View[/secured/otherusers.xhtml]: javax.el.PropertyNotFoundException: /secured/edituserdialog.xhtml @82,86 value="#{userController.selectedUser.dateOfBirth}": Target Unreachable, 'null' returned null
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:64)
	at deployment.ProjectName-1..0.war//org.primefaces.component.api.UICalendar.getTypeFromValueByValueExpression(UICalendar.java:356)
	at deployment.ProjectName-1.0.war//org.primefaces.component.datepicker.DatePickerRenderer.encodeEnd(DatePickerRenderer.java:59)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.api@3.0.0.SP04//javax.faces.render.Renderer.encodeChildren(Renderer.java:152)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at deployment.ProjectName-1.0.war//org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:72)
	at deployment.ProjectName-1.0.war//org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:59)
	at deployment.ProjectName-1.0.war//org.primefaces.component.dialog.DialogRenderer.encodeContent(DialogRenderer.java:195)
	at deployment.ProjectName-1.0.war//org.primefaces.component.dialog.DialogRenderer.encodeMarkup(DialogRenderer.java:118)
	at deployment.ProjectName-1.0.war//org.primefaces.component.dialog.DialogRenderer.encodeEnd(DialogRenderer.java:47)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:286)
	at com.sun.jsf-impl@2.3.14.SP04//com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko getExpectedType fixes the problem but now I am running all the Integration Tests to make sure nothing is broken

### CODE REVIEW

**Comment by melloware** [comment]
Awesome the Integration Tests prove that getExpectedType() will not work here.
```
 Failures: 
Error:    DatePicker004Test.testClearButtonMilliseconds:213 expected: <2021-06-25T23:22:21.019> but was: <2021-06-25T00:00>
Error:    DatePicker004Test.testClearButton:131 expected: <2020-08-20T22:20:19> but was: <2020-08-20T00:00>
Error:    DatePicker004Test.testDateAndTimeWithHours:105 expected: <2020-10-31T13:13> but was: <2020-10-31T00:00>
Error:    DatePicker004Test.testDateAndTimeWithMilliseconds:186 expected: <2021-06-25T23:22:21.019> but was: <2021-06-25T00:00>
Error:    DatePicker004Test.testDateAndTimeWithSeconds:51 expected: <2020-08-20T22:20:19> but was: <2020-08-20T00:00>
Error:    DatePicker004Test.testSetDateWidgetApi:78 expected: <2020-08-20T22:20:19> but was: <2020-08-20T00:00>
Error:    DatePicker004Test.testTodayButtonMilliseconds:241 expected: <2021-06-25T23:22:21.019> but was: <2021-06-25T00:00>
Error:    DatePicker004Test.testTodayButton:159 expected: <2020-08-20T22:20:19> but was: <2020-08-20T00:00>
```

**Comment by melloware** [comment]
Now I am trying getType but wrapping it a try catch and returning NULL if there is an error.

**Comment by tandraschko** [comment]
can you try getExpectedType first and fallbak to getType like in DynamicContentSrcBuilder?

**Comment by melloware** [comment]
No it looks like getExpectedType is returning a LocalDate and not LocalDateTime which is why the Integration Tests are faling..

```
DatePicker004Test.testClearButtonMilliseconds:213 expected: <2021-06-25T23:22:21.019> but was: <2021-06-25T00:00>
```

So its giving us the incorrect class.

**Comment by tandraschko** [comment]
yeah
the only solution would be to allow a type attribute like type="java...LocalDateTime"

**Comment by tandraschko** [comment]
cc @christophs78

**Comment by christophs78** [comment]
IMO this is a valid fix.
UICalendar#getTypeFromValueByValueExpression is only called from this two point´s and they handle null-return-values correct.
image

The other (maybe philosphical) question is what sense it makes to have an input where the value the user enters can never be stored somewhere. Not the kind of UI i´ll personally like to work with.

**Comment by tandraschko** [comment]
i will think about it
the fix is quite dirty in general

**Comment by tandraschko** [comment]
i mean
what does the PR fix? it fixes the NPE but it still fails to collect the required type as the EL cant be resolved
in this case the only fix would be to add a type attr?

**Comment by melloware** [comment]
This fixes this issue `value="#{userController.selectedUser.dateOfBirth}"` where `selectedUser` is null it fills out the DatePicker with an empty value to make the behavior match Calendar.

**Comment by tandraschko** [comment]
but couldnt it generate a wrong setTimeOnly then?

**Comment by melloware** [comment]
Anything where it needs to know the "true" type of the underlying DateTime object yes could be skewed if the user doesn't manually set `timeOnly="true"` on the DatePicker itself.

**Pull request merged**
