### PR TITLE
#4939: Schedule: remove superfluous _container div

### PR DESCRIPTION
**Pull request by maasvdberg**
Can not come up with a justification for the additional **_container** div...

### CODE REVIEW

**Review by melloware — APPROVED** [review]
I like this change but want to make sure @tandraschko reviews it.

**Comment by tandraschko** [comment]
No idea, sorry. Never used or implemented anything in this component.
Thats up to mert or @OBreidenbach.

**Comment by tandraschko** [comment]
Also not sure if this still works:
this.jq.find('> .fc-toolbar button:not(' + excludedClasses + ')'),

as it searches for direct children?

**Comment by maasvdberg** [comment]
Works... **viewChange** events are still correctly fired when hitting the Month/Year/Day buttons ... and 
**not** when hitting the Prev/Next/Today buttons

**Comment by melloware** [comment]
OK I tested this and everything appears to be working.  I am going to merge it.

**Pull request merged**
