### PR TITLE
RemoteCommand: consider AjaxSource.getForm()

### LINKED ISSUE #4317: RemoteCommand: The form attribute is ignored
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: WildFly 14
- Affected browsers: Any

## 2) Expected behavior

Using `<p:remoteCommand form=":rootForm" />` outside a `h:form` should render fine.

## 3) Actual behavior

Using `<p:remoteCommand form=":rootForm" />` outside a `h:form` causes a `javax.faces.FacesException: RemoteCommand 'doStuff'must be inside a form.`

## 4) Steps to reproduce

* create a plain view file `remote-command-test.xhtml`
* insert `<p:remoteCommand form=":rootForm" />` (*not* nested inside a `h:form`, see below)
* try to render the view.

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<h:body>

  <h:form id="rootForm" />

  <p:remoteCommand form=":rootForm" />

</h:body>
</html>
```

Like #2358 this is caused by the [renderer](https://github.com/primefaces/primefaces/blob/ae1e952d897e310de6c5b6acb09aa3851b22f870/src/main/java/org/primefaces/component/remotecommand/RemoteCommandRenderer.java#L62) which does not consider the form attribute and instead just looks for the enclosing form. Right now only the [AjaxBehaviorRenderer](https://github.com/primefaces/primefaces/blob/ae1e952d897e310de6c5b6acb09aa3851b22f870/src/main/java/org/primefaces/behavior/ajax/AjaxBehaviorRenderer.java#L97) considers the form attribute at all.

### PR DESCRIPTION
**Pull request by schulzp**
fixes #4317

### CODE REVIEW

**Review by melloware — COMMENTED** [review]
Nice work.  You might be able to
Simplify it some more by only checking traverse utils if the formId is null. Right now you are always executing traverse utils and search facade every time.

**Comment by tandraschko** [comment]
Thanks for the PR.
The PR in generell is very good but could we skip the "closest form lookup", if a form was specified on the component?
I think thats the same for other components, it's a very small but good perf improvement.

**Comment by tandraschko** [comment]
I will apply it now, i will come back with my idea.

**Comment by Rapster** [comment]
The comment of your commit sounds actually much better

**Comment by melloware** [comment]
@tandraschko I had the same thought wouldn't this be a better fix?  Or maybe we could wrap it it up in ComponentUtils so we can reuse it.

```java
 String formId = SearchExpressionFacade.resolveClientId(context, component, source.getForm());
        if (formId == null) {
            UIComponent form = ComponentTraversalUtils.closestForm(context, command);
            if (form == null) {
                throw new FacesException("RemoteCommand '" + name + "' must be inside a form or reference a form via its form attribute.");
            }
            formId = form.getClientId(context);
        }
...
        String request = builder.init()
                .source(clientId)
                .form(formId)
```

**Comment by tandraschko** [comment]
Please review: https://github.com/primefaces/primefaces/commit/c7f8c9539ff07ce291a7f6e9f24fe4ad33431b79

**Comment by melloware** [comment]
That is a fantastic fix.  Huge improvement.

**Comment by Rapster** [comment]
Regarding this ticket, why not calling `CoreRenderer#buildAjaxRequest` looks like it does the same no?

**Comment by melloware** [comment]
@tandraschko I believe your refactoring now fixes this issue as well:  https://github.com/primefaces/primefaces/issues/2358

**Comment by tandraschko** [comment]
@Rapster because it uses preventDefault.
It probably needs a refactor after the release. the CoreRendere#buildAjaxRequest should not return a string, it should return the builder.
So the CoreRenderer could do the default mapping from AjaxSource<>AjaxRequestBuilder. And each renderer could "enhance" the builder with stuff like preventDefault e.g.

**Comment by Rapster** [comment]
Ah ok, fair enough. We should create a ticket for the refactoring part then :wink:

**Comment by schulzp** [comment]
Cool, thanks a lot @tandraschko, @melloware, and @Rapster!

**Pull request merged**
