### PR TITLE
Fix #10067 - DataTable: set default filter either on UIColumn#filterValue or custom facet value

### LINKED ISSUE #10067: DataTable: set default filter either on UIColumn#filterValue or custom facet value
### Description

Based on this: https://github.com/primefaces/primefaces/issues/9349#issuecomment-1520843859

> In regards to when or when not to utilize the filterValue attribute...I was under the impression that the attribute was to be used if a filter was not explicitly defined in a filter facet via <f:facet name="filter">. Or in other words, the filterValue attribute was to be ignored if I did define a filter facet.

As there are two potential ways to define default value, users are confused which one to used, but more recently users tend to use custom facet filter value due to a "regression"

My solution is here https://github.com/primefaces/primefaces/issues/9349#issuecomment-1524099844

>So, maybe the best way to go about it is to support both by simply doing a coalesce 😄 I can propose a fix, but maybe in another issue, your issue is pretty clear as to what is not working /confusing

### Describe the solution you would like

support both `UIColumn#filterValue` and custom facet value, `UIColumn#filterValue` being priority number 1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by melloware** [comment]
Looks like IT's are failing.

**Comment by Rapster** [comment]
Yeah I noticed, funny thing is, it only works in 4.0

**Comment by tandraschko** [comment]
yeah, i only copied some tests to test some basic functionality (startup/shading stuff)

**Comment by Rapster** [comment]
I might need your insights on this, i'm not sure what's wrong... @melloware @christophs78  Another thing, how do I debug PF components, I can debug the IT itself but that's it, probably because they're running on another port?

**Comment by melloware** [comment]
Yep that is what I usually do run it as a webapp and debug.

**Comment by Rapster** [comment]
Ok so I think this ticket fixes a few things:

- #10067 
- similar to #8992 but the default value is a collection of complex objects (e.g Representative)
- #9349 like I mentionned in the original ticket (and restore fix for #9040)... trying to workaround the provided API will only lead to potential bugs

**Comment by melloware** [comment]
nice!

**Review by melloware — APPROVED** [review]

**Comment by christophs78** [comment]
Glad to see you got it working.
For the case of some open questions regarding debugging Integrationtests we may do a short videomeeting at some point in the future. (~15 min) There are no limitations. You can use the jetty-plugin to start integration-test-web-application like the showcase. Or you can run the integration-tests, set breakpoint´s into to integration-test-java-code, set breakpoint into the javascript code (do not use headless for this) and/or set breakpoint´s into primefaces-java-code, ...

**Pull request merged**
