### PR TITLE
Fix #6447: InputNumber browser autofill

### LINKED ISSUE #6447: InputNumber: Browser AutoFill not working
**Describe the defect**
If you input a value like "55,55" into an element and submit the form, the browser displays a dropdown select the next time you visit the page and double click the same element.
When you select the previously entered value "55,55" The value is pasted, but as soon as the focus is lost on the input element, autoNumeric deletes the value.

See AutoNumeric defect: https://github.com/autoNumeric/autoNumeric/issues/536

**Expected behavior**
If you input a value like "55,55" into an element and submit the form, the browser displays a dropdown select the next time you visit the page and double click the same element.
When you select the previously entered value "55,55" it is pasted into the element.

**NOTE:** One of our production clients reported this defect.

### PR DESCRIPTION
**Pull request by melloware**
We have tested this fix in our production application and verified it resolves the issue based on the AutoNumeric fix described in the issue ticket.

### CODE REVIEW

**Comment by melloware** [comment]
Still investigating.

**Comment by melloware** [comment]
Discovered during testing that the old `input` event we were using for MouseWheel and Paste is no longer needed as its built into the newer AutoNumeric already.   So we could remove that for a single `blur` event to address  the browser autofill issue.

**Comment by tandraschko** [comment]
+1 if well tested

**Comment by melloware** [comment]
Our QA team discovered this in PRD and have thoroughly tested this fix in a large application.  Thanks for reviewing!

**Pull request merged**
