### PR TITLE
DataExporter: Support custom Export class #4397

### PR DESCRIPTION
**Pull request by ravihariharan**
The proposed PR solution could also help to support other file format if required.

PS : i have raised it for discussion and could do addition test if the enhancement is accepted.

### CODE REVIEW

**Comment by melloware** [comment]
I like it.

**Comment by tandraschko** [comment]
why not pass a bean-instance to it instead of a className?

**Comment by ravihariharan** [comment]
> why not pass a bean-instance to it instead of a className?

I used String for fully qualified name of the custom Exporter  to be used in place of DataExporter.  

@tandraschko  can you elaborate on you suggestion? sorry did not clearly understand how it can be  done with bean-instance.

**Comment by tandraschko** [comment]
customExporter="#{myCustomExporterNamedBean}"

**Comment by ravihariharan** [comment]
@tandraschko can you review the new fix?

**Comment by tandraschko** [comment]
please also remove tryNewInstanceOfClass

**Comment by ravihariharan** [comment]
@tandraschko  i have removed tryNewInstanceOfClass

**Comment by tandraschko** [comment]
Please also rename customExporterClass, after that i can merge it

**Comment by ravihariharan** [comment]
@tandraschko  in addition to the rename , i also added customExporterClass to restoreState and saveState.

**Comment by tandraschko** [comment]
Why customExporterClass? It's just "customExporter". It's the instance, not a class.

**Comment by ravihariharan** [comment]
> Why customExporterClass? It's just "customExporter". It's the instance, not a class.

Sorry.. my bad.. need to get some extra strong coffee :P

**Pull request merged**
