### PR TITLE
Added README

### PR DESCRIPTION
**Pull request by hatemalimam**
An initial commit for README.md file

### CODE REVIEW

**Comment by cagataycivici** [comment]
@tandraschko @mertsincan What do you guys think? Doesn't it duplicate information at pf.org so we have to maintain two separate introductions. Should we use something like this or just add a link to primefaces.org?

**Comment by tandraschko** [comment]
+0 as the it's really duplicate content
It would be better to bring some new content like "how to create good issues":
- tested on newest versions
- provide a xhtml and bean snippet e.g. via gist
- ...
- ...

**Comment by hatemalimam** [comment]
Well I don't agree 100% that this is +0, that would be a clear underestimating of github's indexing and search results. Considering the fact not every user knows PrimeFaces, and github is a good source to let the people know. The current content might not provide the utimate desired goal. But still having this file is a plus from my point of view. And a lot of projects would have duplicate info like https://github.com/twbs/bootstrap/blob/master/README.md . Also the contribution part is still blury. An idea would be that if someone submits a pull-request, they should create a new branch and ask to merge with a specific one rather than or to the master. That could be a helpful part of the README. I hope I'm helping here.

**Comment by cagataycivici** [comment]
Applied and edited with some changes, thank you.

**Pull request merged**
