### PR TITLE
Fix #5312: Steps allow active step to be executed

### LINKED ISSUE #5312: Steps: Allow clickable active item
Well, I have a problem with the Steps component. When I want to execute actions, updates or url in the active index these are not executed.

The problem is that when the component is rendered, the action index is deleted from the action code or url etc., preventing it from being pressed. Here I show the code of the current operation:

**Example Outputcode:**
in this example, the active index is 2, and as can be seen in the output of the generated html, the element of the list that has the class "ui-state-highlight", can be seen as it has in the onclick the code return false; and the code that the previous list items have is not added.

```
<div id="j_idt49" class="ui-steps ui-widget ui-helper-clearfix custom">
    <ul role="tablist">
        <li class="ui-steps-item ui-state-default ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="PrimeFaces.ab({s:&quot;j_idt50&quot;,f:&quot;solicitudDependenciaForm&quot;,u:&quot;solicitudDependenciaForm&quot;});return false;"><span class="ui-steps-number">1</span><span class="ui-steps-title">Paso 1</span></a></li>
        <li class="ui-steps-item ui-state-default ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="PrimeFaces.ab({s:&quot;j_idt51&quot;,f:&quot;solicitudDependenciaForm&quot;,u:&quot;solicitudDependenciaForm&quot;});return false;"><span class="ui-steps-number">2</span><span class="ui-steps-title">Paso 2</span></a></li>
        <li class="ui-steps-item ui-state-highlight ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">3</span><span class="ui-steps-title">Paso 3</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">4</span><span class="ui-steps-title">Paso 4</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">5</span><span class="ui-steps-title">Paso 5</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">6</span><span class="ui-steps-title">Paso 6</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">7</span><span class="ui-steps-title">Paso 7</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">8</span><span class="ui-steps-title">Paso 8</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">9</span><span class="ui-steps-title">Paso 9</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">10</span><span class="ui-steps-title">Paso 10</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">11</span><span class="ui-steps-title">Paso 11</span></a></li>
        <li class="ui-steps-item ui-state-default ui-state-disabled ui-corner-all" role="tab"><a tabindex="-1" class="ui-menuitem-link ui-corner-all" href="#" onclick="return false;"><span class="ui-steps-number">12</span><span class="ui-steps-title">Paso 12</span></a></li>
    </ul>
</div>
```
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 9 JSF 2.3
- Affected browsers: ALL

## 2) Expected behavior
That actions, updates etc. be executed when you click on the item that has the index active.

## 3) Actual behavior
Actions or updates or anything are not executed when you click on the item that has the index active.

## 4) Steps to reproduce
1. Add the Steps component with the attribute readonly = "fasle"
2. Include 2 or more menuitems with actions or updates.
3. Put any of the menu items as an active index.
4. Click on the active element.

## 5) Sample XHTML
```
<p:steps activeIndex="#{MyBean.ultimoPasoValido}" styleClass="custom" readonly="false" >
    <p:menuitem value="Paso 1" actionListener="#{MyBean.cambiarAlPaso(0)}" update="@form"/>
    <p:menuitem value="Paso 2" actionListener="#{MyBean.cambiarAlPaso(1)}" update="@form"/>
    <p:menuitem value="Paso 3" actionListener="#{MyBean.cambiarAlPaso(2)}" update="@form"/>
    <p:menuitem value="Paso 4" actionListener="#{MyBean.cambiarAlPaso(3)}" update="@form"/>
    <p:menuitem value="Paso 5" actionListener="#{MyBean.cambiarAlPaso(4)}" update="@form"/>
    <p:menuitem value="Paso 6" actionListener="#{MyBean.cambiarAlPaso(5)}" update="@form"/>
    <p:menuitem value="Paso 7" actionListener="#{MyBean.cambiarAlPaso(6)}" update="@form"/>
    <p:menuitem value="Paso 8" actionListener="#{MyBean.cambiarAlPaso(7)}" update="@form"/>
    <p:menuitem value="Paso 9" actionListener="#{MyBean.cambiarAlPaso(8)}" update="@form"/>
    <p:menuitem value="Paso 10" actionListener="#{MyBean.cambiarAlPaso(9)}" update="@form"/>
    <p:menuitem value="Paso 11" actionListener="#{MyBean.cambiarAlPaso(10)}" update="@form"/>
    <p:menuitem value="Paso 12" actionListener="#{MyBean.cambiarAlPaso(11)}" update="@form"/>
</p:steps>
```	

## 6) Sample bean
```
public class MyBean{
      private int ultimoPasoValido;

	public void cambiarAlPaso(int pasoNuevo) {
		ultimoPasoValido = pasoNuevo;
	}
     //GETTETS $ SETTERS
}
```
Thanks!

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
I think it was by design. So just changing it is probably not the perfect solution.
@mertsincan WDYT?

**Comment by melloware** [comment]
I thought so too but requested by 2 different users in 2016 and 2019.  See: https://forum.primefaces.org/viewtopic.php?f=3&t=44424

Unless we make it a configurable property?

**Comment by mertsincan** [comment]
Hi @tandraschko and @melloware,

I agree with Thomas. It's by design. But, maybe Melloware can add an attribute for it. Then, in StepsRenderer.java please change;
- tabindex value -> line 121
- if check -> line 135
- cursor style for the active item.

**Comment by melloware** [comment]
going to close it for now as its not critical.

**Pull request closed without merging**
