### PR TITLE
Fix #6357: Datatable CellEdit undefined tabbing off last cell.

### LINKED ISSUE #6357: DataTable: NumberFormatException when cell editable and cellEditInit AJAX event
**Describe the defect**
With cell-editable-enabled dataTable and cellEditInit ajax event, if you TAB through cells and reach last cell, last TAB rises a NumberFormatException exception.

**Reproducer**
Just clone https://github.com/dmainardi/primefaces-test repository and follow instructions.

**Environment:**
 - PF Version: 6.2 (exception rose TABBING at the end of row (not last)), 8.0, SNAPSHOT
 - JSF + version: Mojarra 2.2.20, (Mojarra) Jakarta Faces 2.3.14, **it works as expected with MyFaces 2.2.12 and MyFaces 2.3.6**
 - Affected browsers: ALL

**To Reproduce**
- clone https://github.com/dmainardi/primefaces-test.git
- run it with `mvn jetty:run`
- click on a cell (as you wanted to edit it) and TAB until table's end
- TAB another time, error is risen (check error log)

**Expected behavior**
No exception risen

**Example XHTML**
https://github.com/dmainardi/primefaces-test/blob/master/src/main/webapp/test.xhtml

**Example Bean**
https://github.com/dmainardi/primefaces-test/blob/master/src/main/java/org/primefaces/test/CarView.java

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
can you add a comment? cellInfo.indexOf('undefined') reads weird

**Comment by melloware** [comment]
Comment added `// #6357 tabbing off last cell generates "undefined,-1" cellInfo`

**Comment by tandraschko** [comment]
i wonder if it wouldnt be nicer if getCellMeta would return null in this case?

**Comment by melloware** [comment]
Great suggestion.  Updated.

**Comment by tandraschko** [comment]
much better! please merge if you tested it.

**Pull request merged**
