### PR TITLE
Fix #7044/#7045: SelectOne default to value when no label

### LINKED ISSUE #7044: SelectOneMenu: empty value breaks layout
Whenever the item value of a p:selectOneMenu is empty, layout of the menu changes (shrinks). Example:

```
          <p:selectOneMenu value="#{user.title}">
            <f:selectItem itemLabel="" />
            <f:selectItem itemValue="Dr." itemLabel="Dr." />
            <f:selectItem itemValue="Prof. Dr." itemLabel="Prof. Dr." />
          </p:selectOneMenu>

          <p:selectOneMenu value="#{user.salutation}">
            <f:selectItem itemLabel="#{messages.select}" itemDisabled="true" noSelectionOption="true" />
            <f:selectItem itemValue="Mr" itemLabel="Mr" />
            <f:selectItem itemValue="Ms" itemLabel="Ms" />
          </p:selectOneMenu>

```

Screenshot from 2021-02-26 16-06-56

### LINKED ISSUE #7045: SelectOneMenu: item value is not printed when there is no label
p:selectOneMenu delivers empty label when itemLabel is not explicitly defined. Example:

```
        <p:selectOneMenu value="#{user.title}">
            <f:selectItem itemLabel="" />
            <f:selectItem itemValue="Dr." />
            <f:selectItem itemValue="Prof. Dr." />
          </p:selectOneMenu>
```

Screenshot from 2021-02-26 16-12-49

p:selectOneMenu in contrast just prints the item value in such a case:

```
        <h:selectOneMenu value="#{user.title}">
            <f:selectItem itemLabel="" />
            <f:selectItem itemValue="Dr." />
            <f:selectItem itemValue="Prof. Dr." />
          </h:selectOneMenu>
```

### PR DESCRIPTION
**Pull request by melloware**
This makes it act like normal JSF SelectOneMenu.

image

### CODE REVIEW

**Comment by melloware** [comment]
Fixes both issues...

image

**Comment by tandraschko** [comment]
should we really default to itemValue.toString if no label is defined?

**Comment by tandraschko** [comment]
yep, i think we should just do:
itemLabel =  isValueBlank(itemLabel) ? "&nbsp;" : itemLabel;

Otherwise you leave the label empty to display nothing but it defaults to "MyEntity[userid=1]" or something

**Comment by melloware** [comment]
I am fine with that that is what we do in the mode higher up I think he was just pointing out that is not what JSF does but I am OK with that. Let me fix.

**Comment by melloware** [comment]
Refactored into getOptionLabel method so it can be reused in both places.

**Comment by fanste** [comment]
Seems to be a bit buggy. You replace the blank value with `&nbsp;` but still `writer.setText(...)` is used. This effectively writes `&amp;nbsp;` to the stream. If you use e.g. `widget.getSelectedLabel()` you get `&nbsp;` instead of ` ` (single space)

But this is still some kind of a breaking change and should be mentioned in the migration guide. If you added a blank item in JSF you now get a space. This breaks all JavaScripts if you rely on the blank value in your JavaScript (e.g. using `widget.getSelectedLabel()`)

**Comment by melloware** [comment]
@fanste I believe the `&nbsp;` is checked for in the widget.  So it could just be that `getSelectedLabel()` needs to be adjusted right?

**Comment by fanste** [comment]
Possibly yes, but it simply feels wrong that there is a readable `&nbsp;` instead of the HTML entity, IMHO.

**Pull request merged**
