### PR TITLE
#11506 LazyDataModel: no need to count if first == 0 and lazyData.size

### LINKED ISSUE #11506: LazyDataModel: no need to count if first == 0 and lazyData.size < pageSize
### Description

Regarding DataView with lazy=true: 
If first == 0 there is no need to count at the beginning and we can skip the calculateFirst method. 
After the load, if the size of the loaded data is less than the pageSize, there is no need to count.

This is the case for DataView, but I believe its the same case for DataTable, DataList and DataGrid.

Count can be an expensive operation with LazyDataModel, especially when no filters are applied (first load).

It can be achieved playing with the count attribute, but it's awkward and it sometimes breaks on upgrades.

WDYT?

### Describe the solution you would like

If first == 0 and loaded data size < pageSize no count() operation should be performed on the lazyDataModel

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cocorossello**
Reopened the PR to see what makes the build fail

Fix #11506

### CODE REVIEW

**Comment by melloware** [comment]
OK good just a single failing test @Rapster 

```
DataTable045Test.selectionMultipleWithPaging:53 expected: <true> but was: <false>
```

**Comment by cocorossello** [comment]
The problem is in CustomerLazyDataModelNoCountImpl. 

I don't think this is correct however it is intentional:

```
    @Override
    public int count(Map<String, FilterMeta> filterBy) {
        return 0;
    }

```
Changing to return `datasource.size() `works

**Comment by tandraschko** [comment]
Return 0 is a supported feature If you check the docs.

**Comment by cocorossello** [comment]
ok, then this should do the trick.  The logic should be extracted to a method but I'm not sure on where should I put this this.

Maybe in LazyDataModel, something like

`    private void calculateRowCount(List<?> loadedData, Map<String, FilterMeta> filterBy, int rows, int first) {
        if (getRowCount() == 0) {
            if (data.size() < rows && first == 0) {
                setRowCount(data.size());
            }
            else if (first == 0) {
                setRowCount(count(filterBy));
            }
        }
    }`

**Comment by tandraschko** [comment]
Maybe we should change the return type of count to a nullable int
Makes it more clear

**Comment by cocorossello** [comment]
That is not possible, LazyDataModel extends javax.faces.model.DataModel and has
`
public abstract int getRowCount();

`

**Comment by tandraschko** [comment]
Then we should refactor and docs to -1 instead of 0 maybe

**Comment by melloware** [comment]
It looks like all Integration Tests are passing!

**Comment by Rapster** [comment]
I'll have a look later in the week

**Comment by melloware** [comment]
@Rapster just a reminder on this one.

**Pull request merged**
