### PR TITLE
Fix #10751: Apache Commons FileUpload removed

### LINKED ISSUE #10751: FileUpload: Deprecate Apache Commons FileUpload
Now that 14.0.0 is on Servlet 3.0 and JSF2.3 we should drop all the code for Apache Commons FileUpload since the Native Servlet Parts work great and have been heavily tested over the years.

There should be no need for this anymore right?

### PR DESCRIPTION
**Pull request by melloware**
Fix #10751: Apache Commons FileUpload removed

- [x] Remove all code
- [x] remove special nightly integration tests for file uploads
- [x] Update all documentation
- [ ] Check old issues for it works on Apache Commons only issues

### CODE REVIEW

**Comment by melloware** [comment]
@Rapster please confirm `UploadedFileCleanerListener ` was only needed for Servlet 2.5 like the docs said and is safe to remove now?

**Comment by melloware** [comment]
@christophs78 do we need `nightly-file-upload.yml` work now since we no longer have native and Commons uploads it can just be part of the main IT's?

**Comment by christophs78** [comment]
> @christophs78 do we need `nightly-file-upload.yml` work now since we no longer have native and Commons uploads it can just be part of the main IT's?

Yep. Think we can get rid of this.

**Comment by melloware** [comment]
@christophs78 thanks I just removed it entirely!

**Comment by tandraschko** [comment]
can you go through old issues and check if we had something like "works only with commons"?

**Comment by melloware** [comment]
Yes I will go through all the old issues.

**Comment by melloware** [comment]
The only real feature I can find that is not supported by native out of the box is https://github.com/primefaces/primefaces/issues/9860

But I assume since its Servlet spec there is some servlet property to control max file uploads?

**Pull request closed without merging**
