### PR TITLE
Fix #5279: InputNumber update AutoNumeric 4.5.9

### LINKED ISSUE #5279: InputNumber: Upgrade AutoNumeric 4.5.x
Current version: 1.9.45
Latest Version:  4.5.10

Upgrade Guide:
https://github.com/autoNumeric/autoNumeric/blob/next/doc/HowToUpgradeToV4.md

### PR DESCRIPTION
**Pull request by melloware**
Lots of bugs and features fixed in the last 3 years.
Last build was 16 days ago so they are keeping it up to date.
Allow removal of the dead jquery Metadata plugin.

### CODE REVIEW

**Comment by tandraschko** [comment]
@melloware 
https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml
the "Empty value (sign)" is not empty and a error is logged to the console:
Error: The display on empty string option 'emptyInputBehavior' is invalid ; it should either be 'focus', 'press', 'always', 'min', 'max', 'zero', 'null', a number, or a string that represents a number, [sign] given.


Please check it, otherwise we have to revert
and please test at least all cases in the showcase next time

**Comment by melloware** [comment]
Yep I just merged my Showcase PR: https://github.com/primefaces/showcase-facelift/pull/80

**Comment by melloware** [comment]
i did "sign" is no longer valid its "always".

**Comment by tandraschko** [comment]
I see
then please add it to the migration guide

**Comment by melloware** [comment]
Just updated Migration Guide.

**Comment by tandraschko** [comment]
great!

**Pull request merged**
