### PR TITLE
Fix #7616: FileUpload NPE when part is null on size check

### LINKED ISSUE #7616: FileUpload: Simple auto upload throws exception while size limit is reached
I tried to use the simple file upload component with auto=true, and an error occurs while I sent a file that reaches the max upload size.  Debugging the code I see that field `part` inside `NativeUploadedFile` class is null.

**Reproducer**
Clone repository https://github.com/garcia-jj/primefaces-upload-issue in order to reproduce that issue. The page http://127.0.0.10:8080/primefaces-test/basic.xhtml contains the test case.

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _e.g. Wildfly 21, Mojarra
 - Affected browsers: tested on Chorme and Firefox, but I guess this is not a browser issue

**To Reproduce**
1. Go to 'http://127.0.0.10:8080/primefaces-test/basic.xhtml'
2. Click on '+ Choose' button, then select a file with size greater than 1kb.
4. See error on logs. A NullPointerException will occurs.
```
Jul 21, 2021 3:35:56 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.NullPointerException: Cannot invoke "javax.servlet.http.Part.getSize()" because "this.part" is null
        at org.primefaces.model.file.NativeUploadedFile.getSize(NativeUploadedFile.java:70)
        at org.primefaces.model.file.UploadedFileWrapper.getSize(UploadedFileWrapper.java:74)
        at org.primefaces.util.FileUploadUtils.tryValidateFile(FileUploadUtils.java:299)
        at org.primefaces.component.fileupload.FileUpload.validateValue(FileUpload.java:85)
```

**Expected behavior**
The file upload sucessfully.

**Example XHTML**
```html
<p:growl id="messages" showDetail="true"/>

<div class="card">
    <h5>Single</h5>
    <h:form>
        <p:fileUpload value="#{fileUploadView.file}" mode="simple" skinSimple="true" auto="true"
                      process="@this" update="messages"
                      sizeLimit="1"
                      listener="#{fileUploadView.handleFileUpload}"/>
    </h:form>
</div>

<div class="card">
    <h5>Multiple</h5>
    <h:form>
        <p:fileUpload value="#{fileUploadView.files}" mode="simple" skinSimple="true" multiple="true"
                      auto="true"
                      sizeLimit="1"
                      process="@this" update="messages"
                      listener="#{fileUploadView.handleFilesUpload}"/>
    </h:form>
</div>
```

**Example Bean**
```java
@Named
@RequestScoped
public class FileUploadView {

	private UploadedFile file;
	private UploadedFiles files;

	public UploadedFile getFile() {
		return file;
	}

	public void setFile(UploadedFile file) {
		this.file = file;
	}

	public UploadedFiles getFiles() {
		return files;
	}

	public void setFiles(UploadedFiles files) {
		this.files = files;
	}

	public void handleFileUpload(FileUploadEvent event) {
		FacesMessage message = new FacesMessage("Successful", event.getFile().getFileName() + " is uploaded.");
		FacesContext.getCurrentInstance().addMessage(null, message);
	}

	public void handleFilesUpload(FilesUploadEvent event) {
		for (UploadedFile f : event.getFiles().getFiles()) {
			FacesMessage message = new FacesMessage("Successful", f.getFileName() + " is uploaded.");
			FacesContext.getCurrentInstance().addMessage(null, message);
		}
	}
}
```

Thank U

### PR DESCRIPTION
**Pull request by melloware**
If the Part is NULL I return LONG.MAX_VALUE for the size.

### CODE REVIEW

**Comment by tandraschko** [comment]
i wonder if there should be a NativeFileUpload item anyway if no part is found

**Comment by melloware** [comment]
Good question.  His scenario is valid though a 1KB max and upload a file more than 1 KB.

**Comment by tandraschko** [comment]
i think a UploadedFile instance should be thrown away or not used anymore after its invalided
and a NativeUploadedFile should never be instantiated with a null part

just my thoughts after looking at the stacktrace
would need to debug by myself

**Comment by melloware** [comment]
Agreed and this might fix both recent bugs reported as they are related.

**Comment by garcia-jj** [comment]
Looks fine to me @melloware. I also agree with @tandraschko about `NativeFileUpload` instantiation.

Great job. Thank U.

**Comment by wal-jan** [comment]
@melloware  sorry to say, but `null` check for `part` in `getSize()` is not sufficient. There is another NPE in case of multiple=true
```
java.lang.NullPointerException
        at org.primefaces.component.fileupload.FileUpload.validateValue(FileUpload.java:91)
        at javax.faces.component.UIInput.validate(UIInput.java:1021)
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1318)
        at javax.faces.component.UIInput.processValidators(UIInput.java:733)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:608)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIForm.visitTree(UIForm.java:355)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:261)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1308)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:73)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
```
 I also agree with @tandraschko about NativeFileUpload instantiation. I looked at where  `NativeUploadedFile#NativeUploadedFile(Part, Long)` is called. Thats in `NativeFileUploadDecoder#createUploadedFiles(HttpServletRequest ...)` and `NativeFileUploadDecoder#createUploadedFile(HttpServletRequest ...)`. Former method just could filter out null parts and latter method could return null in case of null part. But maybe I overlooked something.

**Comment by melloware** [comment]
Yep I think @tandraschko is going to investigate.

**Comment by tandraschko** [comment]
currently i dont have much time, so i would appreciate if anyone could work on

**Comment by melloware** [comment]
@wal-jan did you want to take a crack at this one?

**Comment by wal-jan** [comment]
@melloware yes, I'll try to fix the NPEs (based on @tandraschko's idea to throw away UploadedFile instance if part is empty). But it'll take some time, I am working on some integration tests checking these conditions.

**Comment by melloware** [comment]
Fantastic. I am going to close this PR then.

**Pull request closed without merging**
