### PR TITLE
Fix #3078: TabView add swipe events

### LINKED ISSUE #3078: Add swipe functionality to TabView
## 1) Environment
- PrimeFaces version: 6.1.10
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? 
- Application server + version:
- Affected browsers:

## 2) Expected behavior
When you swipe left on a TabView, the screen should move one tab to the right and when you swipe right the screen should move one tab to the left.

Note: the TabView menu should also scroll to the right or left so that the currently displayed tab is visible in the menu.

I documented how I added swipe to TabView in the following Forum entry.

https://forum.primefaces.org/viewtopic.php?f=3&t=53503

Note:  In my solution, the TabView menu does not scroll with the page swipe so if the entire menu is not visible you can display a page not visible/selectable on the menu. 

## 3) Actual behavior

At the moment, TabView does not support swipe left or swipe right.

## 4) Steps to reproduce

N/A

## 5) Sample XHTML

N/A

## 6) Sample bean

N/A

### PR DESCRIPTION
**Pull request by melloware**
Follow Carousel as the pattern for adding swipe events.

Test in Chrome mobile.

### CODE REVIEW

**Comment by tandraschko** [comment]
should we make it configurable?

**Comment by melloware** [comment]
My thought was Carousel does not and it lets TouchSwipe detect whether your browser has touch events like IOS or Android.  So on desktop systems swipe is disabled by default.  I can be convinced to make it configurable ?

**Comment by tandraschko** [comment]
no idea :D it was just a question
for me its also ok without configuration

**Comment by fanste** [comment]
This change breaks components like `p:selectCheckboxMenu` inside `p:tab`in IE11. The component uses `mousedown` to show the panel which seems to be affected by the `pointerdown` event that is used by the touchswipe plugin.

Maybe it is enough to add `.ui-selectcheckboxmenu` to the `excludedElements`, I have not tested it

**Comment by melloware** [comment]
Investigating...  For now to temporarily fix it add styleClass="noSwipe" to your selectCheckBoxMenu.

**Pull request merged**
