### PR TITLE
Fix #8950: DatePicker: year navigator input type number

### LINKED ISSUE #8950: DatePicker: use input number as year navigator
### Description

When you use the date picker to select a date of birth, you may need to navigate to years ago. With the current selector you either need to include a lot of years, or you need to navigate multiple times.

### Describe the solution you would like

Instead of a select input it would be better (IMO) to have a numeric input.
```html
<input type="number" min="..." max="..." step="1" value="..."/>
```
This allows you to spin up and down, but also to simply enter a year.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jepsar**
Fix #8950

This is working. However, somehow the spinner buttons are not showing on the input number. I don't get why. After some research it looks like they could be disabled by CSS, but I cannot find where. They are not inspectable using the DOM inspector (at least I didn't find a way), so it's hard to debug.

### CODE REVIEW

**Comment by melloware** [comment]
Have you tried it with `primefaces.THEME` set to `none` to turn off the PF CSS to see if its something with that?

**Comment by jepsar** [comment]
https://github.com/primefaces/primefaces/blob/d09ef48aa15aeda31678eb0c80d59bbd8349674b/primefaces-showcase/src/main/webapp/resources/showcase/css/layout/_core.scss#L68-L76

I'll have a look at the ITs

**Comment by melloware** [comment]
Oh OK thta was added for the FloatLabel but in 12.0.0-SNAPSHOT I added a FloatLabel showcase page with every component that supports floatlabel.  Not sure why in particular it hid those for number fields?

**Comment by melloware** [comment]
Actually I didn't add that looks like that has been in that Showcase CSS for a while but no idea why it would be needed.

**Comment by jepsar** [comment]
I tried to fix the IT, but I cannot fix these errors:
```
[ERROR] Errors: 
[ERROR]   DatePicker011Test.testLazyMetaDataNoBehaviour1:147->testDatePickerPart1:296 » Timeout
[ERROR]   DatePicker011Test.testLazyMetaDataViewChangeBehaviour1:155->testDatePickerPart1:296 » Timeout
[ERROR]   DatePicker011Test.testMetaDataCloseBehaviour1:83->testDatePickerPart1:296 » Timeout
[ERROR]   DatePicker011Test.testMetaDataDateSelectBehaviour1:67->testDatePickerPart1:296 » Timeout
[ERROR]   DatePicker011Test.testMetaDataNoBehaviour1:59->testDatePickerPart1:296 » Timeout
[ERROR]   DatePicker011Test.testMetaDataViewChangeBehaviour1:75->testDatePickerPart1:296 » Timeout
```

**Comment by jepsar** [comment]
> Actually I didn't add that looks like that has been in that Showcase CSS for a while but no idea why it would be needed.

For now I explicitly show spinners on the year input of a date picker.

**Comment by jepsar** [comment]
Actually, I think I'll be closing the issue as won't fix. I'm not convinced that the input is a great improvement. Rerendering of the calendar (including the input) makes using the spinner awkward. And clearing the year will get you an empty calendar.

**Pull request closed without merging**
