### PR TITLE
Fix #6303: Diagram upgrade jsPlumb 2.14.6

### LINKED ISSUE #6303: Diagram: Upgrade jsPlumb to 2.14.6
**Description**
Diagram is currently using a very old jsPlumb 2.1.0.  (Apr 21, 2016)

**Describe the solution you would like**
Upgrading to the latest 2.14.6 (Sep 4, 2020)

See: https://github.com/jsplumb/jsplumb/blob/master/doc/wiki/changelog.md

### PR DESCRIPTION
**Pull request by melloware**
- [x] Separated widget from plugin lib like other components
- [x] Updated and tested with Showcase
- [x] Update JSDoc
- [x] Update Migration Guide

### CODE REVIEW

**Comment by melloware** [comment]
@blutorange I need your help on this one for JSDOC.  diagram.d.ts had a note in there about using the built in Type Declarations once we updated JS Plumb.  

I  have done that however in your old diagram.d.ts you had `declare namespace JsPlumb` however in the the included index.d.ts from JsPlumb they have `declare module` so the JSDoc is failing.  How do I update the widget.js to point to the module?

For example its giving me failures on:
```javascript
@prop {JsPlumb.jsPlumbInstance} canvas The JSPlumb instance for this diagram.
```

**Comment by blutorange** [comment]
@melloware Hold on a second, I'm taking a look. Declarations come in various forms, it's not always easy to include them.

**Comment by blutorange** [comment]
Here you go https://github.com/melloware/primefaces/pull/2

fyi, I removed the *.d.ts file completely and added the `jsplumb` package via npm. So now we can use `import("jsplumb").jsPlumbInstance` (for modules) instead of `JsPlumb.jsPlumbInstance`  (which was for namespaces).

**Comment by melloware** [comment]
Just tested and docs are now generated!

**Comment by tandraschko** [comment]
+1 if well tested

**Pull request merged**
