### PR TITLE
Update of Messages_pl.properties

### PR DESCRIPTION
**Pull request by Emkas**
* Add missing properties
* Remove non-ASCII characters

### CODE REVIEW

**Comment by melloware** [comment]
@Emkas did you also review the client side properties as well for PL?

**Comment by melloware** [comment]
See: https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/locales/locale-pl.js

**Comment by Emkas** [comment]
> @Emkas did you also review the client side properties as well for PL?

No...

I will look for it, and I can update it as well. No problem.

**Comment by Emkas** [comment]
Thanks. I need a second for this. I'll provide next commit if needed.

**Comment by melloware** [comment]
Perfect much appreciated.

**Comment by Emkas** [comment]
OK, there's not so much to add there. Only two new properties.

**Pull request merged**
