### PR TITLE
Fix #2452: PanelGridRenderer add padding when columns > 0.

### LINKED ISSUE #2452: p:panelGrid, header lacks padding when columns > 0
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) NO
- Application server + version: Tomcat 7
- Affected browsers: All

## 2) Expected behavior
The header of the `p:panelGrid` should have proper padding, even if the `columns` attribute is provided.

## 3) Actual behavior
The header doesn't have the proper padding, becuase a css class is missing. Rendered output:
panelgrid

## 4) Steps to reproduce
Just open the provided xhtml.

## 5) Sample XHTML
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
		<p:panelGrid columns="1">
			<f:facet name="header">
				<h:outputText value="With columns"/>
			</f:facet>
			<h:outputText value="Content"/>
		</p:panelGrid>
		
		<p:spacer height="10"/>
		
		<p:panelGrid>
			<f:facet name="header">
				<p:row>
					<p:column>
						<h:outputText value="Without columns"/>
					</p:column>
				</p:row>
			</f:facet>
			<p:row>
				<p:column>
					<h:outputText value="Content"/>
				</p:column>
			</p:row>
		</p:panelGrid>
    </h:body>
</html>
```

## 6) Sample bean
Not needed

### PR DESCRIPTION
**Pull request by melloware**
Fix #2452: PanelGridRenderer add padding when columns > 0.

### CODE REVIEW

**Review by NicolaIsotta — APPROVED** [review]

**Comment by tandraschko** [comment]
Didn't check it in detail but doesn't it look like you missuse this class?

**Comment by melloware** [comment]
You mean the PanelGrid.CELL_CLASS ?  That class i believe it what gives this header the proper padding when columns > 0.  Is there some other class that should be used?

**Comment by tandraschko** [comment]
Yep :D
to be honest, i don't know. I just thought that its already used for other dom elements, so it might be just a "hack" to fix the layout.

**Comment by melloware** [comment]
@mertsincan can you review this one and give your opinion if the fix is ok?

**Comment by tandraschko** [comment]
it conflicts currently, would be great if you will resolve it.

**Comment by melloware** [comment]
Fixed conflicts!

**Pull request merged**
