### PR TITLE
TreeScrollable

### PR DESCRIPTION
**Pull request by huseyinturkmenoglu**

### CODE REVIEW

**Comment by ekennedy80** [comment]
When will the scrollable Tree be coming out to the community?

**Comment by Rapster** [comment]
Next community realease I assume, meaning December 2018 (if PR accepted)

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
@mertsincan Will you review this, too?

**Comment by tandraschko** [comment]
@HuseyinTurkmenoglu 
The PR conflicts now and i assume that @mertsincan still didn't check your changes.
I will close it for now, but you can surely reopen if the conflicts are fixed - or just commit it if reviewed internally by PrimeTek.

**Pull request closed without merging**
