### PR TITLE
Fix #5455: CSP initialized before PF scripts.

### LINKED ISSUE #5455: CSP: Timeline AJAX Missing CSP nonce
Getting "Missing CSP nonce" error when making an AJAX call.

**Steps to reproduce:**
1. Enable CSP in Showcase
```xml
    <context-param>
        <param-name>primefaces.CSP</param-name>
        <param-value>true</param-value>
    </context-param>
```

2. Navigate to http://localhost:8080/showcase/ui/data/timeline/allEvents.xhtml 

3. When the RangeChanged Ajax event is fired you will get the below stacktrace.

**StackTrace:**
```
SEVERE: Error Rendering View[/ui/data/timeline/allEvents.xhtml]
javax.faces.FacesException: Missing CSP nonce
        at org.primefaces.csp.CspState.validate(CspState.java:75)
        at org.primefaces.csp.CspState.getNonce(CspState.java:57)
        at org.primefaces.csp.CspResponseWriter.listenOnEndAttribute(CspResponseWriter.java:185)
        at org.primefaces.csp.CspResponseWriter.write(CspResponseWriter.java:167)
        at org.primefaces.csp.CspPartialResponseWriter.write(CspPartialResponseWriter.java:167)
        at java.io.Writer.write(Writer.java:192)
        at java.io.Writer.write(Writer.java:157)
        at org.primefaces.util.WidgetBuilder.init(WidgetBuilder.java:59)
        at org.primefaces.util.WidgetBuilder.init(WidgetBuilder.java:78)
        at org.primefaces.component.growl.GrowlRenderer.encodeEnd(GrowlRenderer.java:67)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:615)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1468)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:400)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:319)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1101)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:442)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1583)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)

Dec 18, 2019 7:15:34 AM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
SEVERE: Missing CSP nonce
javax.faces.FacesException: Missing CSP nonce
        at org.primefaces.csp.CspState.validate(CspState.java:75)
        at org.primefaces.csp.CspState.getNonce(CspState.java:57)
        at org.primefaces.csp.CspPhaseListener.beforePhase(CspPhaseListener.java:73)
        at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:201)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:74)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1583)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko @Rapster  Our QA team keeps intermittenly getting the "Missing CSP Nonce" issue when they click a button or an Ajax script runs before the CSP Init script has run.    I am able to reproduce it every time using the Timeline All Events example.

This PR is for your review where I basically move that CSP Init script to the top so it executes before any other PF widget script.   This fixes the issue and I have noticed we are no longer getting those Missing CSP Nonce errors.

This PR is for your review or if you think of a better way to do it I am listening....but I think this is something we absolutely need to fix to allow adoption of CSP.

### CODE REVIEW

**Comment by tandraschko** [comment]
doesn't this fix it? https://github.com/primefaces/primefaces/commit/ee55c6d9302b7588cc453e01e1d5b8cb9b57644e

**Comment by melloware** [comment]
Let me do some testing...

**Comment by tandraschko** [comment]
I think it's the same as your PR for AJAX requests.
For non-AJAX the scripts are probably rendered to late (before body end)

**Comment by melloware** [comment]
OK so i tested your fix and it does not work for all situations. It still renders it last.

My commit I have tested with both MOVE_SCRIPTS_TO_BOTTOM true and false and the CSP is initialized before the widgets and everything is working with no "Missing CSP NONCE" errors.

**Comment by tandraschko** [comment]
Is it by design that the init-scripts are not executed on ajax requests?

**Comment by tandraschko** [comment]
Just to be sure: with your PR, the CSP init script is never executed on AJAX requests (which breaks form updates as the CSP is not reinialized in the updated/new form)

**Comment by melloware** [comment]
OK let me do some more testing.  I think I need to add it to Partial rendering.

**Comment by melloware** [comment]
Updated PrimePartialResponseWriter to return init scripts as well.

**Comment by tandraschko** [comment]
ok, thanks
i will merge it and do some refactorings

**Comment by tandraschko** [comment]
/ cosmetics :D

**Comment by tandraschko** [comment]
@melloware i will commit some naming changes now
Please retest

i'm not sure about one thing: should the init scripts be executed without a DOM-ready ($function()...) in the HeadRenderer? not sure...

**Comment by tandraschko** [comment]
committed now

**Comment by melloware** [comment]
So when I tested here is what happens..

**MOVE_SCRIPTS_TO_BOTTOM = True**
If wrapped in "function{}" the error still occurs.

**MOVE_SCRIPTS_TO_BOTTOM = False**
If wrapped in "function{}" everything works, if not wrapped in it then the same CSP Missing error happens.

That is why I chose the way I did to only wrap it in "function{}" if its NOT move scripts to bottom.

**Comment by melloware** [comment]
OK also testing your latest changes now...

**Comment by tandraschko** [comment]
Yep, i see
CSP needs all forms the be availble in the DOM, so DOM-ready ($function()...) is required

**Comment by melloware** [comment]
OK i just tested your latest changes with CSP=true and false and MOVE_SCRIPTS_TO_BOTTOM=true and false and everything is working in all scenarios!

**Comment by tandraschko** [comment]
perfect

**Pull request merged**
