### PR TITLE
Fix #4140 / #1836: Spotlight and any modal dialog/overlays prevent scrolling.

### LINKED ISSUE #4140: Spotlight: Body is still scrollable when the spotlight is shown
## 1) Environment
- PrimeFaces version: 6.3.0
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: Tomcat 8.5.15
- Affected browsers: ALL

## 2) Expected behavior
When the spotlight is visible, it should be already attached to the corresponding item.

## 3) Actual behavior

When the spotlight is visible, if the user scroll the page using mouse wheel then the position of the highlight area is fixed, but the content underneath is moved. It makes the spotlight mark the wrong area.

## 4) Steps to reproduce
- Go to current primefaces showcases: https://www.primefaces.org/showcase/ui/misc/spotlight.xhtml
- Do not enter anything in the form
- Click button SAVE

primefaces-spotlight

### PR DESCRIPTION
**Pull request by melloware**
Much better fix thanks to @tandraschko !!

Tested:
 - OverlayPanel modal and non-modal
 - Dialog modal and non-modal
 - SideBar blockScroll="true" and blockScroll="false"
 - Spotlight modal and non-modal

### CODE REVIEW

**Comment by tandraschko** [comment]
Imo we should introduce the same attribute as on sidebar, so everything can be configurable!?

**Comment by melloware** [comment]
OK no problem.  Should it be TRUE by default on dialog, spotlight and overlaypanel?   I feel like that is a good default where as Sidebar False is the correct default.

**Comment by tandraschko** [comment]
Dont know, i would make it false as overlaypanel could be used without preventscroll and its probably the default

**Comment by melloware** [comment]
OK made major improvements to the utility and added blockScroll attribute to Lightbox, Dialog, DialogFramework, OverlayPanel, and Spotlight.

**Comment by tandraschko** [comment]
@melloware its used for modal overlays, right? So i think we could set the default to true. Also for sidebar.
I'm just not sure if this could break some layout types?

**Comment by melloware** [comment]
Correct it it’s used on any modal calls. I made it false in all situations by default to not affect any current behavior.  But we could consider making in true in certain scenarios

**Pull request merged**
