### PR TITLE
cleanup test-classpath to avoid interference with embedded Tomcat

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by tandraschko** [comment]
jetty runs still fine?

**Comment by christophs78** [comment]
Yep. Jetty still fine.
But i don´t get rid of the warnings regarding double initialization. (I hoped to improve this by doing this, but there seems to be another issue.)

**Comment by tandraschko** [comment]
should we close or merge?

**Comment by christophs78** [comment]
IMO merge

**Pull request merged**
