### PR TITLE
Fix #873 - not to deselect all when selectManyMenu is under checkbox …

### LINKED ISSUE #873: selectManyMenu only selects one when clicking on the label
To reproduce visit http://www.primefaces.org/showcase/ui/input/manyMenu.xhtml

In the advanced menu click on the select item label, ie. Afterdark, Afternoon etc.

Expected Result:
All clicked items should remain selected.

Actual Result:
Only the last clicked item is selected

### PR DESCRIPTION
**Pull request by jxmai**
…mode

Fix #873 

image

### CODE REVIEW

**Comment by jxmai** [comment]
There is a bug. Hold on. To reopen when it is ready.

**Comment by jxmai** [comment]
False alarm. I thought the shift key behavior was changed, so I did the side by side comparison of the old code versus the new one. The result was OK (the same as before). 

The key of this PR is not to unselect all even if meta key is not pressed when checkbox is set

Before this pull:

```js
 if(!metaKey) {
    $this.unselectAll();
}
```

so if ctrl key is not pressed, the unselect all will be triggered which leads to the inconsistent  behaviors.

After this pull:

```js
if(!metaKey && !$this.cfg.showCheckbox) {
  $this.unselectAll();
}
```

We should take checkbox into consideration as jasonex7 described in the issue

> I think setting showCheckbox="true" should by default keep the selected items instead of just select the last one and clearing the previous selected ones.

**Comment by jasonex7** [comment]
Thanks @jxmai I think that is the correct behavior from the user's perspective.

**Comment by jxmai** [comment]
You're welcome :smile:

**Pull request merged**
