### PR TITLE
Fix #4191 tabIndex shouldn't be rendered when component is disabled.

### LINKED ISSUE #4191: TriStateCheckbox: tabIndex shouldn't be rendered when component is disabled
## 1) Environment
- PrimeFaces version: 6.3-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Not Version? 6.2
- Does it work on the newest sources in GitHub? Not
- Application server + version: WildFly 13
- Affected browsers: Any

## 2) Expected behavior
TabIndex shouldn't be rendered when component is disabled

## 3) Actual behavior
TabIndex is rendered when component is disabled

## 4) Steps to reproduce
Simply include this component disabled, the tabindex is rendered, then this component take the focus even disabled.

### PR DESCRIPTION
**Pull request by wsaca**
Fix issue #4191.

### CODE REVIEW

**Comment by tandraschko** [comment]
currently we always render the tabindex, so not sure if the change is correct

**Comment by wsaca** [comment]
The component is receiving the focus even when it is disabled. Another option is to set tabIndex -1 or work with the input element to control the focus and states instead of the div.

**Comment by tandraschko** [comment]
why does it work with other components?

**Comment by wsaca** [comment]
If you want to verify this issue in other component you can do it with SelectOneButton, they both use tabindex on a div to control the focus and they have a similar issue.
The component SelectBooleanCheckbox works fine because the focus is controlled with the input element and when the disabled attribute is added then tabIndex is ignored, that's why we don't need to remove/change it if the component is disabled.

**Comment by tandraschko** [comment]
Wouldn't it be a better fix to move the tabindex to a hidden input like done in other components?

**Comment by wsaca** [comment]
I think so, but that change affects the way how to control the three states, should I give a proposal creating another PR or do it in this one?

**Comment by wsaca** [comment]
I will create another issue.

**Pull request closed without merging**
