### PR TITLE
Fix #2662 - Panel: add ui-panel-actions for facet "actions"

### LINKED ISSUE #2662: Panel: add ui-panel-actions for facet "actions"
Basically, our panel will contain menubutton in facet actions, instead of writing something like this:
```xml
<p:panel>
    <f:facet name="actions">
        <div class="float: right">
            <p:menuButton />
        </div>
    </f:facet>
</p:panel>
```

I could simply use:
```css
.ui-panel-actions {
    float: right;
}
```
Facet would generated in div (with inline-block style)

I'll try to provide a PR soon

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by Rapster** [comment]
I think encodeFacet should be placed in `CoreRenderer`, what do you think @tandraschko?

**Comment by tandraschko** [comment]
What do you mean with the last question?

**Comment by Rapster** [comment]
There is 6 implementaions of `encodeFacet` in primefaces, I think we could only have one implemented in `CoreRenderer` so every renderer could use it

**Comment by tandraschko** [comment]
Do you mean this:

`        
UIComponent actionsFacet = panel.getFacet("actions");
if (actionsFacet != null) {
     actionsFacet.encodeAll(context);
}
`
?

**Comment by Rapster** [comment]
yes

**Comment by tandraschko** [comment]
Yep, why not but it wouldn't work for this case as clean as for a normal case :P

**Comment by Rapster** [comment]
Why wouldn't it work?

**Pull request merged**
