### PR TITLE
#12394 - Include SASS themes in project folder 

### LINKED ISSUE #12394: Include SASS themes in project folder

### PR DESCRIPTION
**Pull request by tandraschko**
Fixes #12394

### CODE REVIEW

**Comment by tandraschko** [comment]
2 things to mention
1) we have more sass themen then themes in PF.jar, i skip them for now
2) some themes.css already have changes, maybe we missed some commits before

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Hmmm I have been keeping the themes up to date and usually copy them over when a change it made?  It could just be a line ending difference with the DART compressor?

**Comment by tandraschko** [comment]
we may also add the other themes to something like primefaces-extra-themes in future, not sure

**Comment by melloware** [comment]
I like this way better.

**Comment by tandraschko** [comment]
i mean that we have like 10 themes in primefaces-themes but only 5 in primefaces.jar

**Comment by melloware** [comment]
Should we just add them all?

**Comment by tandraschko** [comment]
dont think so, 1 is about 200kb

**Comment by tandraschko** [comment]
they may be just legacy, no idea

**Comment by melloware** [comment]
OK then i think what you have is good.  Those other themes might be used in premium themes or they are legacy like you said.

**Comment by melloware** [comment]
want me to squash and merge it?

**Comment by tandraschko** [comment]
yeah

**Comment by jepsar** [comment]
What happened to the build scripts?

**Comment by melloware** [comment]
you don't need them now its done as part of the Maven build in the pom.xml it copies the files to the correct place.

**Pull request merged**
