### PR TITLE
Fix #12507 - DataTable: default input facet filter not working with dynamic columns

### LINKED ISSUE #12507: DataTable: Filter isn't working when <f:facet> is added
### Describe the bug

When <f:facet name="filter"> added to DataTable or TreeTable filter isn't working for default filter inputs. #12474 
You can see in [Primefaces Showcase](https://www.primefaces.org/showcase/ui/data/datatable/columns.xhtml?jfwid=b09b2) dropdown filter works but inputText ones aren't working also DatePicker filter is not work correctly.

### Reproducer

_No response_

### Expected behavior

Prime faces filter should works.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.4

### Theme

Poseidon

### JSF implementation

Mojarra

### JSF version

4.0.5

### Java version

21

### Browser(s)

Chrome Version 127.0.6533.120

### PR DESCRIPTION
**Pull request by Rapster**
Fix #12507

Regression by #11135 

@tandraschko Why do we need a FacetUtils? All methods are not related to facet, but can be used on any UIComponent. IMO, that util should be removed, and everything  should go back to ComponentUtils

### CODE REVIEW

**Comment by tandraschko** [comment]
because ComponentUtils is a just a weird pool of methods currently

**Comment by melloware** [comment]
Looks like the IT's are failing...

```
DataTable043Test.filter:69->AbstractDataTableTest.assertRows:82->AbstractDataTableTest.assertRows:88 expected: <2> but was: <3>
Error:    DataTable043Test.filterPlusPaging:99->AbstractDataTableTest.assertRows:82->AbstractDataTableTest.assertRows:93 expected: <3> but was: <2>
```

**Comment by melloware** [comment]
@Rapster i wonder if this fix will also fix: https://github.com/primefaces/primefaces/issues/12274 it seems similar.

**Comment by Rapster** [comment]
> because ComponentUtils is a just a weird pool of methods currently

True, but creating a new class without doing anything about ComponentUtils won't solve anything except making things more "weird" as you call it. IMO, we should stick to 3 utils at best:

ComponentUtils _(no CompositeUtils, no TraversalUtils, the disctinction is very questionable)_
RendererUtils
ConverterUtils

A few methods can move elsewhere, for instance isFlex / isTouchable etc. can go in their respective classes

**Comment by tandraschko** [comment]
Just create a new issue or discussion ;)

**Comment by Rapster** [comment]
Sure... https://github.com/primefaces/primefaces/issues/12519

**Comment by melloware** [comment]
@Rapster you are right it looks like some SONAR configs are missing?

**Review by melloware — APPROVED** [review]

**Pull request merged**
