### PR TITLE
Fix #5477: Tree iterates over its descendants w/o iterating over data model if hinted SKIP_ITERATION

### LINKED ISSUE #5477: Tree: composite components inside miss their values on update (only mojarra with full state saving)
(Attached the primefaces-test based reproducer, see first comment.)

## 1) Environment
- PrimeFaces version: 6.1.
- Does it work on the newest released PrimeFaces version? Version? No, 7.0.
- Does it work on the newest sources in GitHub? No - checked with com.github.primefaces:primefaces:master-SNAPSHOT.
- Application server + version: Wildfly 10.1, Wildfly 18.1. Also primefaces-test's jetty (mojarra only).
- Affected browsers: Firefox (shouldn't matter).

## 2) Expected behavior

Updating the tree correctly rerenders the composite components in its nodes.

## 3) Actual behavior

Composite components' values dissappear.

## 4) Steps to reproduce

Press the "Update the tree" button. See values dissapear.

image

## 5) Sample XHTML

The view.
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ccomp="http://xmlns.jcp.org/jsf/composite/composites">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h1>#{testView.testString}</h1>
		<p />
		<h:form>
			<p:tree id="tree" value="#{testView.dateTree}" var="data">
				<p:treeNode>
					<ccomp:outputDate id="od" value="#{data}" />
				</p:treeNode>
			</p:tree>
			<p:commandButton value="Update the tree" process="@this" update="tree" />
		</h:form>

    </h:body>
</html>
```

And the composite component.
```
<ui:component xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough" xmlns:cc="http://java.sun.com/jsf/composite">

	<cc:interface>
		<cc:attribute name="value" type="java.util.Date" required="true" />
	</cc:interface>

	<cc:implementation>
		<span id="#{cc.clientId}" class="comp-date">
			Time: #{cc.attrs.value.time}
		</span>
	</cc:implementation>

</ui:component>
```

## 6) Sample bean

```
package org.primefaces.test;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import org.primefaces.model.TreeNode;
import org.primefaces.model.DefaultTreeNode;

@Named
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }    

    private TreeNode dateTree;

    public TreeNode getDateTree() {
		if (dateTree == null) {
			dateTree = new DefaultTreeNode();
			new DefaultTreeNode(new Date(), dateTree);
			new DefaultTreeNode(new Date(), dateTree);
		}
        return dateTree;
    }

}
```

## Also necessary: disable partial state saving in web.xml:

```
	<context-param>
		<param-name>javax.faces.PARTIAL_STATE_SAVING</param-name>
		<param-value>false</param-value>
	</context-param>
```

### PR DESCRIPTION
**Pull request by VsevolodGolovanov**

### CODE REVIEW

**Comment by tandraschko** [comment]
I will check it after 8.0 release

**Comment by tandraschko** [comment]
@VsevolodGolovanov could you please fix conflicts? i would like to apply it next week or on weekend

**Comment by VsevolodGolovanov** [comment]
Verified that the issue is still there in the current 9.0-SNAPSHOT, merged, built, verified that the fix works.

**Comment by tandraschko** [comment]
Thanks!

**Pull request merged**
