### PR TITLE
Fix #5817: JQMIGRATE: Use of number-typed values is deprecated in CSS

### LINKED ISSUE #5817: JS: Remediate all JQMIGRATE deprecations
I think the JQMigrate plugin needs to be run against the showcase and all deprecation warnings should be addressed.

https://github.com/jquery/jquery-migrate

A lot of these deprecation are being removed in Jquery 4.0 so fixing them now will alleviate pain later.

- [x] jQuery.fn.bind()/unbind() are deprecated
- [x] jQuery.isArray is deprecated
- [x] jQuery.isFunction is deprecated
- [x] jQuery.trim is deprecated; use String.prototype.trim 
- [x] Use of number-typed values is deprecated in CSS
- [x] jQuery.fn.click() event shorthand is deprecated, use `on` and `trigger` instead.  Also includes blur, focus, focusin, focusout, resize, scroll, dblclick, mousedown, mouseup, mousemove, mouseover, mouseout, mouseenter, mouseleave, change, select, submit, keydown, keypress, keyup, and contextmenu

### PR DESCRIPTION
**Pull request by melloware**
JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css
Cause: In past versions, when a number-typed value was passed to `.css()` jQuery converted it to a string and added "px" to the end. As the CSS standard has evolved, an increasingly large set of CSS properties now accept values that are unitless numbers, where this behavior is incorrect. It has become impractical to manage these exceptions in the jQuery.cssNumber object. In addition, some CSS properties like line-height can accept both a bare number 2 or a pixel value 2px. jQuery cannot know the correct way to interpret `$.css("line-height", 2)` and currently treats it as "2px".

**Solution:** Always pass string values to `.css()`, and explicitly add units where required. For example, use `$.css("line-height", "2")` to specify 200% of the current line height or `$.css("line-height", "2px")` to specify pixels. When the numeric value is in a variable, ensure the value is converted to string, e.g. `$.css("line-height", String(height))` and `$.css("line-height", height+"px")`.

### CODE REVIEW

**Comment by tandraschko** [comment]
ok, no problem for dimensions like height and width. But really also for zindex?

**Comment by melloware** [comment]
Yep zIndex and Opacity are all on the list.

**Comment by tandraschko** [comment]
should we use `new String` instead `String`? looks more java-like IMO

**Comment by GedMarc** [comment]
On layout I'm hitting this problem where the assignment to string is breaking the calculations used, i could get rid of most of them - but one or two, i simply cannot change from number to string, screws up the math with javascript

I'm not sure how/what they want us to do as a replacement

**Comment by melloware** [comment]
@GedMarc can you give an example?  So for example you can just change `1` to `String(1)` as the old way use to convert to pixels so that one you would have to give it your units like `1px`.

**Comment by melloware** [comment]
> should we use `new String` instead `String`? looks more java-like IMO

@tandraschko You peeked my interest in this so I researched it and I think we are doing the correct thing with `String()` vs `new String()` based on this: https://stackoverflow.com/a/50082325/502366

**Comment by GedMarc** [comment]
@melloware 

So i'm setting css() using an object that has an number as a variable --

```
obj : {
var1: 0
}
```
If i pass the object into the css, you get the warning because of var1.
If you change var 1 to string, obviously math won't work in JavaScript

So what is meant to be the replacement? :)

**Comment by melloware** [comment]
I guess I am confused on what math is being done after it’s passed to .css()???  Once you have handed it off isn’t that the end of it.  Can you give me a more elaborate example?

**Comment by tandraschko** [comment]
where is it in https://jquery.com/upgrade-guide/3.0/ ?

**Comment by melloware** [comment]
Unfortunately @tandraschko I have noticed Jquery has stopped updating there documentation or site examples.  That Upgrade guide is for 3.0 but they never put one out for 3.2, 3.3, 3.4.  

They did create one for 3.5 however though: https://jquery.com/upgrade-guide/3.5/

However the JQMigrate 3.3 plugin has it documented here:
https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-use-of-number-typed-values-is-deprecated-in-jqueryfncss

And if you run the migrate plugin you will see his warnings pop up.

**Comment by tandraschko** [comment]
i see
+1 then

**Pull request merged**
