### PR TITLE
Fix #9941: Overlays hide tooltips on show/hide

### LINKED ISSUE #9941: Overlays: Hide tooltips on show/hide
### Describe the bug

When a tooltip (on a button) is shown, and you open a modal dialog (via this button), the tooltip remains indefinitely visible.
Especially within a table, you could end up with "dead" tooltips all over the place.
The monkey patch:
https://github.com/e-Contract/enterprise-jsf/blob/master/ejsf-taglib/src/main/resources/META-INF/resources/ejsf/monkey-patch.js
fixes this issue by hiding all tooltips when dialogs open/close.
Demonstrator is available at:
https://demo.e-contract.be/ejsf-demo/monkey-patch.xhtml

Maybe this behavior could be included within `Dialog` and `ConfirmDialog` per default?

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8

### Browser(s)

_No response_

### LINKED ISSUE #10100: Dialog: Primefaces tooltip gets behind dialog on every click on dialog
### Describe the bug

Hi , could you check this bug please if it's fixed. The thing is when Primefaces dialog is opened, whenever I click on dialog property "z-index" is getting incremented and it lefts hover component behind dialog component.

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

None

### PrimeFaces version

12.0

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

_No response_

### Java version

11.0.11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #9941: Overlays hide tooltips on show/hide
Fix #10100: Hide tooltips on dialog focus

Adds base `show()` and `hide()` in OverlayWidget

### CODE REVIEW

**Comment by melloware** [comment]
@blutorange need an assist here fixing the JSDoc for this one.  I added new superclass methods for `show` and hide` but its choking on this ConfirmPopup one.

**Comment by blutorange** [comment]
Well, judging from the error message:

```
[INFO] [tsDiagnosticsError] at <unknown> (/home/runner/work/primefaces/primefaces/primefaces/target/type-declaration/PrimeFaces.d.ts:5422:18)
[INFO] Property 'hide' in type 'ConfirmPopup<TCfg>' is not assignable to the same property in base type 'DynamicOverlayWidget<TCfg>'.
[INFO]   Type '(callback: HideCallback) => void' is not assignable to type '() => void'.
```

* `ConfirmPopup` extends from `DynamicOverlayWidget`
* So it's legal for somebody somebody to assign a confirm popup to a variable of type overlay widget, e.g.
   > const widget: DynamicOverlayWidget = new ConfirmPopup();
* Thus it's legal for them to call `widget.hide()`. But that will throw since `ConfirmPopup`  expects one parameter `callback`.

Or in other words, it's not legal the same way as the following is not legal Java code:

```java
class OverlayWidget { public void hide() {} }
class Popup extends OverlayWidget {
  @Override
  public void hide(Object callback) {} // <-- compile error
} 
```

Since we probably don't want to change `DynamicOverlayWidget` as that class might be used by other people already, you could make the `callback` parameter optional:

```js
    /**
     * Hides the popup.
     * @override
     * @param {PrimeFaces.widget.ConfirmPopup.HideCallback} [callback] Optional callback that is invoked after this popup was closed.
     */
    hide: function(callback) { 
     if (callback) { callback(); }
    }
```

**Comment by melloware** [comment]
Thank you!  Didn't realize the brackets make the param optional!

**Comment by melloware** [comment]
OK worked with Mert on a better solution.

**Pull request closed without merging**
