### PR TITLE
Add partialUpdate attribute to DataTable

### PR DESCRIPTION
**Pull request by mertsincan**
For this issue;
https://github.com/primefaces/primefaces/issues/1178
https://github.com/primefaces/primefaces/issues/1715

| Name | Default | Type | Description
| ---| --- | --- | --- |
| partialUpdate | true | Boolean  | When disabled, it updates the whole table instead of updating a specific field such as body element in the client requests of the dataTable. Default is true.

**Note:** When disabled, it updates the whole table for Sorting, Filtering, and Page events.

**Test codes;**
<details>
<summary>TestModel.java</summary>

```
package org.primefaces.test;

import java.io.Serializable;

public class TestModel implements Serializable {
    
    private static final long serialVersionUID = 1L;

    public int id;
    public String str;
    public int number;

    public TestModel(int id, String str, int number) {
        this.id = id;
        this.str = str;
        this.number = number;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getStr() {
        return str;
    }

    public void setStr(String str) {
        this.str = str;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 19 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TestModel other = (TestModel) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }
}
```
</details>

<details>
<summary>TestView.java</summary>

```
package org.primefaces.test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestView implements Serializable {

    private List<TestModel> testModels;
    private List<TestModel> filteredTestModels;


    @PostConstruct
    public void init() {
        testModels = new ArrayList<>();

        testModels.add(new TestModel(1, "a", 1));
        testModels.add(new TestModel(2, "b", 2));
        testModels.add(new TestModel(3, "c", 3));
        testModels.add(new TestModel(4, "d", 4));
        testModels.add(new TestModel(5, "e", 5));
        testModels.add(new TestModel(6, "f", 6));
        testModels.add(new TestModel(7, "g", 7));
        testModels.add(new TestModel(8, "h", 8));
        testModels.add(new TestModel(9, "k", 9));
        testModels.add(new TestModel(10, "l", 10));
        testModels.add(new TestModel(11, "m", 11));
    }

    public List<TestModel> getTestModels() {
        return testModels;
    }

    public void setTestModels(List<TestModel> testModels) {
        this.testModels = testModels;
    }

    public List<TestModel> getFilteredTestModels() {
        return filteredTestModels;
    }

    public void setFilteredTestModels(List<TestModel> filteredTestModels) {
        this.filteredTestModels = filteredTestModels;
    }
}
```
</details>

<details>
<summary>test.xhtml</summary>

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="frmTest">
            <p:dataTable widgetVar="testDT" var="testModel" value="#{testView.testModels}" reflow="true" rows="5" partialUpdate="false"
                         paginatorTemplate="{NumberOfEntries} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         id="testDTFilter" filteredValue="#{testView.filteredTestModels}" paginator="true" paginatorPosition="top">
                
                <f:facet name="{NumberOfEntries}" >
                    <h:outputFormat value="Filtered {0} of {1} entries">
                        <f:param value="#{testView.filteredTestModels == null or testView.filteredTestModels.size() == testView.testModels.size() ? 0 : testView.filteredTestModels.size()}" />
                        <f:param value="#{testView.testModels.size()}" />
                    </h:outputFormat>
                </f:facet>
                
                <p:column headerText="Id" sortBy="#{testModel.id}" filterBy="#{testModel.id}">
                    <h:outputText value="#{testModel.id}"/>
                </p:column>
                <p:column headerText="Str" sortBy="#{testModel.str}" filterBy="#{testModel.str}">
                    <h:outputText value="#{testModel.str}"/>
                </p:column>
                <p:column headerText="Number" sortBy="#{testModel.number}" filterBy="#{testModel.number}">
                    <h:outputText value="#{testModel.number}"/>
                </p:column>
                <f:facet name="footer">
                    <div style="text-align: right">
                       Total Number: #{testView.filteredTestModels == null ? testView.testModels.stream().map(item->item.number).sum() : (testView.filteredTestModels.size() > 0 ? testView.filteredTestModels.stream().map(item->item.number).sum() : 0)} 
                    </div>
                </f:facet>
            </p:dataTable>
        </h:form>
    </h:body>
</html>
```
</details>

**Test video;**
https://www.dropbox.com/s/mc09itd4sbderfe/datatable_autoUpdate_test.mov?dl=0

### CODE REVIEW

**Comment by mertsincan** [comment]
@tandraschko @melloware @Rapster @sqores WDYT?

**Comment by tandraschko** [comment]
i would like to see another name for this feature as its completely different compared to p:autoUpdate / the old autoUpdate attribute on panelGrid.

**Comment by melloware** [comment]
I like this change too but I agree with Thomas that `autoUpdate` might imply something its not. how about `autoRender` or `autoRerender`??

**Comment by mertsincan** [comment]
@tandraschko +1 ;) When it's ok for everyone, I'll change its name. Do you have any other feedback? :D

**Comment by Rapster** [comment]
Instead of introducing a new attribute, why not making it as a new behavior? Meaning, from now on, it will update the whole table?

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
wheter autoUpdate nor autoRender/autoReRender are correct.
The new flag means that the whole table is rendered, not just the "data" part (rows/columns)

Does it make sense to make it the default behavior? Not sure here. It may flicker more and its not required in all cases.

I'm also not sure about this line:
table.setValue(null);

please add some comments mert :P

**Comment by tandraschko** [comment]
we may also think about making it a attribute to p:ajax, like we did for skipChildren. 
skipChildren isnt used in all components, neither this new attribute would be used in all components.
But it would be great to have it configurable for each event, not global in DT.

Maybe something like "p:ajax updateDataOnly=true|false"

**Comment by Rapster** [comment]
I agree it doesn't hurt, but giving a lot of options to a component makes it harder to maintain and a more cumbersome... If you look at the corresponding issues, there are defects, I think most of users expect this to be the behavior.

Regarding updateDataOnly, makes only sense for data components don't you think?

Yup please comment code, specially on datatable, not sure I follow why so much java code is modified but I'm probably missing something

**Comment by mertsincan** [comment]
> Instead of introducing a new attribute, why not making it as a new behavior? Meaning, from now on, it will update the whole table?

@Rapster I think it would be better not to make such a change by default for now. As Cagatay said, innovations will be made in the DataTable in future versions. After these innovations, it would be better if we talk about this issue together and decide.
Example: https://primefaces.org/primeng/showcase/#/table/filter :D 

> I'm also not sure about this line:
> table.setValue(null);

@tandraschko it is the most important line of all code :D Since all states are rendered on the server side, when we delete the filter value from input field, a sort operation is performed according to the values that the filter has previously changed. Therefore, I need to reset the value. The filterFeature interferes too much with the value.

**Comment by mertsincan** [comment]
> we may also think about making it a attribute to p:ajax, like we did for skipChildren.
- Yes, but for such issues, Most users don't want to use <p: ajax> events in each operation to update the table. So updateDataOnly="true|false" may be a different option.

Exp;
```
<p:dataTable autoRender="true"> // for filter, page and sort

OR

<p:dataTable>
    <p:ajax event="filter" updateDataOnly="false" /> // for filter
    <p:ajax event="sort" updateDataOnly="false" /> // for sort
    <p:ajax event="page" updateDataOnly="false" /> // for page
</p:dataTable>
```

**Comment by tandraschko** [comment]
please dont call it autoRender, it currently does "autoRender of data". The new flag switches to "autoRender of whole component".
It also doesnt make sense to add it on p:ajax and p:dataTable. Either we decide to make it a global dataTable option or make it configurable for each event. Not both.

> Yes, but for such issues, Most users don't want to use <p: ajax> events in each operation to update the table. So updateDataOnly="true|false" may be a different option.

Nope, its exactly the same option, just global. Thats always our way like process on p:ajax. Default is @this, if someone needs to configure it, you can add p:ajax to overwrite to the default. Its the same with this new config.



We could even call it something like "partial component rendering".
Per default, AJAX (doesnt matter if p or f), always renders the whole component. 
In some components we implemented "partial rendering" of a component. DataTable just renders the "data / rows / columns" and replaces only this parts in the DOM.
We have this already in MANY components. Sidebar loads only the content, accordion or tabView only loads the new tab content and replaces only this tab-content in the DOM.
Its a global feature, we already have it since ages.

**Comment by mertsincan** [comment]
Thank you very much for your feedback. I think "partial component rendering" word sounds good. For now, however, we can add it to the dataTable as an attribute named "autoRerenderComponent". Based on feedback from users and tests, we can make an improvement as suggested by you and remove the "autoRerenderComponent" attribute if necessary. For now, it would be more accurate to detect the effects of this feature on users' applications. Of course, your suggestion is more accurate as it covers all components for such problems.

@tandraschko Can you open a new issue about your suggestion? Thanks a lot!

**Comment by tandraschko** [comment]
@mertsincan Im ok with the attribute for now as we can move the flag later to p:ajax if required.
BUt i would like to propose something like following names ("update" or "render"):
1) partialUpdate (my favorite; with true as default which means the current behavior)
2) updateDataOnly
3) updateWholeComponent

autoRerenderComponent doesnt really fit for 100% at it already does auto-rendering but just for the data, not the whole compnent.

**Comment by mertsincan** [comment]
Nice!! partialUpdate +1 ;)

**Pull request merged**
