### PR TITLE
PF-2383 Add p:ajax support to p:textEditor

### PR DESCRIPTION
**Pull request by brainlag**
This hooks up all basic events for p:ajax inside a p:textEditor. See #2383.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
I'm not sure if that much JS is really required.
If you check InputText e.g. than there is no additional JS required for the event handling.
The reason for that is, that the events (e.g. oninput) is directly rendered on the input element instead of passing it to script as behavior script.
Isn't that possible with qill, too?

**Comment by brainlag** [comment]
I didn't know how this should work and this worked for me. But after looking up your suggestion I think I could get ride of the javascript for the common events. But blur, focus, change and select will need javascript.

**Comment by tandraschko** [comment]
why? i think these are common JS events - only select will be a custom event?
I would just try to add onblur/onfocus/onchange on the quill input and check if it works automatically

**Comment by brainlag** [comment]
Quill does not use a input element, it uses a div with contenteditable which doesn't have native focus events.

**Comment by tandraschko** [comment]
Ahh i see, yep, than it's ok.

**Comment by tandraschko** [comment]
I think we can leave your PR as it it - Quill seems a little bit special, so it's ok IMO.
Will apply it later :)

**Comment by mauromol** [comment]
I'd suggest you add this to the documentation. Thank you!

**Pull request merged**
