### PR TITLE
#3324 MultiViewState optionally per ClientWindow instead of session

### LINKED ISSUE #3324: DataTable: Allow to store TableState for multiViewState in another scopes
## 1) Environment
- PrimeFaces version: 6.2 RC2

## 2) Expected behavior
I would like to have a possibility to use another scope than session scope for storing TableStates.  Would it be possible to allow to define own inplementation of let's say "storage provider" with methods?

org.primefaces.PrimeFaces.**clearTableStates()**
org.primefaces.PrimeFaces.**clearTableState(String key)**
org.primefaces.component.datatable.DataTable.**getTableState(boolean create)**

Using session scope, consumer has to handle clearing of the map in many cases. In our app we use other scopes like Spring's Conversation or Flow scope which we could use to store data for this functionality and they would be cleared automatically when not needed.
Another issue is multi-window usage, where the same table shares it's state with another browser window.

### PR DESCRIPTION
**Pull request by christophs78**
I need to add at least some documentation.

Showcase-PR: https://github.com/primefaces/primefaces-showcase/pull/164

Is there a need to add some cleanup-code for clientWindowMap and remove "old" clientWindows?
IMO the amout of data is quite small so it should not be necessary.

### CODE REVIEW

**Comment by tandraschko** [comment]
1) i would use ConcurrentHashMaps
2) use LangUtils#isBlank
3) update documentation
4) the context-param should have 2 options: session, client-window (all our options are lower case)
5) rename getMVSSessionMap to getMVSStorate or similar

otherwise + 1 :)

**Comment by christophs78** [comment]
Good points. Done.
Switched to ConcurrentHashMaps for both Maps. Ok?
Adding the new option to configuration.md enough or should we add an explicit multiviewstate.md?

**Comment by tandraschko** [comment]
the docu still has `client_window` isntead of `client-window`

it would be great if you can make a global docu about multiviewstate

**Comment by tandraschko** [comment]
looks good, thanks!

**Pull request merged**
