### PR TITLE
CI - switch back to Chrome

### PR DESCRIPTION
**Pull request by christophs78**
... because it´s way faster than Firefox

### CODE REVIEW

**Comment by tandraschko** [comment]
shoudlnt dialog.getYesButton() guard itself ajax?

**Comment by tandraschko** [comment]
see CommandButton#click

**Comment by christophs78** [comment]
> shoudlnt dialog.getYesButton() guard itself ajax?

i thougth so too until we had
```
Error:  Errors: 
Error:    ConfirmDialog001Test.testConfirmYes:119 » StaleElementReference stale element ...
```

When i debug this following code-path is selected:
image

**Comment by tandraschko** [comment]
Doesnt it hit the guardAjax line?

**Comment by christophs78** [comment]
Yep. He does not walk into guardAjax.
image

**Comment by christophs78** [comment]
Maybe somehow related to the way `p:confirm` works.

**Comment by tandraschko** [comment]
Maybe, yes
Thats a missing piece in pfselenium then, we must not workaround this in the tests

**Comment by christophs78** [comment]
You are right. What do you about my last commit which tries to fix this for PF Selenium?

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
Ist a confirm always Ajax?

**Comment by christophs78** [comment]
> Ist a confirm always Ajax?

Nope.

Figuring out whether it is ajax or not is at least not easy. The button marked with red arrows needs to know how the button marked with green arrows is configured.
image

The easier thing is to handle this on the integration-test-side, what we had before.

**Comment by tandraschko** [comment]
Yep i see

**Comment by tandraschko** [comment]
would you like to switch back to guard in our tests?

**Pull request merged**
