### PR TITLE
#12915: CSP Integration Test

### LINKED ISSUE #12915: Scripts / InitScripts rendered in HeadRenderer#encodeInitScripts and BodyRenderer#encodeOnloadScripts requires $
i think we should do something like:

```
var somegeneratedfunctionname() {initscripts...};
if (window.$) { 
    $(function(){ somegeneratedfunctionname(); });
} else if (document.readyState === "complete") {
    somegeneratedfunctionname();
} else {
    document.addEventListener("DOMContentLoaded", somegeneratedfunctionname);
}
```

### PR DESCRIPTION
**Pull request by melloware**
Fix #12915: CSP Integration Test

@tandraschko started this integration test expecting it to fail but its not.  Can you give me the exact steps for the scenario. I know it's a page with no PF components on it.  Let me know and I will update this test.

### CODE REVIEW

**Comment by tandraschko** [comment]
Not sure 
Did you try tge primefaces-test project?

**Comment by melloware** [comment]
Its because MOVE_SCRIPTS_TO_BOTTOM prevents this error in the console.

Script generated doesn't use `$` because its wrapped in `if`

```js
var pf = window.PrimeFaces;
if (pf) {
  pf.settings.locale = 'en_US';
  pf.settings.viewId = '/test.xhtml';
  pf.settings.contextPath = '';
  pf.settings.cookiesSecure = false;
  pf.settings.cookiesSameSite = 'Strict';
  pf.settings.validateEmptyFields = false;
  pf.settings.considerEmptyStringNull = false;
};
if (pf) {
  PrimeFaces.csp.init('NDBkNWJhMDgtNjlhMS00M2Q0LTllNTAtNmRiNjU5M2I2ZjNi');
};
document.getElementById('c95b8e6f-d203-42a1-9e15-82346d59771b').remove();
```

**Comment by melloware** [comment]
After

```js
if (window.PrimeFaces) {
  PrimeFaces.settings.locale = 'en_US';
  PrimeFaces.settings.viewId = '/test.xhtml';
  PrimeFaces.settings.contextPath = '';
  PrimeFaces.settings.cookiesSecure = false;
  PrimeFaces.settings.cookiesSameSite = 'Strict';
  PrimeFaces.settings.validateEmptyFields = false;
  PrimeFaces.settings.considerEmptyStringNull = false;
}
var pfInitScripts = function() {
  if (window.PrimeFaces) {
    PrimeFaces.csp.init('ODQ2NmU5MWEtZThkMy00YjE2LTkyMTUtNDAzNTM5ZTAyODEz');
  };
};
if (window.$) {
  $(function() {
    pfInitScripts();
  });
} else if (document.readyState === "complete") {
  pfInitScripts();
} else {
  document.addEventListener("DOMContentLoaded", pfInitScripts);
}
```

**Comment by tandraschko** [comment]
why is the PrimeFaces.settings.locale stuff duplicated?

**Comment by melloware** [comment]
Sorry its not that was a cut  and paste issue on my end!  I updated it above

**Comment by tandraschko** [comment]
looks good for me

**Pull request merged**
