### PR TITLE
#7201 Corrected rendering menu elements (children)

### PR DESCRIPTION
**Pull request by wal-jan**

### CODE REVIEW

**Comment by tandraschko** [comment]
Please explain it
Actually we should just skip non-MenuItem, Not sure why you switched all to Object

**Comment by wal-jan** [comment]
_AbstractMenu#getElements()_ returns either _List&lt;org.primefaces.model.menu.MenuElement&gt;_ in case of menu has a model or _List&lt;javax.faxces.component.UIComponent&gt;_ otherwise. The common parent is List&lt;Object&gt;. Just to avoid class cast exceptions in subsequent foreach loops.

As far I can see the return value of _AbstractMenu#getElements()_ may also be _null_ so I added null checks.

**Comment by melloware** [comment]
I think there is an easier way to do this.  Let me me investigate.

**Comment by melloware** [comment]
See my PR: https://github.com/primefaces/primefaces/pull/7205/files

**Pull request closed without merging**
