### PR TITLE
DataTable: support of columns in colgroup

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by melloware** [comment]
I think the most only reason we did this is a user did it and we added it so that we could make sure the exporter exported correctly?  But I will have to look through the commits. 

But either way I agree we shouldn't be showing users a bad way to do something.

**Comment by Rapster** [comment]
I tink you're refering to this https://github.com/primefaces/primefaces/issues/9179 I'll give it a try

**Comment by Rapster** [comment]
Exporters works fine with p:columns and colgroup

**Comment by melloware** [comment]
HA yes that was the ticket i was referring to!

**Pull request merged**
