### PR TITLE
Fix #12352: Spinner allow min+required to be NULL

### LINKED ISSUE #12352: Spinner: required+min does not allow a NULL start value
### Describe the bug

Reported by one of my customers.  They need to be able to specify `min="0" max="100" required="true"` and FORCE the user to pick a value.  Right now that is not possible.

here is the scenario:

```xml
<p:spinner id="allowsNull" value="#{spinnerView.number1}" required="true" max="100" />

<p:spinner id="notAllowsNull" value="#{spinnerView.number1}" required="true" min="0" max="100"/>
```

Renders like this:
image

The reason is this code in the spinner.js widget has been there for years but to me this is not correct behavior.

```js
if(isNaN(parsedValue)) {
            if(PrimeFaces.trim(value) === '' && this.cfg.min !== undefined && this.cfg.required) {
                parsedValue = this.cfg.min;
            } else {
                parsedValue = null;
            }
        }
```

Basically it defaults to the `min` if `required="true"` the required becomes moot and a user can submit the page without having to select a value.

### Reproducer

[pf-spinner-required.zip](https://github.com/user-attachments/files/16428388/pf-spinner-required.zip)

### Expected behavior

The spinner should be allowed to be NULL if using a `min` and `required`

### PrimeFaces edition

Community

### PrimeFaces version

14.0.3

### Theme

ALL

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #12352: Spinner allow min+required to be NULL

Neeed to update SASS theme to make #11681 more specific

### CODE REVIEW

**Review by jepsar — APPROVED** [review]

**Comment by tandraschko** [comment]
what are those theme changes?

**Comment by melloware** [comment]
@tandraschko we added this in 15.0: https://github.com/primefaces/primefaces/issues/11681

Well that theme is not specific enough so the Spinner "required" red highlighting was not showing up because that other style was "more specific".  I am going to do more testing today.

**Comment by tandraschko** [comment]
shouldnt we make a new issue then for better tracking?

**Comment by melloware** [comment]
OK i think i will reopen https://github.com/primefaces/primefaces/issues/11681 since its related to that 15.0.0 ticket.

**Comment by tandraschko** [comment]
code looks good, +1 if well tested

**Pull request merged**
