### PR TITLE
Use OpenPdf 1.0.5 as dependency instead of iText 2.1.7.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by melloware** [comment]
Linking to:  https://github.com/primefaces/primefaces/issues/2363

**Comment by tandraschko** [comment]
Not sure about this one.
We could change it but the user must still import it as we only set it to provided.

So we could change it but not necessary.
It would be better to mention this in the docu.

**Comment by ghost** [comment]
Why not both? Update docs, and pom file.

**Comment by tandraschko** [comment]
because the API is the same and everybody could fork it and provide "yet another bugfix fork of the old lowagie"

I think the only good solution for the future is to switch to other frameworks like pdfbox (does it support the same features?)

**Comment by danteCarvalho** [comment]
For some reason, empty encoding="" works for me,i am using itext 2.1.7

**Comment by tandraschko** [comment]
Will close it for now but you can create a issue, so we can check it in future again if its worth to do a hard switch to openpdf.
As i said, currently the user can use both as the API is the same.

**Pull request closed without merging**
