### PR TITLE
#4054 fix default label of SelectCheckboxMenu

### PR DESCRIPTION
**Pull request by OBreidenbach**
#4054

### CODE REVIEW

**Review by melloware — APPROVED** [review]
After reviewing this component it is the right fix because the Menu itself does not have an "escape" proper the Label can never be HTML in its current state.

**Comment by tandraschko** [comment]
It would be great If you can check the js, too. We often had checks for nbsp

**Comment by melloware** [comment]
I checked the JS and we are OK on this one.  I believe this to be the correct fix.

**Comment by tandraschko** [comment]
As i said, there is a JS logic for &nbsp:
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/forms/forms.selectcheckboxmenu.js#L181

**Comment by OBreidenbach** [comment]
This code is in the renderItem method in the for loop for the items. So this logic is checking the label of an item not the label that is shown when the menu is closed.

**Pull request merged**
