### PR TITLE
PrimeX use StyleClassBuilder

### PR DESCRIPTION
**Pull request by melloware**
Discussed with @sqores on Discord this cleans up all the String concat += stuff and makes the code much cleaner

### CODE REVIEW

**Review by buunsal — APPROVED** [review]

**Comment by tandraschko** [comment]
why Objects.equals(avatar.getShape(), "circle")?
"circle".equals(avater.getShape()) is shorter and widely used as pattern

**Comment by melloware** [comment]
I use ObjectEquals because it prevents NULL checking.  A lot of places if you look in the review there was `if != null and if shape.equals("circle") etc.  This allows the boolean to always evaluate with never having to do NULL checking or assume one side is not null.

but you are right I could do "circle.equals() but for some reason Objects.equals looks better to me.

I can switch them all if you want?

**Comment by tandraschko** [comment]
yeah, `avater.getShape().equals("circle")` would a require a null check but `"circle".equals(avater.getShape())` does not.
in the past there were checkstyle/PMD rules for this: https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/EqualsAvoidNullCheck.html

i would use this pattern everywhere and try to introduce this rule; for other types only Object.equals is possible ofc

**Comment by melloware** [comment]
OK I flipped them all not to use `Objects.equals`

**Pull request merged**
