### PR TITLE
Fix #3034 / #506: FileUpload filename resolution.

### LINKED ISSUE #3034: FileUpload: Issue with filenames containing semicolon or double quotes
Method NativeUploadedFile.resolveFilename splits by ';' and replaces '"' in filename param. It leads to problems with getting name of uploaded file.

## 1) Environment
- PrimeFaces version: 6.1.6

## 2) Expected behavior
All file names are processed correctly

## 3) Actual behavior
* Name **'File;Import.xlsx'** is extracted as **'File'**
* Name **'File"Import.xlsx'** is extracted as **'FileImport.xlsx'**

## 4) Steps to reproduce
1. Create a fileUpload component.
1. Add fileUploadListener.
1. Try to get name of file from FileUploadEvent.

## 5) Sample XHTML
```
  <p:fileUpload fileUploadListener="#{fileHandler.handleFileUpload}"/>
```

## 6) Sample bean
```
public void handleFileUpload(FileUploadEvent event) throws IOException {
        UploadedFile uploadedFile = event.getFile();
        System.out.println(uploadedFile.getFileName());
}
```

### PR DESCRIPTION
**Pull request by melloware**
- uses only native Java code
- provides test cases for all scenarios discussed
- seems to be future proofed as well

### CODE REVIEW

**Comment by jxmai** [comment]
Bug: If the uploaded file name is `\\\\`, the output will be `\\`

**Comment by melloware** [comment]
OK let me add a test case.  So you are saying file name of `hello\\\\world.png` is coming out `hello\\.png` ?

Is that correct though because that is Java escaping the chars and if the file was uploaded like that it would have come in with 8 slashes right?

**Comment by jxmai** [comment]
> So you are saying file name of hello\\\\world.png is coming out hello\\.png ?

Exactly.

**Comment by jxmai** [comment]
Input from file System: `hello\\\\world.png`

content-disposition input:  `form-data; name="j_idt6:j_idt7"; filename="hello\\\\world.png"`

output: `hello\\world.png`

**Comment by melloware** [comment]
Well that goes against what the code above was saying that a file name with a quote in it comes in escaped like `\"`  wouldn't that mean all slashes get escaped?  So `hello\\\\world.png` should come in like `form-data; name="j_idt6:j_idt7"; filename="hello\\\\\\\\world.png"` unless their JEE6 escaping is not escaping correctly?

because `\\` in Java becomes `\` no matter what?

**Comment by jxmai** [comment]
and a fileName like `\t\b\t\t` can crash the algorithm.

```
INFO: javax.faces.FacesException: Content-Disposition filename has unknown escape character: 't'.
javax.faces.FacesException: Content-Disposition filename has unknown escape character: 't'.
	at org.primefaces.model.NativeUploadedFile.getContentDispositionFileName(NativeUploadedFile.java:161)
	at org.primefaces.model.NativeUploadedFile.resolveFilename(NativeUploadedFile.java:104)
	at org.primefaces.model.NativeUploadedFile.<init>(NativeUploadedFile.java:41)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decodeAdvanced(NativeFileUploadDecoder.java:67)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decode(NativeFileUploadDecoder.java:38)
	at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:51)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:831)
	at javax.faces.component.UIInput.decode(UIInput.java:771)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1225)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:676)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:573)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:927)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
```


>  So hello\\\\world.png should come in like form-data; name="j_idt6:j_idt7"; filename="hello\\\\\\\\world.png"

I only tested through the sample, and that's what I observed.

**Comment by melloware** [comment]
OK so the JEE6 escaping is not escaping all slashes.  It is only escaping when there is a double quote in the file name?

**Comment by jxmai** [comment]
I think so :+1:  Maybe the fix will be to duplicate the `\` during the loop

(side note:  backslash as a part of a file name is prohibited in windows, but it is valid in Unix like system )

**Comment by melloware** [comment]
OK try that commit I add two more test cases for your two scenarios above too.

**Comment by jxmai** [comment]
File Name `\\\\` results in 

```
SEVERE: javax.faces.FacesException: Content-Disposition filename has unclosed quote.
	at org.primefaces.model.NativeUploadedFile.getContentDispositionFileName(NativeUploadedFile.java:163)
	at org.primefaces.model.NativeUploadedFile.resolveFilename(NativeUploadedFile.java:103)
	at org.primefaces.model.NativeUploadedFile.<init>(NativeUploadedFile.java:41)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decodeAdvanced(NativeFileUploadDecoder.java:67)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decode(NativeFileUploadDecoder.java:38)
	at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:51)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:831)
	at javax.faces.component.UIInput.decode(UIInput.java:771)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1225)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:676)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:573)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:927)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

---

`\t\b\t\t`  (passed)

`hello\\\\world.png`  (passed)

**Comment by jxmai** [comment]
The same bug can be replicated by the fileName : `\`

**Comment by melloware** [comment]
OK submitted another fix.  Are we sure even in unix that `\` is a valid file name?

Can you do a debug print of the Content-Disposition when you send in just a `\` file name?

**Comment by jxmai** [comment]
First of all, `\` was not fixed by the latest commit (up to: https://github.com/primefaces/primefaces/pull/3043/commits/3a7fcdd19aad1faabee8886c0b0707f39091d4bf)

`form-data; name="j_idt6:j_idt7"; filename="\"`


```
INFO: javax.faces.FacesException: Content-Disposition filename has unclosed quote.
javax.faces.FacesException: Content-Disposition filename has unclosed quote.
	at org.primefaces.model.NativeUploadedFile.getContentDispositionFileName(NativeUploadedFile.java:164)
	at org.primefaces.model.NativeUploadedFile.resolveFilename(NativeUploadedFile.java:104)
	at org.primefaces.model.NativeUploadedFile.<init>(NativeUploadedFile.java:41)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decodeAdvanced(NativeFileUploadDecoder.java:67)
	at org.primefaces.component.fileupload.NativeFileUploadDecoder.decode(NativeFileUploadDecoder.java:38)
	at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:51)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:831)
	at javax.faces.component.UIInput.decode(UIInput.java:771)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1225)
	at javax.faces.component.UIInput.processDecodes(UIInput.java:676)
```

**Comment by jxmai** [comment]
> Are we sure even in unix that "" is a valid file name?

Is it empty string ? or `""`

empty string is not allowed

`""` is valid in unix like OS (`form-data; name="j_idt6:j_idt7"; filename="%22%22"`)

The output is OK: `""` (passed)

**Comment by jxmai** [comment]
> OK submitted another fix. Are we sure even in unix that \ is a valid file name?

Yes, I am pretty sure it is valid. that's why I created and uploaded that file.

**Comment by melloware** [comment]
Added test cases for
`\`
`\\\\`
`%22%22`

**Comment by jxmai** [comment]
File Name: `\\\` results in 

```
SEVERE: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.String.charAt(String.java:658)
	at org.apache.tomcat.util.http.parser.HttpParser.unquote(HttpParser.java:135)
	at org.apache.catalina.core.ApplicationPart.getSubmittedFileName(ApplicationPart.java:152)
	at org.apache.catalina.connector.Request.parseParts(Request.java:2871)
	at org.apache.catalina.connector.Request.parseParameters(Request.java:3211)
	at org.apache.catalina.connector.Request.getParameterNames(Request.java:1183)
	at org.apache.catalina.connector.RequestFacade.getParameterNames(RequestFacade.java:398)
	at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:89)
	at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:62)
	at java.util.Collections$UnmodifiableMap.get(Collections.java:1454)
	at com.sun.faces.application.view.MultiViewHandler.calculateRenderKitId(MultiViewHandler.java:222)
	at com.sun.faces.context.FacesContextImpl.isPostback(FacesContextImpl.java:212)
	at javax.faces.context.FacesContextWrapper.isPostback(FacesContextWrapper.java:461)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:193)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:121)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by tandraschko** [comment]
Isnt there a method in commons fileupload we can copy? It should be battle tested ;)

**Comment by melloware** [comment]
@tandraschko looks like they do let me try theirs...

**Comment by melloware** [comment]
OK committed using Commons FileUpload Parameter parser however this will force all implementations doing file uploads to include the FileUpload jar which I am OK with but you guys may not be.

**Comment by tandraschko** [comment]
If its not easy to copy, we should not use it. Native fileupload must not depend on commons.

**Comment by jxmai** [comment]
https://github.com/apache/commons-fileupload/blob/6c00d575a9521c386743891fd34bc5181174cc01/src/main/java/org/apache/commons/fileupload/FileUploadBase.java#L493-L525 

What about copying the code above ?

**Comment by jxmai** [comment]
but I think melloware's solution is close enough. Maybe just to continue to resolve `\\\` ?

**Comment by melloware** [comment]
@tandraschko I totally agree. That is why I was going for pure Java version which I think I have nailed all the above except the strange scenario where someone names their file `\\\` etc.  Which to me is a ridiculous file name and maybe we just chalk up to a corner case.

@jxmai if you look at that FileUploadBase its deferring to Parameter Parser so you have to copy more than just FileUpload Base you would have to copy ParameterParser too which brings in their MimeUtility etc etc.

**Comment by jxmai** [comment]
> if you look at that FileUploadBase its deferring to Parameter Parser so you have to copy more than just FileUpload Base you would have to copy ParameterParser too.

I see. I prefer your previous approach, and I assume it was almost there (The only tricky part is `\` as I did not find any other character that can cause trouble). As long as we have enough unit test cases, there is no need to borrow other's code.

**Comment by melloware** [comment]
I think we have hit 99% of use cases.  At least we have fixed the two open tickets about semicolon's and double quotes and have unit tests around proving we didn't break anything new.

**Comment by jxmai** [comment]
I agree. Currently the only bug I found is `\\\` , `\\\\\`   ....

can be summarized as 

 `\ * (2n) + 1`  as n >= 1

**Comment by jxmai** [comment]
Actually, the extreme file name `\\\` was not working in the first place, and the error message was occurred before reaching primefaces

Take tomcat stack trace for example

```
SEVERE: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.String.charAt(String.java:658)
	at org.apache.tomcat.util.http.parser.HttpParser.unquote(HttpParser.java:135)
	at org.apache.catalina.core.ApplicationPart.getSubmittedFileName(ApplicationPart.java:152)
	at org.apache.catalina.connector.Request.parseParts(Request.java:2871)
	at org.apache.catalina.connector.Request.parseParameters(Request.java:3211)
	at org.apache.catalina.connector.Request.getParameterNames(Request.java:1183)
	at org.apache.catalina.connector.RequestFacade.getParameterNames(RequestFacade.java:398)
	at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:89)
	at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:62)
	at java.util.Collections$UnmodifiableMap.get(Collections.java:1454)
	at com.sun.faces.application.view.MultiViewHandler.calculateRenderKitId(MultiViewHandler.java:222)
	at com.sun.faces.context.FacesContextImpl.isPostback(FacesContextImpl.java:212)
	at javax.faces.context.FacesContextWrapper.isPostback(FacesContextWrapper.java:461)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:193)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:121)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```


> I think we have hit 99% of use cases. At least we have fixed the two open tickets about semicolon's and double quotes and have unit tests around proving we didn't break anything new.

That's 100%  ignoring the bug outside of PF.

**Review by jxmai — APPROVED** [review]

**Comment by tandraschko** [comment]
are all bugs fixed now? Or should i wait to apply the PR?

**Comment by jxmai** [comment]
I do think this PR can be safely applied now since I have tested thoroughly. (No regression but only improvement). To back it up, I think @orange-buffalo also tested this PR and did not find out any problem: https://github.com/primefaces/primefaces/issues/3034#issuecomment-349305373. The only glitch is https://github.com/primefaces/primefaces/pull/3043#issuecomment-349123666 but I am sure it has nothing to do with this PR.

**Pull request merged**
