### PR TITLE
Fix #10457: queueMicroTask instead of setTimeout(0)

### LINKED ISSUE #10457: Core: queueMicroTask instead of setTimeout(0)
See: https://www.freecodecamp.org/news/queuemicrotask/

Supported on all Major browsers since we dropped IE support: https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask

### PR DESCRIPTION
**Pull request by melloware**
Fix #10457: queueMicroTask instead of setTimeout(0)

### CODE REVIEW

**Comment by tandraschko** [comment]
what are the exact reason anyway to have timeout=0? maybe we can fix those things completely different in newer browsers

**Comment by melloware** [comment]
If I had to guess most of the Timeout(0) are due to AJAX calls and needing to perform a task after the AJAX stuff is done but right before returning the browser event loop.  It might be possible to remove some of these but that would require much more extensive testing.

**Comment by jepsar** [comment]
I've seen timeouts of 1, 2, 5 or 10 millis being replaces with queueTask. Those small delays are not relevant?

**Comment by melloware** [comment]
I have been testing and so far they don't seem relevant. I think anything under 10ms is probably not noticeable and so far I have not see any difference. The ones specifically set higher I assume were done on purpose so I left those.

**Pull request merged**
