### PR TITLE
Fix #8205: ExportTag and ExportRowTag attributes

### LINKED ISSUE #8205: XML Exporter: Generate element names for a fixed locale without breaking other exporter behavior
**Description**

In my multi-lingual application, I export tables to XML output and other formats like PDF and XLSX. The table column header string changes with the selected language.

The current implementation of DataTableXMLExporter derives tag names in the XML output from the corresponding column header value, which change according to the current locale setting used in the application.

This leads to different XML element names in the output for different locale settings, which really makes no sense at all.

When I set a fixed language exportHeaderValue string for the XMLTableExporter it will also appear for PDF, XSLX and other formats, so the user will stumble about column headers in a wrong language there. 

The application is currently using PrimeFaces 11.

**Describe the solution you would like**

Clearly, element names in the XML exporter and table headers in PDF/XLSX are two different things. I am looking for a way to specify both without having cross-dependencies between them.

One quick idea for a solution would be to default to a single locale in this case, which has the benefit to not having to add extra element name information on each  column.

Can this be circumvented by extending DataTableXMLExporter?

I think I need to override Exporter.exportValue(...) for this, but I am lost on how to force the locale to use there.

Would it make sense to at least pin down the locale used for element tags by an option to DataTableXMLExporter?

Whatever the solution is, it has to be on a per-Exporter basis, just targeting the XML export.

### PR DESCRIPTION
**Pull request by melloware**
Fix #8205: ExportTag and ExportRowTag attributes

For TreeTable and Datatable allowing you to do this..

```xml
                
<p:dataTable id="tbl" var="product" value="#{dataExporterView.products}" exportRowTag="rowval">
	<p:column headerText="Code" exportTag="code-tag" >
		<h:outputText value="#{product.code}"/>
	</p:column>
	<p:column headerText="Name" exportTag="name-tag" >
		<h:outputText value="#{product.name}"/>
	</p:column>
	<p:column headerText="Category" exportTag="cat-tag">
		<h:outputText value="#{product.category}"/>
	</p:column>
	<p:column headerText="Quantity" exportTag="quantity-tag">
		<h:outputText value="#{product.quantity}"/>
	</p:column>
	<p:column headerText="Price" exportTag="price-tag">
		<h:outputText value="#{product.price}">
			<f:convertNumber type="currency" />
		</h:outputText>
	</p:column>
</p:dataTable>
```

And output will look like this...

```xml
<?xml version="1.0"?>
<tbl>
	<rowval>
		<code-tag>mbvjkgip5</code-tag>
		<name-tag>Galaxy Earrings</name-tag>
		<cat-tag>Accessories</cat-tag>
		<quantity-tag>23</quantity-tag>
		<price-tag>$34.00</price-tag>
	</rowval>
	<rowval>
		<code-tag>250vm23cc</code-tag>
		<name-tag>Green T-Shirt</name-tag>
		<cat-tag>Clothing</cat-tag>
		<quantity-tag>74</quantity-tag>
		<price-tag>$49.00</price-tag>
	</rowval>
```

### CODE REVIEW

**Comment by stolp** [comment]
Shouldn't dataTable also have a exportTag attribute? Or is this missing from the example here?

**Comment by stolp** [comment]
It's not that I cannot live with that decision. But still, the rationale behind it escapes me.

In my use case, I set my table id to `projectTable`, but would like to export the table to XML with the tag `projects` for the document and `project` for the column elements. It feels not right, that I can now do the latter but not the former without changing the id.

As far as I can see, this has nothing to do with the use of EL in an id attribute.

Sorry, should I be a PITA here.

**Comment by melloware** [comment]
yeah but its an immutable field?   You are introducing an extra tag field here when to me its not necessary. If you want your XML to be `projects` then simply set your `id="projects"` no?

**Comment by melloware** [comment]
I guess my point is its already tag soup and adding this extra tag for this very specific use case when its...

A) not used in other exporters
B) immutable (no EL expression can change it)
C) Locale agnostic

**Comment by stolp** [comment]
For me it just following the same design conventions as with the p:column/exportTag attribute.

There we already argued, that id and exportTag are similar but semantically different attributes.

Following the paradigm of least surprise I would expect the exportTag in dataTable and potentially other XML-exportable components as well.

If a user doesn't find it there, he will have to guess which other attribute is used instead. This feels inconsistent to me.

Besides there is a collision with id naming scheme vs. XML export schemes.

Other than that, your points are of course all valid and sound.

**Comment by melloware** [comment]
I submitted a PR and Integration test adding `exportTag`

**Comment by stolp** [comment]
Thank you. This relieves my soul. Sorry again for nagging.

**Pull request merged**
