### PR TITLE
Fix #6906: Menu fix both dialog and non dialog show

### LINKED ISSUE #5035: Menu: wrong position when using trigger element
## 1) Environment
- PrimeFaces version: 7.0.

An element with `float: right` which is a trigger for the menu. The menu has the following position attributes `my="right bottom" at="right top"`.

## 2) Expected behaviour
Menu positioned by the right side of the element.

## 3) Actual behaviour
The offset position is wrong. The problem in this code
https://github.com/primefaces/primefaces/blob/251ab3b91622d8187ad29b201166019be71350d8/src/main/resources/META-INF/resources/primefaces/menu/menu.base.js#L92-L100

First, it set `display: block` and `visibility: hidden` for the element, and at that point, as the menu container is located outside of content the scrollbar (attached to the `body`) appears (and changes the viewport size). After that, the code calculates the correct location for the element and relocate it, the scrollbar is not needed anymore and it disappears.

As a result, the menu position is not right. We need to add the size of the scroller to offset value of the target element. Or we can calculate position first and then change `display` style.

### LINKED ISSUE #6906: Menu: wrong calculated position with overlay="true"
Same defect as #4536. Defect was solved in 7.x but comes back with 8.0

## 1) Environment
PrimeFaces version: 8.0.4
Application server + version: TomEE 8.0.4
Affected browsers: All

## 2) Expected behavior
Calculated position of tag p:menu (overlay="true") on p:dialog is not dependent on the position of the scroll bar main window.

## 3) Actual behavior
Calculated position of tag p:menu (overlay="true") on p:dialog is dependent on the position of the scroll bar main window.

## 4) Steps to reproduce
Create page with vertival scroll bar. Open p:dialog with button with p:menu (overlay="true").
p:menu position is dependent on the location of the scroll bar.

## 5) Sample XHTML
``` 
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body style="height: 1500px;">
	<p:commandButton value="Modal" type="button" onclick="PF('dlg2').show();" />

	<p:dialog header="Modal Dialog" widgetVar="dlg2" modal="true" position="top" height="150">
		<h:form>
			<h:outputText value="This is a Modal Dialog." />
			<h3>Overlay</h3>
			<p:commandButton id="dynaButton" value="Show menu" type="button" />
			<p:menu overlay="true" trigger="dynaButton" my="left top" at="left bottom">
				<p:menuitem value="Save" />
				<p:menuitem value="Update" />
			</p:menu>
		</h:form>
	</p:dialog>
</h:body>
</html>
```

### PR DESCRIPTION
**Pull request by melloware**
Draft for now which puts back the original fix for #4536.  Waiting to hear back from @astappiev  on his use case for #5035 which broke this.

### CODE REVIEW

**Comment by melloware** [comment]
OK fixed it and made sure both test cases work.

#6906: Inside Dialog:
[pf-6906.zip](https://github.com/primefaces/primefaces/files/5889298/pf-6906.zip)

#5035: Outside Dialog:
[pf-5035.zip](https://github.com/primefaces/primefaces/files/5889304/pf-5035.zip)

**Comment by astappiev** [comment]
Looks more like a workaround, ideally, we have to investigate why the shift appears and fix a reason. But the method is deep inside Jquery UI.

Also, if you open a menu in modal and scroll the window, the menu will be fixed on the screen, but a button will be moved with a page.

Don't you have plans to get rid of JQuery and all plugins? I guess something like [Popper.js](https://popper.js.org/) should be better.

**Comment by melloware** [comment]
@astappiev Not in 10,0.0 it doesn't it scrolls with the window.  That was fixed already.

**Comment by astappiev** [comment]
Sure, PF 10 is already RC.

But in general, most of the components which use UI is using Jquery and/or Jquery UI. I guess it will be super hard to replace it.
Meanwhile, Jquery UI looks abandoned and JQuery is rarely used in new projects.

**Comment by melloware** [comment]
Right not arguing the jQuery UI point.    Was simply stating your statement of _"Also, if you open a menu in modal and scroll the window, the menu will be fixed on the screen, but a button will be moved with a page."_ was incorrect.  It works fine in 10.0.0.RC1.

**Comment by melloware** [comment]
You can view the ticket about jQuery UI here: https://github.com/primefaces/primefaces/issues/5492

**Comment by astappiev** [comment]
Thanks for the link to the ticket.

And yes, I gave the wrong description. In my reproducer, if you open user menu and then scroll down, the navbar will be fixed, but the menu will be moved.
image

But I know, the navbar is not PF component and it has a fixed position.

**Comment by melloware** [comment]
I just fixed that issue too.  Refresh this PR.

```javascript
PrimeFaces.utils.registerScrollHandler(this, 'scroll.' + this.id + '_hide', function() {
            $this.hide();
        });
```

it should have been there we do this for other overlays.

**Comment by astappiev** [comment]
Hm, thank you. Even simpler than I expected.

**Comment by melloware** [comment]
we actually do that on all the other overlays somehow i missed this one.

**Comment by tandraschko** [comment]
This is something that must be reviewed by PrimeTek.
But in general i wonder what happens in other overlays like OverlayPanel?

**Comment by melloware** [comment]
Closing this PR as Mert is fixing this with his other issues: #6978 and #6973

**Pull request closed without merging**
