### PR TITLE
#6490: SelectRenderer: add fast path to doValidateSubmittedValues

### LINKED ISSUE #6490: SelectRenderer: add fast path to doValidateSubmittedValues
`SelectRenderer#doValidateSubmittedValues` eats up a good amount of CPU-cycles. Especially with explicit converter.
We can stop evaluating when `submittedValues.length == validSubmittedValues.size()`.

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by tandraschko** [comment]
can you explain the fix?

**Comment by christophs78** [comment]
> can you explain the fix?

After we have validated value for each submitted value there is no need to further loop through the other available SelectItems.

**Comment by tandraschko** [comment]
couldnt it be that the size could be different and still valid?

**Comment by christophs78** [comment]
When eg 3 values have bean submitted we IMO can have a maximum of 3 valid values.
After we found 3 valid values we can stop iterating SelectItems.
When we find eg only 2 valid values everything is like before. We return valid values after we iterated over all SelectItems.

**Comment by christophs78** [comment]
Hm. It´s more complicated when we have oldValues which are now disabled. I have to take this into account.

**Comment by tandraschko** [comment]
i will close it for now, please come back if you have a second idea/PR.

**Pull request closed without merging**
