### PR TITLE
Fix #5492: jQuery UI 1.13

### LINKED ISSUE #5492: Upgrade jQuery UI 1.13
As jQuery UI is not active anymore, we should try to move away from long-term perspecive.

Currently we have following dependencies:
- some widgets like calendar and slider
- animations
- utils
- class names (we just use the same names, we don't need to change it)

### PR DESCRIPTION
**Pull request by melloware**
Upgraded to jQuery UI 1.13.  Tested locally but submitting this PR to make sure all integration tests pass.

### CODE REVIEW

**Comment by tandraschko** [comment]
It adds many new styles, not sure
Im sure they will conflict with ours or themes

I think we need more thinking how we should use jquery ui in general

**Comment by melloware** [comment]
The styles can definitely be removed but so far in my testing I have not seen any issues.   And this fixes all the issues with JQMigrate making this version compatible with JQuery 3.6.0

**Comment by tandraschko** [comment]
I think we should remove the styles as they are Not used
It just blows up styling on the client

**Comment by melloware** [comment]
Styles removed.

**Comment by tandraschko** [comment]
did you a extensive test in the showcase? If yes -> +1

**Comment by melloware** [comment]
Yes I hit pretty much every function in the showcase looking for errors and saw none, tested Effects, Calendar (even though its hidden), and poked around on all the pages.

**Pull request merged**
