### PR TITLE
fix: check filename of uploaded file at server side as well (#2791)

### PR DESCRIPTION
**Pull request by cnsgithub**
add: content type checking of uploaded file based on java 7 FileTypeDetector (#2791)

### CODE REVIEW

**Comment by cnsgithub** [comment]
@tandraschko @melloware This is a first draft only and needs thorough testing. 

Unfortunately, I have not yet managed to get `org.apache.tika.filetypedetector.TikaFileTypeDetector `picked up by the `java.nio.file.spi.FileTypeDetector` service loader despite adding the dependency to the showcase's `pom.xml`:
```xml
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-java7</artifactId>
            <version>1.19.1</version>
            <scope>runtime</scope>
        </dependency>  
```
Might be a classloading problem? Webapp vs. system classloading?

**Comment by cnsgithub** [comment]
Btw, my last commit to this branch upgrades junit and mockito to work with java 11, too. Should be okay? I need this for providing a unit test...

**Comment by tandraschko** [comment]
it should actually work but if you are on Java11, maybe a modules problem?

the dependency upgrade is ok, yes.

1) Could you please add 2-3 simple unit tests for the isValidType method?
2) Should we make this feature deactivatable? If tika is not present, the content check is not reliable and should be deactivatbale. Otherwise is tika is >actually< required dependency.

**Comment by cnsgithub** [comment]
> it should actually work but if you are on Java11, maybe a modules problem?

After upgrading the versions everything works fine with java 11, thus my question. It was due to a method in `sun.misc.Unsafe` being removed. This method however was frequently used by code generators, see https://dzone.com/articles/jdk-11-and-proxies-in-a-world-past-sunmiscunsafe for an explanation.

> Could you please add 2-3 simple unit tests for the isValidType method?

Yes, it was my intention to do that.

> Should we make this feature deactivatable? If tika is not present, the content check is not reliable and should be deactivatbale. Otherwise is tika is >actually< required dependency.

Usually there is always one default implementation for `java.nio.file.spi.FileTypeDetector`. On my Windows machine with JRE 11 it's `sun.nio.fs.RegistryFileTypeDetector `that simply picks up the file extension from the Windows registry for example. That means if you upload a file `test.png `it'll lookup `image/png`. However, if you upload an executable and rename it to test.png it'll still lookup `image/png ` wrongly. In very rare cases `Files.probeContentType `may return `null`. Then we have to decide what to do. My current implementation will strictly refuse the upload.

**Comment by tandraschko** [comment]
Yup, i know ;) But that should be unrelated to the serviceloader.


I see. I would make it deactivatable.

**Comment by cnsgithub** [comment]
> Could you please add 2-3 simple unit tests for the isValidType method?

Added some more unit tests. Some advanced tests making use of Apache Tika are still required...

**Comment by tandraschko** [comment]
JFYI:

`ng.Boolean</type>re`

the "re" is to much :D

EDIT: you already changed it

**Comment by tandraschko** [comment]
Thanks for the good PR, it's a good improvement.

**Comment by cnsgithub** [comment]
Continued this PR in https://github.com/primefaces/primefaces/pull/4249

**Pull request merged**
