### PR TITLE
Fix #5200: Refactor facets using ComponentUtils.shouldRenderFacet()

### LINKED ISSUE #5200: Facet: Refactor facets using ComponentUtils.shouldRenderFacet()
Anywhere in the code doing..

```java
if (facet != null) {
```

needs to be..

```java
if (ComponentUtils.shouldRenderFacet(facet) {
```

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Review by Rapster — CHANGES_REQUESTED** [review]
Start your conditional statement with boolean first please, otherwise good decision to refactor all of this :wink:

**Comment by melloware** [comment]
Are you referring to these ternary's?
```java
!ComponentUtils.shouldRenderFacet(filterFacet)
                                                          ? params.get(filterId)
                                                          : ((ValueHolder) filterFacet).getLocalValue();
```

**Comment by melloware** [comment]
Oh no i think you mean this?
```java
if (legendText != null || renderFacet) {
```

**Comment by melloware** [comment]
OK I flipped those boolean checks and on the ternary I made them read easier using the postive case so instead of...

`!shouldRenderFacet ? text : facet;`

it is now...

`shouldRenderFacet ? facet : text;`

**Comment by Rapster** [comment]
Sorry using my phone so I'm kinda lazy typing... I should have said `shouldRenderFacet` should be called in last wherever it's possible since it's a time consuming call. For example:

`(ComponentUtils.shouldRenderFacet(rightTopContent) && isTop` becomes `isTop &&(ComponentUtils.shouldRenderFacet(rightTopContent)`

See my point?

**Comment by melloware** [comment]
Now I totally understand. I will fix!

**Review by Rapster — APPROVED** [review]

**Comment by tandraschko** [comment]
+1 if you fixed the last review from rapster

**Comment by melloware** [comment]
I did I flipped all the checks to do the RenderFacet check as late as possible.

**Comment by Rapster** [comment]
can be merged 😉

**Comment by Rapster** [comment]
I didn't know you could squash and merge with github, so cool! If only I knew that 😅

**Comment by melloware** [comment]
That is the only way I do it!

**Comment by melloware** [comment]
I just changed my default to Squash and Merge.

**Comment by Rapster** [comment]
How did you change your default?

**Comment by melloware** [comment]
So next time you go to merge if you just change your default like in the screenshot below it seems to stick for all future merges.

image

**Comment by Rapster** [comment]
alright sounds good! thanks

**Pull request merged**
