### PR TITLE
Fix #6874/#6876: DataView: pagesize check and emptyMessage

### LINKED ISSUE #6874: DataView: DataViewRenderer.encodeListLayout skips code if pageSize is greater than the number of elements
**Describe the defect**
The method **encodeListLayout** will end abruptly if the pageSize is greater than the number of elements in the dataView.

Thus, writer.endElement("ul") and dataview.setRowIndex(-1) will not be called.
This leaves the rowIndex at an invalid position that is not within the range of elements in the DataView.

**Reproducer**
I don't have a reproducer; simply compare DataView.encodeGridLayout and encodeListLayout:

encodeGridLayout :
```
if (!dataview.isRowAvailable()) {
  break;
}
```

encodeListLayout :
```
if (!dataview.isRowAvailable()) {
  return;
}
```

**Environment:**
 - PF Version: master-SNAPSHOT (10.0)

**Expected behavior**
writer.endElement("ul") and dataview.setRowIndex(-1) should be called.

### LINKED ISSUE #6876: DataView: "No records found." message missing if the DataView has no elements
**Describe the defect**
If a DataView (GridLayout and/or ListLayout) has no elements in it, the message "No records found." should be displayed.

2021-01-21 11_35_34-PrimeFaces Test

**Reproducer**
[primefaces-reproducer.zip](https://github.com/primefaces/primefaces/files/5848666/primefaces-reproducer.zip)

**Environment:**
 - PF Version: master-SNAPSHOT (10.0)
 - JSF + version: Mojarra 2.3.14
 - Affected browsers: all

**To Reproduce**
Run the reproducer.

**Expected behavior**
The message "No records found." should be displayed

### PR DESCRIPTION
**Pull request by ghost**
The method encodeListLayout will end abruptly if the pageSize is greater
than the number of elements in the dataView. Thus,
writer.endElement("ul") and dataview.setRowIndex(-1) will not be called.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Thanks for the PR!

**Comment by tandraschko** [comment]
looks good to me, can someone retest?

**Comment by melloware** [comment]
I can check it today.

**Comment by melloware** [comment]
OK tested and working.  Merging.

**Pull request merged**
