### PR TITLE
add ja locale.

### LINKED ISSUE #9861: Locales: Add Japanese

### PR DESCRIPTION
**Pull request by tsuyoz**
Hi, I've added 2 files of ja locale.

### CODE REVIEW

**Comment by tandraschko** [comment]
arigato gozaimasu!

the build just fails, @melloware can you check it?

**Comment by tsuyoz** [comment]
Sorry. I missed some settings. It has been corrected, please check again.

**Comment by tandraschko** [comment]
perfect, thank you!

**Comment by jepsar** [comment]
@tsuyoz can you please comment on #9861 so we can assign you?

**Comment by melloware** [comment]
@tsuyoz you rock!

**Pull request merged**
