### PR TITLE
Fix #2168: Remove Layout and Editor

### LINKED ISSUE #2168: Remove p:editor, p:layout
maybe in 7.x or something.
Currently it's only deprecated.

Its not maintained since years and has many bugs.
We should completely remove it as we now have the textEditor.

### PR DESCRIPTION
**Pull request by melloware**
Finally remove Layout and Editor after 3 years. Subject to review from PrimeTek.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Looks good to me!

**Comment by GedMarc** [comment]
This is so sad xD :)

**Comment by melloware** [comment]
@GedMarc We are keeping it alive on Primefaces Extensions though so all is not lost!

**Comment by melloware** [comment]
Migration guide updated

**Pull request merged**
