### PR TITLE
Add setup for separate checkstyle config for tests

### PR DESCRIPTION
**Pull request by krichter722**
Some basic rules which make sense to start with.

### CODE REVIEW

**Comment by tandraschko** [comment]
we use the same checkstyle by design, so we wont merge this

**Comment by krichter722** [comment]
@tandraschko I don't understand, currently you're not using any checkstyle for tests (this is due to includeTestSourceDirectory=false by default).

**Comment by tandraschko** [comment]
then its currently by mistake
free to change includeTestSourceDirectory and fix the checkstyle but adding a second checkstyle isnt good

**Comment by krichter722** [comment]
OK, I tried that at first, but you need to make some sacrifices for that, e.g. test methods can't have `_` in you current setup. Do you want the `_` to be removed from test method names (become even harder to read) or the rule to be dropped for prod code?

Maybe you want to think about the separate setup again based on this example with the test method names which would allow you to have almost the same setup except for some rules that just make sense for tests.

**Comment by melloware** [comment]
I thought we excluded tests because they are just tests and yeah they would violate a lot of our check style rules.

**Comment by tandraschko** [comment]
If its just _, i think we could just add it for prod code

**Comment by krichter722** [comment]
I'm just doing (early) branch spring cleaning. It's sort of meditative work for me, for you it's your code base. I don't know if it's just `_`, however I think dropping a rule for prod has way more impact than adding a separate smaller ruleset for test which wasn't covered before.

Test methods with `_` could be surrounded by a suppression as well. However that's a lot of effort in comparison to the separate ruleset.

**Comment by tandraschko** [comment]
for me it seems that its just "_" in method names
so i would go for add this in our global checkstyle and just fix tests

**Comment by krichter722** [comment]
I'll try that. Just to make sure, because you talked about adding a rule twice. The rule to forbid `_` in method names will be **removed** from the ruleset for prod. Only that allows the same ruleset to pass for prod and test. It also allows (usually unwanted) method names with `_` in prod code.

**Comment by tandraschko** [comment]
yeah
we can also copy the config + allow _ but everything else must be the same config

**Comment by tandraschko** [comment]
applied our default checkstyle to the tests, with 2 modifications:
allow _ in methods
allow package scoped variables for our Page classes in the integration tests

**Comment by krichter722** [comment]
OK. The work was also in the PR...

The removal of final is maybe not intended, usually you want as much immutability as possible, even on the local level. That might even be enforced with a rule.

I'd wrap the classes in `TerminalAutoCompleteTest` in `//CHECKSTYLE:OFF/ON` because they're test data rather than code.

**Pull request closed without merging**
