### PR TITLE
Fix #3453,#3455,#3615: Remove NUMPAD_ENTER.

### LINKED ISSUE #3453: defaultCommand: with browser autocomplete not working together in Firefox
## 1) Environment
- PrimeFaces version: 6.*
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 7.0
- Affected browsers: Firefox (tested with v58)

## 2) Expected behavior
When selecting the browsers autocomplete suggestions using Enter the selected suggestion should be filled in and the `defaultCommand` should not be triggered. The next press of enter should trigger the default command.

This works as expected in in Chrome: 
defaultcommand-chrome

## 3) Actual behavior

The completion is ignored (the selected value not filled in) and the characters that were typed are submitted.

defaultcommand-firefox

This is really annoying especially for login forms.

## 4) Steps to reproduce
Using firefox on [defaultCommand showcase](https://www.primefaces.org/showcase/ui/misc/defaultCommand.xhtml)

1. Type "name" and press enter
2. Clear the field. Type n
3. Select autocompletion suggestion by arrow keys confirming the selection with Enter

## 5) Sample XHTML & bean
https://www.primefaces.org/showcase/ui/misc/defaultCommand.xhtml

## 6) Related issues

#2448 only Chrome and Safari, which is now working like expected (see 2)

### PR DESCRIPTION
**Pull request by melloware**
Fixes #3453,#3455,#3615, by removing NUMPAD_ENTER which was removed in Jquery 1.11 and restored for PF https://github.com/primefaces/primefaces/issues/2448 which it should not have been.

This PR rolls up all the changes in one.

### CODE REVIEW

**Comment by tandraschko** [comment]
So keypad enter doesn't work anymore with this PR, when you e.g. would like to "select "a autocomplete item?

**Comment by cnsgithub** [comment]
I think it should not stop working.

**Comment by melloware** [comment]
So it is my understanding that NUMPAD_ENTER is not always 108 depedning on the browser and should not be relied upon.  @jxmai @david0 please chime in?

Here is a great chart @david0 put together showing the exact problem:  https://gist.github.com/david0/36a6b3cf0d07dd1fe1296fcfbe8527ba

**Comment by david0** [comment]
Yes, I actually never saw numpad enter reported as 108. It was always reported as regular enter (13).

Maybe it was different with some very old browsers, but at last this change will fix the problems for all modern browsers.

**Comment by jxmai** [comment]
Yes, 108 does not mean numpad enter at all. I also wrote similar post on https://github.com/primefaces/primefaces/pull/3455#issuecomment-386097198.

---

and yes, the keypad enter's keycode is 13, which is the same as Enter key.

**Pull request merged**
