### PR TITLE
Add itemClass attribute to AutoComplete control

### PR DESCRIPTION
**Pull request by danielthegray**
This is a feature I added to the AutoComplete control, to control the class tag of the little selection pellets that appear inside the input container when selecting an item from the drop down.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
please rename to "itemStyleClass" to be consistent

**Comment by danielthegray** [comment]
And the HTML attribute? Should I also rename it to `data-item-style-class` or is it OK to leave it as `data-item-class`?

**Comment by tandraschko** [comment]
i think it's ok to leave it as "data-item-class"

**Comment by danielthegray** [comment]
OK! I have done the requested rename and added the itemStyleClass to the server-side rendering of the control (which was missing in my initial implementation).

**Comment by tandraschko** [comment]
Ui, didn't you create a issue for it?

**Comment by tandraschko** [comment]
Done for you ;) -> https://github.com/primefaces/primefaces/issues/2437

Please create one next time before opening a PR.
Also did a small refactoring on your code.

**Comment by danielthegray** [comment]
The UI issue was just an incomplete implementation of the itemClass feature
which is why I didn't consider it necessary to create a separate issue :)

**Comment by danielthegray** [comment]
Ahhh I'm sorry, I misunderstood... I wasn't aware I needed to create an issue for it. Thank you and I will keep that in mind for next time.

**Pull request merged**
