### PR TITLE
Fix #4855 - Refactor AjaxBehaviorHandler

### LINKED ISSUE #4855: Refactor AjaxBehaviorHandler
Since I'm working on https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/706 and bringing a new tag handler on top of `AjaxBehaviorHandler`. I realized `AbstractBehaviorHandler` could be a lot more simplified and extendable to ease overriding existing tag handlers

PR on his way, as I'd like to read your comments before merging into master

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by tandraschko** [comment]
+1 in generell but -1 for the "I" prefix
I would call it "BehaviorAttributes" as component properties can be received via component.getAttributes

**Comment by Rapster** [comment]
Thanks Thomas. I applied your suggestion

**Comment by tandraschko** [comment]
Cool!
Should we name it "BehaviorAttribute" or "BehaviorAttributeS"?

**Comment by Rapster** [comment]
BehaviorAttribute is fine, I understand your question but it's because we use enum that makes us questionning the name.

**Comment by Rapster** [comment]
Though should I rename `AbstractBehavior#getAllProperties` into `AbstractBehavior#getAllAttributes`?

**Comment by tandraschko** [comment]
+1

**Comment by Rapster** [comment]
If that's okay, i'll merge that PR into master then

**Comment by melloware** [comment]
+1

**Pull request merged**
