### PR TITLE
Fix #7213: Added panelFooter facet to AutoComplete

### LINKED ISSUE #7213: AutoComplete: Footer
Can we have a Footer in AutoComplete component.

Use case:
Suppose we display a list of Items in AutoComplete and now we like to add a new Item. 
It will be very useful to add a Command link("Add item") in footer so we can display a dialog and display form etc.

### PR DESCRIPTION
**Pull request by jepsar**
Fix #7213

Showcase https://github.com/primefaces/primefaces-showcase/pull/354

```xhtml
<f:facet name="footer">
    <div class="ui-fluid" style="padding:0.5rem 1rem 1rem 1rem">
        <p:button value="Add new" onclick="alert('This could open a dialog')"/>
    </div>
</f:facet>
```

Screenshot 2021-04-25 at 11 55 01

### CODE REVIEW

**Comment by jepsar** [comment]
We might want to request a theme change: `.ui-autocomplete-footer { padding: 0.5rem 1rem 1rem 1rem; }` Also, the empty message could benefit from a padding. @mertsincan WDYT?

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
i dont understand the name TBH
can you please add a screenshot where "header" facet is rendered and where this new facet is rendered?

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
why .html vs .prepend?

**Comment by jepsar** [comment]
Html would overwrite the footer

**Pull request merged**
