### PR TITLE
Provide BaseMenuModel.equals and hashCode

### PR DESCRIPTION
**Pull request by krichter722**
BaseMenuModel.equals and hashCode should be based on elements which is
the central class data and useful for subclasses.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Please create an Issue ticket that this PR can be linked to.  PrimeTek doesn't accept PR's without an accompanying Issue ticket!

**Comment by krichter722** [comment]
@melloware issue #3931. Added `equals` and `hashCode` to DefaultMenuItem as well.

**Comment by krichter722** [comment]
I just realized that I changed this because I was working with the view rather than the model (JPA entities) which is never a good idea (`MenuModel` is more of a view component than a model in the sense of JSF's and Primefaces' MVC afaik). Therefore this change might not be a good idea.

**Comment by tandraschko** [comment]
Also not sure about it.
I think it would make more sense to compare the id but the id is auto generated by the menu renderers?!

**Comment by krichter722** [comment]
I thought more about it and it doesn't make sense, sorry for bothering you with this.

**Pull request closed without merging**
