### PR TITLE
Fix #4263: OverlayPanel - Ensure top is not negative

### LINKED ISSUE #4263: OverlayPanel: Top position out of view
1) Environment
Reproduceable with current showcase (6.2.11), primefaces-test-master sample project (6.2 - see below) and my app (6.2.1 with Wildfly 13.0.0.Final)
Browsers: Firefox 63.0.3 and Chrome 70.0.3538.110

2) Expected behaviour
The top of the overlay panel should always be visible (no negative top-value)

3) Actual behaviour
If the browser window is too small the overlay panel is moved to the top of the bound element. But too far so that the top of the overlay panel is no longer visible (exceeds the top of the browser window).

4) Steps to reproduce
See sample project: Decrease the size (height) of the browser window and click the test button. There is enough space to put the overlay panel at the bottom of the panel but it's moved to the top. But even is there wasn't enough space below the button the top of overlay panel should never get out of view.

5) Sample XHTML
See sample project

6) Sample bean
See sample project

Sample project: https://github.com/tdtappe/primefaces-test/tree/overlay-panel-position

### PR DESCRIPTION
**Pull request by fanste**

### CODE REVIEW

**Comment by tdtappe** [comment]
Does not work as I would expect it to work. I think the top position has to be checked with its "absolute" value. If the overlay panel is for example inside a parent at the bottom of the page then a negative relative top position should be allowed. But the "absolute" value should never be negative.

**Comment by tandraschko** [comment]
@fanste Can you rework your PR based on the input from @tdtappe ?

**Comment by fanste** [comment]
This week I'm out of time. 

@tdtappe Could you create a test case that reproduces the behavior from your comment? That would make it easier for me.

**Comment by tdtappe** [comment]
In my sample project I added another button at the bottom of the page that also shows an overlay panel. And this panel is mostly out of view though it doesn't have to be that way because there's a lot of space available above it.

**Comment by tandraschko** [comment]
@fanste can you work on @tdtappe s Feedback?

**Comment by fanste** [comment]
I will work on this again when I'm back from holidays.

**Comment by tandraschko** [comment]
i will close the PR for now. If you reworked it, you can still create a new one.

**Pull request closed without merging**
