### PR TITLE
CSS for #4696 and #125

### PR DESCRIPTION
**Pull request by ltlBeBoy**
The required CSS modifications for #4696 and #125, according to `SelectOneMenu`.

Is PrimeTek responsible for modification of the themes in
_src/main/resources/META-INF/resources/primefaces-[arya|luna...|nova...|saga|vela]_
?

### CODE REVIEW

**Comment by melloware** [comment]
@ltlBeBoy yes we can make core CSS changes here like you did.  But anything thta deals with colors, styles etc goes into Themes and only PrimeTek makes those changes.

**Comment by melloware** [comment]
Also the width doesn't look right here?

image

**Comment by ltlBeBoy** [comment]
Looks like you have to delete the browser files to get the updated CSS. Should look like this:
Screenshot 2023-01-23 at 18-19-48 PrimeFaces Showcase

**Comment by melloware** [comment]
2 things.

1. I meant the width of the dropdown.   I am seeing a hardcoded width of `15rem` ?
2.

**Comment by ltlBeBoy** [comment]
> @ltlBeBoy yes we can make core CSS changes here like you did. But anything thta deals with colors, styles etc goes into Themes and only PrimeTek makes those changes.

OK. The border color and item padding is specified by the themes. So my CSS modifications are finished. The remaining changes are done by #9674.

**Comment by melloware** [comment]
I meant the width of the dropdown.   I am seeing a hardcoded width of `15rem` ?

image

**Comment by ltlBeBoy** [comment]
OK, I will check.

**Review by melloware — APPROVED** [review]

**Comment by ltlBeBoy** [comment]
The fixed panel width resulted from the property `panelStyle="width: 15rem"`:

selectcheckboxmenu_advanced

But I removed it because it's too small for the content.

I also changed from `px` to `rem` to make the style more flexible.

**Comment by melloware** [comment]
i like it.

**Pull request merged**
