### PR TITLE
Corrected .gitignore

### PR DESCRIPTION
**Pull request by ova2**
I've corrected .gitignore for all availabe IDEs and cases.

### CODE REVIEW

**Comment by tandraschko** [comment]
Oleg, please don't mix different stuff.
Your pull requests also don't seems correct:
-                var sourceId = null,
-                $this = this,
-                var $this = this,

**Comment by ova2** [comment]
Well, multiple Pull Requests are merged automatically to one. Sorry. I don't have control for that

Thomas, why it is not correct? I just followed advices by IntelliJ and rewritten:

``` javascript
var sourceId = null,
$this = this,
sourceId = ...
```

to the

``` javascript
var $this = this,
sourceId = ...
```

It is correct. In the old code piece, `sourceId` was declared twice!

P.S. In the fact, the PrimeFaces JS code needs to be optimized. I think nobody looked really into the JS code and tried to optimize it. I would check it first with `JSLint` and then declare `"use strict"` directive as many JS libs do that. I'm sure you can do then some basic optimizations.

**Comment by tandraschko** [comment]
Ahh, i see. Yep looks fine.
@cagataycivici Would you like to review first?

**Comment by srbala** [comment]
When all changes are in same branch (in this case [master](https://github.com/ova2/primefaces/commits/master)), github tends to pull all-in-one together. Fixes needs to be in isolated branch for separate pull requests.

**Comment by cagataycivici** [comment]
Please create separate pull requests with references to issues.

**Pull request closed without merging**
