### PR TITLE
added new function to obtain widgets by type

### PR DESCRIPTION
**Pull request by matinh**
For details see forum topic at https://forum.primefaces.org/viewtopic.php?f=3&t=47792

### CODE REVIEW

**Comment by tandraschko** [comment]
please also add it to the documentation and create a issue for tracking

**Comment by matinh** [comment]
I created JavaDoc style documentation. Where else should I add documentation?

**Comment by tandraschko** [comment]
the userguide (https://primefaces.github.io/primefaces/9_0/#/), its also on the sources

**Comment by matinh** [comment]
Ok, I found I have to update https://github.com/primefaces/primefaces/blob/master/docs/9_0/core/javascriptAPI.md.
Do I also have to update `*.html` files in `docs/jsdocs` or are they generated somehow?
And what about the `export` in `PrimeFaces.d.ts`?

I didn't find this info on https://github.com/primefaces/primefaces/wiki/Contributing-to-PrimeFaces. Maybe it should be added to this wiki page?

Thanks for your help.

**Comment by tandraschko** [comment]
they are generated automatically via our travis task

**Comment by tandraschko** [comment]
thanks!

**Pull request merged**
