### PR TITLE
Fix #11429: Message tooltip fix

### LINKED ISSUE #11429: Message: tooltip is not shown in 14.0.0-RC1
### Describe the bug

Message in tooltip display mode is not shown.

### Reproducer

1.Run 
```
wget https://github.com/primefaces/primefaces/archive/refs/tags/14.0.0-RC1.tar.gz -O- | tar -x -z -C /tmp/ 
cd /tmp/primefaces-14.0.0-RC1/
mvn clean install 
cd primefaces-showcase
mvn -Ddev
```
2.Open http://localhost:8080/showcase/ui/message/messages.xhtml
3.Click Submit button

### Expected behavior

Tooltip should be shown - it works on https://www.primefaces.org/showcase/ui/message/messages.xhtml

### PrimeFaces edition

None

### PrimeFaces version

14.0.0-RC1

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #11429: Message tooltip fix

### CODE REVIEW

**Comment by tandraschko** [comment]
still double plus

**Comment by tandraschko** [comment]
i also wonder if this really targets the right id?
`target.attr('aria-describedby', this.id + '_error-' + + summaryOrDetail);`

**Comment by melloware** [comment]
Checking it now.

**Comment by melloware** [comment]
It looks like it is matching..

image

**Comment by tandraschko** [comment]
what about

```
        
		var msgSrc = this.jq.find('.ui-message-error-summary');
		if (msgSrc.length == 0) {
			msgSrc = this.jq.find('.ui-message-error-detail');
		}

		var text = msgSrc.text();
        if(text) {
           var target = $(PrimeFaces.escapeClientId(this.cfg.target));

           if (this.cfg.tooltip) {
              target.data('tooltip', text);
           }

           target.attr('aria-describedby', msgSrc.attr('id'));
        }
```

**Comment by melloware** [comment]
let me try that i like it.

**Comment by melloware** [comment]
works perfectly.

**Pull request merged**
