### PR TITLE
Chrome 91 - issues

### PR DESCRIPTION
**Pull request by christophs78**
~~Looking into some weird issues i have in IntelliJ after our multi-module-merge.
Maybe related to https://github.com/primefaces/primefaces/issues/7410~~

### CODE REVIEW

**Comment by christophs78** [comment]
Currently playing around to figure out what´s going on.

**Comment by christophs78** [comment]
Ok. I´m able to reproduce the Chrome 91 - integration-test - freeze on my Windows 10 - notebook too.
(Enabling/disabling parallel tests does not matter.)

**Comment by christophs78** [comment]
Looks like TriStateCheckbox001Test#testSetValue is freezing on Chrome 91. 
After disabling this one our test´s do not freeze anymore.
But we have a long list of other test´s which fail on Chrome 91.
So all this is related to Chrome 91 and not to our multi-module-merge.
It´s getting 23PM. So done for today....

**Comment by christophs78** [comment]
Official bug in Chromedriver 91: https://bugs.chromium.org/p/chromium/issues/detail?id=1205107

**Comment by melloware** [comment]
Great work and research. I say we wait until chrome 92 driver until we try and take any action. Sounds like chrome 91 driver broke a lot of people!

**Comment by melloware** [comment]
Looks like they released a new ChromsDriver for that issue...

ChromeDriver 91.0.4472.101
Resolved issue 1205107: Unable to get attribute value for fields on the web application.

**Comment by christophs78** [comment]
Yep. Now only Github needs to build new CI-VMs. Should be solved in a week or two.

**Comment by christophs78** [comment]
Some mutations of nightly.xml-matrix already get new images with fixed chrome driver. Some mutations still get old ones. Hope in another day or two all is green again.

**Comment by tandraschko** [comment]
i wonder if it works now?

**Comment by christophs78** [comment]
> i wonder if it works now?

It´s still weird.
https://github.com/primefaces/primefaces/runs/2939064649
Some combinations of our IT-matrix get new Github-images which work, other still get old Github-images with the broken ChromeDriver. Maybe Github does some A/B-thing.

**Pull request closed without merging**
