### PR TITLE
fix guru badge name

### PR DESCRIPTION
**Pull request by kursataktas**
Hey @melloware, I noticed that the name of the Gurubase badge was incorrect, so I fixed it.

### CODE REVIEW

**Comment by melloware** [comment]
Thanks!

**Comment by kursataktas** [comment]
Hello @melloware,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

**Comment by melloware** [comment]
Thanks @kursataktas !

**Comment by kursataktas** [comment]
Hello Everyone,

I want to share an exciting update about Gurubase. We've recently released several great features that I think you'll find interesting.

### 1. Slack & Discord Integration
You can now add your Guru as a bot to Slack and Discord, allowing you to ask questions instantly. More details here: [Discord Bot Integration](https://docs.gurubase.ai/integrations/discord-bot).

### 2. Analytics Dashboard
Track what your users ask your Guru and gain valuable insights. This feature is available on the "My Gurus" page. If you haven’t maintained your Guru yet, I highly recommend doing so to access your analytics. More information about claiming your Guru can be found [here](https://github.com/Gurubase/gurubase?tab=readme-ov-file#how-to-claim-a-guru).
image

### 3. API Support
All Guru functionalities are now accessible via API. You can ask questions, edit data sources, and more using our API endpoints. Here is the [API Doc](https://docs.gurubase.ai/api-reference/introduction).

### 4. Codebase Indexing
We now support indexing codebases from GitHub repositories to generate answers for related queries. This feature is available for select Gurus. If you don’t see the "Codebase Indexed" label on your Guru edit page and would like access, please let me know, I’d be happy to enable it for you!
image

Let me know if you have any questions or feedback!

**Comment by melloware** [comment]
@kursataktas i don't see the CodeBase  Indexing on the PrimeFaces Guru can you add it please?

**Comment by kursataktas** [comment]
@melloware Sure, I’ve enabled codebase indexing for PrimeFaces Guru. You can view its status on the Guru edit page.

**Pull request merged**
