### PR TITLE
#5335 DatePicker SonarCloud-Issue

### PR DESCRIPTION
**Pull request by christophs78**
https://sonarcloud.io/project/issues?id=org.primefaces%3Aprimefaces&open=AWxM5-Nqdg2jiL0yV2Wf&resolved=false&rules=squid%3AS2175

### CODE REVIEW

**Comment by tandraschko** [comment]
-1
this just changes 1 place
if you look in the DatePicker base, it's defined as non-generic list.
We should first define what can be inside the disabledDays list and then change everything.

**Comment by christophs78** [comment]
I had not been happy with this change too. Do you think it got better with my second commit. (I´m still not totally happy myself.) Or should we revert this and use the old non-generic list for disabledDays in DatePicker to keep SonarCloud happy?

**Comment by tandraschko** [comment]
why you are not happy?
If it can only contain ints, the change seems to be good?

**Comment by christophs78** [comment]
We stilll have
- `return (List<Integer>) getStateHelper().eval(PropertyKeys.disabledDays, null);` and
- and we have to keep other attributes like disabledDates as untyped list because it may contain String or java.util.Date or java.time.LocalDate

But it´s not a perfect world. :-) I think this PR makes the code a bit better than it was before and we can merge it.

**Comment by tandraschko** [comment]
yep :)

**Pull request merged**
