### PR TITLE
Fix #6108

### LINKED ISSUE #6108: Schedule: DefaultScheduleEvent.Builder missing generic return type
(https://forum.primefaces.org/viewtopic.php?f=3&t=62538)
I experienced a small problem while using the new Builder for org.primefaces.model.DefaultScheduleEvent.
Neither one of the setters not the build()-method uses Builder<T> as it's return type
This leads to the generic infomation being lost after the first call and the IDE issuing a warning.

The builder for org.primefaces.model.timeline.TimelineEvent does use generic return types. So I assume, it was not intentional.

(Working on a PR)

### PR DESCRIPTION
**Pull request by Markus-Patt**
Adding missing generics declaration to org.primefaces.model.DefaultScheduleEvent.Builder

### CODE REVIEW

**Comment by melloware** [comment]
You may have to sync your fork as its showing changes from a previous PR?

**Comment by melloware** [comment]
@blutorange please review as you are also making changes to Schedule right now.

**Comment by blutorange** [comment]
Looks good to me. I added two methods to the Builder, I should add the generics there as well. Perhaps you can merge this first, then I'll merge back into my branch and make the change there.

Also, seeing that this Travid build failed as well, it seems it's a general problem with oss index responding with a 500...

**Comment by Markus-Patt** [comment]
> You may have to sync your fork as its showing changes from a previous PR?
@melloware I did (I think...). Since I'm still quite new to github: Do I have to do anything else?

**Comment by melloware** [comment]
looks good!  merging so @blutorange can merge this into his PR as well.

**Pull request merged**
