### PR TITLE
Fix #7586: Badge value empty

### LINKED ISSUE #7586: Badge: does not render with ui-badge-dot class on empty value

### PR DESCRIPTION
**Pull request by jepsar**
Fix #7586

Before:

Screenshot 2021-07-14 at 19 59 30

After:

Screenshot 2021-07-14 at 19 59 41

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Shouldn't the after the badge not be rendered at all? or at least not visible?

**Comment by jepsar** [comment]
@melloware that was my initial idea, but then I ran into the line that added a class on empty values, so decided to fix that.

Maybe add a flag to hide if empty?

**Comment by melloware** [comment]
That might be a good idea unless PrimeTek expected us to use the `rendered` flag?

**Comment by jepsar** [comment]
The `rendered` attribute is useless for this, as you need to include children:
```xhtml
<p:badge value="1">
    <p:commandButton value="Fiets"/>
</p:badge>
```

**Comment by melloware** [comment]
Got it.

**Comment by melloware** [comment]
I am adding PrimeTek to this review to get their 2 cents...

**Comment by jepsar** [comment]
If we would add a flag, I would suggest to make it a breaking change and hide the badge by default if it is empty, and show the dot if the flag is set.

**Comment by tandraschko** [comment]
i think we can at least add this PR

**Comment by melloware** [comment]
OK I am good with it if you want to merge it!

**Comment by jepsar** [comment]
Opened a new issue for hiding the badge: https://github.com/primefaces/primefaces/issues/7676

**Pull request merged**
