### PR TITLE
Fix #6535 - MessageFactory: use varargs

### LINKED ISSUE #6535: MessageFactory: use varargs
**Description**
Use varargs instead of Object[]

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by tandraschko** [comment]
the change in general looks good, however the code in MessageFactory is by design that i didnt use a shared method for both String and FacesMessage return values, as this now creates a necessary array.

**Review by melloware — APPROVED** [review]

**Comment by Rapster** [comment]
I can always revert it even though I'm not sure what differences it makes...

**Comment by tandraschko** [comment]
less memory, less GC, thats all

**Comment by Rapster** [comment]
Mmmh... If we were working on embedded systems with very limited memory I would understand, but in such scenario not sure... Anyway, I'll revert it

**Comment by tandraschko** [comment]
yeah, i can understood you
but we have to microoptimize the core-functions of a framework
just think about hundrets of concurrent requests
if we only save like 10 objects in such a function each request, it isn't that few

same for for vs foreach on component childlists

**Comment by tandraschko** [comment]
thanks!

**Pull request merged**
