### PR TITLE
Fix #7022: Add close event to column toggler if popup is closed

### LINKED ISSUE #7022: ColumnToggler: Additional Event "close" if toggler popup is closed again
**Description**
At the moment there only exists an ajax event if a single column is toggled. If a customer toggles multiple columns multiple events are fired and a lot of ajax calls updates are fired. 
If you are only interested in the final selection of a column toggeling listening to the new close event of the column toggler is more efficient because this way only a single ajax call is fored once all columns are toggled.

**Describe the solution you would like**
Add an additional event "close" with the complete list of currently selected columns after the toggle popup is closed.

See Pull Request #7021

### PR DESCRIPTION
**Pull request by gako**
Fire close event if toggler popup is closed with list of all selected columnIds

### CODE REVIEW

**Review by melloware — CHANGES_REQUESTED** [review]
Can you add "Ajax Behavior Events" to 10.0.0/components/columntoggler.md.  It should like similar to AutoComplete's section here: https://primefaces.github.io/primefaces/10_0_0/#/components/autocomplete?id=ajax-behavior-events

I guess there are only two events toggle and now close.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Sorry can you rebase this PR and also add your new docs for events to the 11_0_0 columntoggler.md doc instead of the 10_0_0 since this didn't make 10_0_0. Thanks in advance!

**Comment by melloware** [comment]
@gako ping...

**Comment by gako** [comment]
hi, busy week, moved docu to 11.0.0 and rebased it to current master.

**Comment by melloware** [comment]
Hmm this now looks like it has 1100+ commits to merge.  Is there any way you could create a new PR and then close this one and then I will merge it?

**Pull request closed without merging**
