### PR TITLE
SelectItemGroup element support in SelectManyCheckbox

### PR DESCRIPTION
**Pull request by OskarsPakers**
In case of SelectItemGroup elements appearing in the list, pageDirection layout supports grouped items. Similar to feature described in #500 but for SelectManyCheckbox.

### CODE REVIEW

**Comment by OskarsPakers** [comment]
Support for SelectItemGroup was discussed in the forum quite some time ago here:
http://forum.primefaces.org/viewtopic.php?f=3&t=24672&sid=17f9dd24523eebcfcfb36d19c307a41e

**Comment by tandraschko** [comment]
I just did a very very short review of your changes.
Could it be that you miss a closing tr in the SelectManyCheckboxRenderer after line 264?

Would be great if you could also provide a PR for the showcase to demonstrate the feature. So we can also validate the changes better.

**Comment by OskarsPakers** [comment]
There was indeed missed closing tr. I fixed it.
Created pull request for primefaces/showcase: https://github.com/primefaces/showcase/pull/12

**Comment by tandraschko** [comment]
your PR now has more changes like styling/blanks etc.
Would be great if you could remove that, otherwise we can't see the real changes.

**Comment by OskarsPakers** [comment]
Fixed all spaces/indents. Now those which are left are because of the new code or additional if clause.

**Comment by spauny** [comment]
Any update on this? I tested and it seems to work properly.

**Comment by tandraschko** [comment]
#500

**Comment by tandraschko** [comment]
Merged! Thanks for the PR!

**Pull request merged**
