### PR TITLE
Fixes #11135 - DataTable/TreeTable: support composite as filter

### LINKED ISSUE #11135: DataTable/TreeTable: support composite as filter
https://github.com/orgs/primefaces/discussions/691#discussioncomment-7868229

and

related to #11092

### PR DESCRIPTION
**Pull request by tandraschko**
Fixes #11135

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
@melloware do you have some time to add a integration test?
the discussion contains a sample for globalFilter but we would also need a second, normal filter via filter facet, which contains a composite and using cc:editableValueHolder liked in https://github.com/primefaces/primefaces/issues/11092

**Comment by melloware** [comment]
Let me put it on my TODO list for this week. Leave this PR open and I will add the tests to this PR.

**Comment by melloware** [comment]
Or you can merge this and I will re-open the ticket and mark it for "integration test".

**Comment by melloware** [comment]
I am going to merge this and write integration tests

**Pull request merged**
