### PR TITLE
#4646 Schedule: add java.time.LocalDateTime-support

### PR DESCRIPTION
**Pull request by christophs78**
This PR replaces java.util.Date with java.time.LocalDateTime for the Schedule-component.
see also https://github.com/primefaces/showcase-facelift/pull/53

Additionaly i added a few documentation-updates for Calendar and Datepicker.

### CODE REVIEW

**Comment by melloware** [comment]
Hmm you removed and deprecated all of the java.util.Date handling?  I thought we were allowing both LocalDate and util.Date to still be viable.

**Comment by christophs78** [comment]
Yes. Schedule internally works now with LocalDateTime. But this is something we should discuss.

In my opinion there a the following options:
- Keep Schedule java.util.Date only.
- Make Schedule java.time.LocalDateTime only.
- Keep some kind of backward-compatibility as i do.

Keeping some kind of backward-compatibilty raises the following questions:
- Do we deprecate the old (java.util.Date) constructors and getter/setter?
- Which type does Schedule (DefaultScheduleEvent) use internally. (Date? LocalDateTime? Both?)

**Comment by christophs78** [comment]
Schedule is a different beast compared to Calendar and Datepicker, because it has its own model. So IMO we need to take a somewhat different approach.

**Comment by melloware** [comment]
Understood.  I have never used Schedule so I trust your judgement here.

**Comment by tandraschko** [comment]
I (personally) would migrate it to DateTime API and add a hint to the migration guide, that a user has to migrate, too.

IMO it would be also much better to remove Date support from Calendar and just proide a converter / force a converter from the user.
The codebase is really bad if we always need to support both Date APIs.

**Comment by melloware** [comment]
Yep I guess as long as there is a DateConverter for backward compatibility it shouldn't be a problem and we could keep the code base clean.

**Comment by christophs78** [comment]
A converter does not help there. You have to put your data into ScheduleModel and add DefaultScheduleEvent-instances to the ScheduleModel.

**Comment by tandraschko** [comment]
Yep, for Schedule it's not possible. I would just migrate to DateTime API and we should realy think about removing Date support from Calendar/DatePicker (converters are supported there, so no problem actually)

**Comment by christophs78** [comment]
Ok, i´ll remove java.util.Date - support from Schedule within the next week.
When i move Timeline to java.time, i´ll do the same. (only support java.time)
Schedule and Timeline are IMO both components that are not used that often.
For Calendar and DatePicker IMO we have to keep java.util.Date - support for the PF 7.x - Releases.
Calendar and DatePicker are used very frequent. So IMO this is a breaking change we only should do with am major release. (eg 8.0)

**Comment by christophs78** [comment]
@tandraschko: Please look at @Rapster latest comment in https://github.com/primefaces/primefaces/issues/4646.
What should we do?
IMO making a breaking change to Schedule and Timeline should not harm to that many people. But i´m also totally fine with keeping Backward-Compatibility in Schedule (and Timeline) as currently suggested in this PR.

**Comment by christophs78** [comment]
Breaking Schedule (and Timeline) would at least result in compile-time-errors.
Breaking Calendar and DatePicker would be much more perfidious because this results in runtime-errors.

**Comment by tandraschko** [comment]
+1 for the breaking chance for this Not often used components

If we can rename attributes for cosmetics, we can also do this (and you fail compile time, not silently)

**Comment by christophs78** [comment]
Ok. I removed java.util.Date - support. Schedule is now java.time.LocalDateTime-only.
I also updated the showcase-PR.
@tandraschko: One of-topic-question: JetBrains offers free IntelliJ-licences for open-source-projects. (https://www.jetbrains.com/community/opensource/) Is there a way to get some of this for PrimeFaces. (Would save some money for the IntelliJ-licencse on my home-PC.)

**Comment by tandraschko** [comment]
Looks like not possible (PrimeFaces is sponsored) - If you would become a PrimeFaces Extensions commiter, it should work

**Comment by christophs78** [comment]
No problem. Just tried to ask before i pay 150 for my home-licence.

**Comment by christophs78** [comment]
@tandraschko: Are we able to make some progress with this PR? (I´d like to continue with Timeline after Schedule is done. And finally i´ll do some cleanup and maybe refactoring (as suggested by @Rapster) with CalendarUtils.)

**Comment by tandraschko** [comment]
i will have time again mid/end next week
i had to start some releases @ apache this week.

**Comment by tandraschko** [comment]
If we only have LocalDate in the models now, we should not name them "getStartLocalDateTime". We should use the same names as before

**Comment by christophs78** [comment]
Ok. I updated this PR and showcase-PR according to your suggestions.

**Comment by tandraschko** [comment]
Thanks!

**Pull request merged**
