### PR TITLE
Sonar Fixes: map.computeIfAbsent()

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
I wont make a diff here but in general computeIfAbsent is slower

**Comment by melloware** [comment]
Interesting under the covers I just assumed it was doing `containsKey` etc so it would be the same just more concise.  i will have to read up on this.

**Comment by tandraschko** [comment]
Also its misused here, its already computed

**Comment by melloware** [comment]
OK i will kill this PR.

**Pull request closed without merging**
