### PR TITLE
Fix #12961: Remove legacy ThemeRoller ui-shadow

### LINKED ISSUE #12961: Remove unused JQuery ui-corner-* classes
found the following old themroller stuff:

unused:

- [x] ui-corner-* #12983 

only a few usages in our CSS but almost rendered for every component; we need to check:
- [ ] ui-widget
- [ ] ui-widget-content
- [ ] ui-shadow

### PR DESCRIPTION
**Pull request by melloware**
Fix #12961: Remove legacy ThemeRoller ui-shadow

@tandraschko this one was easier to manage and I removed all spacing.

### CODE REVIEW

**Comment by tandraschko** [comment]
i dont think this is complete
ui-shadow is still used in some cases and we need some theme css

**Comment by melloware** [comment]
Ahh yep I see it in some themes.

**Comment by tandraschko** [comment]
also ui-shadow has an effect
we have to align those components in theme.css which used ui-shadow in the past

**Comment by melloware** [comment]
IT used in `_menu.scss` so I reverted removing it from all the Menu components

**Comment by tandraschko** [comment]
i will take care of it, dont have much to explain now

**Pull request closed without merging**
