### PR TITLE
check selection in SelectOneRadioRender with null or empty values

### PR DESCRIPTION
**Pull request by buett**
see primefaces issue #2247

### CODE REVIEW

**Comment by tandraschko** [comment]
@melloware Would you like to check this? You fixed something similar for SelectOneMenu

**Comment by melloware** [comment]
Yes, let me investigate.

**Review by melloware — APPROVED** [review]
Nice work!

**Comment by melloware** [comment]
@tandraschko I have looked at this change and the other one I did was a much simpler fix.  @buett fix is not only a good fix it cleans up the code greatly as it had 3 sections of duplicate code.  I give this fix the thumbs up!

**Pull request merged**
