### PR TITLE
Fix #12786: SASS math, meta, color updates

### LINKED ISSUE #12786: Themes: fix deprecation warnings of sass compiler
e.g. darken() or lighten() now have a new syntax

maybe anyone has time to fix it

### PR DESCRIPTION
**Pull request by melloware**
Fix #12786: SASS math, meta, color updates

### CODE REVIEW

**Comment by tandraschko** [comment]
the generated theme.css should be the same afterwards actually?

**Comment by melloware** [comment]
lte me see if I can do a better diff since the file is 1 big line we can't see what is different.

**Comment by melloware** [comment]
Hmmm my locale compare is showing them as identical?  Maybe a EOL thing?

**Comment by melloware** [comment]
looks like `*.css` was missing in `.gitattributes` for EOL

**Comment by melloware** [comment]
@tandraschko you are right it looks like the lighten and darken algorithm in SASS has changed slightly.

For example this line.

**was:**
```css
$focusOutlineColor: lighten($primaryColor, 35%) !default;
```
**now:**
```css
$focusOutlineColor: color.scale($primaryColor, $lightness: 35%) !default;
```

Translates to.

**was:**
```css
--focus-ring: 0 0 0 0.2rem rgb(64.55, 171.6232718894, 255);
```

**now:**
```css
--focus-ring: 0 0 0 0.2rem rgb(140.5, 204.8732718894, 255);
```

**was:**
image

**now:**
image

**Pull request merged**
