### PR TITLE
Fix #8443/#7072: Menubar id refactoring

### LINKED ISSUE #7072: ClassCastException with DefaultMenuItem in MenuModel when set an id programmatically
Describe the defect
When setting MenuModel for a menubar programmatically and giving an id to an DefaultMenuItem, their is an ClassCastException on clicking the menu items.

Environment:
PF Version: 10.0.0-RC 1+2

Example working:
```xml
            <p:menubar>
                <p:menuitem value="Default Item" id="default" />
                <p:submenu label="Submenu">
                    <p:menuitem value="Submenu Default Item" />
                </p:submenu>
            </p:menubar>
```

Example not working:
```xml
                <p:menubar model="#{controller.menu}" />
```

```java
	public MenuModel getMenu() {
		final DefaultMenuModel menu = new DefaultMenuModel();

		menu.getElements().add(DefaultMenuItem.builder().value("Default Item").id("default").build());
		final DefaultMenuItem submenu_item = DefaultMenuItem.builder().value("Submenu Default Item").build();
		menu.getElements().add(DefaultSubMenu.builder().label("Submenu").elements(ImmutableList.of(submenu_item)).build());
		menu.generateUniqueIds();
		return menu;
}
```

Exception:
SEVERE [javax.enterprise.resource.webcontainer.jsf.context] (default task-3) java.lang.ClassCastException: org.primefaces.model.menu.DefaultMenuItem cannot be cast to org.primefaces.model.menu.MenuGroup at org.primefaces.renderkit.MenuItemAwareRenderer.findMenuitem(MenuItemAwareRenderer.java:192)

In Primefaces 8, both ways are working.

### LINKED ISSUE #8443: Menubar/menu: might execute wrong (not clicked) items
**Describe the defect**
Clicking menu items while the ajax request is still in progress might lead to unexpected results. This might be exactly the case either in slow environment or if the user acts rapidly clicking fast. Please check the attached primefaces-test zip reproducing the problem, it explains the problem in details.

**Reproducer**
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/8064098/primefaces-test-master.zip)

**Environment:**
 - PF Version: any
 - PF Theme: any
 - JSF + version: any
 - Affected browsers: any

**To Reproduce**
There are two examples in the attached app, just follow the instructions.

**Expected behavior**
I'd expect the menu behaving similar to the button component (the reproducer app includes the demonstration with buttons as well)

**The app screenshot giving a short overview**
image

### PR DESCRIPTION
**Pull request by melloware**
Submitting for review and so we can see the Integration Tests run.

### CODE REVIEW

**Comment by tandraschko** [comment]
this needs to be done for all menus if we change it and we need to discuss and check history heavly

**Comment by christophs78** [comment]
We do not have integrationtests yet for menubar.

**Comment by rabiter** [comment]
let me know if I can help with investigation/testing (the patch initially comes from me)

**Comment by melloware** [comment]
@tandraschko so far in all my testing this fix looks really good. I can't find anything broken with it.

**Comment by melloware** [comment]
I just pulled in @christophs78 new Integration Tests into this branch and letting it run!

**Comment by melloware** [comment]
Confirmed this also fixes: #7072

**Pull request merged**
