### PR TITLE
MenuBar IT

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by melloware** [comment]
Nice!

**Comment by tandraschko** [comment]
of course a new IT is always great, i just wonder if can add a MenuBar component? but we can also work later on it of course

**Comment by melloware** [comment]
Yeah I told @christophs78 if he gets the tests working I don't mind refactoring it into a MenuBar component all the re-usable bits.

**Comment by melloware** [comment]
Nice work!

**Review by melloware — APPROVED** [review]

**Pull request merged**
