### PR TITLE
#1915 Evaluate navigation rule parameter value

### PR DESCRIPTION
**Pull request by AndrewShwaika**

### CODE REVIEW

**Comment by tandraschko** [comment]
Why does it only take of the first value?

**Comment by AndrewShwaika** [comment]
As original from Mojarra javax.faces 2.2.13

**Comment by tandraschko** [comment]
ok - how is it done in MyFaces?

**Comment by AndrewShwaika** [comment]
Yes. MyFaces evaluates them all.

**Comment by tandraschko** [comment]
So it would be great if you could provide a PR based on MyFaces.

**Pull request closed without merging**
