### PR TITLE
#9646 Core: Filter normalization should be optional

### LINKED ISSUE #9646: Core: Filter normalization should be optional
We now normalize options and filter text by default (#9629). This should be optional.

SelectOneMenu, SelectOneListbox, SelectManyMenu, SplitButton, PickList

### PR DESCRIPTION
**Pull request by jepsar**
Fix #9646

Added a draft before I fix all instances. @melloware WDYT? Fix all of them like this?

### CODE REVIEW

**Comment by tandraschko** [comment]
I really wonder If we should make it only configurable global?
Not sure

**Comment by jepsar** [comment]
> I really wonder If we should make it only configurable global? Not sure

Could be an option. We could apply it on server side filtering as well.

**Comment by melloware** [comment]
what about like RTL where we turn it on with a web.xml param so the whole app is now normalized or not?  I think that is what @tandraschko is saying make it a global config and you can always pass the value to the widgets without allowing customization per widget just have them respect the global flag?

Only because I really don't think someone would want to turn this on for one component and not another??

**Comment by tandraschko** [comment]
yeah
we have 3 different ways:
1) attr on component
2) global attrs (we should really make this into Faces 4.1)
3) context param

in general we have to think about it: is it really required to set it on each component? global always makes sense but better we go 2) then

also i wonder if we should name it filterNormalize? same as current caseSensitiv, shouldnt it be filterCaseSensitiv?

**Comment by jepsar** [comment]
Something like this?

**Comment by tandraschko** [comment]
i dont know TBH

Could it make sense to have it configurable on each component? Then we should go for 1+2

**Comment by jepsar** [comment]
You mean https://primefaces.github.io/primefaces/12_0_0/#/core/globalattributes ? That is how it was before the last commit, right?

**Comment by tandraschko** [comment]
yep - sorry for confusing ;D

**Comment by jepsar** [comment]
Okay, back to attribute. I agree that `filterXxx` is better for filter related attributes and is in line with the existing filter attributes. I do think we should (breaking) change `caseSensitive` to `filterCaseSensitive`, but should we do that in this PR?

**Review by melloware — APPROVED** [review]

**Pull request merged**
