### PR TITLE
Fix #1439: File Upload XSS Vulnerability

### LINKED ISSUE #1439: FileUpload XSS vulnerability
Primefaces version 5.1.141 (ELITE Build)

``` xml
<p:fileUpload fileUploadListener="#{calendarMappingController.handleFileUpload}" mode="advanced" label="#{msg['calendarmapping.importfromexcel']}"
                                allowTypes="/(\.|\/)(xls|xlsx)$/"
                                update="calendarMappings" 
                            />
```

Uploading a file named  `.xlsx` (under Linux, since Windows won't allow file names with special characters).

Result:

html content in file name is not escaped.

image

### PR DESCRIPTION
**Pull request by melloware**
Fix #1439: File Upload XSS Vulnerability

### CODE REVIEW

**Comment by anouartrigui** [comment]
Can someone help me how to fix the XSS Vulnerability in Primefaces, the firewall block for me the file upload and I got following trace in the log file: 
request=https://..../galleryAbonne.xhtml msg=Cross-site script check failed for field form-image1:file-image1\="" cn1=1060151106 cn2=732672341 cs1=WAF_TT1200_PROF cs2=PPE6 cs4=ALERT cs5=2019 act=not blocked

The problem persists even after updating to Primefaces 6.2

**Comment by cnsgithub** [comment]
This specific XSS vulnerability has been fixed in PF 5.3.18 and 6.0.30, i.e. PF 6.2 should also contain the fix. 

Either you have found another XSS vulnerability or your web application firewall is rejecting the request because the request contains suspicious content. In this case it's not a PF bug however. Might be a false positive as well. Maybe the _ALERT_? Btw, the log also says _not blocked_. Maybe just informal?

If you think you've a found problem with PF, please create an issue containing detailed information on how to reproduce the problem.

**Comment by anouartrigui** [comment]
If you can see, this is my source code:


---------------xhtml-----------------
<h:form id="form-logo" enctype="multipart/form-data">
                                <div class="col-md-4">                                    
                                        <p:fileUpload id="file-logo"  fileUploadListener="#{abonneAccount.fileUploadListenerLogo}"
                                            allowTypes="/(\.|\/)(gif|jpe?g|png)$/" sizeLimit="1000000"  mode="advanced" 
                                            label="Choisir" auto="true"  onstart="PF('statusDialog').show()"  
                                            oncomplete="javascript:window.location.reload()" 
                                            dragDropSupport="true" invalidSizeMessage="la taille de l'image est trop grande" 
                                            invalidFileMessage="n'est pas une image valide."    />                            

                                    </div>
                            </h:form>
​​​​​​--------------AbonneAccountMB.java------------------
 
public void fileUploadListenerLogo(FileUploadEvent event) {

        setLogo(event.getFile());
        log.info("Start uploading logo " + getLogo().getFileName());
        uploadLogo();

    }
-------------------------------------------------------------
ANd in my web.xml i have the following part: 

<filter>
    <filter-name>PrimeFaces FileUpload Filter</filter-name>
    <filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>
  </filter>
  <filter-mapping>
    <filter-name>PrimeFaces FileUpload Filter</filter-name>
    <servlet-name>Faces Servlet</servlet-name>
  </filter-mapping>
Thank you for your prompt response

**Comment by anouartrigui** [comment]
When I temper data by uploading an image, I will find the Post Parameter content as follows, 
and this will be blocked by the firewall because it is vunerable to XSS attacks (see the \r\n\ in the Post Parameters, do you know how to avoir this? 


-----------------------------46941713230281\r\nContent-Disposition: form-data;
name="form-logo"\r\n\r\nform-logo\r\n-----------------------------46941713230281\r\nContent-Disposition: form-data; name="javax.faces.ViewState"\r\n\r\nOwpRWrzfkN8hD9Q2BWPksU1Al3IqmQ1r9bMKSRsI8ibAF9NT9sEzKP0db+VQPH2GsHN9w3wWJZdL/ZtH4P677eXxDmbc1tqU03IeqYMl7oYP+GkXnGMTHdTF1LSWFtYgy3cOawpmo0YuiquUtTjPUAdgehsiVL4onm4p0hg4eK/4CHbz1pMlbwtBLhgDImbt6Ddg4rv6+8c9hNRzUfkGGlnBVIxOtnopNBLxSb9mMq9fSgLXmcKScb9QqnPFHeDYT86gLFiVsD+bvijR1/2rctkKQvooya2PS6SuDI/iDeRKnq2BxNYAUV2hjtQwSJ9uLEq1pbwGmfxtEOgzUib3zDr3mjuRG/ZUc7/oikYZ429xcfIiwJCt5rPeczRw35VtfD5IZXNpSvqEqg37hfRY+HG41EVuQNuGx2YtnPIQ4sUhDRRs2OJqktodlLunGz8Sbofl+1lOParJg84OAR67c7z/ccocdbybOh/IX8vaodVFp5K+0XgywCG30hRCy0M29+DqHhl7MISaPZnJGzwg2jaBXfeVbJTq61R9gmc/NU8IELqBGvqyJDGfiKwodPPgdCsbAP6ZCB5aHXVCVXRpnS/iJQs/FKLlpzV2398SHJPnkOR1NCk65jmvu854TjhhNfH4RF1EZXhSvWUiHlq5/yjurj+bD3smHvgTmKuQpck9g/FZm9d7wd3nDB1p7+G6uH+DOX1u33ncY8yRl+JLEbirYPN6/U2b5Oty9+EoAdmFd5zsbb1uZ0R7WCh45XU0QtuEvDQWbzH0MZh7+guMoGHRCisAsoXa5MLbE2lEYenFHu6++6WhznbZBKa1Ol7TCVKYFBbx+MQs837180cXFDnabBxQ50g2VGf7AvqItDQdsMk8FtLMa5D3O4XM5tekuPhhwS1VawWFXRXReZUvIdGXAXwxrgpY7AvRqWJgG6RkuKtB68JweQw0SThaGoa8/w4YVcwWIOICoYzMIDMA7F3St88nYwO05LYMoujBa6OnAyeHlqgeMi2tSgZoP239Y6mjpxk2GXWiwdb+ezlgSH3LwsQsXLXmL4P3/MrWkSb35AryEvyKY1AF5laM0b3srIidnLQx3ZscBZS2hKTtATm4zNpm96pUqDPPW49epXZdQ/4DuDJ6dyZaMG31LnlMl7oM2xtQ6YRnwtugS5bA/g5QtlZ2icB+Uiu7+rs92DHt4IlvMbg9ePmqRckJre29ZBmwIC4Nr+71sqWgIKKu33DRwcNap7DFGsWaa2IEzsCnfTvdhJoq6hqpuNuJ3VFk2xNidNfXNbt/KxMxUayUaXSFTh273xXj7uExHX18ZxU=\r\n-----------------------------46941713230281\r\nContent-Disposition: form-data; name="javax.faces.partial.ajax"\r\n\r\ntrue\r\n-----------------------------46941713230281\r\nContent-Disposition: form-data; name="javax.faces.partial.execute"\r\n\r\nform-logo:file-logo\r\n-----------------------------46941713230281\r\nContent-Disposition: form-data; name="javax.faces.source"\r\n\r\nform-logo:file-logo\r\n-----------------------------46941713230281\r\nContent-Disposition: form-data; name="form-logo:file-logo"; filename="4.png"\r\nContent-Type: image/png\r\n\r\nPNG\r\n \n

-------------

**Comment by cnsgithub** [comment]
@anouartrigui 
1. Please use markdown syntax correctly: https://guides.github.com/features/mastering-markdown/ 
2. What you're describing is most likely not related to PF but to your WAF.
3. If you still think it is, please provide an issue following PF's issue template and provide a minimal, complete and verifiable example as described here: https://stackoverflow.com/help/mcve

**Pull request merged**
