### PR TITLE
Fix #5649: Log dev warning if first is not evenly divisible by rows

### LINKED ISSUE #5469: Exporter: XLSXSTREAM NullPointerException
Using the showcase basic example: https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml

Switch 
```xml
<p:dataExporter type="xls" target="tbl" fileName="cars" />
```

To:
```xml
<p:dataExporter type="xlsxstream" target="tbl" fileName="cars" />
```

It throws a NPE with the stack trace:
```
Dec 23, 2019 10:34:14 AM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
SEVERE: null
java.lang.NullPointerException
	at org.primefaces.component.datatable.export.DataTableExcelXStreamExporter.createSheet(DataTableExcelXStreamExporter.java:62)
	at org.primefaces.component.datatable.export.DataTableExcelExporter.doExport(DataTableExcelExporter.java:79)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.visit(DataTableExporter.java:350)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:127)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:910)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.lambda$invoke$0(DataTableExporter.java:369)
	at org.primefaces.util.ComponentUtils.invokeOnClosestIteratorParent(ComponentUtils.java:623)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.invoke(DataTableExporter.java:367)
	at org.primefaces.component.datatable.export.DataTableExporter.export(DataTableExporter.java:313)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:135)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:72)
```

### LINKED ISSUE #5649: DataTable: Pagination combined with first not correct
## 1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior
`<p:dataTable pagination="true" rows="20" first="105" ...>` should be the 6th item on the 6th page. 

## 3) Actual behavior
The 6th page is opened but the item is at the very top of that page. But if you go to another page and than back to page 6 again, the item is at the 6th position and not at 0 anymore.

grafik

What do you think. Should this be changed?

### PR DESCRIPTION
**Pull request by melloware**
Fix #5649: Log dev warning if first is not evenly divisible by rows

Prints out in JSF Stage Development:

```
Feb 21, 2024 9:18:04 AM org.primefaces.renderkit.CoreRenderer logDevelopmentWarning
WARNING: j_idt5 Invalid 'first' value 105 is not divisible evenly by 'rows' 20
```

### CODE REVIEW

**Review by Rapster — COMMENTED** [review]
This is the right place to put it, but not sure it makes sense if virtualscroll/livescroll enable though.

**Comment by melloware** [comment]
Good point I updated and also check development stage first as not it is evaluating more stuff.

**Comment by Rapster** [comment]
You can move that check here (up to you): https://github.com/primefaces/primefaces/blob/f805764f3b99f9c7a4333e74addf9139633b78b0/primefaces/src/main/java/org/primefaces/component/datatable/DataTableRenderer.java#L1030

so you don't have to check virtualscroll/livescroll again

**Comment by melloware** [comment]
Good call i moved it down there and removed the live and virtual checks

**Review by Rapster — APPROVED** [review]

**Pull request merged**
