### PR TITLE
Fix #10046: InputNumber integration test

### LINKED ISSUE #10046: InputNumber: valueChange after updating without actually changing the value
### Describe the bug

InputNumber fires valueChange event even though the value was not changed at all. This happens when it gains focus during an update. (e.g. tab from other input that caused the InputNumber to be updated)

### Reproducer

see: https://github.com/jungm/primefaces/commit/52683d1d9b76d60938a528955d1efe512602cbc4

### Expected behavior

valueChange event is not fired as the user made absolutely no inputs at all in the InputNumber

### PrimeFaces edition

None

### PrimeFaces version

13.0.0-SNAPSHOT

### Theme

_No response_

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Just trying this now that the code is merged to see if the result is any different.

### CODE REVIEW

**Comment by melloware** [comment]
@christophs78 no rush on this but neither @jungm or myself can get this test to fail locally and he has verified the code works in his real application so I know the fix is right I am just stumped as to why the test fails?

**Comment by christophs78** [comment]
Hm. Still the old JS code running inside my browser. --> First need to fix this.

**Comment by christophs78** [comment]
There seem´s to be some aggregation issue with inputnumber.js:

1-inputnumber.js is copied into inputnumber.js multiple times. First your new code, afterwards the old (not fixed) code.

image
image

**Comment by christophs78** [comment]
Some `clean install` later it work´s on my dev-machine. Let´s look what Github Actions thinks ...

**Comment by melloware** [comment]
yeah i thought our Selenium tests always worrked with fresh browser cache

**Pull request closed without merging**
