### PR TITLE
Make Tag implement UIOuptut (fix #8055)

### LINKED ISSUE #8055: Tag: add ValueHolder interface
**Description**
I was adding a converter to a p:tag but I found out I can't because Tag doesn't implement the ValueHolder interface.

**Describe the solution you would like**
Either make Tag implement [ValueHolder](https://docs.oracle.com/javaee/7/api/javax/faces/component/ValueHolder.html) or extend [UIOutput](https://docs.oracle.com/javaee/7/api/javax/faces/component/UIOutput.html)

### PR DESCRIPTION
**Pull request by NicolaIsotta**
Fix #8055

### CODE REVIEW

**Comment by melloware** [comment]
Please open a matching Issue ticket so we can link it.

**Comment by NicolaIsotta** [comment]
Issue is #8055 , should be already linked

**Comment by tandraschko** [comment]
you also need to add the converter attr to the taglib and please remove "final"

**Comment by NicolaIsotta** [comment]
Fixed and squashed

**Pull request merged**
