### PR TITLE
Fix #11875: Remove deprecation and restore SubTable demo

### LINKED ISSUE #11875: SubTable: still alive even after been announced deprecated in 10.0.0
### Describe the bug

`p:subTable` component still appears to be alive in PF, yet, showcase has been deleted for this compnent, still there in docs, any idea what we should do about this? 

### PrimeFaces version

15.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by melloware**
Fix #11875: Remove deprecation and restore SubTable demo

### CODE REVIEW

**Review by Rapster — APPROVED** [review]

**Comment by Rapster** [comment]
This can be port in 14.0 right?

**Comment by melloware** [comment]
Yep I already removed the 1 line deprecation warning in 14.0.1.  I didn't add the showcase example back though as the showcase doesn't seem to get deployed.

**Comment by Rapster** [comment]
I'm thinking if we're able to deploy 13/14/15, would be great to see this ?

**Comment by melloware** [comment]
No problem I will backport it.

**Comment by jepsar** [comment]
@melloware should we remove the note from the migration guide for version 10? WDYT?

https://stackoverflow.com/questions/79207470/display-multiple-psubtable-on-pdatatable

**Comment by melloware** [comment]
Yes we should!

**Comment by melloware** [comment]
OK Done!

**Pull request merged**
