### PR TITLE
Data table column cell editor rendered

### PR DESCRIPTION
**Pull request by bodabela**

### CODE REVIEW

**Comment by tandraschko** [comment]
Please provide a issue first with a detailed description.
Also your PR contains 2 changes, 1 is unrelated to the title.

**Comment by bodabela** [comment]
Ok. Thanks Thomas,

Let me get more conform with your work.
I am really into something else based on primefaces and I find these bugs
and I just wanted to let you know about them.

Generally they are all related to mistakes with the rendered. I think the
developers should be more careful with the rendered attribute :) It is
vital.

Cheers,
Bela

Thomas Andraschko notifications@github.com ezt írta (időpont: 2016. márc.
17., Cs, 9:19):

**Comment by tandraschko** [comment]
Sure, thanks for your work!
But we need a issue for each PR and a PR should contain changes for one issue.

**Comment by bodabela** [comment]
I have created the issues and PRs (#1220,#1246). Hope it works for you now.
And of course I owe you all guys with gratitude :)

By the way I am a big fun of primefaces and I always propose in the
upcoming projects.
I work with the latest version on my hobbi project only of course, but it
is pretty strange that there are so many broken features compared to 5.x
and they all related to rendered. What do you think, why is that?

Cheers,
B

Thomas Andraschko notifications@github.com ezt írta (időpont: 2016. márc.
17., Cs, 14:55):

**Comment by tandraschko** [comment]
This PR was about the rendered flag - the other PR is about another issue.
What about the rendered flag? If we should apply it, please create a new PR for it.

**Comment by tandraschko** [comment]
Nevermind, i the other PR contains this fix.

**Pull request closed without merging**
