### PR TITLE
CheckStyle EqualsAvoidNullCheck

### PR DESCRIPTION
**Pull request by melloware**
294 paces this violation occurred after I turned on the CheckStyle rule

### CODE REVIEW

**Comment by melloware** [comment]
If this is too big we can close this PR and I can do it again after 10.0 goes live.

I have also switched my Imports to match @Rapster and @sqores  which is...

org
javax
java
com

any imports with more than 5 get .*.

**Comment by tandraschko** [comment]
It would be much easier to turn off auto-reorder of imports.
It doesnt make any code better and just harder to review.

**Comment by tandraschko** [comment]
We should either
1) add IDE configs for codestyle in git and add checkstyle rules for import order
Or
2) add a readme that committers should disable auto format stuff. 

 
2. Is IMO much better...

**Comment by melloware** [comment]
I like the idea of coming up with what our standard is. Then adding check style rules to enforce it!

**Comment by tandraschko** [comment]
i just can say that i dont like that because to strict checks make it much harder to contribute and disable auto-formatting of the IDEs takes the most pain away.

**Comment by melloware** [comment]
Understood let me close this one and submit another with the bare minimum changes.

**Pull request closed without merging**
