### PR TITLE
Fix #2364 - overlaypanel fit viewport before showing

### LINKED ISSUE #2364: Dynamic overlaypanel display outside of viewport
## 1) Environment
- Current Showcase: PrimeFaces-6.1-SNAPSHOT on Mojarra-2.2.8.

## 2) Expected behavior

Overlaypanel should always try to display itself in visible viewport. If above the element is enough space it shall use this space instead below the element.

## 3) Actual behavior

Dynamic overlaypanel does not displays itself in visible viewport. 

## 4) Steps to reproduce

Decrease viewport size in showcase and click at dynamic button

overlaypanel-dynamic-outside

### PR DESCRIPTION
**Pull request by jxmai**
#2364

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
1) methods shoudl not begin begin with "_"
2) why do we need to store the initial width? IMO it's ok if it's resizes if the content changes

**Comment by jxmai** [comment]
> methods shoudl not begin begin with "_"

Done

> why do we need to store the initial width? IMO it's ok if it's resizes if the content changes

The internal design of overlay panel is only hiding the content on invisible state. If we don't store the supposed initial dimension, the width and height  cannot be recovered when there is enough room to show the overlay.

**Comment by tandraschko** [comment]
Can't follow you. Could you explain in detail?

**Comment by jxmai** [comment]
Say for example. If I change `fitViewPort` to be 

```js
fitViewPort: function() {
        var windowHeight = $(window).height();
        var windowWidth = $(window).width();

        if (windowHeight < this.jq.height()) {
            this.jq.height(windowHeight);
        } 
        if (windowWidth < this.jq.width()) {
            this.jq.width(windowWidth);
        } 
    },
```

If we have a narrow screen:

image


then show the overylay panel again on a larger screen. As you can see the previous resize function has affected the dimension

image

**Comment by tandraschko** [comment]
Yep of course. BUT if you have the smaller screen first, the overlaypanel would never resize, also if the window size increases.

**Comment by jxmai** [comment]
so what do you think ? :thinking:  just leave it as the following function and not to store initial value for  resizing afterward ?

```js
fitViewPort: function() {
        var windowHeight = $(window).height();
        var windowWidth = $(window).width();

        if (windowHeight < this.jq.height()) {
            this.jq.height(windowHeight);
        } 
        if (windowWidth < this.jq.width()) {
            this.jq.width(windowWidth);
        } 
    },
```

**Comment by jxmai** [comment]
IMHO, the overlay panel should detect the room available then show the content. Leaving narrow content when there is more room available is not user friendly. Keeping in mind that user could resize windows really often when docking the browser to a corner of a screen.

**Comment by tandraschko** [comment]
+1 for 

```js
fitViewPort: function() {
        var windowHeight = $(window).height();
        var windowWidth = $(window).width();

        if (windowHeight < this.jq.height()) {
            this.jq.height(windowHeight);
        } 
        if (windowWidth < this.jq.width()) {
            this.jq.width(windowWidth);
        } 
    },
```

however, it doesn't work for 100% as the margin is calculated.

**Comment by jxmai** [comment]
I slightly improved the PR, and please review. It's better to use `max-width` instead of width IMO. Also the width needs to be subtracted by the offset so that it won't go out of bound.

image

**Comment by jxmai** [comment]
Option 2 css only:  #2900

**Comment by tandraschko** [comment]
Tried it but didn't work for 100% as the scrollbar hides a part of the overlay.
Also the height calculation didn't work for 100%, not sure. I applied a very minimalistic version of the patch now, which only fixes the width.

**Comment by tandraschko** [comment]
But note: this is only a small part of #2364 and doesn't fix the issue at all.

**Comment by jxmai** [comment]
Alright, the width was more problematic in the first place, so the problem should be alleviated at least.

**Pull request closed without merging**
