### PR TITLE
Fix #3411: Diagram: Sync position

### LINKED ISSUE #3411: Diagram: allow synchronization of elements to the server
## 1) Environment
- PrimeFaces version: 6.1

## 2) Expected behavior
 After moving the elements in a p:diagram, there position should be updated.
 when a p:commandButton is pressed, the position of the elements are the same.

## 3) Actual behavior
 Diagram elements have always the same position in bean.

## 4) Steps to reproduce
Exemple https://www.primefaces.org/showcase/ui/data/diagram/basic.xhtml

## 5) Sample XHTML
```
<p:diagram  id="diagram" value="#{wfEngineBuilderBean.model}" var="el"  style="height:600px;border:none;" styleClass="ui-widget-content ui-create-diagram">
        <f:facet name="element">
                <h:outputText value="#{el.getCCode()}" style="cursor: default"/>
        </f:facet>
</p:diagram>
<p:commandButton process="@this, diagram" value="Guardar" styleClass="ui-button-yes" icon="fa fa-floppy-o" action="#{wfEngineBuilderBean.save}"   
..
```

## 6) Sample bean
```
public void save()
{
         for (Element element: model.getElements())
         {
                element.getX();
                element.getY()
          }
}
```

## ) Other exemple
https://forum.primefaces.org/viewtopic.php?p=155138

### PR DESCRIPTION
**Pull request by fanste**
of draggable elements with model on server site.

### CODE REVIEW

**Comment by melloware** [comment]
Thanks for the PR!

Don't forget to edit docs https://github.com/primefaces/primefaces/blob/master/docs/7_1/components/diagram.md

You need to add the new Ajax Behavior Event details and anything else relevant!

**Review by melloware — CHANGES_REQUESTED** [review]
See my comment on documentation.

**Comment by fanste** [comment]
Thanks again for the info :D Is this enough docu for that change?

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Yep good for me!

**Comment by aldolushkja** [comment]
Hi , in which version of Primefaces this will be available? Thanks

**Comment by tandraschko** [comment]
See the assigned version in the fixed ticket, which is linked here: https://github.com/primefaces/primefaces/issues/3411

**Comment by aldolushkja** [comment]
Thanks, good job!

**Pull request merged**
