### PR TITLE
Fix #5429: CSS replace zoom with transform

### LINKED ISSUE #5429: CSS: Replace non-standard zoom property
Go to the showcase page in Firefox 71+: https://www.primefaces.org/showcase/ui/panel/accordionPanel.xhtml

In the console it reports:

> This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

They are correct if you look here its a non standard CSS which used to be used to fix IE8 issues.
https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

It should be replaced with:
```css
transform: scale(1); /* Standard Property */
transform-origin: 0 0;  /* Standard Property */
```

**Components affected:**
- [x] Accordion
- [x] AutoComplete
- [x] Dialog
- [x] Forms
- [x] Menu
- [x] Paginator
- [x] Tabview
- [x] Tree
- [x] Omega Theme (@mertsincan)

### PR DESCRIPTION
**Pull request by melloware**
Everything but the Omage theme which has to be done by @mertsincan

### CODE REVIEW

**Comment by tandraschko** [comment]
does it work correctly in all other browsers?

**Comment by melloware** [comment]
I didn't notice anything different in IE11, Firefox, Chrome, Edge but wanted @mertsincan or @onursenture  or one of the PrimeTek CSS guys to weigh in on this.

**Comment by mertsincan** [comment]
Thanks a lot, @melloware ;)

**Comment by mertsincan** [comment]
Reverted this PR.

**Pull request merged**
