### PR TITLE
Fix #11994: TabView prevent detached DOM elements on TabClose

### LINKED ISSUE #11994: TabView: Memory leak on Tab close
### Describe the bug

When closing a tab the closed tab must clean up all its DOM elements to prevent detached elements and DOM memory leak.

### Reproducer

_No response_

### Expected behavior

When closing a tab it should not leave behind any detached DOM elements.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

_No response_

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

_No response_

### PR DESCRIPTION
**Pull request by melloware**
Fix #11994: TabView prevent detached DOM elements on TabClose

### CODE REVIEW

**Comment by tandraschko** [comment]
why did you refactor like this?

#fireTabCloseEvent should just fire the event, everything else was done before in #remove

**Comment by melloware** [comment]
So i will double check but since `cleanse` removes all elements, events, data off all elements when using `<p:ajax event="tabClose"` it could affect the lifecycle anything that was on that tab expecting the normal widget lifecycle so I chose to do if using `tabClose` to wait until the AJAX is done to clean up the DOM else just clean it up immediately if not using `tabClose`.

It felt like the cleaner / safer way to do it but I could be convinced otherwise?

**Comment by tandraschko** [comment]
both elements were already destroyed before sending the event in the past and also feels better for me
as there is no delay waiting for the ajax response, its just a notifier and we never had any feature request for something here

**Comment by melloware** [comment]
Ok I will test and update.

**Comment by melloware** [comment]
@tandraschko did some testing in my clients real world app.

### Test with just changing to `cleanseElement` instead of `panel.remove()`

Here is what it looks like with this PR where the cleans runs BEFORE the AJAX runs.  Memory recovered back from 16.5MB to 13.3MB.

image


### Current PR
Here is what it looks like with this PR where the cleans runs AFTER the AJAX runs and all the widget.destroy's properly take place.  Memory recovered back to from 16.5MB to 9.5MB and barely any detached elements in memory.

image

**Comment by melloware** [comment]
@tandraschko ok PR updated I got to the bottom of it.  In `cleansDomElement` we must call `jq.remove()` before removing all event listeners with `jq.off()`  This is so the widget `on("remove)` events get fire to register widgets as detached widgets so they clean themselves up.

I have verified with my testing above the memory is now recovered properly in my test scenario.

**Pull request merged**
