### PR TITLE
Fix #5776: FullCalendar 5.3.0

### LINKED ISSUE #5776: Schedule: Upgrade FullCalendar (4.x --> 5.x)
Something we may look into later this year. (Target PrimeFaces 9.0)

FullCalendar 5.x is currently at beta-state. Should go final in may 2020:
https://fullcalendar.io/blog/2020/04/v5-beta-released

### PR DESCRIPTION
**Pull request by melloware**
Tested with Showcase and everything is working properly.

### CODE REVIEW

**Comment by melloware** [comment]
Made this a draft so I can keep updating FullCalendar versions up until we are read to go with 9.0

**Comment by tandraschko** [comment]
I understand your point but i prefer to have only a few open PRs :D

**Comment by melloware** [comment]
OK I marked it ready for review. Safe to merge?

**Comment by tandraschko** [comment]
i'm not a user of the fullcalendar ;D better ask to review other schedule contributors

**Comment by melloware** [comment]
@blutorange can you eyeball this before I merge.  I tested all the showcase examples with it and seems straightforward,

**Comment by blutorange** [comment]
@melloware Looks good for the most part. The full calendar changelog for 6.3 only lists bug fixes, for 6.2 also mostly bug fixes and no breaking changes. I also checked out the showcase examples. A few minor things I noticed:

* showcase/ui/data/schedule/configureable.xhtml There are two empty buttons at the left header - which seems to be cause by the comma in the `leftHeaderTemplate` value `prev, next, today` (also the default according to the docs). When I remove the comma it looks good.

image
 
* The tooltip when hovering over an event seems to be a missing a background color?

image

*  showcase/ui/data/schedule/configureable.xhtml The option `displayEventEnd` either needs a fix or better documentation. When I set it to `false`, it shows the start and end time. According to the docs, it can also be set to something like `month:false,basicWeek:true`, but either that's not working or I don't know which keys to use.

image

**Comment by melloware** [comment]
OK let me investigate those two issue.

**Comment by melloware** [comment]
Fixed LeftheaderTemplate issue with https://github.com/primefaces/primefaces-showcase/pull/187

**Comment by melloware** [comment]
As for displayEventEnd I agree with you. We are doing the right things acccording to the docs so possibly its a bug in FullCalendar.
https://fullcalendar.io/docs/displayEventEnd

**Pull request merged**
