### PR TITLE
Improve OSGi and Liferay support

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
What are the changes in UIData?
They look ok but if it's a bugfix, we need a ticket plz :P

**Comment by stiemannkj1** [comment]
@tandraschko, with UIData, I ran into an issue with the fix for #3519. It seems like that issue should be reopened since my fix is basically improving the original fix for that ticket. But If you'd rather I open a new ticket, I will. Let me know.

**Comment by tandraschko** [comment]
Thats OK, Just a seperate PR would be great

**Comment by stiemannkj1** [comment]
@tandraschko, done:

- https://github.com/primefaces/primefaces/pull/3885
- https://github.com/primefaces/primefaces/pull/3886

**Pull request closed without merging**
