### PR TITLE
Fix #3894: Poll do not start polling if stop = true.

### LINKED ISSUE #3894: Poll: Fix "stop" attribute to not start polling if true
Looking in the poll.xml which generates the documentation for the component is this:

        <attribute>
            <name>stop</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Stops polling when true.</description>
        </attribute>

I cannot find anywhere this property is actually used and I have confirmed it does nothing setting this EL expression.  I think somewhere along the lines this component was modified to autoStart="" attribute but the stop was never removed.

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
Is it tested? This.config should be this.cfg?!

**Comment by melloware** [comment]
Sorry I just checked in that correction.  I had multiple things I was trying out and this was the simplest solution but somehow checked in one of my invalid attempts.  

yes I tested it, basically if Stop is true the component is marked inactive to start even if autoStart="true".

**Comment by tandraschko** [comment]
We should really think if we should merge it.
The documentation says "Stops polling when true."
I think it's ok to control 2 behaviors with 2 different flags.

**Comment by melloware** [comment]
I am ok with it that too.  I just thought it was strange if stop was = true on startup that others might be misled too.  I am definitely OK rejecting this PR.

**Comment by tandraschko** [comment]
Thanks but i would really close it for now as this are really 2 different behaviors

**Pull request closed without merging**
