### PR TITLE
Fix #5179: Document CSP.

### LINKED ISSUE #5179: Document CSP
@melloware interessted?

### PR DESCRIPTION
**Pull request by melloware**
@cnsgithub @tandraschko this was my starting point for CSP doc.  Feel free to suggest any changes or any other information I am leaving out.

### CODE REVIEW

**Comment by tandraschko** [comment]
I think we should mention that we decided for the "nonce" way instead hashes. Also we currently only do it for Scripts?

AFAIR f:ajax doesnt work, right? (We added some support to MyFaces 3.x but one thing is still not working)

**Comment by melloware** [comment]
I will add sections about NONCE vs hashes and that we currently only support script-src.

As for `f:ajax` should I mention that its a limitation of the Faces implementations and that `p:ajax` must be used?

**Comment by tandraschko** [comment]
I would do it for now, yep

**Comment by tandraschko** [comment]
+1 i Like it
Please put in core

Thanks, really appreciate your many contributions

**Comment by melloware** [comment]
No problem.  You did all the hard work...is a huge security win for PrimeFaces!

**Pull request merged**
