### PR TITLE
Fix #105, #6545, #6546: HTML5 Audio and Video components

### LINKED ISSUE #105: Media component with HTML5 Player
Consider using HTML5 player with Media component

### LINKED ISSUE #6545: Audio: New HTML5 Audio Component
**Description**
A new component to render the HTML5 `<audio>` tag.

See: https://github.com/primefaces/primefaces/issues/105

**Example XHTML**
```xml
<p:audio value="http://download.lisztonian.com/music/download/Larghetto+in+F-62.mp3" 
                 player="mp3"
                 controls="true"
                 onplay="console.log('MP3 Started Playing')"
                 onpause="console.log('MP3 Stopped Playing')">
            Your browser does not support the audio element. 
            See: <h:outputLink value="https://www.w3schools.com/html/html5_audio.asp">HTML5 Audio</h:outputLink>
</p:audio>
```

### LINKED ISSUE #6546: Video: New HTML5 Video Component
**Description**
A new component to render the HTML5 `<video>` tag.

See: https://github.com/primefaces/primefaces/issues/105

**Example XHTML**
```xml
<p:video value="https://www.w3schools.com/html/mov_bbb.mp4" 
                 player="mp4"
                 controls="true"
                 width="420"
                 height="250"
                 onplay="console.log('MP4 Started Playing')"
                 onpause="console.log('MP4 Stopped Playing')">
            Your browser does not support the video element. 
            See: <h:outputLink value="https://www.w3schools.com/html/html5_video.asp">HTML5 Video</h:outputLink>
</p:video>
```

### PR DESCRIPTION
**Pull request by melloware**
Showcase PR: https://github.com/primefaces/primefaces-showcase/pull/229

### CODE REVIEW

**Comment by tandraschko** [comment]
I Wonder If we should do real streaming here like chunks / html range param

**Comment by melloware** [comment]
I saw that in this article: https://medium.com/canal-tech/how-video-streaming-works-on-the-web-an-introduction-7919739f7e1

but all of that requires Javascript and I was trying to keep this similar to the media component for now and just have it render the HTML tag with the ability for Dynamic Content src.

**Comment by GedMarc** [comment]
nooo to real streaming? :) i get it but in real world your streaming server *has* to be separate to your web app, perhaps leave it to the browser?
, also image thumbnails on video and audio- 

video and audio tag takes poster tags as sources for thumbnails, :)

poster | URL | Specifies an image to be shown while the video is downloading, or until the user hits the play button

all attributes are below 

autoplay | autoplay | Specifies that the video will start playing as soon as it is ready
controls | controls | Specifies that video controls should be displayed (such as a play/pause button etc).
height | pixels | Sets the height of the video player
loop | loop | Specifies that the video will start over again, every time it is finished
muted | muted | Specifies that the audio output of the video should be muted
poster | URL | Specifies an image to be shown while the video is downloading, or until the user hits the play button
preload | auto/metadata/none | Specifies if and how the author thinks the video should be loaded when the page loads
src | URL | Specifies the URL of the video file
width | pixels | Sets the width of the video player

src can be optional to remove the embedded source video tags as well

This is a good move!

**Comment by melloware** [comment]
I will admit streaming seemed a little over my expertise on this so I am more than happy to accept the help.  My idea was to KISS and keep it simple stupid for the first iteration.

As for `poster` I am adding it for video but not for audio as its not common.

For the other properties you listed I already had them all. See here all all the common attributes and events that audio and video respect.
```java
    public static final List<String> MEDIA_ATTRS = LangUtils.unmodifiableList(
        "autoplay",
        "controls",
        "crossOrigin",
        "currentTime",
        "defaultMuted",
        "defaultPlaybackRate",
        "loop",
        "muted",
        "playbackRate",
        "preload",
        "volume"
    );

    public static final List<String> MEDIA_EVENTS = LangUtils.unmodifiableList(
        "onabort",
        "oncanplay",
        "oncanplaythrough",
        "ondurationchange",
        "onemptied",
        "onended",
        "onerror",
        "onloadeddata",
        "onloadedmetadata",
        "onloadstart",
        "onpause",
        "onplay",
        "onplaying",
        "onprogress",
        "onratechange",
        "onseeked",
        "onseeking",
        "onstalled",
        "onsuspend",
        "ontimeupdate",
        "onvolumechange",
        "onwaiting"
    );
```

**Review by Rapster — APPROVED** [review]

**Comment by tandraschko** [comment]
+1
however, we should add real streaming in future

and please also add it to "whats new" section in the docs

**Comment by melloware** [comment]
Added whatsnew items and I agree in the future we should modify for streaming

**Pull request merged**
