### PR TITLE
Fix #5506: Datatable destroy clones on refresh.

### LINKED ISSUE #5506: DataTable: DOM memory leak on widget.refresh()
1) Environment
- PrimeFaces version: 7.0+
- Does it work on the newest released PrimeFaces version? NO
- Does it work on the newest sources in GitHub? NO
- Application server + version: ALL
- Affected browsers: ALL

## 2) Expected behavior

When calling `widget.refresh(cfg)` there should not be multiple duplicate cloned THEAD objects.

## 3) Actual behavior

For scrollable datatable if you open F12 Console and execute `widget.refresh(cfg)` to refresh the datatable you will see multiple identical THEAD_CLONE DOM elements get created.
```xml
<thead class="ui-datatable-scrollable-theadclone" style="height: 0px;"></thead>
<thead class="ui-datatable-scrollable-theadclone" style="height: 0px;"></thead>
<thead class="ui-datatable-scrollable-theadclone" style="height: 0px;"></thead>
```

## 4) Steps to reproduce

1. Create a Scrollable Datatable.
2. In F12 Console type `widget.refresh(widget.cfg)`
3. Observe duplicate THEAD.

## 5) Sample XHTML

```xml
<p:dataTable id="tblScroll" widgetVar="widget" var="car" value="#{dtScrollView.cars2}" scrollable="true" scrollWidth="100%" resizeMode="expand" paginator="true" rows="2" sortMode="multiple">
                <p:column headerText="Id" footerText="Id" sortBy="#{car.id}" filterBy="#{car.id}">
                    <h:outputText value="#{car.id}" />
                </p:column>
                <p:column headerText="Year" footerText="Year">
                    <h:outputText value="#{car.year}" />
                </p:column>
                <p:column headerText="Brand" footerText="Brand">
                    <h:outputText value="#{car.brand}" />
                </p:column>
                <p:column headerText="Color" footerText="Color">
                    <h:outputText value="#{car.color}" />
                </p:column>
</p:dataTable>
```

## 6) Sample bean

From Showcase.

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
Are the clones not inside the main element?

**Comment by melloware** [comment]
The clones get attached to the datatable body. 
```javascript
clone.removeAttr('id').addClass('ui-datatable-scrollable-theadclone').height(0).prependTo(table);
```

**Comment by tandraschko** [comment]
but shouldn't it be replaced on upadting the whole p:dataTable?

**Comment by melloware** [comment]
Sorry I should have mentioned yes everything works fine using AJAX updates.  The issue is I am using pure JS to update based on this project using this example JS:

Forum Post: https://forum.primefaces.org/viewtopic.php?t=41378

Project: https://github.com/noamik/primefacesDTRedrawIssue

Example JS: https://github.com/noamik/primefacesDTRedrawIssue/blob/master/src/main/webapp/dataTableHelper.js

Because Scrollable Datatable does not readjust on viewport resize we have a Javascript helper which does the resizing and calls table.refresh() widget method.

**Comment by tandraschko** [comment]
ok; then please add a better comment

**Comment by melloware** [comment]
Comments updated to reflect the "why".

**Comment by tandraschko** [comment]
I wonder If we should remove it Just before, where it gets added?

**Comment by melloware** [comment]
I can definitely do that if its preferable. Maybe that is better.  Let me update the PR.

**Comment by tandraschko** [comment]
perfect!

**Pull request merged**
