### PR TITLE
Fix #6360, #6361: AJAX respect form enctype

### LINKED ISSUE #6360: Ajax: support form enctype
Currently we completely ignore the enctype of the form

See: https://github.com/primefaces/primefaces/issues/6351

### LINKED ISSUE #6361: AJAX: support processing input files
like f:ajax does

see: https://github.com/primefaces/primefaces/issues/6351

### PR DESCRIPTION
**Pull request by melloware**
Based on this article how to do multi-part with Jquery:
https://mkyong.com/jquery/jquery-ajax-submit-a-multipart-form/

### CODE REVIEW

**Comment by melloware** [comment]
Still testing this...

**Comment by melloware** [comment]
Something i still not right:

Here is f:ajax:
```
Request URL: http://localhost:8080/primefaces-test/test.xhtml
Request Method: POST
Status Code: 200 OK
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-cache
Content-Type: text/xml;charset=utf-8
Date: Mon, 28 Sep 2020 17:58:59 GMT
Server: Jetty(9.4.31.v20200723)
Transfer-Encoding: chunked
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 1998717
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDLc7af9IDiCzzImW
Cookie: JSESSIONID=node08gw9forov9dr1suen2dzkvhxi0.node0; _ga=GA1.1.540967662.1599240369
Host: localhost:8080
Origin: http://localhost:8080
Referer: http://localhost:8080/primefaces-test/test.xhtml
Sec-Fetch-Dest: iframe
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
```

Here is p:ajax with the new code:
```
Request URL: http://localhost:8080/primefaces-test/test.xhtml
Request Method: POST
Status Code: 200 OK
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
Content-Length: 2825
Content-Type: text/html;charset=utf-8
Date: Mon, 28 Sep 2020 17:54:54 GMT
Server: Jetty(9.4.31.v20200723)
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 999282
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryjfBA90z90DMsEcam
Cookie: JSESSIONID=node08gw9forov9dr1suen2dzkvhxi0.node0; _ga=GA1.1.540967662.1599240369
Host: localhost:8080
Origin: http://localhost:8080
Referer: http://localhost:8080/primefaces-test/test.xhtml
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
X-Requested-With: XMLHttpRequest
form: form
form:text: 
form:file1: (binary)
form:file2: (binary)
javax.faces.ViewState: 4174472176819151704:-4353180437160294190
```

**Comment by tandraschko** [comment]
did you use process=@none?

Could be that the formData automatically adds all inputs now

**Comment by melloware** [comment]
OK let me look I also see there is this method in core.ajax `createFacesAjaxFormData` used by File Upload Simple.

**Comment by melloware** [comment]
OK I now have it working much closer!  Its ALMOST working.
```xml
<h:inputFile id="file1" value="#{testView.file}" pt:class="ignore">
	<p:ajax listener="#{testView.handleFileUpload}" update="@form" />
</h:inputFile>
```

It is updating the form and the request looks good but the `listener="#{testView.handleFileUpload}"` is still not being called.

**Comment by melloware** [comment]
OK I got it all working!

**Comment by tandraschko** [comment]
Bit confused. The request params are now added a second time in the FormData?

**Comment by melloware** [comment]
Yes so to make this work the current params are ignored.

```javascript
processData: false,  // Important!
```
That makes it a MutliPartForm data and does not encode the current data it takes a Serialized `FormData` object.  So all of the params have to be added to the `FormData`.

so..
```javascript
 formData = new FormData(form[0]);
```
That serializes the form and all its INPUTS.  However now we have to inlcude all of the PF special variables that would normally be encoded as params into that FormData.

It looks like `3-fileupload-simple.js` was already doing this it just didn't care about Behavior Events.

**Comment by tandraschko** [comment]
You now serialize the whole form which also breaks partial submit.

**Comment by tandraschko** [comment]
I think it needs refactoring to add params either to the Ajax or FormData object

**Comment by melloware** [comment]
Agreed I wanted to get it all working first.  Refactoring is next step.

**Comment by tandraschko** [comment]
We may also think about to always use FormData, not sure

**Comment by tandraschko** [comment]
I can also do it the next weeks, i really like to do refactorings by myself in this area

**Comment by melloware** [comment]
No problem.

**Comment by melloware** [comment]
Converted to a draft just so you can see it will close once you commit your changes.

**Pull request closed without merging**
