### PR TITLE
#3778, #3740 update schedule documentation

### PR DESCRIPTION
**Pull request by OBreidenbach**
#3778, #3740 update schedule documentation

### CODE REVIEW

**Comment by tandraschko** [comment]
Sorry, renamed the dir to 7_0

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
How can you Approve when it conflicts? :p

**Comment by melloware** [comment]
I just reviewed it for its contents of what he changed not for what was conflicting.

**Comment by OBreidenbach** [comment]
I have a questions. In the documentation the attributes of the components are in the order when they were added. That makes it hard to find a specif attribute in the table, especially if the component does have a lot of them.
Wouldn't it be much nicer, if the attributes would be in a more predictable order? Maybe alphabetically, maybe some basic attributes (like: id, value, ...) at the top.

**Comment by tandraschko** [comment]
Sure

**Comment by mertsincan** [comment]
> Wouldn't it be much nicer, if the attributes would be in a more predictable order? Maybe alphabetically, > maybe some basic attributes (like: id, value, ...) at the top.

Yes, unfortunately we need to do this manually in all *.md files :( But, maybe we can use markdown table sort plugin -> https://marketplace.visualstudio.com/items?itemName=simonguo.vscode-markdown-table-sort

I'll try it.

**Comment by mertsincan** [comment]
WDYT?

https://github.com/primefaces/primefaces/blob/master/docs/7_0/components/datatable.md

**Comment by tandraschko** [comment]
Thats also weird 😅
Id Binding widgetvar are much more common

**Comment by mertsincan** [comment]
@tandraschko, could you please change them :D

**Comment by melloware** [comment]
Just my two cents and maybe we just fix pages as the community offers a new PR on a component that we make that part of the checklist rather than editing all 100 pages by hand right now...just edit them as we make changes.

**Common:**
ID
WidgetVar
Rendered
Binding

**Attributes:**
(alphabetical order)

**Callbacks:**
onStart
onComplete
onClick
etc...

**Comment by OBreidenbach** [comment]
@melloware I like your suggestion

**Comment by tandraschko** [comment]
+0.75
Common + Callbacks as name makes sense. But this are all Attribute, so "Attributes" is not a good label


WDYT mert?

**Comment by melloware** [comment]
Yep I couldn't think of what to call it maybe "Custom" or "Component Specific"

**Comment by tandraschko** [comment]
I also wonder if it makes sense to add facets + behaviors the same table?
At lest we should make it the same in all widgets (the order - but we can make is as sections of course):
- short description
- renderer class and this stuff
- attributes
- behaviors
- facets
- client side API

**Pull request merged**
