### PR TITLE
Selenium 4; some Firefox & Safari - work (WIP)

### PR DESCRIPTION
**Pull request by christophs78**
On my dev-notebook Firefox works fine together with selenium 4. But on Github Actions we fail to start Firefox.
Maybe interesting detail:  Headless seems to get ignored for Firefox on my dev-notebook. (But `-headless` work´s when i start Firefox from windows terminal)
I´ll keep an eye on this.

### CODE REVIEW

**Comment by melloware** [comment]
Looks like we are getting a consistent failure on Chips004Test as well that just started today.

**Comment by melloware** [comment]
Its so weird this is what I am getting locally..

```
org.opentest4j.AssertionFailedError: expected: <apple, orange, banana> but was: <overlay.css('position', 'fixed'), >
```

**Comment by melloware** [comment]
ahh our code to copy to the clipboard looks like it no longer is copying to clipboard.

```java
 /**
     * Copy the current value in the Input to the clipboard.
     *
     * @return the value copied to the clipboard
     */
    public String copyToClipboard() {
        WebElement input = getInput();
        Keys command = PrimeSelenium.isMacOs() ? Keys.COMMAND : Keys.CONTROL;
        input.sendKeys(Keys.chord(command, "a")); // select everything
        input.sendKeys(Keys.chord(command, "c")); // copy
        return input.getAttribute("value");
    }
```

We might have to disable this test for now.

**Comment by christophs78** [comment]
I may look into this tomorrow. Too tired for today.
My current feeling points me to something Github Actions - related. This already worked with Selenium 4. And it works with a new PR for Firefox.

**Comment by melloware** [comment]
No worries go to bed!

**Comment by christophs78** [comment]
The last successful running CI was with 
```
Virtual Environment
Environment: ubuntu-20.04
Version: 20220131.1
```

The first failing CI is with
```
Virtual Environment
Environment: ubuntu-20.04
Version: 20220207.1
```

--> Seems to be related to this.

**Comment by christophs78** [comment]
Version 20220131.1 - https://github.com/actions/virtual-environments/blob/ubuntu20/20220131.1/images/linux/Ubuntu2004-Readme.md
- Google Chrome 97.0.4692.99
- ChromeDriver 97.0.4692.71

Version 20220207.1 - https://github.com/actions/virtual-environments/blob/ubuntu20/20220207.1/images/linux/Ubuntu2004-Readme.md
- Google Chrome 98.0.4758.80
- ChromeDriver 98.0.4758.80

**Pull request closed without merging**
