### PR TITLE
Fix #2416

### LINKED ISSUE #2416: SelectCheckboxMenu doesn't support SelectItemGroup
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Wildfly 9.0.2
- Affected browsers: Chrome 58, IE11

## 2) Expected behavior
Show an header for the select items group and many checkbox for select items
desidered

## 3) Actual behavior
It shows one checkbox per select item group
actual

## 4) Steps to reproduce
Create a SelectCheckboxMenu with a list of SelectItem 

## 5) Sample XHTML
<p:selectCheckboxMenu id="multiple" value="#{checkboxView.selectedCars}" label="Cars" multiple="true">
            <f:selectItems value="#{checkboxView.cars}" />
        </p:selectCheckboxMenu>

## 6) Sample bean

@ManagedBean
public class CheckboxView {
 
    private List<SelectItem> cars;
    private String[] selectedCars;
 
    @PostConstruct
    public void init() {

        cars = new ArrayList<SelectItem>();
        SelectItemGroup germanCars = new SelectItemGroup("German Cars");
        germanCars.setSelectItems(new SelectItem[] {
            new SelectItem("BMW", "BMW"),
            new SelectItem("Mercedes", "Mercedes"),
            new SelectItem("Volkswagen", "Volkswagen")
        });
         
        SelectItemGroup americanCars = new SelectItemGroup("American Cars");
        americanCars.setSelectItems(new SelectItem[]{
            new SelectItem("Chrysler", "Chrysler"),
            new SelectItem("GM", "GM"),
            new SelectItem("Ford", "Ford")
        });
 
        cars.add(germanCars);
        cars.add(americanCars);
    }
 
    public List<SelectItem> getCars() {
        return cars;
    }
 
    public void setCars(List<SelectItem> cars) {
        this.cars = cars;
    }
 
    public String[] getSelectedCars() {
        return selectedCars;
    }
 
    public void setSelectedCars(String[] selectedCars) {
        this.selectedCars = selectedCars;
    }
}

### PR DESCRIPTION
**Pull request by ValerioEmanuele**
* Added SelectItemGroup capability to SelectCheckboxMenu

### CODE REVIEW

**Comment by ValerioEmanuele** [comment]
Added to SelectCheckboxMenu the SelectItemGroup management capability.

**Review by melloware — APPROVED** [review]
Nice work

**Comment by tandraschko** [comment]
Is that styling really required? If i check those classes for selectOneMenu, there is no such additional styling for the group

**Comment by ValerioEmanuele** [comment]
Yes I know this and I agree with you. 
On my opinion in this way the grouping it's more clear, further I think that this component it's an advanced component so it can be more rich. But this is just my opinion.

Of course you know more the PrimeFaces guidelines,  so I think that it's your decision if that styling should be removed.

**Comment by tandraschko** [comment]
I think we should do the following:
- You should align your PR without the additional styling
- Create a new issue to enhance the styling of the grouping (with screenshots and the code)

**Comment by ValerioEmanuele** [comment]
@tandraschko style removed and Issue #2431 opened.

**Comment by tandraschko** [comment]
Applied and did some small alignements. Thanks!

**Comment by ValerioEmanuele** [comment]
It's a pleasure working with you!

**Comment by tandraschko** [comment]
good to hear, thanks! :)

**Pull request merged**
