### PR TITLE
Fixed #3450

### LINKED ISSUE #3433: Datatable: filter do not work with UIInput Components in the data rows
## 1) Environment
- PrimeFaces version: 6.1/6.2
- Does it work on the newest released PrimeFaces version? Neither 6.1 nor 6.2
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
no
- Application server + version: wildfly 11 / jetty-8.1.9
- Affected browsers: every browser

## 2) Expected behavior
I have a datatable with 3 columns Firstname | Lastname | Gender which represents a list of customers.
In the Gender column there is a SelectOneMenu in each row to choose the gender for each Customer.
It should be possible to filter the customer by firstname and lastname.

## 3) Actual behavior
If I filter by firstname or by lastname at the first time the filter works. 
But in the Post request there are the values of the SelectOneMenu. 
If I filter the second time, jsf triggers the valueChangedEvent of the SelectOneMenus and I get an IllegalStateException.
I guess this is because the second time (the table is already filtered) some values of the SelectOneMenus are missing. 

`java.lang.IllegalStateException
        at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1052)
        at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1054)
        at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1054)
        at org.primefaces.component.selectonemenu.SelectOneMenu.queueEvent(SelectOneMenu.java:309)
        at javax.faces.component.UIInput.validate(UIInput.java:991)
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1248)
        at javax.faces.component.UIInput.processValidators(UIInput.java:712)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1258)
        at org.primefaces.component.api.UIData.process(UIData.java:382)
        at org.primefaces.component.api.UIData.processChildren(UIData.java:366)
        at org.primefaces.component.api.UIData.processPhase(UIData.java:328)
        at org.primefaces.component.api.UIData.processValidators(UIData.java:301)
        at org.primefaces.component.datatable.DataTable.processValidators(DataTable.java:844)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:575)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
        at org.primefaces.component.api.UIData.visitTree(UIData.java:827)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIForm.visitTree(UIForm.java:371)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1193)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:368)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:943)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1004)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:748)`

## 4) Steps to reproduce
Filter by firstname or by lastname 2 times. 

## 5) Sample 
[https://github.com/floriandulzky/primefaces-test](https://github.com/floriandulzky/primefaces-test)

### LINKED ISSUE #3450: Datatable: scrollHeight 100% not working since PF 6.2
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: jetty / wildfly
- Affected browsers: chrome

## 2) Expected behavior
If I set the property scrollHeight="100%" the datatable height should be calculated.

## 3) Actual behavior
If I set the property scrollHeight="100%" the datatable height won't be calculated.

## 4) Steps to reproduce
set primefaces version to 6.2 (in 6.1 it works)
set datatable scrollHeight="100%" (without % scrollHeight works)

## 5) Sample XHTML
`
<p:dataTable id="testtable" value="#{datatabletest.customers}"
			var="customer" paginator="true" rows="50"
			paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
			rowsPerPageTemplate="10,50,100,200" stickyHeader="true"
			filterDelay="1000" sortBy="#{customer.firstname}"
			binding="#{datatabletest.dataTable}" scrollHeight="100%" scrollable="true" style="height: 100%;">
			<p:column headerText="Firstname" filterBy="#{customer.firstname}">
				<h:outputText value="#{customer.firstname}" />
			</p:column>
			<p:column headerText="Lastname" filterBy="#{customer.lastname}">
				<h:outputText value="#{customer.lastname}" />
			</p:column>
			<p:column>
				<p:outputPanel rendered="#{not empty customer}" required="false">
					<p:selectOneMenu value="#{customer.gender}" id="gender-select" >
						<f:selectItems value="#{datatabletest.genderList}" />
					</p:selectOneMenu>
				</p:outputPanel>
			</p:column>
		</p:dataTable>
`

## 6) Sample bean

`
@ViewScoped
@ManagedBean(name="datatabletest")
public class DatatableTestManagedBean {
	
	private LazyDataModel<Customer> lazyCustomer;

	private List<Customer> customers;
	private List<String> genderList;
	private DataTable dataTable;
	private SelectOneMenu selectOneMenu;
	
	@PostConstruct
	public void init() {
		this.customers = new ArrayList<Customer>();
		for(int i = 0; i < 150; i++) {
			this.customers.add(new Customer("Florian " + i, "D.", "Male"));
			this.customers.add(new Customer("Christian " + i, "K.", "Female"));			
		}
		this.genderList = new ArrayList<String>();
		this.genderList.add("Male");
		this.genderList.add("Female");
	}
... getters/setters
}
`

### PR DESCRIPTION
**Pull request by floriandulzky**

### CODE REVIEW

**Comment by tandraschko** [comment]
Does this really work? "(this.jq.children('.ui-datatable-header') > 0)"
does children really return a array? i thought it returns a jquery wrapper, so "> 0" shouldn't work on a object?!

**Comment by melloware** [comment]
Agreed wouldn't it have to use .length like this.jq.children('.ui-datatable-header').length > 0 ??

**Comment by tandraschko** [comment]
I really wonder what happens here? What will be returned when the selector is empty and you call .outerHeight(true) on it?
Doesn't it return 0?

**Comment by floriandulzky** [comment]
image

it will return undefined

**Comment by tandraschko** [comment]
Yep, ok. Damn :/
We could store the result of the .children call in variable, maybe someone like @melloware would do it?

I will merge it for now. Thanks!

**Comment by melloware** [comment]
@tandraschko I will take care of that right now.

**Comment by melloware** [comment]
I just submitted this PR and I found a 2nd place in the datatable code where this was happening and added the fix in that place as well.
https://github.com/primefaces/primefaces/pull/3838

**Pull request merged**
