### PR TITLE
Fix #12933: FileUpload rename directoryPath and fix path check

### LINKED ISSUE #12933: UploadedFile#write broken
the param is currently called filePath, but its actually the directory. If yes we should return the whole filepath then and rename the param to directory.
we should also check docs

### PR DESCRIPTION
**Pull request by melloware**
Fix #12933: FileUpload rename directoryPath and fix path check

### CODE REVIEW

**Comment by tandraschko** [comment]
Should we return the File instead of void?

**Comment by melloware** [comment]
probably a good idea!

**Comment by melloware** [comment]
Updated

**Comment by tandraschko** [comment]
Thanks!

**Pull request merged**
