### PR TITLE
Fix #11879: FileUpload prevent NPE for CSV

### LINKED ISSUE #11879: FileUpload (advanced): DragAndDrop not working, javascript error
### Describe the bug

If you drop a file into a fileupload with dragDropSupport="true" or a custom zone dropZone="customDropZone", then a javascript error is logged to the console and the file is not uploaded

### Reproducer

To reproduce the error you can use the Primefaces showcase.
In the showcase, navigate to ```/showcase/ui/file/upload/dnd.xhtml```
Then drag a supported file (jpeg, gif or png file of max size 100kb) from the file explorer to the fileupload component or the associated drop zone.
An error is logged to the javascript console and the file is not processed/uploaded.

Currently (2024-05-06), the showcase at Primefaces [http://www.primefaces.org/showcase/ui/file/upload/dnd.xhtml?](http://www.primefaces.org/showcase/ui/file/upload/dnd.xhtml) uses Primefaces version 13.0.9 and it works as expected.

If you build and run the showcase for 14.0.0 or the latest 15.0.0-SNAPSHOT in your computer it fails.

This javascript error is logged to the console (Chrome)
```
jQuery.Deferred exception: Cannot read properties of undefined (reading 'data') TypeError: Cannot read properties of undefined (reading 'data')
    at HTMLDivElement.add (http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:2035:48)
    at $.<computed>.<computed>._trigger (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=14.0.0:717:13)
    at File.<anonymous> (http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:1375:23)
    at Function.each (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:3129)
    at $.<computed>.<computed>._onAdd (http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:1368:9)
    at $.<computed>.<computed>._onAdd (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery-plugins.js.xhtml?ln=primefaces&v=14.0.0:143:25)
    at http://localhost:8080/showcase/javax.faces.resource/fileupload/fileupload.js.xhtml?ln=primefaces&v=14.0.0:1629:18
    at c (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:25304)
    at fireWith (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:26053)
    at e (http://localhost:8080/showcase/javax.faces.resource/jquery/jquery.js.xhtml?ln=primefaces&v=14.0.0:2:27300) undefined
```

### Expected behavior

A message confirming the file have been uploaded

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### Theme

_No response_

### JSF implementation

All

### JSF version

2.3

### Java version

11

### Browser(s)

Tested in Chrome and Firefox

### PR DESCRIPTION
**Pull request by melloware**
Fix #11879: FileUpload prevent NPE for CSV

### CODE REVIEW

**Comment by tandraschko** [comment]
hmm, fixing a simple NPE here feels like CSV doesnt work then with drag drop?

**Comment by melloware** [comment]
I think you might be right. I didn't fully understand how this drag and drop scenario was supposed to work.

**Comment by melloware** [comment]
@christophs78 @tandraschko i would appreciate some help analyzing this as the FileUpload CSV stuff is new in 14.0.0 so i hope its fresh in your minds 😄

**Comment by christophs78** [comment]
Start thinking and analysing ...
Related issues where we may check related commits: https://github.com/primefaces/primefaces/issues/11001, https://github.com/primefaces/primefaces/issues/11043, https://github.com/primefaces/primefaces/issues/11044

**Comment by melloware** [comment]
I closed the PR for now as deeper analysis is required and I don't use CSV so i am not gonna burn any time on this one.

**Comment by christophs78** [comment]
Yep. Seems to require way more time. The bad thing is it´s - from a users point of view - not related to CSV.
Drag´n´drop-support for p:fileUpload was simply broken by Thomas modifications.
But we will find solutions at some point in the future.

**Pull request closed without merging**
