### PR TITLE
Fix #5608 - FileUpload: Refactor decoders

### LINKED ISSUE #5608: FileUpload: Refactor decoders
I was having a look at #5594 and I figured the whole decoding thing could be simplified

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by melloware** [comment]
Nice cleanup!

**Comment by christophs78** [comment]
Very welcome improvement!

**Comment by tandraschko** [comment]
Can you please test it in a servlet 2.5 environment? I assume that the serviceloader fails for the native entry

**Comment by tandraschko** [comment]
@rapster shouldn't decodeAdvanced also use UploadedFileWrapper?

**Comment by tandraschko** [comment]
is it tested in servlet 2.5 now?

**Comment by Rapster** [comment]
Not failing in Servlet 2.5 for native entry, but still have to make sure everything is working fine after merging #5615

**Review by melloware — APPROVED** [review]

**Comment by christophs78** [comment]
I´d like to see this merged into master so i can progress with https://github.com/primefaces/primefaces/pull/5607.

**Comment by melloware** [comment]
@Rapster are you all done your changes. I can squash and merge this if its ready. it looks good to me.

**Comment by Rapster** [comment]
Yes I'm done with the changes

**Pull request merged**
