### PR TITLE
Change in AutoComplete.

### PR DESCRIPTION
**Pull request by fbrissi**
In multiple selection by pressing backspace and have no more text to erase the previous selection as works in gmail.

### CODE REVIEW

**Comment by tandraschko** [comment]
Looks like the same PR? -> https://github.com/primefaces/primefaces/pull/1083

**Comment by fbrissi** [comment]
Yes, I didn't know this.

**Comment by tandraschko** [comment]
Thanks for the PR but please test it next time. It crashes with an JS error.
I fixed it and applied your changes.

**Comment by fbrissi** [comment]
Sorry, I could not wait one version, I made a overide in my code and then moved on to the fork . I will create an environment for testing . Thanks for the comment .

**Pull request closed without merging**
