### PR TITLE
Fix #11836 - SONAR: enable quality checks on JS/CSS files

### LINKED ISSUE #11836: SONAR: enable quality checks on JS/CSS files
### Description

For the very same reasons as we do for java files, we should also do it for JS/CSS files

### Describe the solution you would like

report JS/CSS issues on sonarcloud

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rapster**

### CODE REVIEW

**Comment by melloware** [comment]
Are we worried about this creating too many issues 😀

**Comment by Rapster** [comment]
Besides the 3.4K of "Unexpected var, use let or const instead", it's about 450 issues (some of them look legit) I don't think it's that much...

**Comment by melloware** [comment]
That is not bad at all.   I guess we would just turn the "use let instead of var" rule off?

**Comment by Rapster** [comment]
Yup I just did (you can either merge it, or wait for my local build to be over toee the final results)

**Pull request merged**
