### PR TITLE
Fix #146,#2363,#3585: Exporter set font for PDF/Excel

### LINKED ISSUE #146: Customizable font in PDFExport
Add option to change font in pdf export

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
not sure about the default font.... I would make it null or something, is that possible?
JFYI: arial doesn't exist on linux

**Comment by melloware** [comment]
Interesting.  Those were the 2 default fonts PrimeTek had in the code before I refactored.
PDF = Times
Excel = Arial

I don't feel like a NULL font is a good idea so maybe we should find a font that is common to Windows/Linux?

**Comment by tandraschko** [comment]
no idea
what is the default in POI e.g.?

**Comment by melloware** [comment]
OK POI has this in the docs.
https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/usermodel/XSSFFont.html#DEFAULT_FONT_NAME

> By default, Microsoft Office Excel 2007 uses the Calibri font in font size 11

So I will switch to use this constant XSSFFont.DEFAULT_FONT_NAME

DEFAULT_FONT_NAMEBy default, Microsoft Office Excel 2007 uses the Calibri font in font size 11
--

**Comment by melloware** [comment]
No definitely NOT as Cilibri will never be on a linux system as its a Microsoft font.  I can't believe no one noticed this before I just downloaded an XLSX using PrimeFaces Exporter in my production app using Red Hat Linux and the XLSX downloads fine and when I open it the font is "Arial".  So on Red Hat Linux it appears to be working.  

What do you recommend?  Or maybe Excel is smart enough to downgrade if it doesn't find the font listed when you open the excel doc?

**Comment by tandraschko** [comment]
ok, then i think its ok to not change the defaults for now
+1 for the PR

**Pull request merged**
