### PR TITLE
Fix #2127: Picklist prevent client side manipulation.

### LINKED ISSUE #2127: Picklist: disabled items allow for client-side manipulation
This may cause security issues in cases where people rely on the disabled items assignment not being able to be manipulated on the client-side.

## 1) Environment
- PrimeFaces version: 6.0 and 6.0.15 and newest
- Does it work on the newest released PrimeFaces version? Version?
- Application server + version: Apache Tomcat 8.5.11
- Affected browsers: All

## 2) Expected behavior
Disabled items cannot be transferred from source to target list or vice-versa.
Real behaviour: 

## 3) Actual behavior
Items can be transferred from source to target list or vice-versa by client-side manipulation, by removing the disabling CSS style class.

## 4) Steps to reproduce
I use a picklist with "itemDisabled" property.
The disabled entries can't be dragged or transferred from source list to target list and vice versa, as one would expect.

However, by simply removing the style class, e.g. via jQuery
`$('ul.ui-picklist-list > li.ui-state-disabled').removeClass('ui-state-disabled');`
I am able to swap items between the source and target lists.
These changes are then applied to the model (here: `personBean.personAssignment` DualListModel) upon submit, because a respective server-side check is missing.

## 5) Sample XHTML
```
<p:pickList id="personAssignment"
            value="#{personBean.personAssignment}"
            var="person"
            itemDisabled="true"
            itemLabel="#{person.toString()}"
            itemValue="#{person}"/>
```

## 6) Sample bean

```
public class PersonBean {
  private DualListModel<Object> personAssignment;

  public DualListModel<Object> getPersonAssignment() {
    if (personAssignment == null) {
        List<Object> source = Arrays.asList(new String[]{"One", "Two"});
        List<Object> target = Arrays.asList(new String[]{"A", "B"});
        personAssignment = new DualListModel<>(source, target);
    }
    return personAssignment;
  }

  public void setPersonSelection(DualListModel<Object> personAssignment) {
    this.personAssignment = personAssignment;
  }

}

```

### PR DESCRIPTION
**Pull request by melloware**
1. Cleaned up the example code
2. Chose to use javax.faces.component.UIInput.UPDATE as the error message which will be "An error occurred when processing your submitted information."
3. Refactored to make the validate method more readable now that it includes both REQUIRED validation and client side scrubbing validation.

### CODE REVIEW

**Review by Rapster — CHANGES_REQUESTED** [review]
Please remove these cumbersone "this.xxx". I got rid of all of them recently

**Comment by melloware** [comment]
"this." has been removed.   Man I am not a big fan of the Whitepsace checkstyle rules.

**Comment by Rapster** [comment]
What's wrong with it?

**Comment by melloware** [comment]
@Rapster to me it seems overly cumbersome it just took me 3 attempts to understand why it was wrong I had this...

`new Object[] { label }`

And it wanted...

`new Object[] {label}`

To me that is not making the code better its just going to annoy committers like me who just had to spend 10 minutes fixing whitespace issues.  Just my two cents.

And Sonar is now failing for some reason that is past my CheckStyle checks something about couldn't connect to localhost:9000?

**Comment by tandraschko** [comment]
Yup, looks like sonarcube still failing.
@Rapster can you fix it? Otherwise i have to revert this changes. It's annoying that maven-build fails because something additional like sonarcube fails.

**Comment by tandraschko** [comment]
and @melloware 
i actually also use this in my applications:
`new Object[] { label }`

i just added the check to validate that we use the same whitespaces everywhere. We can also change the definition that we must add spaces after { and before }

**Comment by Rapster** [comment]
No need to revert, it has been correctly built
`The command "mvn install -Dmaven.javadoc.skip=true --batch-mode --show-version" exited with 0.`

Something's wrong with SonarQube server, there might some custom configuration for PR (see https://sonarcloud.io/documentation/integrations/github)

Regarding formatting, we should share Eclipse/IntelliJ/Netbeans formatting preferences. I never had to complain about it since IDE do it for me...

**Comment by Rapster** [comment]
@melloware Try updating your branch please. I tried to disable SonarCloud for PR

**Comment by Rapster** [comment]
I was more thinking, you sycnhronizing your branch with master but that works too :wink:

**Comment by tandraschko** [comment]
@rapster would you Like to retest it? Seems like @cnsgithub doesnt have much time currently 😪

**Pull request merged**
