### PR TITLE
Fix #4238: SelectOneRadio: support readonly

### LINKED ISSUE #4238: SelectOneRadio: support readonly
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Not with 6.2
- Application server + version: Tomcat 8.0
- Affected browsers: Firefox 63.0.1

## 2) Expected behavior
When I set `readonly="true"` on a `p:selectOneRadio` with `layout="custom"` I expect radio buttons to be rendered as read-only (not clickable).

## 3) Actual behavior
When I set `readonly="true"` on a `p:selectOneRadio` with `layout="custom"` radio buttons are clickable, although some kind of JavaScript code is called after my click to restore the original selection state of buttons. So, even if, in the end, the selectOneRadio value cannot be changed, the current implementation is quite confusing for the end user  (it seems like the interface is joking on him/her...)

Please note that setting `readonly="true"` on all radio buttons as well seems to have no effect.

## 4) Steps to reproduce
Create a  `p:selectOneRadio` with `layout="custom"` and `readonly="true"` and a couple of radio buttons.

## 5) Sample XHTML

```xhtml
<p:selectOneRadio id="myRadioButton"
  value="#{myBean.value}" layout="custom" readonly="true">
  <f:selectItem itemValue="true" />
  <f:selectItem itemValue="false" />
 </p:selectOneRadio>
<p:radioButton id="trueRB" for="myRadioButton" itemIndex="0" /><p:outputLabel for="trueRB" value="True!" /><br/>
<p:radioButton id="falseRB" for="myRadioButton" itemIndex="1" /><p:outputLabel for="falseRB" valure="False!" />
```

## 6) Sample bean
```java
public class MyBean {
  private boolean value = true;
  // setter and getter omitted
}
```

### PR DESCRIPTION
**Pull request by jepsar**
Fix #4238

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by jepsar** [comment]
Should we disable the failing IT? Or is someone working on it?

**Comment by melloware** [comment]
We are still discussing.  In the other thread @christophs78 determined it was an update to the GitHub Actions environment Google Chrome version that broke it.

**Comment by christophs78** [comment]
I can reproduce this issue on my dev-notebook with chrome 98. I plan to fix it this evening.

**Comment by christophs78** [comment]
It´s a Chrome 98 - bug:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999
--> so we may disable this one test until Chrome 99

**Review by melloware — CHANGES_REQUESTED** [review]
Do we need to add to the selectOneRadio.md in 12.0 docs this new `readonly` property?

**Comment by jepsar** [comment]
Right! Forgot to add it.

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
can we add a integration test?
sorry for asking that often currently but it makes it easier as i dont have to retest it and makes PF more stable

**Comment by melloware** [comment]
@jepsar it should be easy to add a test for readonly here is my one for Rating.  You could also add the `isReadOnly()` method to the Selenium Component itself like I did in Rating.

```java
@Test
    @Order(3)
    @DisplayName("Rating: read only")
    public void testReadonly(Page page) {
        // Arrange
        Rating rating = page.ratingReadOnly;
        Assertions.assertEquals(3L, rating.getValue());
        Assertions.assertTrue(rating.isReadOnly());

        // Act
        rating.setValue(5);

        // Assert
        Assertions.assertEquals(3L, rating.getValue());
        JSONObject cfg = assertConfiguration(rating.getWidgetConfiguration());
        Assertions.assertTrue(cfg.getBoolean("readonly"));
    }
```

The one thing you could add is a check for `Assertions.assertFalse(PrimeSelenium.isElementClickable(xxx);)` to make sure its not clickable as well.

**Review by melloware — APPROVED** [review]

**Pull request merged**
