### PR TITLE
Added viewFormat to set all parameters as per http://fullcalendar.io/docs/views/View-Specific-Options/

### PR DESCRIPTION
**Pull request by tryptichon**
Added viewFormat (http://fullcalendar.io/docs/views/View-Specific-Options/)
Added showWeekNumber

### CODE REVIEW

**Comment by tryptichon** [comment]
Changed time conversion to avoid loss of DST times.

**Comment by tryptichon** [comment]
TimeZone / DST calculation should be correct now.

**Comment by tryptichon** [comment]
Closing pull request because this here handles multiple issues in one request. Trying to create separate pull requests for each issue.

**Comment by cagataycivici** [comment]
Thank you.

**Pull request closed without merging**
