### PR TITLE
Fix #6053: Switch client cookies to HTML Local Storage

### LINKED ISSUE #6053: Storage: Switch from cookies to HTML5 local storage
**Description**
Based on a conversation with @GedMarc cookies were used for storing client side state because legacy browers like IE7 could only support cookies.  

**Describe the solution you would like**
Now that PF supports IE11 and higher we should switch client cookie usage for HTML5 LocalStorage which has the same lifespan as a cookie does but allows for more than 4KB of values and is the proper way to handle this type of behavior today.

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

### PR DESCRIPTION
**Pull request by melloware**
- Tested and works perfectly
- Solves any future cookie security issues by not using cookies

@blutorange @ravihariharan

### CODE REVIEW

**Comment by GedMarc** [comment]
datatables :)

**Comment by melloware** [comment]
@GedMarc I found every reference to these PrimeFaces.getCookie() etc methods and only PlainMenu, PanelMenu, and Carousel came up in my search.  Does Datatable also use cookies?

**Comment by tandraschko** [comment]
What about PrimeFaces.download Cookie? It was used on the clientside as well

**Comment by melloware** [comment]
Yep let me look at the download cookie i see it now.

**Comment by melloware** [comment]
Had to restore cookie methods to support file download.  As far as I can tell its the only place in all of PF now using cookies.

**Comment by tandraschko** [comment]
TBH i would remove our setStore etc. wrappers
we would need to call them setLocalStore as we soon need sessionStorage for ClientWindow.

**Comment by melloware** [comment]
I like that. let me make that change.

**Comment by GedMarc** [comment]
ahh not for data tables 1.10 and up - i'm out of date 
https://datatables.net/forums/discussion/26654/prevent-datatables-from-creating-cookies

**Comment by tandraschko** [comment]
we dont use "datatables" - we have own script

@melloware 
we probably need to add the contextPath somehow
the storage shares between domains

**Comment by melloware** [comment]
@tandraschko I am confused i thought local storage was domain based already: https://jcubic.wordpress.com/2014/06/20/cross-domain-localstorage/

So are we saying we do NOT want it domain based?

**Comment by GedMarc** [comment]
oo, ok so i understand as 

* localstorage is a perm store, cookies can be a perm store
* cookies can have expiry, localstorage requires manual expiry 

localstorage is for state (client side), cookies are for server-side identifiers, usually only identity

localstorage domains are separated by sub domain

it's about what data is required on the server and what isn't :) sessionstorage comes into play when doing 2-phase authentication, perm logins, long lasting tokens etc that you want killed on tabclose, client side ViewScope data as it were

change of behavior will be experienced when the cookie default expiry would clear the data, now the data will persist until cleared

**Comment by tandraschko** [comment]
@melloware domains are ok
but look how stateKeys are are generated
`this.stateKey = 'carousel-' + this.id;`

this misses the viewId + contextPath

currently the state could unintentionally shared between views and even between webapps inside the same domain

**Comment by melloware** [comment]
AHH ok so right you are saying if someone had a carousel on 2 different pages and both were called `id="carouselTest"` it would share that config.  So by adding viewId and context it makes it unique per page per site.  I understand now.  Let me work on that.

**Comment by melloware** [comment]
OK I am seeing something really strange even on the showcase and I tested my production apps as well.  I see this code in HeadRenderer:
```java
        writer.write("if(window.PrimeFaces){");
        writer.write("PrimeFaces.settings.locale='" + LocaleUtils.getCurrentLocale(context) + "';");
        writer.write("PrimeFaces.settings.viewId='" + context.getViewRoot().getViewId() + "';");
        writer.write("PrimeFaces.settings.contextPath='" + context.getExternalContext().getRequestContextPath() + "';");
```

However in my UI when I look at page source the values for viewId and context are never there...only the locale is coming through?
```javascript
--
if(pf){pf.settings.locale='en';pf.settings.validateEmptyFields=true;pf.settings.considerEmptyStringNull=true;};
```

**Comment by melloware** [comment]
OK its MOVE_SCRIPTS_TO_BOTTOM. When I turn it off I get the full values.
```javascript
if(window.PrimeFaces){PrimeFaces.settings.locale='en';PrimeFaces.settings.viewId='/index.xhtml';PrimeFaces.settings.contextPath='/showcase';PrimeFaces.settings.validateEmptyFields=true;PrimeFaces.settings.considerEmptyStringNull=true;}
```

**Comment by tandraschko** [comment]
weird
would be great if you can check it.

**Comment by melloware** [comment]
@tandraschko I am an idiot. You just added those in 9.0 and I am testing with 8.0 and showcase is on 8.0 so of course those props are not there!  I had just assumed they had been there forever.  OK now I can fix this ticket.

**Comment by melloware** [comment]
OK updated and now it generates a unique key like this:
```
carousel-form:j_idt729-ui-data-carousel.xhtml-showcase
```
Component + ID + View + ContextPath

**Comment by tandraschko** [comment]
i would change it:
context - view - component - id

**Comment by melloware** [comment]
OK i switched it to your order.

**Comment by tandraschko** [comment]
i thought about it and i think we should switch a bit:
context - view - id - key (instead of component; i think some components could store different stuff under different keys)

**Comment by melloware** [comment]
@tandraschko Good idea I will fix...

**Comment by tandraschko** [comment]
perfect
last cosmetics: could we switch the id and key method param? id is important, key probably optional

**Comment by tandraschko** [comment]
Great PR, thank you!

**Comment by tandraschko** [comment]
do you know whats wrong with the travis build?

**Comment by melloware** [comment]
Hmm looking at it is just saying it failed the JSDOC step parsing core.js but it doesn't say what is failing.

**Comment by melloware** [comment]
nevermind I see it.  Will fix.

**Comment by schaeferm** [comment]
Hi there. I really like the idea of this fix. However I noticed that this is a big change from the stateful cookie based implementation. With the old implementation one could create menus with shared state across multiple pages. This is no longer possible and now possibly messes with many main menus. Can you please implement a parameter that allows for the old global state saving instead of the new view based one?

**Comment by tandraschko** [comment]
sounds weird
localStorage is shared between all pages in the same application?

**Comment by schaeferm** [comment]
But the generated keys are per page and so the menu now saves the state per page.

**Comment by melloware** [comment]
@schaeferm is correct we use the view based ID so each page gets a unique local storage.  We would need a new option for Menu to be global which would generate its key not using the ViewId.

**Comment by melloware** [comment]
@schaeferm can you please open a new ticket.

**Pull request merged**
