### PR TITLE
Fix #9179: Exporter support dynamic column groups

### LINKED ISSUE #9179: DataExporter: support dynamic grouped columns with ui:repeat
### Describe the bug

The showcase page :
http://primefaces.org/showcase/ui/data/datatable/group.xhtml?jfwid=f547e 
shows the issue. 
After exporting data to  XLSX - button on the top right - the data export for second table (Dynamic Columns tab in export) does not show any header for dynamic columns ( 2010 2011 2012 2013 2014 - are missing).

Environment: v.12 ( tested also in v.11 - same issue)

image

### Reproducer

_No response_

### Expected behavior

_No response_

### PrimeFaces edition

_No response_

### PrimeFaces version

11.0.0 and up

### Theme

_No response_

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

### Browser(s)

all

### PR DESCRIPTION
**Pull request by melloware**
Fix #9179: Exporter support dynamic column groups

@tandraschko you were right had to use `forEachColumn` and now it works!

### CODE REVIEW

**Comment by tandraschko** [comment]
we should also change this for TreeTable exporter etc.?
Also we could add a new fuction #forEachColumnGroup to make the code easier and reusable

**Comment by melloware** [comment]
Added new `forEachColumnGroup` callback to return each `row` of a column group.  This cleans up the code nicely and added TreeTable support.

**Comment by tandraschko** [comment]
+1 if well tested
cool change!

**Comment by tandraschko** [comment]
Just wonder if it shouldnt be forEachRow? as you pass the ColumnGroup

**Comment by melloware** [comment]
I renamed it `forEachColumnGroupRow` I didn't want to throw someone off thinking `forEachRow` meant each row in the DT.

**Pull request merged**
