### PR TITLE
Fix #7004: Refactor resolveAppendTo

### LINKED ISSUE #7004: DatePicker: JS-Error in destroy and refresh
**Describe the defect**
When the DatePicker widget should be removed during `PrimeFaces.ajax.Response.destroyDetachedWidgets` it will throw a JS error because of an illegal usage of a utililty method.

grafik

```Javascript
// ... code from refresh
PrimeFaces.utils.cleanupDynamicOverlay(this, this.panel, this.id + '_panel', this.cfg.appendTo);

// ... code from destroy
PrimeFaces.utils.removeDynamicOverlay(this, null, this.id + '_panel', this.cfg.appendTo);
```

In both cases `this.cfg.appendTo` is a string - per default `@(body)`. But both utility methods expect a JQuery instance. (see [here](https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/core/core.utils.js#L83))

**Environment:**
 - PF Version: 10.0.0-RC1
 - Affected browsers: ALL

### PR DESCRIPTION
**Pull request by melloware**
@tandraschko refactored to pass in panel and fixed the DatePicker cleanup overlay issue

### CODE REVIEW

**Comment by tandraschko** [comment]
thanks!

**Comment by vonnai** [comment]
hi, why should be overlay panel scrolled together with content when dialog fitViewPort = true? I expect that the overlay panel is always fixed to its input component. After your fix, there is not any solution to how to stop scrolling of overlay panel with dialog content together. If I set appendTo e.g. :dialogFormId:dialogContentId, it will be ignored and will be appended to the body. Thanks for you reply.

image

**Comment by melloware** [comment]
@vonnai have you tried 10.0.0RC2?  I believe this is already fixed.

**Comment by vonnai** [comment]
@melloware I have not tried yet, but as I see there are not any changes in selectonemnu.js. The original appendTo method has been only moved to another lib class, haven't been? The code is the same as in 8.0.3 for forms.selectonemu.js. Why is overlay panel appended to the body if it's inside dialog?

```
if(!overlay.parent().is(document.body)) {
                    widget.cfg.appendTo = "@(body)"
                    return widget.cfg.appendTo;
                }
```

**Comment by melloware** [comment]
@vonnai there were 3 major fixes done for 10.0.0.RC2 I am begging you to try it.  Trust me its fixed.

https://github.com/primefaces/primefaces/issues/6978

https://github.com/primefaces/primefaces/issues/6973

**Comment by vonnai** [comment]
@melloware ok thanks, I'll try it.

**Pull request merged**
