### PR TITLE
Fix #9004: Menus: Add badge support to menu items

### LINKED ISSUE #9004: Menus: Add badge support to menu items
### Description

I would like to be able to use a badge on specific menu items of a menu to indicate that there are to dos within them.

### Describe the solution you would like

I hope we can do something similar as what we did with SpeedDial.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jepsar**
Fix #9004

Screenshot 2022-08-21 at 11 56 49

```xhtml
        <div class="card">
            <h5 class="mt-0">Basic</h5>
            <p:tabMenu activeIndex="#{param.i}">
                ...
                <p:menuitem value="Calendar" outcome="/ui/menu/tabMenu" icon="pi pi-fw pi-calendar"
                            badge="#{menuBadgeView.badgeModel}">
                    <f:param name="i" value="1"/>
                </p:menuitem>
                ...
            </p:tabMenu>
        </div>
```
```java
    @PostConstruct
    public void init() {
        badgeModel = DefaultBadgeModel.builder()
                .severity("danger")
                .build();
    }
```

### CODE REVIEW

**Comment by jepsar** [comment]
@melloware WDYT? Is it okay to add to the other menu components?

**Comment by melloware** [comment]
I think so i think this is a great addition!

**Comment by jepsar** [comment]
Okay, I'll continue to work on this then.

**Comment by jepsar** [comment]
Actually I only had to change the `TieredMenuRenderer`.

**Comment by jepsar** [comment]
Ah, no, need to add docs... one sec

**Review by melloware — APPROVED** [review]
This looks great and thanks for adding showcase demo too.

**Pull request merged**
