### PR TITLE
Fix #5625: Hotkey add disabled attribute

### LINKED ISSUE #5625: Hotkey: Add support for disabling a hotkey via disabled attribute
## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: all
- Affected browsers: all

## 2) Expected behavior
There are many use cases where a user wants to disable hotkeys from the server side.
One example is the display of a modal dialog where it is expected that page related hotkeys are disabled.

See also discussion in: [https://forum.primefaces.org/viewtopic.php?f=3&t=61198](url)

The obvious solution is add a `disabled` attribute to the component.

I will provide a pull request for this.

Support for widget representation will be done in a different issue/pr.

## 3) Actual behavior

Support for this is missing.

### PR DESCRIPTION
**Pull request by stolp**
This implements a disabled attribute for the hotkey component. I also added a test case to issue #5625

@melloware Please review.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Can you update the new 9.0 documentation as well please.

**Comment by tandraschko** [comment]
and IMO we should remove the getter/setter docu
they are all documented in the taglib only

**Comment by stolp** [comment]
I will take care of this.

**Comment by melloware** [comment]
@stolp any update on this PR?

**Comment by melloware** [comment]
@tandraschko I will take care of updating the 9.0 docs and code review comments

**Comment by stolp** [comment]
I am travelling this week and will not be able to do anything until next week.

**Comment by melloware** [comment]
@stolp  I already took care of it.  made the fixes and updated the docs and merged it.

**Pull request merged**
