### PR TITLE
Fix #3245: Timeline updates.

### LINKED ISSUE #3245: Timeline: Migrate to vis.js
http://almende.github.io/chap-links-library/

> CHAP Links Library now has a successor: vis.js. A couple of fundamental limitations in the current architecture of CHAP Links Library have been reached. Therefore, a new initiative has been started, aiming at more flexible data manipulation, better performance, and expandable visualization tools.

http://visjs.org/

### PR DESCRIPTION
**Pull request by melloware**
- Timeline 6.1.0 release
- Add ~strikethrough~ in docs for deprecated attributes
- Fixed RTLAware since it was updated since the original PR to a default interface

Adding @jasonex7 @christophs78 for awareness.

### CODE REVIEW

**Comment by jasonex7** [comment]
Considering this https://github.com/primefaces/primefaces/pull/5257#discussion_r340375246 I suggest remove the following properties from the taglib which has NO replacement:

- `dragAreaWidth`
- `unselectable`
- `groupsOnRight`
- `showButtonNew`
- `showNavigation`
- `animate`
- `animateZoom`
- `groupsWidth`
- `groupMinHeight`

Edited: Missed groupsWidth and groupMinHeight properties

**Comment by melloware** [comment]
I found the following marked as deprecated:

- animate
- animateZoom
- axisOnTop
- dragAreaWidth
- groupMinHeight
- groupWidth
- groupsChangeable
- groupsOnRight
- showButtonNew
- showNavigation
- snap
- timeChangeable
- unselectable

Can you confirm this list is bigger than your list?

**Comment by jasonex7** [comment]
In my previous comment I missed groupsWidth and groupMinHeight properties.

The following 4 properties are really deprecated in java code as the behavior is practically the same as other new properties and the `TimelineBase` class can handle automatically:

- `axisOnTop`
- `groupsChangeable`
- `snapEvents`
- `timeChangeable`

So I suggest this 4 properties remain as deprecated in taglib file and also in documentation, but the other 9 properties (following list) disappear from taglib and documentation because they don't have direct replacement and `TimelineBase` class can't handle. All 13 properties should be in migration guide.

- `dragAreaWidth`
- `unselectable`
- `groupsOnRight`
- `showButtonNew`
- `showNavigation`
- `animate`
- `animateZoom`
- `groupsWidth`
- `groupMinHeight`

**Comment by melloware** [comment]
Thanks for the clarification.  I removed those props.  Migration guide looks good.

**Pull request merged**
