### PR TITLE
Fix #5255 #4992 #4693: ImageCropper switch to Cropper.js

### LINKED ISSUE #5255: ImageCropper: Use Cropper.js
Currently ImageCropper uses JCrop https://github.com/tapmodo/Jcrop which has 54 open pull requests and no activity in the last almost 2 years.

Would like to upgrade to Cropper.js https://fengyuanchen.github.io/cropperjs/ which is actively maintained.

We have open ImageCropper issues that could be addressed:
https://github.com/primefaces/primefaces/issues/4992
https://github.com/primefaces/primefaces/issues/4693

Current Status:
- Removed backgroundColor and backgroundOpacity as they don't have equivalents in Cropper.js the default background is transparent.
- Looking for equivalent of boxWidth and boxHeight

### PR DESCRIPTION
**Pull request by melloware**
This PR is just for review its not ready yet to merge.

Still need to figure out what to do about boxHeight and boxWidth.

### CODE REVIEW

**Comment by melloware** [comment]
BoxHeight and Width might be https://github.com/fengyuanchen/cropperjs#getcroppedcanvasoptions

maxWidth: the maximum destination width of the output canvas, the default value is Infinity.
maxHeight: the maximum destination height of the output canvas, the default value is Infinity.

**Comment by tandraschko** [comment]
last change of the cropper:  2018-04-01T06:20:13.168Z

are you sure this is MUCH better as the old one?

**Comment by melloware** [comment]
@tandraschko That Jquery wrapper is just the wrapper which doesn't change. The core library is Cropper.JS which was updated 17 days ago.  See this:  https://github.com/fengyuanchen/cropperjs

He has wrappers for Jquery, ReactJS etc, but the core library is what is important.

**Comment by tandraschko** [comment]
ok
+1 then if everything is working fine

**Comment by melloware** [comment]
I am still testing some things and waiting on an answer about boxHeight and boxWidth properties.

**Pull request merged**
