### PR TITLE
fix p:ajax not firing server side listener

### PR DESCRIPTION
**Pull request by paolopiccinini**
p:ajax inside p:textEditor is broken. It want not fire listener method.

### CODE REVIEW

**Comment by tandraschko** [comment]
Please create a valid issue first

**Comment by melloware** [comment]
Also you have a CheckStyle issue that needs to be resolved.

> [ERROR] /home/travis/build/primefaces/primefaces/src/main/java/org/primefaces/component/texteditor/TextEditorRenderer.java:36: 'method def' child has incorrect indentation level 16, expected level should be 8. [Indentation]

**Comment by tandraschko** [comment]
we should probably also add 
`
        if (!shouldDecode(inputText)) {
            return;
        }
`
to the decode method

**Comment by tandraschko** [comment]
Thanks for the PR

**Pull request merged**
