### PR TITLE
Fix #4790: DatePicker: client side setDate() sets wrong value

### LINKED ISSUE #4790: DatePicker: client side setDate() sets wrong value
## 1) Environment
- PrimeFaces version: 7.0.1
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Tomcat 8.5
- Affected browsers: Firefox, IE, Chrome

## 2) Expected behavior
When calling client side function "setDate('12/11/13')" of the DatePicker component, the corresponding inputfield should show the passed date and the popup calendar should show the month December and highlight the day "11".

## 3) Actual behavior
Apparently the function "setDate" sets the parsed date object as value to the input field. The input field uses the toString() method to display the date and showing "Wed Dec 11 2013 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)". The date is also not selected in the popup calendar.

## 4) Steps to reproduce
Simply call setDate() Method of the widget variable from the DatePicker component in JavaScript.

## 5) Sample XHTML
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Test Page</title>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	</f:facet>
</h:head>

<h:body>
	<h:form id="form">
		<p:outputLabel for="datepicker" value="DatePicker:"/>
		<p:datePicker id="datepicker" widgetVar="datepickerWdg" pattern="MM/dd/yy" />
		<br />
		<p:commandButton type="button" value="Set date (12/11/13)" onclick="PF('datepickerWdg').setDate('12/11/13')" />
	</h:form>
</h:body>
</html>
```

## 6) Sample bean
no bean necessary.
..

### PR DESCRIPTION
**Pull request by christophs78**
Showcase-PR: https://github.com/primefaces/showcase-facelift/pull/95

### CODE REVIEW

**Comment by christophs78** [comment]
Getting tired when fixing DatePicker-bugs in my spare time. Should play with my children who sit behind me...

**Comment by melloware** [comment]
Great work on this PR.  Your work on DatePicker has been much appreciated.

**Comment by mertsincan** [comment]
Thanks a lot @christophs78 ;) Thanks to you, the Datepicker has become better.

**Comment by cagataycivici** [comment]
@christophs78 Thank you for your contributions, please send an email to contact at primetek.com.tr, we'd be happy to grant you a license of Elite, Designer or a Premium Template of your choice.

**Pull request merged**
