### PR TITLE
Fixed #3028: SelectOneMenu reverting to actual value on mouse click

### LINKED ISSUE #3028: SelectOneMenu: Selected value is not reverted after clicking on same value in dropdown
## 1) Environment
- PrimeFaces version:
6.1.6
- Does it work on the newest released PrimeFaces version? Version?
No
- Does it work on the newest sources in GitHub?
No
- Application server + version:
Jetty
- Affected browsers:
Chrome
## 2) Expected behavior
Component displays actual value.

## 3) Actual behavior
Component displays pre-selected value.

## 4) Steps to reproduce

1. Select 'Xbox One' value
1. Click on SelectOne with mouse to open items.
1. By keyboard select another item - 'Wii U'.
1. By mouse click on 'Xbox One' item
1. 'Wii U' is displayed in the component. Expected: 'Xbox One' displayed.

## 5) Sample XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form>
          <p:selectOneMenu id="console" value="#{selectOneMenuView.console}" style="width:125px">
              <f:selectItem itemLabel="Select One" itemValue="" />
              <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
              <f:selectItem itemLabel="PS4" itemValue="PS4" />
              <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
          </p:selectOneMenu>
        </h:form>
    </h:body>
</html>
```
## 6) Sample bean
```
@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {
    
    private String testString;
    
    @PostConstruct  
    public void init() {
        testString = "Welcome to PrimeFaces!!!";
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }    
}

```

### PR DESCRIPTION
**Pull request by jajajaja**

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Looks good to me as long as you have tested it!

**Comment by jajajaja** [comment]
@melloware I've tested it.

**Comment by melloware** [comment]
Nice work.  Thanks for the PR!

**Comment by tandraschko** [comment]
@melloware did you retest it? Would always be great if someone from the "team" could retest it before applying the PR.

**Comment by melloware** [comment]
@tandraschko yep i tested it and it was working.

**Pull request merged**
