### PR TITLE
Fix #97: SelectOneMenu footer facet.

### LINKED ISSUE #97: Footer Facet for SelectOneMenu
Add support for optional footer facet in selectOneMenu.

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
+1 if well tested
but please add it to the documentation
not sure if we have a list of facets for other components already

**Comment by melloware** [comment]
It looks like we don't really have documentation for facets but I did add a showcase example showing the use of the footer facet.

**Comment by tandraschko** [comment]
feel free to apply the PR but i would really like to have a documentation about facets
selectOneMenu would be great to start (it only has header and footer)

**Comment by melloware** [comment]
OK let me add some docs for the facets

**Comment by tandraschko** [comment]
did you add css classes instead facets to the docu?

**Comment by melloware** [comment]
Good catch forgot to hit Save in my editor.  Added the RTL and Footer Styles.

**Comment by tandraschko** [comment]
+1

**Pull request merged**
