### PR TITLE
Crash when label value contains CSS selector special chars

### PR DESCRIPTION
**Pull request by xtron**
Issue https://github.com/primefaces/primefaces/issues/3612

### CODE REVIEW

**Review by cnsgithub — APPROVED** [review]

**Comment by tandraschko** [comment]
Please create a issue with example first.

**Comment by xtron** [comment]
created https://github.com/primefaces/primefaces/issues/3612

**Comment by tandraschko** [comment]
@melloware can you check?=

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@tandraschko verified this is a good change and I do not see any side effects.

**Pull request merged**
