### PR TITLE
Fix #8180: SelectOneRadio: improve ARIA accessibility of custom layout

### LINKED ISSUE #4569: Reimplemented RadioButton component
It may have a widget and we can move all custom events from SelectOneRadio.

### LINKED ISSUE #8180: SelectOneRadio: improve ARIA accessibility of custom layout
Problem with screen reader JAWS or NVDA
jaws(screen reader ) can't read element radioButton and read as 1 from 1 without label 

**Reproducer**
https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml?jfwid=574c3

**Environment:**
 - PF Version: 11
 - JSF + version: Mojarra 2.2.20 or MyFaces 2.3.9_
 - Affected browsers:  ALL

**To Reproduce**
1. run screen reader 
2. Click on Red radioButton 
3. listen reader 
4. select Green by arrow
5. listen reader 

**Expected behavior**
screen reader can read information from aria-label but input doesn't have it

**Example XHTML**
```html
[<h:form id="frmTest">
<p:outputPanel id="customPanel" style="margin-bottom:10px">
            <p:selectOneRadio id="customRadio" value="#{radioView.color}" layout="custom">
                <f:selectItem itemLabel="Red" itemValue="Red"/>
                <f:selectItem itemLabel="Green" itemValue="Green"/>
                <f:selectItem itemLabel="Blue" itemValue="Blue"/>
            </p:selectOneRadio>

            <h:panelGrid columns="3" cellpadding="5">
                <p:radioButton id="opt1" for="customRadio" itemIndex="0"/>
                <h:outputLabel for="opt1" value="Red"/>
                <p:spinner/>

                <p:radioButton id="opt2" for="customRadio" itemIndex="1"/>
                <h:outputLabel for="opt2" value="Green"/>
                <p:inputText/>

                <p:radioButton id="opt3" for="customRadio" itemIndex="2"/>
                <h:outputLabel for="opt3" value="Blue"/>
                <p:calendar/>
            </h:panelGrid>
        </p:outputPanel>
```

```

### LINKED ISSUE #8324: SelectOneRadio: HTML validation error when using required attribute
**Describe the defect**
When using selectOneRadio with attributes layout="grid", columns="3" and required="true", the selectOneRadio is rendered as a \<table>-element in the HTML DOM with the attribute aria-required="true". This HTML syntax causes a validation error when analyzing the site with the [Nu HTML Checker](https://validator.w3.org/nu/) as the attribute aria-required is not allowed on \<table>-elements.

**Environment:**
 - PF Version: _10.0_

**To Reproduce**
1. Add the example code below to your application.
2. Copy your site's HTML code into the [Nu HTML Checker](https://validator.w3.org/nu/) and start validation.
3. See validation error from Screenshot below.

**Expected behavior**
The attribute "aria-required" should not be added to the \<table>-element within selectOneRadios as it causes an HTML validation error and thus violates [WCAG success criterion 4.1.1](https://www.w3.org/TR/WCAG21/#parsing) for accessibility.

**Example XHTML**
```html
<h:form id="frmTest">
      <div class="p-grid ui-fluid">
         <div class="p-col-12">
            <div class="card">
               <h5>SelectOneRadio</h5>
               <p:selectOneRadio id="testRadio" columns="3" required="true" layout="grid">
                  <f:selectItem itemLabel="Option1" itemValue="Option1"/>
                  <f:selectItem itemLabel="Option2" itemValue="Option2"/>
                  <f:selectItem itemLabel="Option3" itemValue="Option3"/>
                  <f:selectItem itemLabel="Option4" itemValue="Option4"/>
                  <f:selectItem itemLabel="Option5" itemValue="Option5"/>
                  <f:selectItem itemLabel="Option6" itemValue="Option6"/>
                  <f:selectItem itemLabel="Option7" itemValue="Option7"/>
                  <f:selectItem itemLabel="Option8" itemValue="Option8"/>
                  <f:selectItem itemLabel="Option9" itemValue="Option9"/>
              </p:selectOneRadio>
            </div>
        </div>
      </div>
</h:form>
```
**Screenshot rendered HTML**
Screenshot_HTML_SelectOneRadio

**Screenshot HTML validation error**
Screenshot_HTML_Validation_SelectOneRadio

### PR DESCRIPTION
**Pull request by jepsar**
Fix #8180

Reference https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Nice work!  I am assigning to @mertsincan to review since this is a breaking change but I think its a good one.

**Comment by jepsar** [comment]
Put it to draft as there was an issue reported. But that has been fixed now. Removing draft.

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
i like the PR from a short view
is it battle tested?

i can try to do a deep review the next days and merge it

**Comment by jepsar** [comment]
I tested it with the showcase. I must say that I don't have any projects with custom radio buttons.

I would like to take out the `f:selectItem`s and add values to the radio buttons (making this an even bigger breaking change, but less messy).

**Comment by melloware** [comment]
@jepsar @tandraschko there is also this ticket:  https://github.com/primefaces/primefaces/issues/4569

I think @mertsincan was thinking the same thing that @jepsar basically did in this code !

**Comment by jepsar** [comment]
This is the idea I had (WIP) to remove the select items https://github.com/jepsar/primefaces/compare/8180_selectoneradio_aria...jepsar:8180_selectoneradio_aria_ii?expand=1

**Comment by tandraschko** [comment]
i would tackle this is another issue PR
we should discuss this first

**Comment by tandraschko** [comment]
@jepsar before your change, it was possible to place different oneRadio in different places in the view; with your change, we now need a facet=custom for it? im not sure if its a good change for the most users

**Comment by jepsar** [comment]
I need a facet in order to render a wrapper for the accessibility attributes. What we could do is offer both (so old style as well) and advice users to use the facet.

**Comment by jepsar** [comment]
Putting this back to draft to implement the custom facet as optional.

**Comment by jepsar** [comment]
This is no longer a breaking change and ready for review.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
nice work!

**Comment by tandraschko** [comment]
could you please add a integration test for the old-style markup, so we are safe for the future?

**Comment by jepsar** [comment]
Tests added

**Pull request merged**
