### PR TITLE
squid:S2386 Immutable Sets instead of String[]

### PR DESCRIPTION
**Pull request by melloware**
Code is frozen for RC1 but i wanted to put this out there for review.

### CODE REVIEW

**Comment by Rapster** [comment]
-1 for `MenuItemAware` These attributes are here so they're not instanciate over and over again, but making that change is countering the initial idea. Either we leave it as it is, or we don't make them as attributes

**Comment by melloware** [comment]
Agreed I didn’t love that either. Any suggestion on a better way to do it?  Or just revert that and leave that class as is?

**Comment by Rapster** [comment]
Yeah right now, I don't have a better suggestion except leave it as it is

**Comment by melloware** [comment]
Reverted MenuItemAware as suggested.

**Comment by melloware** [comment]
@tandraschko now that 8.0RC1 is out the door is this safe to merge?

**Comment by tandraschko** [comment]
Nope, we should so it after the final release

**Comment by Rapster** [comment]
Safe to merge yes, don't see why not

**Comment by melloware** [comment]
I marked it for 9.0

**Pull request merged**
