### PR TITLE
Fix #5339: Respect 'target' attribute in openLink

### LINKED ISSUE #5339: PanelMenu: link ignores "target" attribute
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (PrimeFaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0 Community
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Tomcat 9.0.4
- Affected browsers: FireFox, Chome

## 2) Expected behavior
I want to display an url in iframe using panelMenu. The iframe should be as target. The result should be displayed in iframe. 

## 3) Actual behavior
The result displayed in page. The page will load the url.

## 4) Steps to reproduce

Display in page
```
<h:form id="menuForm">
    <p:panelMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:panelMenu>
</h:form>
```
Display in iframe
```
<h:form id="menuForm">
    <p:slideMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:slideMenu>
</h:form>
```

## 5) Sample XHTML

menu.xhtml
Display in page
```
<h:form id="menuForm">
    <p:panelMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:panelMenu>
</h:form>
```
Display in iframe
```
<h:form id="menuForm">
    <p:slideMenu id="appSlideMenu" autoDisplay="false" toggleEvent="click" style="width:250px">
        <p:submenu label="Homepage">
            <p:menuitem value="Primefaces" url="http://www.primefaces.org" target="dcontainer" />
        </p:submenu>
    </p:slideMenu>
</h:form>
```
iframepage.xhtml
```
<h:body>

    <div class="row-container">

        <div class="first-row">
            <div class="start-button">
                <p:commandButton icon="fa fa-arrow-right" value="Start"
                    oncomplete="PF('nsidebar').show()" />
            </div>
            <div class="bottom">
                <ui:include src="bottom.xhtml" />
            </div>
        </div>

        <div class="second-row">
            <iframe id="dcontainer" name="dcontainer"> </iframe>
        </div>
    </div>

    <p:sidebar widgetVar="nsidebar" style="width:300px;">
        <ui:include src="menu.xhtml" />
    </p:sidebar>

</h:body>
```

## 6) Sample bean

..

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
shouldn't ctrl always open in blank?

**Comment by melloware** [comment]
But if your target is an IFRAME you wouldn't want it to open in a new tab would you?  or maybe you would?

**Comment by tandraschko** [comment]
don't know :D
what does firefox or chrome with a normal anchor+ctrl+target=frame?

**Comment by melloware** [comment]
You are right browser says CTRL always means new tab.  Fixing it now.

**Comment by tandraschko** [comment]
window.open() with _self and .focus() works fine in all brothers? just to be sure :D

**Comment by melloware** [comment]
Let me do some more testing to be sure.

**Comment by melloware** [comment]
OK tested in all browsers. Had to make one more fix to make IE11 work properly by checking if window is returned by window.open() as its NULL in IE but has values in other browsers.

**Comment by tandraschko** [comment]
thanks!

**Pull request merged**
