### PR TITLE
Fix #6002: Remove Aristo theme

### LINKED ISSUE #6002: Task: Remove Aristo Theme
**Description**
Aristo is a legacy ThemeRoller theme and doesn't even support new components like ToggleSwitch.

**Describe the solution you would like**
I think we should remove it for PF 9.0 as PF includes high quality themes already and the legacy ThemeRoller themes are considered deprecated.

@mertsincan WDYT?

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
JFYI: still no feedback from

But please also update the docu, it says "omega" as default currently which is wrong anyway

**Comment by melloware** [comment]
Good catch updates docs in 2 places

**Comment by tandraschko** [comment]
Please also add it to the migration guide

**Comment by melloware** [comment]
Migration guide updated!

**Pull request merged**
