### PR TITLE
Fix #5777: Remove @ResourceDependencies annotation

### LINKED ISSUE #5777: Task: Remove @ResourceDependencies wrapper annotation
Before Java 8 if you needed to use multiple instances of the same annotation, they had to be wrapped in a container annotation. With Java 8, that's no longer necessary, allowing for cleaner, more readable code.

**Noncompliant Code Example**
```java
@ResourceDependencies ({  // Noncompliant
  @ResourceDependency(..a..),
  @ResourceDependency(..b..),
  @ResourceDependency(..c..),
})
public class Component {
  ...
}
```

**Compliant Solution**
```java
@ResourceDependency(..a..)
@ResourceDependency(..b..)
@ResourceDependency(..c..)
public class Component {
  ...
}
```

### PR DESCRIPTION
**Pull request by melloware**
This looks like a bigger change than it is....

### CODE REVIEW

**Comment by tandraschko** [comment]
+1

**Comment by tandraschko** [comment]
@melloware what happens e.g. with this code: https://github.com/apache/myfaces/blob/master/impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java#L1672

Will it only collect 1 annotation?

**Comment by tandraschko** [comment]
I think it will return the first only, so we need to revert this change here

**Comment by tandraschko** [comment]
... andcheck mojarra and myfaces how they receive the annotations in all cases, to make it compatible for the future

**Comment by tandraschko** [comment]
or will it automatically be wrapped by a ResourceDependencies annotation?

**Comment by melloware** [comment]
@tandraschko I tested on Mojarra and MyFaces and didnt see any issues.  I believe this is JDK8 compiler magic that if it sees `@Repeatable(ResourceDependencies.class)` it automatially compiles it with the `@ResourceDependencies` parent.

**Pull request merged**
