### PR TITLE
Fix #7222: SelectBooleanButton IL8N on/off labels

### LINKED ISSUE #7222: SelectBooleanButton: make onLabel/offLabel attributes optional
Currently, p:selectBooleanButton requires the attributes onLabel/offLabel. Could you please makes these attributes optional and use the default labels true/false in that case.

This would help to quickly migrate SelectOneCheckboxes by simply replacing h:selectBooleanCheckbox by p:selectBooleanButton.

### PR DESCRIPTION
**Pull request by melloware**
Decided to go with "True" and "False" for defaults?

### CODE REVIEW

**Comment by tandraschko** [comment]
why not on/off like the name of the property?

**Comment by melloware** [comment]
I like ON/OFF better but the ticket the user was mentioning True and False.  I prefer On and Off.

**Comment by tandraschko** [comment]
lets to on/off

**Comment by melloware** [comment]
Yep just pushed the fix to ON OFF

**Comment by jepsar** [comment]
NL:
primefaces.boolean.LABEL_ON = Aan
primefaces.boolean.LABEL_OFF = Uit

**Comment by melloware** [comment]
@Rapster @stolp if you want to provide German and French translation that would be great for this PR

**Comment by melloware** [comment]
OK updated to `primefaces.switch.` as it is a better name.

**Comment by stolp** [comment]
DE:
primefaces.switch.LABEL_ON = Ein
primefaces.switch.LABEL_OFF = Aus

**Pull request merged**
