### PR TITLE
Chinese full translations for PrimeFaces

### PR DESCRIPTION
**Pull request by IKKI2000**

### CODE REVIEW

**Comment by jepsar** [comment]
Can you please also have a look at translating https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/org/primefaces/Messages.properties

**Comment by melloware** [comment]
@IKKI2000 you rock!  As @jepsar said any chance you can do the Messages.properties as well?

**Comment by IKKI2000** [comment]
@jepsar @melloware I have submitted a PR: https://github.com/primefaces/primefaces/pull/8204

**Comment by melloware** [comment]
@IKKI2000 the PF community thanks you for donating this translation and your time!

**Pull request merged**
