### PR TITLE
Fix #1459 #1473 #1297

### LINKED ISSUE #1459: icon attribute for p:menuButton
it would be good if the component p:menuButton had the icon attribute, so we can change the default icon and create it without label, only with icon

### PR DESCRIPTION
**Pull request by Rapster**
And some formatting (replace tab by 4 spaces)

### CODE REVIEW

**Comment by tandraschko** [comment]
Please provide different PR for formatting and logic changes. Your real changes are almost invisible ;)

**Comment by Rapster** [comment]
My formatting is fine actually (it respects the coding style set by Primefaces anyway), it's the previous one which was a mess though (a mix of tab and spaces...). My advise would be to use a little trick I know to ignore whitespaces so you can see real changes: add **?w=1** to the url where you want review changed files (in this case https://github.com/primefaces/primefaces/pull/1471/files?w=1)

**Comment by Rapster** [comment]
I don't understand why each commit I do are in this PR, as I want to create a PR for each commit :/

**Comment by michael-las** [comment]
@Rapster: PRs work on branches. That way you can discuss the PR, make changes and commit those changes to the same branch/PR. If you create a branch for each fix, then you'll be able to create a PR for each branch/fix.

**Pull request merged**
