### PR TITLE
#5129 Calendar/DatePicker out of range validation message not customizable enough

### PR DESCRIPTION
**Pull request by christophs78**
Implemented this for DatePicker.
Will look into Calendar as a second step.

### CODE REVIEW

**Comment by tandraschko** [comment]
like it! seems even bit more readable

**Comment by tandraschko** [comment]
Thanks for your work.
@melloware please also review and apply if it's ok from your side

**Comment by melloware** [comment]
Reviewing it now.

**Comment by melloware** [comment]
@christophs78 The ticket says Calendar/DatePicker validation but this PR looks like it is only for DatePicker? Am I seeing that correctly?

**Comment by melloware** [comment]
Oh I see you comment you are still investigating Calendar.  I will wait until you have that in.

**Comment by christophs78** [comment]
Now also covers Calendar. And did some refactoring to reduce duplicated code.

**Comment by melloware** [comment]
This is a really nice refactoring.  Thanks for the PR.

**Pull request merged**
