### PR TITLE
Fix #8491: Add support for Tab options and actions facets to AccordionPanel

### LINKED ISSUE #8491: AccordionPanel: Add support for actions, options and/or footer facets of Tab children like it is done for Panel
**Description**
We use dynamic `AccordionPanel` to group related preferences of our system in some configuration view. Some of the groups have some integrated test to verify the configured values as a whole. We are looking for a nice and easy accessible way to navigate to the corresponding test page from a group context. 

Our use case is just exemplary but could be generalized.

Currently we make usage of some custom flex style class for the `Tab`s in combination with a customized _title_ via `facet` containing a `LinkButton` to emulate  the accustomed _options/actions_ `facet`s of `Panel`.

**Describe the solution you would like**
It would be nice to have _options_ and/or _actions_ (and maybe _footer_) `facet` of `Tab` implemented for `AccordionPanel` like it is done for `Panel` for maximum overall consistency and user experience.

**Additional context**
[Existing _actions_ `facet` for `Tab`](https://github.com/primefaces/primefaces/issues/2666)
[Requested _footer_ `facet` for `Tab`](https://github.com/primefaces/primefaces/issues/3204)

**Example XHTML**

Current
```xml
<p:accordionPanel
  value="#{preferencesController.preferenceGroups}"
  var="group"
  varStatus="groupStatus"
  dynamic="true"
  multiple="true"
  activeIndex="#{preferencesController.preferenceGroups.size() eq 1 ? '0' : ''}"
>
  <p:tab
    title="#{preferences[group]}"
    titleStyleClass="custom-flex-style-class"
  >
    <f:facet name="title">
      <h:outputText value="#{preferences[group]}"></h:outputText>
      <p:linkButton
        id="testButton"
        icon="pi pi-cog"
        onclick="event.stopPropagation();"
        styleClass="rounded-button ml-auto"
        outcome="#{group.test.get()}"
        rendered="#{group.test.present}"
      >
        <f:param
          name="token"
          value="#{tokenProvider.getTestToken(group)}"
        ></f:param>
      </p:linkButton>
    </f:facet>
    ...
  </p:tab>
</p:accordionPanel
```
current

Wish
wish

### PR DESCRIPTION
**Pull request by irieill**
First working version for #8491 by only copy+paste of relevant code from `Panel` implementation.

I would like to improve by introduction of some common base for both `Panel`/`Tab` (`::getOptionsMenu`, `ARIA_OPTIONS_MENU`) and `PanelRenderer`/`AccordionPanelRenderer` (`::encodeIcon`, `::encodeOptionsMenu`, `::encodeActions`) or is this generally undesirable. If not, where to put such shared stuff within the package hierarchy?

I intentionally reused the `.ui-panel-titlebar-icon` and `.ui-panel-actions` style classes and `Panel.ARIA_OPTIONS_MENU`. Thoughts?

I am not happy with the `event.stopPropagation()` "hack" to disable tab selection on clicking the icons. Do you have ideas for a better approach?

I am not sure about the theme additions (therefore only changed saga here). It looks like themes are generated from some other source. How to extend themes in general?

### CODE REVIEW

**Comment by tandraschko** [comment]
looks good from a first short review

@melloware can you give some inputs?

in general we dont modify the theme.css and create issues for PrimeTek, so the can add this rules to their scss

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@tandraschko these changes look good to me and I am OK with the CSS styles added these are the default styles like Panel has that can then be overridden per theme.

**Comment by melloware** [comment]
@irieill can you update whatsnew.md in 12.0.0 docs MD to add this blurb.

**Comment by irieill** [comment]
@melloware Done.

**Comment by tandraschko** [comment]
@mertsincan this can also be merged but we need theme.css adjustments

**Comment by mertsincan** [comment]
Hi,

@melloware @tandraschko Is this feature Ok for you? If yes, could you please merge it? And then, could you please create a new issue with 'theme' label? Thanks a lot!

**Comment by melloware** [comment]
Ok. No problem!

**Comment by irieill** [comment]
@melloware @tandraschko 
> @melloware @tandraschko Is this feature Ok for you? If yes, could you please merge it? And then, could you please create a new issue with 'theme' label? Thanks a lot!

I think that was missed somehow. The style stuff is missing in the 12 release.

**Comment by melloware** [comment]
@irieill can you open a new ticket please.

**Pull request merged**
