### PR TITLE
Issue #4128

### PR DESCRIPTION
**Pull request by mrswadge**
https://github.com/primefaces/primefaces/issues/4128#issuecomment-541213394

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
this breaks processing of a normal DataTable, i need to revert it.

I just have a p:selectBooleanCheckbox inside a row and the listener is not invoked anymore:


`            <p:dataTable var="r" value="#{bean.myListWithEntities}" id="table">
                <p:column>
                    <p:selectBooleanCheckbox id="chk"
                                             value="#{r.enabled}"
                                             valueChangeListener="#{....}">
                        <p:ajax update="@composite:@composite"/>
                    </p:selectBooleanCheckbox>
                </p:column>`

**Comment by mrswadge** [comment]
Ok, understood.

We will have to revisit the solution as the infinite loop causes an OutOfMemoryException which takes down the server, so it's a severe bug when triggered. 

It creates an infinite number of org.primefaces.component.api.SavedState objects as it iterates through UIData.restoreDescendantState(UIComponent component, FacesContext context).

This stack trace is running on PrimeFaces 7.0.

```
"[ACTIVE] ExecuteThread: '6' for queue: 'weblogic.kernel.Default (self-tuning)'" #62 daemon prio=5 os_prio=0 tid=0x000000002a2f4000 nid=0xe2c runnable [0x000000003747a000]
   java.lang.Thread.State: RUNNABLE
	at javax.faces.component.UIComponentBase.getRenderer(UIComponentBase.java:1496)
	at javax.faces.component.UIComponentBase.getClientId(UIComponentBase.java:378)
	at org.primefaces.component.api.UIData.restoreDescendantState(UIData.java:746)
	at org.primefaces.component.api.UIData.restoreDescendantState(UIData.java:773)
	at org.primefaces.component.api.UIData.restoreDescendantState(UIData.java:728)
	at org.primefaces.component.api.UIData.setRowIndexWithoutRowStatePreserved(UIData.java:581)
	at org.primefaces.component.api.UIData.setRowIndex(UIData.java:640)
	at org.primefaces.component.api.UIData.visitRows(UIData.java:1010)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:889)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIForm.visitTree(UIForm.java:395)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
	at com.io_software.catools.jspacc.bb.UI.findComponentById(UI.java:358)
        ...
```

**Comment by mrswadge** [comment]
Before committing any code, perhaps worth a brief discussion. 

I trapped the issue in debug, I was wrong to think it was the `processed` counter, it's the `rowIndex` which is counting up infinitely. I was thinking I could simply alter my change to look at whether `rowIndex` is greater than `rows`. 

Do you think this is ok?

image

**Comment by tandraschko** [comment]
i think this breaks other things as well as we have to visit all rows probably, not only the "rows per page"

**Comment by mrswadge** [comment]
The LazyDataModel has a rowIndex set to 14, which is the size of the data array. This is despite the UIData.visitRows(..) setting the value well above that (debug trapped at over 10,000). When it calls through UIData.isRowAvailable() [next line in screenshot above] it's saying that the row *is* available. This check appears to be ignoring the rowIndex value that was set in UIData.visitRows(..).

Row count is zero which is interesting too?

image

**Comment by mrswadge** [comment]
In UIData.getRows() it appears to get the value from a property stored on the component. For some reason this is coming back as zero. Under the LazyModel it's using data.size() instead.

```
UIData:
    public int getRows() {
        return (Integer) getStateHelper().eval(PropertyKeys.rows, 0);
    }
```
vs.
```
LazyDataModel:
    @Override
    public boolean isRowAvailable() {
        if (data == null) {
            return false;
        }

        return rowIndex >= 0 && rowIndex < data.size();
    }
```

Is there a reason for UIData using a property value instead of using the data model to get the row count?

Observations:

 - When UIData.rowCount is returned as 0 and using a LazyDataModel
   - UIData.processed does not increment due to left-hand-side of `if ((rows > 0) && (++processed > rows)) {`
   - UIData.isRowsAvailable() does not return false as LazyDataModel.rowIndex does not increase beyond LazyDataModel.data.size()

**Comment by mrswadge** [comment]
We think we discovered the cause, but it was in our own code.

We have _LazyDataModel_ with a subclass implementation _GenericLazyModel_. Both have member _data_ as an ArrayList. The _GenericLazyModel.data_ list was empty, but the _LazyDataModel.data_ list was not because it had previously been populated. 

The _LazyDataModel.isRowAvailable()_ was looking at _LazyDataModel.data_, which was populated despite the _GenericLazyModel_ having an empty list. We were able to fix the issue with a single line of code that ensures that the data lists on both data models were in sync with each other.

I've not spent the time to prove it, but presumably the _UIData.getRows()_ row count was being calculated via the _GenericLazyModel.data_ or _LazyDataModel.rowCount_ value - either way it was being set to 0.

The two methods of calculating the number of rows caused the infinite loop. I don't know if this is something that Primefaces could protect against better. As I don't know the Primefaces code well, I probably will leave it here as we have identified a workaround.

**Comment by melloware** [comment]
@mrswadge Thanks for posting back.  

@tandraschko Do you think this is likely the cause of the original ticket?  Is this jut misuse of the LazyDataModel?

**Comment by mrswadge** [comment]
There are definitely some similarities in the circumstances between the OP and our setup as we both had checkboxes in data tables. The OP also mentioned the visit contexts, so it appears to land in the same ball park. There is no stack trace, so it's hard to be 100% sure.

I think our case is a misuse of the LazyDataModel as we duplicated the data list into our own implementation. I can't see a good reason for this as we could have used LazyDataModel.getWrappedData() to populate LazyDataModel.data in the subclass implementation directly.

**Comment by mrswadge** [comment]
The code in the OP is quite close to our LazyDataModel code.

```
    @Override
    public List<Car> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String,Object> filters) {
        ...
        //rowCount
        int dataSize = data.size();
        this.setRowCount(dataSize);
        ...
```

Our fix was simply to add another line to ours to call _this.setWrappedData( data );_

```
    @Override
	public List<Object> load(int first, int pageSize, List<SortMeta> multiSortMeta, Map<String,Object> filters) {
        ...
        //rowCount
        int dataSize = data.size();
        this.setRowCount(dataSize);
        this.setWrappedData( data ); // ensure LazyDataModel.data and GenericLazyModel.data are in sync
        ...
```

We're going to remove GenericLazyModel.data and use the one on the LazyDataModel instead in future.

**Comment by mrswadge** [comment]
The question that remains for me is whether when LazyDataModel.load(int first, int pageSize, List<SortMeta> multiSortMeta, Map<String,Object> filters) is called whether it should set the returned list to LazyDataModel.data. I've not looked at the callers, so up to you guys.

**Pull request merged**
